- go.mod
- go.sum
> Fix #3340: change default url from iam accessgroup SDK

- ibm/config.go
Updating the Client Config before every resource Provisioning to avoid consistency.
> Consistency issue

- ibm/resource_ibm_cis_page_rule.go
> fix: Actions fail to import for ibm_cis_page_rule resources 

- ibm/resource_ibm_is_instance_test.go
```
--- PASS: TestAccIBMISInstance_action (529.46s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	533.593s
```
> TestAccIBMISInstance_action test fix

- ibm/resource_ibm_event_streams_topic.go
> Add nil check before accessing Error

- ibm/resource_ibm_database.go
- website/docs/r/database.html.markdown
> Fix#3327 :Added force new to plan in ibm_databse resource

- website/docs/d/iam_trusted_profiles.html.markdown
> trusted profiles- doc fixes

- website/docs/d/cbr_rule.html.markdown
- website/docs/d/is_flow_log.html.markdown
- website/docs/r/cis_page_rule.html.markdown
> DocFix: flowlog and cbr_rule datasource

- ibm/data_source_ibm_pi_cloud_connection.go
- ibm/data_source_ibm_pi_cloud_connections.go
- ibm/data_source_ibm_pi_cloud_connections_test.go
- ibm/provider.go
- ibm/resource_ibm_pi_cloud_connection.go
- website/docs/d/pi_cloud_connection.html.markdown
- website/docs/d/pi_cloud_connections.html.markdown
Relates #3386
```
=== RUN   TestAccIBMPICloudConnectionsDataSourceBasic
--- PASS: TestAccIBMPICloudConnectionsDataSourceBasic (39.04s)
PASS
...
```
> Add data source for power cloud connections

- ibm/resource_ibm_iam_user_invite.go
> CrashFix: iam_user_invite #3226

- ibm/resource_ibm_satellite_location.go
- website/docs/d/iam_trusted_profile_claim_rules.markdown
> DocFix 3421: and enhance satellite location error message

- ibm/resource_ibm_iam_custom_role.go
Relates OR Closes #3353
```
=== RUN   TestAccIBMIAMCustomRole_Basic
--- PASS: TestAccIBMIAMCustomRole_Basic (37.84s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	40.813s
```
> Fix #3353: update description in custom roles resource

- .github/ISSUE_TEMPLATE/Documentation_Request.md
- .github/ISSUE_TEMPLATE/Terraform_IBM_Provider_Questions.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/labeler-issue.yml
- .github/workflows/issue_comment_created.yml
- .github/workflows/issues.yml
> Add issue labeler workflow and update issue template

- ibm/resource_ibm_cos_bucket.go
- website/docs/d/cos_bucket.html.markdown
- website/docs/d/kms_key.html.markdown
- website/docs/d/kms_keys.html.markdown
- website/docs/d/kp_key.html.markdown
- website/docs/r/cos_bucket.html.markdown
- website/docs/r/kms_key.html.markdown
- website/docs/r/kms_key_alias.html.markdown
- website/docs/r/kp_key.html.markdown
> DocFix 3349

- website/docs/r/satellite_host.html.markdown
> DocFix: satellite_host resource

- ibm/data_source_ibm_cos_bucket.go
- ibm/resource_ibm_cos_bucket.go
- website/docs/d/cos_bucket.html.markdown
- website/docs/r/cos_bucket.html.markdown
> Fix #3436: set direct endpoint to cos_bucket

- website/docs/r/iam_access_group_policy.html.markdown
- website/docs/r/iam_service_policy.html.markdown
- website/docs/r/iam_trusted_profile_policy.html.markdown
- website/docs/r/iam_user_policy.html.markdown
> DocFix #3425: Fix IAMPAP examples with region argument

- ibm/config.go
Relates OR Closes #2929
```=== RUN   TestAccIBMKMSResource_basic
--- PASS: TestAccIBMKMSResource_basic (150.50s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	154.111s
=== RUN   TestAccIBMIAMServiceID_Basic
--- PASS: TestAccIBMIAMServiceID_Basic (37.63s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm …
```
> Fix: iam url issue in kms client

- website/docs/r/container_bind_service.html.markdown
> Update doc of container service bind #3422

- ibm/data_source_ibm_pi_key.go
- ibm/data_source_ibm_pi_keys.go
- ibm/data_source_ibm_pi_keys_test.go
- ibm/provider.go
- website/docs/d/pi_dhcps.html.markdown
- website/docs/d/pi_keys.html.markdown
Fixes #3386
```
=== RUN   TestAccIBMPIKeyDataSource_basic
--- PASS: TestAccIBMPIKeyDataSource_basic (25.84s)
=== RUN   TestAccIBMPIKeysDataSourceBasic
--- PASS: TestAccIBMPIKeysDataSourceBasic (46.61s)
...
```
> Support for ibm_pi_keys

- ibm/resource_ibm_is_instance_template.go
- website/docs/r/is_instance_template.html.markdown
Relates OR Closes #2750
```
...
```
> fix(is_instance_template): made name as Optional to avoid name already in use

- ibm/resource_ibm_resource_instance.go
- website/docs/r/resource_instance.html.markdown
> Fix #3458: add parameters_json to ibm_resource_instance

- ibm/resource_ibm_container_vpc_worker_pool.go
> Fix the entitlement for VPC worker pool

- ibm/data_source_ibm_pi_snapshot_test.go
- ibm/data_source_ibm_pi_snapshots.go
- ibm/data_source_ibm_pi_snapshots_test.go
- ibm/resource_ibm_pi_instance_test.go
- ibm/resource_ibm_pi_snapshot.go
- ibm/resource_ibm_pi_snapshot_test.go
- website/docs/d/pi_instance_snapshots.html.markdown
- website/docs/d/pi_pvm_snapshots.html.markdown
```
=== RUN   TestAccIBMPIInstanceSnapshotbasic
--- PASS: TestAccIBMPIInstanceSnapshotbasic (886.66s)
PASS
=== RUN   TestAccIBMPISnapshotDataSource_basic
--- PASS: TestAccIBMPISnapshotDataSource_basic (14.03s)
PASS
=== RUN   TestAccIBMPISnapshotsDataSource_basic
--- PASS: …
```
> Add Docs: pi_pvm_snapshots & pi_instance_snapshots, enhanced snapshot testcases.

- ibm/resource_ibm_pi_volume_attach.go
- ibm/resource_ibm_pi_volume_attach_test.go
- website/docs/r/pi_volume_attach.html.markdown
```
=== RUN   TestAccIBMPIVolumeAttachbasic
--- PASS: TestAccIBMPIVolumeAttachbasic (667.66s)
PASS
=== RUN   TestAccIBMPIShareableVolumeAttachbasic
--- PASS: TestAccIBMPIShareableVolumeAttachbasic (878.03s)
PASS
```
> Add resource & docs: volume_attach 

- go.mod
- go.sum
- ibm/provider.go
- ibm/provider_test.go
- ibm/resource_ibm_pi_image_export.go
- ibm/resource_ibm_pi_image_export_test.go
- website/docs/r/pi_image_export.html.markdown
Update new resource to export image to COS bucket.
=== RUN   TestAccIBMPIImageEport
--- PASS: TestAccIBMPIImageEport (2761.42s)
PASS
> Export image to COS bucket update

- ibm/data_source_ibm_pi_instance.go
- ibm/data_source_ibm_pi_placement_group.go
- ibm/data_source_ibm_pi_placement_group_test.go
- ibm/data_source_ibm_pi_placement_groups.go
- ibm/data_source_ibm_pi_placement_groups_test.go
- ibm/provider.go
- ibm/provider_test.go
- ibm/resource_ibm_pi_instance.go
- ibm/resource_ibm_pi_placement_group.go
- ibm/resource_ibm_pi_placement_group_test.go
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_placement_group.html.markdown
- website/docs/d/pi_placement_groups.html.markdown
- website/docs/r/pi_instance.html.markdown
- website/docs/r/pi_placement_group.html.markdown
Add placement group function to terraform which
includes a new placement group field the instance
object and a new placement group resource.
Relates OR Closes #3456
=== RUN   TestAccIBMPIPlacementGroupBasic
[INFO] TEST PG MEMBERS: []string{}
[INFO] TEST PG name: "tf-pi-placement-group-36"
[INFO] TEST PG policy: "affinity" …
> Add placement group function to terraform

- ibm/data_source_ibm_pi_instance.go
- ibm/resource_ibm_pi_instance.go
- ibm/resource_ibm_pi_instance_test.go
- website/docs/d/pi_instance.html.markdown
- website/docs/r/pi_instance.html.markdown
```
=== RUN   TestAccIBMPIInstanceDataSource_basic
--- PASS: TestAccIBMPIInstanceDataSource_basic (66.30s)
=== RUN   TestAccIBMPIInstanceMixedStorage
--- PASS: TestAccIBMPIInstanceMixedStorage (877.46s)
PASS
```
> Allow mixed storage for pi_instance

- ibm/provider_test.go
- ibm/resource_ibm_pi_capture.go
- ibm/resource_ibm_pi_capture_test.go
- website/docs/r/pi_capture.html.markdown
```
=== RUN   TestAccIBMPICaptureBasic
--- PASS: TestAccIBMPICaptureBasic (599.78s)
PASS
=== RUN   TestAccIBMPICaptureWithVolume
--- PASS: TestAccIBMPICaptureWithVolume (1330.26s)
PASS
=== RUN   TestAccIBMPICaptureCloudStorage
--- PASS: TestAccIBMPICaptureCloudStorage (2728.01s)
PASS
=== RUN …
```
> Updated Code for Capture Instance

- website/docs/r/kms_key.html.markdown
> Update deprecation notice for kms key policies

- website/docs/r/kms_key.html.markdown
> Update example and deprecation message of kms key policies through ibm_kms_key resource

- ibm/service/vpc/resource_ibm_is_instance.go
> enhancement(instance) : added status reason in case of failure in is_instance

- website/docs/d/is_vpc_default_routing_table.html.markdown
- website/docs/r/is_vpc_routing_table.html.markdown
Relates OR Closes #2983
```
...
```
> fix(routing_table) : document fix for routing table 

- website/docs/r/scc_posture_collector.html.markdown
- website/docs/r/scc_posture_credential.html.markdown
- website/docs/r/scc_posture_scope.html.markdown
> Fix the sub category

- website/docs/r/is_image.html.markdown
> fix(is_image): Added more info for href

- ibm/provider/provider.go
- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_instances.go
- ibm/service/power/data_source_ibm_pi_instances_test.go
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instances.html.markdown
```
=== RUN TestAccIBMPIInstancesDataSource_basic
--- PASS: TestAccIBMPIInstancesDataSource_basic (1259.82s)
PASS
...
```
> Data source update to fetch pvm instances

- ibm/service/vpc/data_source_ibm_is_vpcs.go
Relates OR Closes #3535
```
=== RUN   TestAccIBMISVPCsDatasource_basic
--- PASS: TestAccIBMISVPCsDatasource_basic (121.69s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     124.857s
```
> fix(is_vpcs) : Subnet pagination fix in is_vpcs datasource

- ibm/service/pushnotification/data_source_ibm_push_notification_chrome.go
- ibm/service/pushnotification/resource_ibm_push_notification_chrome.go
> update: push notifications deprecation label

- ibm/service/power/data_source_ibm_pi_network.go
- ibm/service/power/resource_ibm_pi_network.go
- website/docs/d/pi_network.html.markdown
- website/docs/r/pi_network.html.markdown
Relates OR Closes #3551 
```
=== RUN   TestAccIBMPINetworkDataSource_basic
--- PASS: TestAccIBMPINetworkDataSource_basic (53.55s)
PASS
```
> Add dns attribute to power network

- .goreleaser.yml
- scripts/build.sh
> Support arm , arm64 for terraform provider

- go.mod
- go.sum
> Fix: #3562 Updating members_cpu_allocation_count to 0 fails with ibm_database

- ibm/service/cloudshell/resource_ibm_cloud_shell_account_settings.go
> Fix cloud shell account setting #3289

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateways.go
- ibm/service/vpc/resource_ibm_is_floating_ip.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway_test.go
- website/docs/d/is_virtual_endpoint_gateway.html.markdown
- website/docs/d/is_virtual_endpoint_gateways.html.markdown
- website/docs/r/is_virtual_endpoint_gateway.html.markdown
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3488
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISVirtualEndpointGateway_Basic_SecurityGroups'
```
> VPE SG Integration

- ibm/conns/config.go
Relates to https://ibm-argonauts.slack.com/archives/C53NF5MB4/p1644589844895569
> Fix: visibility private for vpc

- ibm/provider/provider.go
- ibm/service/satellite/data_source_ibm_satellite_host_script.go
- ibm/service/satellite/resource_ibm_satellite_host.go
- website/docs/d/satellite_attach_host_script.html.markdown
- website/docs/r/satellite_host.html.markdown
Relates OR Closes #3576
This PR fixes following:
1. Fix custom scripts for ibm hosts
2. Enable user to provide custom_script using following argument custom_script in host_strip datasource
3. Enable user to wait till location is normal while using ibm_satellite_host resource
> Fix: satellite resource and datasource

- ibm/service/kubernetes/resource_ibm_container_addons.go
- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
- website/docs/d/cis.html.markdown
- website/docs/r/cis.html.markdown
This PR closes  #3583
Doc fix container_addons issue #3584
Update fix for https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3528
> Fix: cis docs, resource_instance and addons resource

- ibm/flex/structures.go
- ibm/service/iampolicy/data_source_ibm_iam_access_group_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_service_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_trusted_profile_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_user_policy.go
- ibm/service/iampolicy/resource_ibm_iam_access_group_policy.go
- ibm/service/iampolicy/resource_ibm_iam_access_group_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_service_policy.go
- ibm/service/iampolicy/resource_ibm_iam_service_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_trusted_profile_policy.go
- ibm/service/iampolicy/resource_ibm_iam_trusted_profile_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_user_policy.go
- ibm/service/iampolicy/resource_ibm_iam_user_policy_test.go
- website/docs/d/iam_access_group_policy.html.markdown
- website/docs/d/iam_service_policy.html.markdown
- website/docs/d/iam_trusted_profile_policy.html.markdown
- website/docs/d/iam_user_policy.html.markdown
- website/docs/r/iam_access_group_policy.html.markdown
- website/docs/r/iam_service_policy.html.markdown
- website/docs/r/iam_trusted_profile_policy.html.markdown
- website/docs/r/iam_user_policy.html.markdown
Relates OR Closes #3290 
**User policy acceptance testcases**
**Trusted profile acceptance testcases**
**Service policy acceptance testcases**
**account-group policy acceptance testcases**
> Support of access management tags

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_instance.go
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/data_source_ibm_is_instances.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instance_template.html.markdown
- website/docs/d/is_instance_templates.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_metadata_service'
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_profile'
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_basic'
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstanceTemplate_metadata_service'
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstanceTemplate_basic'
> Support for instance metadata and trusted profile for instances.

- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway_test.go
Relates OR Closes #3606
```
--- PASS: TestAccIBMISVirtualEndpointGateway_CharacterCount (107.69s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     109.694s
```
> fix(virtual_endpoint_gateway): virtual endpoint gateway name regex fix

- ibm/conns/config.go
> fix proxy on kms client

- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
Relates OR Closes [#3643](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3643)
> Fix crash on resource_instance

- examples/ibm-is-ng/main.tf
- ibm/provider/provider.go
- ibm/service/vpc/resource_ibm_is_subnet.go
- ibm/service/vpc/resource_ibm_is_subnet_public_gateway_attachment.go
- ibm/service/vpc/resource_ibm_is_subnet_public_gateway_attachment_test.go
- website/docs/r/is_public_gateway.html.markdown
- website/docs/r/is_subnet_public_gateway_attachment.html.markdown
```
--- PASS: TestAccIBMISSubnetPublicGatewayAttachment_basic (147.31s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     149.093s
```
> enhancement(subnet): added support for ibm_is_subnet_public_gateway_attachment

- ibm/service/iampolicy/resource_ibm_iam_authorization_policy.go
- ibm/service/iampolicy/resource_ibm_iam_authorization_policy_test.go
- website/docs/r/iam_authorization_policy.html.markdown
Relates OR Closes #2945 
Resource Group related testcase results
Authorization policy between two specific services having resource specific attribute `cfgType`
Authorization policy between two specific services having resource specific attribute `keyRing`
> Authorization policy to support any service specific attributes

- website/docs/r/pi_instance.html.markdown
> Add note for disabled VTL creation

- ibm/service/kubernetes/data_source_ibm_container_cluster_config.go
```
$ make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainer_ClusterConfigDataSourceBasic'
--- PASS: TestAccIBMContainer_ClusterConfigDataSourceBasic (1111.79s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes	1112.674s
```
> Workaround for intermittent 500s for data lookup of clusters

- go.mod
- go.sum
- ibm/service/database/resource_ibm_database.go
> Allow 0 allocation for optional scaling group types

- ibm/service/database/data_source_ibm_database_connection.go
- website/docs/d/database_connection.html.markdown
> Update connections schema with mongodbee analytics and bi_connector

- ibm/service/vpc/data_source_ibm_is_flow_log.go
- ibm/service/vpc/data_source_ibm_is_flow_log_test.go
- ibm/service/vpc/data_source_ibm_is_image.go
- ibm/service/vpc/data_source_ibm_is_instance.go
- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/data_source_ibm_is_volume.go
```
--- PASS: TestAccIBMIsFlowLogDataSourceBasic (186.73s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 190.093s
```
```
--- PASS: TestAccIBMISImageDataSource_basic (16.88s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 20.582s
```
```
--- PASS: …
```
> enhancement(changed): changed list logic in datasource by name

- ibm/service/vpc/data_source_ibm_is_lb.go
- ibm/service/vpc/data_source_ibm_is_lb_profiles.go
- ibm/service/vpc/data_source_ibm_is_lbs.go
- ibm/service/vpc/resource_ibm_is_lb.go
- ibm/service/vpc/resource_ibm_is_lb_listener.go
- ibm/service/vpc/resource_ibm_is_lb_listener_test.go
- ibm/service/vpc/resource_ibm_is_lb_pool.go
- ibm/service/vpc/resource_ibm_is_lb_pool_test.go
- ibm/service/vpc/resource_ibm_is_lb_test.go
- website/docs/d/is_lb.html.markdown
- website/docs/d/is_lb_listener.html.markdown
- website/docs/d/is_lb_listeners.html.markdown
- website/docs/d/is_lb_profiles.html.markdown
- website/docs/d/is_lbs.html.markdown
- website/docs/r/is_lb.html.markdown
- website/docs/r/is_lb_listener.html.markdown
- website/docs/r/is_lb_pool.html.markdown
```
--- PASS: TestAccIBMISLB_basic_udp (713.17s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     714.768s
```
```
--- PASS: TestAccIBMISLBPool_basic_udp (802.21s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     803.506s
```
```
--- PASS: …
```
> feature(lb): support for udp protocol in load balancers

- ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_servers.go
- ibm/service/vpc/data_source_ibm_is_instance.go
- ibm/service/vpc/data_source_ibm_is_instances.go
- ibm/service/vpc/data_source_ibm_is_volume.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_action.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_action.go
- ibm/service/vpc/resource_ibm_is_volume.go
- website/docs/d/is_bare_metal_server.markdown
- website/docs/d/is_bare_metal_servers.markdown
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/d/is_volume.html.markdown
- website/docs/r/is_bare_metal_server.markdown
- website/docs/r/is_bare_metal_server_action.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_action.html.markdown
- website/docs/r/is_volume.html.markdown
> fix(status_reasons): fixed status reasons in volume, instance and baremetalserver service

- go.mod
- go.sum
> Fix the go mod

- ibm/service/globaltagging/resource_ibm_resource_tag.go
Relates OR Closes #3703
**with old binary** 
**with new binary**
> Fix #3703: validation on resource_id in resourc_tag resource

- README.md
- ibm/service/power/README.md
> Added badges to README

- website/docs/r/container_cluster.html.markdown
- website/docs/r/container_vpc_cluster.html.markdown
...as I'm fairly sure "us_south-2" isn't legal here.
> Correct a minor typo

- examples/ibm-power/main.tf
- examples/ibm-power/provider.tf
- examples/ibm-power/variables.tf
- examples/ibm-power/versions.tf
> Fix the power example configuration

- website/docs/r/iam_authorization_policy.html.markdown
- website/docs/r/satellite_cluster.html.markdown
> Doc fix: authorisation policy and satellite cluster

- ibm/service/iamaccessgroup/data_source_ibm_iam_access_group.go
Relates OR Closes #3728
```
...
```
> added pagination for access groups listing api

- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/power/data_source_ibm_pi_system_pools.go
- ibm/service/power/data_source_ibm_pi_system_pools_test.go
- ibm/service/power/resource_ibm_pi_dhcp.go
- website/docs/d/pi_system_pools.markdown
Relates OR Closes #3731
```
=== RUN   TestAccIBMPISystemPoolsDataSourceBasic
--- PASS: TestAccIBMPISystemPoolsDataSourceBasic (52.64s)
PASS
```
> Added data source for power system pools

- ibm/service/vpc/resource_ibm_is_floating_ip.go
Relates OR Closes #3759
```
--- PASS: TestAccIBMISFloatingIP_basic (356.11s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     357.171s
```
```
--- PASS: TestAccIBMISFloatingIP_NoTarget (60.45s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     62.229s
```
> fix(floating_ip): fixed nil check on floating ip target

- go.mod
- go.sum
> Fix: vulnerable package

- go.mod
- go.sum
- ibm/service/appconfiguration/data_source_ibm_app_config_feature.go
- ibm/service/appconfiguration/data_source_ibm_app_config_feature_test.go
- ibm/service/appconfiguration/data_source_ibm_app_config_features.go
- ibm/service/appconfiguration/data_source_ibm_app_config_features_test.go
- ibm/service/appconfiguration/resource_ibm_app_config_feature.go
- ibm/service/appconfiguration/resource_ibm_app_config_feature_test.go
- website/docs/d/app_config_feature.html.markdown
- website/docs/d/app_config_features.html.markdown
- website/docs/r/app_config_feature.html.markdown
> App config : phased rollout support for terraform

- .secrets.baseline
> Fix the detect secrets

- .secrets.baseline
- ibm/acctest/acctest.go
- ibm/provider/provider.go
- ibm/service/database/data_source_ibm_database_backup.go
- ibm/service/database/data_source_ibm_database_backup_test.go
- ibm/service/database/data_source_ibm_database_backups.go
- ibm/service/database/data_source_ibm_database_backups_test.go
- website/docs/d/database.html.markdown
- website/docs/d/database_backup.html.markdown
- website/docs/d/database_backups.html.markdown
```
$ make testacc TEST=./ibm/service/database TESTARGS='-run=TestAccIBMDatabaseBackupsDataSourceBasic'
...
=== RUN   TestAccIBMDatabaseBackupsDataSourceBasic
--- PASS: TestAccIBMDatabaseBackupsDataSourceBasic (24.06s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/database	25.198s …
```
> Datasource for Cloud Databases Backups and Backup

- ibm/service/secretsmanager/data_source_ibm_secrets_manager_secret.go
- website/docs/d/secrets_manager_secret.html.markdown
> add support to retrieve secrets of all secret types

- website/docs/r/pi_network.html.markdown
> Correct attribute reference names

- ibm/service/iampolicy/data_source_ibm_iam_access_group_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_access_group_policy_test.go
- ibm/service/iampolicy/data_source_ibm_iam_service_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_service_policy_test.go
- ibm/service/iampolicy/data_source_ibm_iam_trusted_profile_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_trusted_profile_policy_test.go
- ibm/service/iampolicy/data_source_ibm_iam_user_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_user_policy_test.go
- website/docs/d/iam_access_group_policy.html.markdown
- website/docs/d/iam_service_policy.html.markdown
- website/docs/d/iam_trusted_profile_policy.html.markdown
- website/docs/d/iam_user_policy.html.markdown
Relates OR Closes #3801
**DataSource IAM user policy testcases**
**DataSource IAM TrustedProfile policy testcases**
**DataSource IAM Service policy testcases**
**DataSource IAM AccessGroup policy testcases**
> Data source to list the policies if the policy has service specific attributes

- ibm/service/atracker/resource_ibm_atracker_route.go
- ibm/service/atracker/resource_ibm_atracker_settings.go
- ibm/service/atracker/resource_ibm_atracker_target.go
- ibm/service/cis/resource_ibm_cis_firewall_rules.go
- ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go
- ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go
- ibm/service/eventnotification/resource_ibm_en_destination.go
- ibm/service/satellite/resource_ibm_satellite_endpoint.go
- ibm/service/scc/resource_ibm_scc_posture_collector.go
- ibm/service/scc/resource_ibm_scc_posture_credential.go
- ibm/service/scc/resource_ibm_scc_posture_scope.go
- ibm/service/scc/resource_ibm_scc_rule_attachment_validator.go
- ibm/service/scc/resource_ibm_scc_si_occurrence.go
- ibm/service/scc/resource_ibm_scc_template_attachment_validator.go
- ibm/service/schematics/resource_ibm_schematics_inventory.go
- ibm/service/schematics/resource_ibm_schematics_job.go
- ibm/service/schematics/resource_ibm_schematics_resource_query.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_action.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_disk.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface.go
- ibm/service/vpc/resource_ibm_is_instance_action.go
- ibm/service/vpc/resource_ibm_is_instance_network_interface.go
- ibm/service/vpc/resource_ibm_is_placement_group.go
- ibm/validate/validators.go
> added ValidateCIDRAddress to the validator list

- ibm/service/cis/resource_ibm_cis_cache_settings.go
CIS browser_expiration 0 value is not reflected.
Description : Issue was when we provide browser_expiration value 0, it was not being applied.
Root cause : Our scheme API use 0 as false or non exists key, so wrote a wrapper specially to handle this
case. 
Main TF.
resource ibm_cis_cache_settings "cache_settings" {
cis_id             = data.ibm_cis.cis.id
domain_id          = ibm_cis_domain.domain.domain_id
caching_level       = "aggressive"
browser_expiration  = 0
development_mode    = "off"
query_string_sort   = "on"
serve_stale_content = "off"
}
Testing .
1st . Build was successful.
After fix:
2nd. Ran tf file with different-2 value after fix, 0 was being applied
Before fix:
3rd.  Ran ft file with zero, zero was not being applied as expected code was not able to handle it.
> CIS browser_expiration 0 value is not reflected

- ibm/provider/provider.go
- ibm/service/dnsservices/resource_ibm_private_dns_glb_pool.go
- website/docs/r/dns_glb_pool.html.markdown
> Add new Healthcheck regions

- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver.go
- website/docs/r/dns_custom_resolver.html.markdown
> [ Doc ] [ ibm_dns_custom_resolver ] Update Documentation 

- website/docs/r/dns_custom_resolver_location.html.markdown
> Deprecated Custom Resolver Location resource

- go.mod
- go.sum
- ibm/service/vpc/resource_ibm_is_snapshot.go
> enhancement(vpc-go-sdk): sdk migration from 0.19.0 to 0.20.0

- ibm/service/vpc/data_source_ibm_is_floating_ip.go
> floating ip data source nil fix

- examples/ibm-power/README.md
- examples/ibm-power/main.tf
- examples/ibm-power/provider.tf
- examples/ibm-power/variables.tf
- examples/ibm-power/versions.tf
Updated Examples for **IBM Power**.
> Updated IBM Power Examples

- go.mod
- go.sum
- ibm/service/eventnotification/resource_ibm_en_source.go
> Fix the error in latest code

- website/docs/index.html.markdown
> Update provider version in docs

- ibm/service/vpc/data_source_ibm_is_placement_groups.go
- ibm/service/vpc/data_source_ibm_is_placement_groups_test.go
> fix: placement targets empty list

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
```
--- PASS: TestAccIBMISBareMetalServer_multi_nic (752.26s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     756.662s
```
> fix(bare_metal_server) : vlan id in multi nic fix

- go.mod
- go.sum
> Consume latest CD Go SDK

- ibm/service/vpc/resource_ibm_is_instance.go
- website/docs/r/is_instance.html.markdown
> placement target patch support

- website/docs/d/is_instance_group_manager_actions.html.markdown
- website/docs/d/is_instance_group_manager_policies.html.markdown
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-23413
```
...
```
> Corrected the names in the documentations (data sources) 

- ibm/service/vpc/resource_ibm_is_security_group.go
- website/docs/r/is_volume.html.markdown
Relates OR Closes #3883
```
...
```
> fix(documentation): error statement fix on security group and is_volume documents fix

- ibm/service/cis/resource_ibm_cis_mtls.go
- website/docs/r/cis_mtls.html.markdown
- website/docs/r/cis_mtls_app.html.markdown
**Problem Description** : Found some discrepancy in mTLS resource documentation and improved formatting of content.
**Issue**
Non Functional : Cosmetic doucmentation changes for CIS mTLS resource. #3903 
**Impact** : Non-fuctional 
Note : Along with this cosmetic changes, Made a minor change in certificate content field to make it sensitive data. 
@hkantare  @kavya498  Please merge these changes.
> Non functional cosmetic changes to mTLS resource documentation

- .secrets.baseline
- examples/ibm-cos-bucket/README.md
- examples/ibm-cos-bucket/main.tf
- examples/ibm-cos-bucket/variables.tf
- go.mod
- go.sum
- ibm/acctest/acctest.go
- ibm/flex/structures.go
- ibm/provider/provider.go
- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_replication_configuration.go
- ibm/service/cos/resource_ibm_cos_replication_configuration_test.go
- website/docs/d/cos_bucket.html.markdown
- website/docs/r/cos_replication.html.markdown
Enabling IAM authorization policy to set the replication rule.
Test results:-
```
step_number=1 test_terraform_path=/usr/local/bin/terraform test_working_directory=/var/folders/xn/m4dxdl711772pnv9plyb9sr80000gn/T/plugintest2220958881
2022-07-12T14:43:19.950+0530 [DEBUG] sdk.helper_resource: Finished TestCase: test_name=TestAccIBMCosBucket_Bucket_Replication
--- PASS: TestAccIBMCosBucket_Bucket_Replication (41.71s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos    	42.579s
```
```
2022-07-12T15:47:29.504+0530 [DEBUG] sdk.helper_resource: Finished TestCase: test_name=TestAccIBMCosBucket_Bucket_Replication
--- PASS: TestAccIBMCosBucket_Bucket_Replication (111.70s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	113.499s
```
> COS: Added bucket replication rule on COS

- website/docs/d/is_instance_group_manager_actions.html.markdown
- website/docs/r/is_backup_policy.html.markdown
> Resource Backup Policy Documentation Correction

- .secrets.baseline
> update secret baseline

- ibm/service/cos/data_source_ibm_cos_bucket.go
> Fix the breaking change of cos bucket with replication configuration

- ibm/service/cos/resource_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket_test.go
GitHub Issue :https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3894
Test Results:
```
=== RUN   TestAccIBMCosBucket_AllowedIP
--- PASS: TestAccIBMCosBucket_AllowedIP (137.80s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	138.733s
```
> 3894:fix the firewall allowed_ip issue

- ibm/service/satellite/data_source_ibm_satellite_location.go
> Fix the nil pointer for coreos enabled

- .legal.yaml
- go.mod
- go.sum
- ibm/service/resourcecontroller/data_source_ibm_resource_key.go
- ibm/service/resourcecontroller/resource_ibm_resource_key.go
- website/docs/d/resource_key.html.markdown
- website/docs/r/resource_key.html.markdown
Signed-off-by: apoorva9s14 <apoorvalaiti16@gmail.com>
```
...
```
> ResourceController service update to add feature of redacted credentials

- ibm/service/power/data_source_ibm_pi_dhcp.go
- ibm/service/power/data_source_ibm_pi_dhcps.go
- ibm/service/power/resource_ibm_pi_dhcp.go
Fixes #3951
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>
```
...
```
> fix: dhcp source crash on nil network

- ibm/service/schematics/resource_ibm_schematics_action.go
> Fix crash on schematics_action resource

- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/appconfiguration/data_source_ibm_app_config_segment.go
- ibm/service/appconfiguration/data_source_ibm_app_config_segment_test.go
- ibm/service/appconfiguration/data_source_ibm_app_config_segments.go
- ibm/service/appconfiguration/data_source_ibm_app_config_segments_test.go
- ibm/service/appconfiguration/resource_ibm_app_config_segment.go
- ibm/service/appconfiguration/resource_ibm_app_config_segment_test.go
- website/docs/d/app_config_segment.html.markdown
- website/docs/d/app_config_segments.html.markdown
- website/docs/r/app_config_segment.html.markdown
> appconfig terraform segement support

- ibm/service/vpc/data_source_ibm_is_vpc.go
- ibm/service/vpc/data_source_ibm_is_vpc_test.go
- website/docs/d/is_vpc.html.markdown
```
--- PASS: TestAccIBMISVPCDatasource_basic (86.40s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     87.966s
```
> enhancement(is_vpc): added support for identifier in vpc data source

- ibm/service/cos/resource_ibm_cos_bucket.go
> Fix the setting of monitoring if it fails with error during update

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance.go
- website/docs/d/pi_instance.html.markdown
```
=== RUN   TestAccIBMPIInstanceDataSource_basic
--- PASS: TestAccIBMPIInstanceDataSource_basic (45.75s)
PASS
=== RUN   TestAccIBMPIInstanceDeploymentType
--- PASS: TestAccIBMPIInstanceDeploymentType (387.58s)
PASS
...
```
> Get the Deployment Type

- .goreleaser.yml
- .secrets.baseline
> add metedata to goreleaser

- ibm/service/database/resource_ibm_database.go
> Prevent runtime error on 0 member allocations

- ibm/conns/config.go
Relates OR Closes https://github.ibm.com/blueprint/product/issues/7432
> fix: schematics regional endpoints issue

- ibm/service/vpc/resource_ibm_is_security_group_target.go
Relates OR Closes #4000
```
--- PASS: TestAccIBMISSecurityGroup_basic (107.18s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     108.742s
```
> fix(ibm_is_security_group_target): missing set statements in sg target resource

- ibm/service/hpcs/resource_ibm_hpcs.go
```
$ echo $TESTARGS
-run TestAccIBMHPCSInstanceBasic
$ make testacc
...
=== RUN   TestAccIBMHPCSInstanceBasic
--- PASS: TestAccIBMHPCSInstanceBasic (561.51s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/hpcs	562.854s
...
```
> Add source units required parameter

- ibm/flex/structures.go
- website/docs/r/is_lb_listener_policy.html.markdown
```
...
```
https://github.com/ibm-vpc/terraform-provider-ibm/pull/169
> target_http_status_code correction

- ibm/service/cis/resource_ibm_cis.go
> fix the diff on cis tags if provisioned from SchematicS

- ibm/service/schematics/data_source_ibm_schematics_action.go
- ibm/service/schematics/data_source_ibm_schematics_inventory.go
- ibm/service/schematics/data_source_ibm_schematics_job.go
- ibm/service/schematics/data_source_ibm_schematics_output.go
- ibm/service/schematics/data_source_ibm_schematics_resource_query.go
- ibm/service/schematics/data_source_ibm_schematics_state.go
- ibm/service/schematics/data_source_ibm_schematics_workspace.go
- website/docs/d/schematics_workspace.html.markdown
> add region to schematics workspace

- ibm/conns/config.go
- ibm/service/schematics/data_source_ibm_schematics_action.go
- ibm/service/schematics/data_source_ibm_schematics_inventory.go
- ibm/service/schematics/data_source_ibm_schematics_job.go
- ibm/service/schematics/data_source_ibm_schematics_output.go
- ibm/service/schematics/data_source_ibm_schematics_resource_query.go
- ibm/service/schematics/data_source_ibm_schematics_state.go
- ibm/service/schematics/data_source_ibm_schematics_workspace.go
- ibm/service/schematics/resource_ibm_schematics_action.go
- ibm/service/schematics/resource_ibm_schematics_inventory.go
- ibm/service/schematics/resource_ibm_schematics_job.go
- ibm/service/schematics/resource_ibm_schematics_resource_query.go
- ibm/service/schematics/resource_ibm_schematics_workspace.go
- website/docs/d/schematics_action.html.markdown
- website/docs/d/schematics_inventory.html.markdown
- website/docs/d/schematics_job.html.markdown
- website/docs/d/schematics_output.html.markdown
- website/docs/d/schematics_resource_query.html.markdown
- website/docs/d/schematics_state.html.markdown
- website/docs/d/schematics_workspace.html.markdown
- website/docs/r/schematics_action.html.markdown
- website/docs/r/schematics_job.html.markdown
- website/docs/r/schematics_resource_query.html.markdown
> fix location on schematics resources

- .secrets.baseline
> fix secretbaseline

- website/docs/d/pi_instance.html.markdown
- website/docs/r/pi_instance.html.markdown
> Updated Description for Deployment type EPIC

- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_instance_groups.go
- ibm/service/vpc/data_source_ibm_is_instance_groups_test.go
- website/docs/d/is_instance_groups.html.markdown
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMIsInstanceGroupsDataSourceBasic'
=== RUN   TestAccIBMIsInstanceGroupsDataSourceBasic
--- PASS: TestAccIBMIsInstanceGroupsDataSourceBasic (181.16s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     183.159s
... …
```
> added instance groups data source

- .secrets.baseline
- .travis.yml
> Fix detect secret

- examples/ibm-cos-bucket/main.tf
- examples/ibm-cos-bucket/variables.tf
- ibm/acctest/acctest.go
- ibm/service/cos/resource_ibm_cos_bucket_test.go
- website/docs/d/cos_bucket.html.markdown
- website/docs/r/cos_bucket.html.markdown
Test Case results :
=== RUN  TestAccIBMCOSKP
--- PASS: TestAccIBMCOSKP (76.40s)
PASS
=== RUN   TestAccIBMCOSHPCS
--- PASS: TestAccIBMCOSHPCS (71.39s)
PASS
> Changes for HPCS COS support

- go.mod
- go.sum
- ibm/flex/structures.go
- ibm/service/vpc/resource_ibm_is_ike_policy.go
- ibm/service/vpc/resource_ibm_is_ike_policy_test.go
- ibm/service/vpc/resource_ibm_is_ipsec_policy.go
- website/docs/r/is_ike_policy.html.markdown
- website/docs/r/is_ipsec_policy.html.markdown
validate method correction
updated test case
```
...
```
> added support for new ciphers

- website/docs/index.html.markdown
- website/docs/r/is_instance.html.markdown
Relates OR Closes #4060
```
...
```
> fix(docs): added details about user data and update link for ibmcloud docs

- ibm/service/vpc/data_source_ibm_is_backup_policies.go
Relates OR Closes #4079 
data "ibm_is_backup_policies" "is_backup_policies" {
}
> Backup Policy Empty List

- ibm/acctest/acctest.go
- ibm/conns/config.go
- ibm/conns/config_functions.go
- ibm/flex/structures.go
- ibm/service/classicinfrastructure/resource_ibm_compute_vm_instance.go
- ibm/service/classicinfrastructure/resource_ibm_dns_record.go
- ibm/service/classicinfrastructure/resource_ibm_dns_reverse_record.go
- ibm/service/classicinfrastructure/resource_ibm_firewall_shared.go
- ibm/service/classicinfrastructure/resource_ibm_multi_vlan_firewall.go
- ibm/service/classicinfrastructure/resource_ibm_network_gateway.go
- ibm/service/cos/resource_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket_test.go
- ibm/service/enterprise/resource_ibm_enterprise_account_test.go
- ibm/service/functions/qualified_name.go
- ibm/service/power/data_source_ibm_pi_catalog_images.go
- ibm/service/power/data_source_ibm_pi_images.go
- ibm/service/satellite/data_source_ibm_satellite_host_script_test.go
- ibm/service/satellite/resource_ibm_satellite_cluster.go
- ibm/validate/validators.go
- version/version.go
> fix(fmt) : fmt changes

- go.mod
- go.sum
- ibm/conns/config.go
> enhancement(vpc-go-sdk) : updated the vpc go sdk to 0.27.0 with terraform user agent

- ibm/service/power/resource_ibm_pi_cloud_connection.go
```
...
=== RUN   TestAccIBMPICloudConnectionbasic
--- PASS: TestAccIBMPICloudConnectionbasic (277.06s)
PASS
=== RUN   TestAccIBMPICloudConnectionNetworks
--- PASS: TestAccIBMPICloudConnectionNetworks (607.10s)
PASS
=== RUN   TestAccIBMPICloudConnectionClassic …
```
> Fix GRE tunnel in cloud connection

- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_network_interface.html.markdown
> VNF Scalability NIC

- ibm/flex/structures.go
- website/docs/d/satellite_attach_host_script.html.markdown
> fix #4099: return error for incorrect label syntax

- .goreleaser.yml
- NOTICE
> Add NOTICE

- ibm/service/power/resource_ibm_pi_volume_test.go
- website/docs/r/is_lb_listener_policy.html.markdown
Results are available in PR https://github.com/ibm-vpc/terraform-provider-ibm/pull/186
> Documentation fix lb listener policy

- ibm/flex/structures.go
> Fix the len of the array to fix len out of range

- website/docs/d/database.html.markdown
- website/docs/r/database.html.markdown
Relates OR Closes #4108
- Documentation fixes
```
$ make testacc TEST=./ibm/service/database TESTARGS='-run=TestAccIBMDatabaseDataSource_basic' 
=== RUN   TestAccIBMDatabaseDataSource_basic
=== PAUSE TestAccIBMDatabaseDataSource_basic
=== CONT  TestAccIBMDatabaseDataSource_basic
--- PASS: TestAccIB
MDatabaseDataSource_basic …
```
> Updates to documentation

- go.mod
> go mod correction

- ibm/flex/structures.go
- ibm/service/resourcecontroller/data_source_ibm_resource_instance.go
- ibm/service/secretsmanager/data_source_ibm_secrets_manager_secret.go
Relates OR Closes #[4137](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4137)
```
=== RUN   TestAccIBMResourceInstanceDataSource_basic
--- PASS: TestAccIBMResourceInstanceDataSource_basic (232.79s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/resourcecontroller	237.749s
...
```
> migrate resource instance datasource to latest platform sdk

- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_definition.go
- website/docs/r/cd_tekton_pipeline.html.markdown
Minor documentation update, no functional change
> chore(tekton): documentation update

- ibm/flex/structures.go
- ibm/service/classicinfrastructure/resource_ibm_lbaas.go
> Fix the provision of lbass

- CHANGELOG.md
- version/version.go
> Release 1.48.0

- go.mod
- go.sum
- ibm/flex/structures.go
- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
> Fix the last operation as per new SDK

- website/docs/r/database.html.markdown
Updates Cloud Database doc examples to use `allowlist`
> docs(Cloud Databases): Update examples to use allowlist

- ibm/service/vpc/resource_ibm_is_subnet.go
- website/docs/r/is_subnet.html.markdown
Relates OR Closes #3183 
```
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSubnet_basic'
```
```
resource "ibm_is_vpc" "testacc_vpc" {
name = "sunitha"
}
resource "ibm_is_subnet" "subnet1" {
name            = "subnet1"
vpc             = ibm_is_vpc.testacc_vpc.id
zone            = "us-south-1"
ip_version      = …
```
> Added fix for access tags for subnets

- website/docs/d/is_subnet_reserved_ip.html.markdown
- website/docs/d/is_subnet_reserved_ips.html.markdown
> [DocuFix] Subnet Reserved IP Target Fix

- ibm/service/vpc/data_source_ibm_is_vpc.go
- ibm/service/vpc/data_source_ibm_is_vpcs.go
- ibm/service/vpc/resource_ibm_is_vpc.go
- website/docs/d/is_vpc.html.markdown
- website/docs/d/is_vpcs.html.markdown
- website/docs/r/is_vpc.html.markdown
```
$  make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVPC_basic'
```
```
resource "ibm_is_vpc" "vpc2" {
name        = "sunitha"
access_tags = ["tfp:ussouth", "tfp:eude"]
}
data "ibm_is_vpc" "testacc_vpc" {
name       = ibm_is_vpc.vpc2.name
depends_on = [ibm_is_vpc.vpc2]
}
data …
```
> Access Tags for VPC

- ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_servers.go
- ibm/service/vpc/data_source_ibm_is_instance_group.go
- ibm/service/vpc/data_source_ibm_is_instance_groups.go
- ibm/service/vpc/data_source_ibm_is_vpn_server.go
- ibm/service/vpc/data_source_ibm_is_vpn_servers.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_instance_group.go
- ibm/service/vpc/resource_ibm_is_vpn_server.go
- website/docs/d/is_bare_metal_server.markdown
- website/docs/d/is_bare_metal_servers.markdown
- website/docs/d/is_instance_group.html.markdown
- website/docs/d/is_instance_groups.html.markdown
- website/docs/d/is_vpn_server.html.markdown
- website/docs/d/is_vpn_servers.html.markdown
- website/docs/r/is_bare_metal_server.markdown
- website/docs/r/is_instance_group.html.markdown
- website/docs/r/is_vpn_server.html.markdown
```
resource "ibm_is_instance_group" "instance_group" {
name              = "sunitha-instance-group"
instance_template = "0727-e86f2959-9842-4ece-a6c4-b7eafd62c854"
instance_count    = 2
subnets           = ["0727-9447a2c3-efb8-44d2-a180-115531e0b0d3"]
access_tags       = ["tfp:ussouth", "tfp:eude"]
}
data "ibm_is_instance_groups" "is_instance_groups" { …
```
> Access tags for Instance Group, VPN Server and Bare Metal Server

- ibm/service/vpc/resource_ibm_is_security_group_network_interface_attachment.go
- website/docs/r/is_security_group_network_interface_attachment.html.markdown
> Added removal notification in docs for ibm_is_security_group_network_interface_attachment

- ibm/provider/provider.go
- ibm/service/vpc/resource_ibm_is_instance_network_interface_floating_ip.go
- ibm/service/vpc/resource_ibm_is_instance_network_interface_floating_ip_test.go
- website/docs/r/is_instance_network_interface_floating_ip.markdown
```
--- PASS: TestAccIBMISInstanceNetworkInterfaceFloatingIp_basic (172.27s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     174.820s
```
> enhancement(floating_ip): Instance nic fip support

- website/docs/r/is_instance.html.markdown
github issue: [1665](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1665) 
```
...
```
> Doc update to intimate the conflict in security groups with instances: Defect 1665 github

- website/docs/r/is_security_group_target.html.markdown
> Added security group target list for supported resources

- examples/ibm-is-ng/main.tf
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_template_test.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/data_source_ibm_is_instance_templates_test.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- website/docs/d/is_instance_template.html.markdown
- website/docs/d/is_instance_templates.html.markdown
- website/docs/r/is_instance_template.html.markdown
Relates OR Closes #4182
```
```
=== RUN   TestAccIBMISInstanceTemplate_catalog_basic
--- PASS: TestAccIBMISInstanceTemplate_catalog_basic (139.00s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     141.027s
```
```
=== RUN   TestAccIBMISInstanceTemplate_data_catalog
--- PASS: …
> enhancement(template): support for catalog images

- CHANGELOG.md
- version/version.go
> Release 1.49.0-beta0

- ibm/service/schematics/resource_ibm_schematics_workspace.go
> support terraform1.2 for schematics workspace

- examples/ibm-is-ng/main.tf
- go.mod
- go.sum
- ibm/acctest/acctest.go
- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_job.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_job_test.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_jobs.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_jobs_test.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plan.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plans.go
- website/docs/d/is_backup_policy_job.html.markdown
- website/docs/d/is_backup_policy_jobs.html.markdown
Testes in PROD ENV, in VPC DEMO account..
```
export IS_BACKUP_POLICY_JOB_ID="r134-a5265096-0f9b-4731-acdd-a37c74cd64ee"
export IS_BACKUP_POLICY_ID="r134-85e6edda-d5af-4360-8f6a-f1c118d34191"
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMIsBackupPolicyJobDataSourceBasic'
$ make testacc …
```
> Backup policy jobs development

- website/docs/d/is_lb_listener.html.markdown
- website/docs/d/is_lb_listeners.html.markdown
- website/docs/r/is_lb_listener.html.markdown
- website/docs/r/is_vpn_server.html.markdown
> Certificate manager removal

- website/docs/r/container_cluster.html.markdown
Found a couple typos when I was deploying a cluster. This should fix it.
```
...
```
> Fixed a couple typos

- ibm/service/schematics/resource_ibm_schematics_workspace.go
- website/docs/r/schematics_workspace.html.markdown
> Fix #4132: fix values_metadata argument in schematics resource

- go.mod
- go.sum
- ibm/service/vpc/resource_ibm_is_lb.go
> enhancement(vpc-go-sdk) : Migration to latest 0.30.0

- CHANGELOG.md
- version/version.go
> Release 1.50.0_beta0

- ibm/flex/structures.go
```
harinireddy@Harinis-MBP cloudant % terraform12-1 apply  
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
+ resource "ibm_resource_instance" "test" {
+ account_id              = …
```
> update tags from globaltags to search API

- CHANGELOG.md
- version/version.go
> Release 1.50.0

- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_secretsmanager.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_secretsmanager.go
- website/docs/d/cd_toolchain_tool_secretsmanager.html.markdown
- website/docs/r/cd_toolchain_tool_secretsmanager.html.markdown
> New options for secrets manager tool

- .secrets.baseline
> Fix false positivies secrets

- examples/ibm-is-ng/main.tf
- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_snapshot_clone.go
- ibm/service/vpc/data_source_ibm_is_snapshot_clone_test.go
- ibm/service/vpc/data_source_ibm_is_snapshot_clones.go
- ibm/service/vpc/data_source_ibm_is_snapshot_clones_test.go
- ibm/service/vpc/data_source_ibm_is_snapshot_test.go
- ibm/service/vpc/data_source_ibm_is_snapshots.go
- ibm/service/vpc/data_source_ibm_is_snapshots_test.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
- ibm/service/vpc/resource_ibm_is_snapshot_test.go
- website/docs/d/is_snapshot.html.markdown
- website/docs/d/is_snapshot_clone.html.markdown
- website/docs/d/is_snapshot_clones.html.markdown
- website/docs/d/is_snapshots.html.markdown
- website/docs/r/is_snapshot.html.markdown
```
=== RUN   TestAccIBMISSnapshotClone_basic
--- PASS: TestAccIBMISSnapshotClone_basic (389.01s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     391.295s
```
```
=== RUN   TestAccIBMISSnapshotDatasource_clonesbasic
no message …
```
> enhancement(clone): support for snapshot clone

- ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interface.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interfaces.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_servers.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
- website/docs/r/is_bare_metal_server.markdown
- website/docs/r/is_bare_metal_server_network_interface.markdown
> enhancemnet(bare metal): support for z systems

- CHANGELOG.md
- version/version.go
> Release 1.51.0

- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_artifactory.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_artifactory.go
- website/docs/d/cd_toolchain_tool_artifactory.html.markdown
- website/docs/r/cd_toolchain_tool_artifactory.html.markdown
> CD Artifactory parameter description update

- CHANGELOG.md
- version/version.go
> Release 1.52.0-beta0

- ibm/service/schematics/resource_ibm_schematics_workspace.go
> Fix #4452: Add 1.3 version of terraform to schematics workspace resource

- CHANGELOG.md
- version/version.go
> Release 1.52.0

- ibm/acctest/acctest.go
- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/data_source_ibm_cos_bucket_object.go
- ibm/service/cos/data_source_ibm_cos_bucket_test.go
- ibm/service/cos/resource_ibm_cos_bucket_object.go
--- PASS: TestAccIBMCOSBucketObjectDataSource_basic (73.51s)
PASS
ok 	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	75.048s
--- PASS: TestAccIBMCOSBucketDataSource_basic (35.12s)
PASS
ok 	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	36.959s
> Fix for issue 4487

- examples/ibm-cos-bucket-object/README.md
- examples/ibm-cos-bucket/README.md
- examples/ibm-cos-bucket/main.tf
- website/docs/d/cos_bucket.html.markdown
- website/docs/r/cos_bucket.html.markdown
- website/docs/r/cos_bucket_object.html.markdown
- website/docs/r/cos_bucket_object_lock_configuration.html.markdown
Adding some naming convention changes to the objectlock documentation.
> Adding some changes to the object lock documentation

- ibm/service/power/resource_ibm_pi_instance_test.go
Relates #4383 
```
=== RUN   TestAccIBMPIInstanceUpdateActiveState
--- PASS: TestAccIBMPIInstanceUpdateActiveState (770.33s)
PASS
=== RUN   TestAccIBMPIInstanceUpdateStoppedState
--- PASS: TestAccIBMPIInstanceUpdateStoppedState (959.24s)
PASS
...
```
> Test cases for IBM PI Instance Update Flow

- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_lb_profile.go
- ibm/service/vpc/data_source_ibm_is_lb_profile_test.go
- ibm/service/vpc/data_source_ibm_is_lb_profiles.go
- website/docs/d/is_lb_profile.html.markdown
> enhancement(lb_profile): added lb_profile datasource

- ibm/acctest/acctest.go
- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_snapshots.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
- ibm/service/vpc/resource_ibm_is_snapshot_test.go
- website/docs/d/is_snapshot.html.markdown
- website/docs/d/is_snapshots.html.markdown
- website/docs/r/is_snapshot.html.markdown
```
=== RUN   TestAccIBMISSnapshot_encrypted
--- PASS: TestAccIBMISSnapshot_encrypted (272.64s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     274.792s
```
> enhancement(is_snapshot): added support for encryption_key in is_snapshot

- examples/openshift-data-foundation/addon/README.md
- examples/openshift-data-foundation/addon/createaddon.sh
- examples/openshift-data-foundation/addon/createcrd.sh
- examples/openshift-data-foundation/addon/ibm_odf_addon/main.tf
- examples/openshift-data-foundation/addon/input.tfvars
- examples/openshift-data-foundation/addon/main.tf
- examples/openshift-data-foundation/addon/ocscluster/main.tf
- examples/openshift-data-foundation/addon/updatecrd.sh
- examples/openshift-data-foundation/addon/updateodf.sh
- examples/openshift-data-foundation/addon/variables.tf
- go.mod
- go.sum
- ibm/service/kubernetes/resource_ibm_container_addons.go
- website/docs/d/container_addons.html.markdown
Relates OR Closes #3380
```
...
```
> Support for AddOn parameters

- website/docs/d/is_vpn_server_client.html.markdown
- website/docs/d/is_vpn_server_clients.html.markdown
- website/docs/d/is_vpn_server_route.html.markdown
- website/docs/d/is_vpn_server_routes.html.markdown
- website/docs/r/is_vpn_server_route.html.markdown
> VPN Server Document Correction

- ibm/flex/structures.go
- ibm/service/vpc/resource_ibm_is_instance.go
> Volume attachments in sequence to an instance

- website/docs/r/is_vpc_routing_table.html.markdown
> Bug doc correction: routing table's `accept routes from`

- CHANGELOG.md
- version/version.go
> Release 1.53.0

- go.mod
- go.sum
- ibm/service/enterprise/resource_ibm_enterprise_account.go
- ibm/service/enterprise/resource_ibm_enterprise_account_group.go
- ibm/service/enterprise/resource_ibm_enterprise_account_group_test.go
- ibm/service/enterprise/resource_ibm_enterprise_account_test.go
- website/docs/r/enterprise_account.html.markdown
- website/docs/r/enterprise_account_group.html.markdown
Summary of changes in this pull request:
Added destroy methods for ibm_enterprise_account and ibm_enterprise_account_group
Added computed attribute for two fields in response of create account schema
$ make testacc TESTARGS='-run=TestAccIbmEnterpriseAccountGroupBasic'
$ make testacc …
> feat(Enterprise):added support for destroy method

- examples/openshift-data-foundation/addon/README.md
- examples/openshift-data-foundation/addon/ibm_odf_addon/main.tf
- examples/openshift-data-foundation/addon/input.tfvars
- examples/openshift-data-foundation/addon/ocscluster/main.tf
- examples/openshift-data-foundation/addon/variables.tf
> Openshift-Data-Foundation Terraform Example & Documentation

- CHANGELOG.md
- version/version.go
> Release 1.54.0-beta0

- .secrets.baseline
- ibm/service/secretsmanager/resource_ibm_sm_arbitrary_secret_test.go
- ibm/service/secretsmanager/resource_ibm_sm_iam_credentials_secret_test.go
- ibm/service/secretsmanager/resource_ibm_sm_kv_secret_test.go
- ibm/service/secretsmanager/resource_ibm_sm_username_password_secret_test.go
- ibm/service/secretsmanager/utils_for_test.go
> Secrets Manager - Additional tests

- website/docs/r/is_vpc_routing_table_route.html.markdown
Relates OR Closes #4579
```
...
```
> fix(doc): doc fix for vpc_routing_table_route next_hop

- website/docs/d/container_addons.html.markdown
- website/docs/r/container_addons.html.markdown
> Add-On doc Fix

- website/docs/d/is_flow_log.html.markdown
> Corrected the argument repetition in datasource documentation of flow log

- CHANGELOG.md
- version/version.go
> Release 1.54.0

- ibm/service/iamidentity/resource_ibm_iam_service_api_key.go
> fix(iam-service-api-key): added nil check on apikey *string

- website/docs/r/code_engine_app.html.markdown
- website/docs/r/code_engine_build.html.markdown
- website/docs/r/code_engine_config_map.html.markdown
- website/docs/r/code_engine_job.html.markdown
- website/docs/r/code_engine_secret.html.markdown
> Added import example in code engine document

- website/docs/r/pi_cloud_connection.html.markdown
> Update pi_cloud_connection documentation

- website/docs/r/cis.html.markdown
Documentation Update post Standard Next plan updation. Ref - https://github.ibm.com/NetworkTribe/nw-sdk-terraform-planner/issues/448
> CIS - Documentation Update

- website/docs/d/dl_export_route_filter.html.markdown
- website/docs/d/dl_export_route_filters.html.markdown
- website/docs/d/dl_gateway.html.markdown
- website/docs/d/dl_gateways.html.markdown
- website/docs/d/dl_import_route_filter.html.markdown
- website/docs/d/dl_import_route_filters.html.markdown
- website/docs/r/cis_domain_settings.html.markdown
- website/docs/r/dl_gateway.html.markdown
- website/docs/r/dl_gateway_action.html.markdown
> Fix indentation

- ibm/service/kubernetes/resource_ibm_container_addons.go
1. Diff Suppressed managed_addons parameter to prevent config change during plan and apply
2. Users can now set manage_all_addons to false after initial creation.
```
...
```
> managed_addons fix

- ibm/conns/config.go
> Fix the private endpoint for global search API

- examples/ibm-iam-identity-mfaStatus/versions.tf
- examples/ibm-iam_identity-mfaStatus/README.md
- examples/ibm-iam_identity-mfaStatus/main.tf
- examples/ibm-iam_identity-mfaStatus/outputs.tf
- examples/ibm-iam_identity-mfaStatus/variables.tf
- ibm/provider/provider.go
- ibm/service/iamidentity/data_source_ibm_iam_user_mfa_enrollments.go
- ibm/service/iamidentity/data_source_ibm_iam_user_mfa_enrollments_test.go
- website/docs/d/iam_user_mfa_enrollments.html.markdown
```
$ make testacc TESTARGS='-run=TestAccIBMIamUserMfaEnrollmentsDataSourceBasic'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMIamUserMfaEnrollmentsDataSourceBasic -timeout 700m
? …
```
> IAM identity mfa status

- website/docs/r/code_engine_app.html.markdown
- website/docs/r/code_engine_build.html.markdown
- website/docs/r/code_engine_config_map.html.markdown
- website/docs/r/code_engine_job.html.markdown
- website/docs/r/code_engine_secret.html.markdown
> fix import example in code engine document

- go.mod
- go.sum
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_ssh_key.go
- ibm/service/vpc/resource_ibm_is_ssh_key_test.go
- website/docs/d/is_ssh_keys.html.markdown
- website/docs/r/is_bare_metal_server.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_ssh_key.html.markdown
```
=== RUN   TestAccIBMISSSHKey_ed25519
--- PASS: TestAccIBMISSSHKey_ed25519 (38.00s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     43.727s
```
> SSH Key: Support additional encryption algorithms

- go.mod
- go.sum
- ibm/acctest/acctest.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plan.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plan_test.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plans.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plans_test.go
- ibm/service/vpc/resource_ibm_is_backup_policy_plan.go
- ibm/service/vpc/resource_ibm_is_backup_policy_plan_test.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- website/docs/d/is_backup_policy_plan.html.markdown
- website/docs/d/is_backup_policy_plans.html.markdown
- website/docs/r/is_backup_policy_plan.html.markdown
> backup: added suuport for cross region copy for vpc backup

- ibm/service/vpc/resource_ibm_is_instance_group_manager_policy.go
```
resource "ibm_is_vpc" "vpc2" {
name = "sunitha-vpc-tfp"
}
resource "ibm_is_subnet" "subnet2" {
name            = "sunitha-subnet-tfp"
vpc             = ibm_is_vpc.vpc2.id
zone            = "us-south-2"
ipv4_cidr_block = "10.240.64.0/28"
}
resource "ibm_is_ssh_key" "sshkey" {
name       = "sunitha-subnet-tfp"
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCkF5mR1NqO7z6wviLUY2JZAWcEBhOmYi8lNlrLKP1mI4XOLUFq5KeIy5Ta14wqQR/W2dA72E51ummWn+39z9vgWgYKY5yIuVYy6b2W5Mo2MM73iEi1mB+GgqXWRTGRFBAPgT5mnqiwPZE0yKvQAe5vLPx6z4BxWKNi5Tp31Hf0KKHLKzrH4zUGSyoEFFYeoxUO8YSc6oyAKhJQBQAFXl0u9YSnuyiXUqYDpa06w0PUl2M6ALBTVa1uLmacTIJxJhJzDJxidW3fIVO9Nm7RSU0WcS2FGyqP3jNQKLAhpqUyDOyWfV/2yjy/H4Y3gjfLKCIhZIjUVO1KJlWcSScoJo7ILPWnzmr0uWmC/4qrqU0I3+8/AdBvJF1xCpzDBb/nPKWT2m8s5ZyahpmP4F91K6J0Zk3KLWzXkFrrB4MBpW9LLitPmgFh …
```
> Failed to update resource ibm_is_instance_group_manager_policy update

- .pre-commit-config.yaml
- .secrets.baseline
- go.mod
- go.sum
So that the terraform provider can operate the eu-fr2 region.
Closes #4286 
```
$ make testacc TESTARGS='run="TestAccIBMCr.*"'
=== RUN   TestAccIBMCrNamespacesDataSourceBasic
--- PASS: TestAccIBMCrNamespacesDataSourceBasic (17.09s)
=== RUN   TestAccIBMCrNamespaceBasic
--- PASS: TestAccIBMCrNamespaceBasic (25.23s)
=== RUN …
```
> Update container-registry SDK

- CHANGELOG.md
- version/version.go
> Release 1.56.0-beta0

- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket_test.go
--- PASS: TestAccIBMCosBucket_Basic (135.44s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	137.276s
--- PASS: TestAccIBMCosBucket_Basic_Single_Site_Location (74.91s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	76.641s
> Adding the fix for 4699 issue

- ibm/service/vpc/resource_ibm_is_vpc.go
- ibm/service/vpc/resource_ibm_is_vpc_test.go
- website/docs/r/is_vpc.html.markdown
```
resource "ibm_is_vpc" "testacc_vpc" {
name = "sunitha-tfp-vpc"
no_sg_acl_rules = true
}
```
```
resource "ibm_is_vpc" "testacc_vpc" {
name = "sunitha-tfp-vpc"
no_sg_acl_rules = false
}
```
> Feature is no sg acl rules

- website/docs/r/container_addons.html.markdown
A small doc update for container_addons. 
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4704
> doc update for container addons

- website/docs/r/enterprise_account.html.markdown
> move trait field from acc import to acc create

- website/docs/d/pi_dhcps.html.markdown
Relates OR Closes #4725
```
...
```
> Fix ibm_pi_dhcps Example

- website/docs/r/is_bare_metal_server.markdown
- website/docs/r/is_bare_metal_server_network_interface.markdown
> Updated the documentation to cleanup l1bm

- CHANGELOG.md
- version/version.go
> Release 1.56.0

- examples/ibm-iam-accessgroups-templates/main.tf
- go.mod
- go.sum
- ibm/service/iamaccessgroup/data_source_ibm_iam_access_group_template_versions.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template_test.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template_version.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template_version_test.go
- website/docs/d/iam_access_group_template.html.markdown
- website/docs/d/iam_access_group_template_versions.html.markdown
- website/docs/r/iam_access_group_template.html.markdown
- website/docs/r/iam_access_group_template_version.html.markdown
> [fix]remove update from request/response

- CHANGELOG.md
- version/version.go
> Release 1.57.0

- CHANGELOG.md
- version/version.go
> Release 1.58.0-beta0

- website/docs/d/cd_toolchains.html.markdown
> Fix document category for toolchains datasource

- CHANGELOG.md
- version/version.go
> Release 1.58.0

- ibm/service/schematics/resource_ibm_schematics_workspace.go
This allows for creation of workspaces with terraform version 1.5
Community Note
Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
> allow ibm_schematics_workspace template_type 1.5

- go.mod
- go.sum
- ibm/service/eventstreams/resource_ibm_event_streams_schema.go
Refer https://github.com/IBM/eventstreams-go-sdk/releases/tag/v1.4.0
> update terraform as per latest eventstreams go sdk release 1.4.0

- CHANGELOG.md
- version/version.go
> Release 1.59.0-beta0

- website/docs/d/schematics_agent.html.markdown
- website/docs/d/schematics_agent_deploy.html.markdown
- website/docs/d/schematics_agent_health.html.markdown
- website/docs/d/schematics_agent_prs.html.markdown
- website/docs/d/schematics_agents.html.markdown
- website/docs/d/schematics_policies.html.markdown
- website/docs/d/schematics_policy.html.markdown
- website/docs/r/schematics_agent.html.markdown
- website/docs/r/schematics_agent_deploy.html.markdown
- website/docs/r/schematics_agent_health.html.markdown
- website/docs/r/schematics_agent_prs.html.markdown
- website/docs/r/schematics_policy.html.markdown
> Add beta flag to Schematics Agents resources/datasources

- website/docs/d/sm_private_certificate.html.markdown
- website/docs/r/trusted_profile_template.html.markdown
> Fix indentation for subcategory

- CHANGELOG.md
- version/version.go
> Release 1.59.0

- ibm/service/vpc/resource_ibm_is_vpn_gateway.go
```
=== RUN   TestAccIBMISVPNGateway_basic
--- PASS: TestAccIBMISVPNGateway_basic (440.03s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     442.134s
```
> resolved nil pointer issue on vpn gateway resource

- CHANGELOG.md
- version/version.go
> Release 1.60.0-beta0

- CHANGELOG.md
- version/version.go
> Release 1.60.0

- ibm/service/database/resource_ibm_database.go
Fixes failure for go 1.18
```
ibm/service/database/resource_ibm_database.go:92:39: method Unwrap() []error should have signature Unwrap() error
Vet found suspicious constructs. Please check the reported constructs
and fix them if necessary before submitting the code for review.
make: *** [GNUmakefile:45: vet] Error 1
```
Output from …
> fix(Cloud Databases): fix Unwrap return value for go 1.18 compat

- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip.go
Relates OR Closes #4927 
```
...
```
> update issue fixed ibm_is_subnet_reserved_ip

- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float.go
> resolved delete issue for the floated nics on bm server

- CHANGELOG.md
- version/version.go
> Bump up versio to 1.61.0-beta0

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
> added a nil check for boottarget of bms

- website/docs/d/is_image.html.markdown
> fix(docs): UI-33634: mention correct image name in image data source example

- CHANGELOG.md
- version/version.go
> Bump up version to 1.61.0

- ibm/service/vpc/resource_ibm_is_vpc_routing_table.go
- ibm/service/vpc/resource_ibm_is_vpc_routing_table_test.go
Relates OR Closes #5036
```
...
```
> fix(vpc-routing-table): support removing of  advertise routes and accept routes from array

- CHANGELOG.md
- version/version.go
> Bump up version to 1.62.0

- ibm/conns/config.go
> Event Notifications: enabled private endpoint

- ibm/service/kubernetes/data_source_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
- website/docs/d/container_vpc_cluster.html.markdown
- website/docs/r/container_vpc_cluster.html.markdown
Issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5122
```
...
```
> fix: add vpe_service_endpoint_url output

- ibm/service/power/resource_ibm_pi_network.go
> fix the provider plugin failure

- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
> reordered reservation on instance to avoid update and length check on template

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_attachment.go
> fix(bare metal server) : fixed allow to float and ips issue

- CHANGELOG.md
- ibm/service/eventnotification/data_source_ibm_en_integration_cos.go
- version/version.go
> Release 1.63.0-beta0

- ibm/flex/structures.go
- ibm/service/eventnotification/data_source_ibm_en_integration_cos.go
- ibm/service/satellite/resource_ibm_satellite_host.go
- ibm/service/satellite/resource_ibm_satellite_host_test.go
- website/docs/r/satellite_host.html.markdown
```
=== RUN   TestAccFunctionSatelliteHost_Basic
--- PASS: TestAccFunctionSatelliteHost_Basic (2665.98s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/satellite       2669.133s
...
```
> handle host_id in waitForHostAttachment

- ibm/service/project/data_source_ibm_project.go
- ibm/service/project/resource_ibm_project.go
fix for issue https://github.ibm.com/ibmcloud/projects/issues/2909
------------------------------------------------------------------------------------------------
```
...
```
> unable to perform plan/apply after a project config is approved or deployed

- ibm/service/vpc/resource_ibm_is_virtual_network_interface.go
- website/docs/d/is_bare_metal_server_network_attachment.html.markdown
- website/docs/d/is_bare_metal_server_network_attachments.html.markdown
- website/docs/d/is_instance_network_attachment.html.markdown
- website/docs/d/is_instance_network_attachments.html.markdown
- website/docs/d/is_virtual_network_interface_floating_ip.html.markdown
- website/docs/d/is_virtual_network_interface_floating_ips.html.markdown
- website/docs/d/is_virtual_network_interface_ip.html.markdown
- website/docs/d/is_virtual_network_interface_ips.html.markdown
- website/docs/d/is_vpc_dns_resolution_binding.html.markdown
- website/docs/d/is_vpc_dns_resolution_bindings.html.markdown
- website/docs/r/is_bare_metal_server_network_attachment.html.markdown
- website/docs/r/is_instance_network_attachment.html.markdown
- website/docs/r/is_virtual_network_interface.html.markdown
- website/docs/r/is_virtual_network_interface_floating_ip.html.markdown
- website/docs/r/is_virtual_network_interface_ip.html.markdown
- website/docs/r/is_vpc_dns_resolution_binding.html.markdown
> fixed docs and added force new on vni

- ibm/service/vpc/resource_ibm_is_public_gateway_test.go
- website/docs/r/is_public_gateway.html.markdown
```
=== RUN   TestAccIBMISPublicGateway_floatingip
--- PASS: TestAccIBMISPublicGateway_floatingip (92.90s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     96.554s
```
> updated document and added a testcase for public gateway

- CHANGELOG.md
- version/version.go
> Release 1.63.0

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
> Added computed to network_attachments for is_bare_metal_server

- CHANGELOG.md
- version/version.go
> Bump up version to 1.64.0-beta0

- CHANGELOG.md
- go.mod
- go.sum
- version/version.go
> Release 1.64.0

- go.mod
- go.sum
- ibm/conns/config.go
- ibm/service/vmware/data_source_ibm_vmaas_vdc.go
- ibm/service/vmware/data_source_ibm_vmaas_vdc_test.go
- ibm/service/vmware/resource_ibm_vmaas_vdc.go
- ibm/service/vmware/resource_ibm_vmaas_vdc_test.go
- ibm/service/vmware/utils.go
make build fails with fmt and go mod issues due to recent changes related to vmware
> fix build due to vmware fmt and gomod issues

- CHANGELOG.md
- version/version.go
> Release 1.65.0-beta0

- go.mod
- go.sum
- ibm/service/iampolicy/data_source_ibm_iam_policy_assignments.go
Relates OR Closes #[2348](https://github.ibm.com/IAM/AM-issues/issues/2348)
```
=== RUN   TestAccIBMIAMPolicyAssignmentsDataSourceBasic
--- PASS: TestAccIBMIAMPolicyAssignmentsDataSourceBasic (20.45s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/iampolicy	22.388s
...
```
> Fix build issue

- examples/openshift-data-foundation/addon/4.14.0/README.md
- examples/openshift-data-foundation/addon/4.14.0/main.tf
- examples/openshift-data-foundation/addon/4.14.0/ocscluster/main.tf
- examples/openshift-data-foundation/addon/4.14.0/schematics.tfvars
- examples/openshift-data-foundation/addon/4.14.0/variables.tf
- examples/openshift-data-foundation/satellite/odf-local/4.14/README.md
- examples/openshift-data-foundation/satellite/odf-local/4.14/input.tfvars
- examples/openshift-data-foundation/satellite/odf-local/4.14/main.tf
- examples/openshift-data-foundation/satellite/odf-local/4.14/variables.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.14/README.md
- examples/openshift-data-foundation/satellite/odf-remote/4.14/input.tfvars
- examples/openshift-data-foundation/satellite/odf-remote/4.14/main.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.14/variables.tf
> ODF workerpool support

- CHANGELOG.md
- version/version.go
> Release 1.65.0

- ibm/service/enterprise/resource_ibm_enterprise_account.go
- website/docs/d/enterprise_accounts.html.markdown
- website/docs/r/enterprise_account.html.markdown
Added IAM attributes for reference in enterprise markdown file
<!--
Replace TestAccXXX with a pattern that matches the tests affected by this PR.
> Enterprise: Added IAM attributes for reference in enterprise markdown file

- ibm/service/cis/resource_ibm_cis_ruleset_entrypoint_version_test.go
- ibm/service/cis/resource_ibm_cis_ruleset_rule.go
- ibm/service/cis/resource_ibm_cis_ruleset_test.go
- ibm/service/cis/resource_ibm_cis_ruleset_version_detach_test.go
Fix for the managed ruleset issue mentioned in - https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5238/#issuecomment-2110844262
> add computed field for ruleset rule id

- website/docs/r/scc_profile_attachment.html.markdown
Relates OR Closes #5349
```
...
```
> SCC Profile Attachment Doc Update

- website/docs/r/is_security_group_rule.html.markdown
> updated the docs for vpc security group rule

- ibm/service/eventnotification/resource_ibm_en_smtp_user.go
> Fix the fmt

- ibm/service/cis/resource_ibm_cis_filter.go
- ibm/service/cis/resource_ibm_cis_firewall_rules.go
> remove validation for filter and firewall description

- ibm/service/transitgateway/resource_ibm_tg_gateway.go
- ibm/service/transitgateway/resource_ibm_tg_gateway_test.go
Relates OR Closes #4921 
```
--- PASS: TestAccIBMTransitGateway_globalUpdate (74.12s)
```
> fix(tg): fixed global change issue

- CHANGELOG.md
- version/version.go
> Bump up version to 1.66.0

- .secrets.baseline
- examples/ibm-pag/main.tf
- examples/ibm-pag/variables.tf
- ibm/service/pag/resource_ibm_pag_instance_test.go
- website/docs/r/pag_instance.html.markdown
```
$ make testacc TEST=./ibm/service/pag TESTARGS='-run=TestAccIBMResourceInstanceBasic'
. . .
=== RUN   TestAccIBMResourceInstanceBasic
--- PASS: TestAccIBMResourceInstanceBasic (632.44s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/pag	635.131s
...
```
> Adding PAG changes

- ibm/service/schematics/resource_ibm_schematics_workspace.go
Closes #5413
I am currently unable to run acceptance tests.
> support for terraform v1.6 in schematics workspace

- ibm/service/cos/resource_ibm_cos_bucket.go
Contributes to: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5404
- fixes  s3_endpoint_public url output when endpoint_type is set to private
Output from acceptance testing: In progress
> fix public endpoint output for cos bucket

- CHANGELOG.md
- version/version.go
> Bump up verison to 1.67.0-beta0

- CHANGELOG.md
- version/version.go
> Bump up verison to 1.67.0-beta1

- ibm/service/iampolicy/resource_ibm_iam_user_invite.go
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5462
> ignore the case sensitive of email

- ibm/provider/provider.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_host_group.go
- ibm/service/power/resource_ibm_pi_host_group_test.go
- website/docs/r/pi_host_group.html.markdown
```
=== RUN   TestAccIBMPIHostGroupBasic
--- PASS: TestAccIBMPIHostGroupBasic (172.38s)
PASS
...
```
> [Resource] Add HostGroup

- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_shared_processor_pool.go
- website/docs/r/pi_shared_processor_pool.html.markdown
> [Resource]Add host_id to SPP

- ibm/service/vpc/resource_ibm_is_vpn_gateway_connection_test.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connections.go
```
--- PASS: TestAccIBMISVPNGatewayConnection_advanced (392.10s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     394.942s
```
> fix(vpngwc): bug fix for local and peer

- .secrets.baseline
> Mark secrets as false positive

- CHANGELOG.md
- version/version.go
> Bump up verison to 1.67.0

- ibm/service/project/data_source_ibm_project.go
- ibm/service/project/resource_ibm_project.go
> fix plugin crash for projects

- ibm/service/cos/resource_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket_test.go
Regression result :
[Uploading TF_PR5481_regression_result.docx…]()
> Fix for adding retention rule issue for existing bucket

- CHANGELOG.md
- version/version.go
> Bump up version to 1.67.1

- website/docs/d/scc_control_libraries.html.markdown
- website/docs/d/scc_control_library.html.markdown
- website/docs/d/scc_instance_settings.html.markdown
- website/docs/d/scc_latest_reports.html.markdown
- website/docs/d/scc_profile.html.markdown
- website/docs/d/scc_profile_attachment.html.markdown
- website/docs/d/scc_profiles.html.markdown
- website/docs/d/scc_provider_type.html.markdown
- website/docs/d/scc_provider_type_collection.html.markdown
- website/docs/d/scc_provider_type_instance.html.markdown
- website/docs/d/scc_provider_types.html.markdown
- website/docs/d/scc_report.html.markdown
- website/docs/d/scc_report_controls.html.markdown
- website/docs/d/scc_report_evaluations.html.markdown
- website/docs/d/scc_report_resources.html.markdown
- website/docs/d/scc_report_rule.html.markdown
- website/docs/d/scc_report_summary.html.markdown
- website/docs/d/scc_report_tags.html.markdown
- website/docs/d/scc_report_violation_drift.html.markdown
- website/docs/d/scc_rule.html.markdown
- website/docs/r/scc_control_library.html.markdown
- website/docs/r/scc_instance_settings.html.markdown
- website/docs/r/scc_profile.html.markdown
- website/docs/r/scc_profile_attachment.html.markdown
- website/docs/r/scc_provider_type_instance.html.markdown
- website/docs/r/scc_rule.html.markdown
- Changed the note described
Closes #5455
Closes #5290
```
...
```
> Changing the documentation for SCC

- CHANGELOG.md
- version/version.go
> Bump up version to 1.68.0-beta0

- website/docs/r/pi_instance.html.markdown
> Update Doc for E1080 Support

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Release 1.68.0

- CHANGELOG.md
- version/version.go
> Bump up version to 1.68.1

- ibm/service/catalogmanagement/data_source_ibm_cm_catalog.go
- ibm/service/catalogmanagement/data_source_ibm_cm_object.go
- ibm/service/catalogmanagement/data_source_ibm_cm_offering.go
- ibm/service/catalogmanagement/data_source_ibm_cm_offering_instance.go
- ibm/service/catalogmanagement/data_source_ibm_cm_preset.go
- ibm/service/catalogmanagement/data_source_ibm_cm_version.go
- ibm/service/catalogmanagement/resource_ibm_cm_catalog.go
- ibm/service/catalogmanagement/resource_ibm_cm_object.go
- ibm/service/catalogmanagement/resource_ibm_cm_offering.go
- ibm/service/catalogmanagement/resource_ibm_cm_offering_instance.go
- ibm/service/catalogmanagement/resource_ibm_cm_validation.go
- ibm/service/catalogmanagement/resource_ibm_cm_version.go
> fix: updated error messages

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Release 1.69.0-beta0

- go.mod
- website/docs/r/pi_image.html.markdown
Relates OR Closes #5047
```
...
```
> [Doc]Update pi_image doc

- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5568
> Fix the update of service-ednpoints for resources

- website/docs/r/onboarding_catalog_deployment.html.markdown
- website/docs/r/onboarding_catalog_plan.html.markdown
- website/docs/r/onboarding_catalog_product.html.markdown
- website/docs/r/onboarding_iam_registration.html.markdown
- website/docs/r/onboarding_product.html.markdown
- website/docs/r/onboarding_registration.html.markdown
- website/docs/r/onboarding_resource_broker.html.markdown
> fix(partner center sell): add experimental note to pcs resources

- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
Contribute to: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5601
- for async instance update: the wait logic needs to look at `instance.LastOperation.state` instead of `instance.state`
- updated deprecated functions.
- error message update for consistency.
run below cases:
```
TF_ACC=1 go test . -v …
```
> fix: wait for async instance update (for BNPP)

- website/docs/r/is_subnet_reserved_ip.html.markdown
> Updated ibm_is_subnet_reserved_ip docs

- ibm/service/kubernetes/data_source_ibm_container_cluster.go
- ibm/service/kubernetes/data_source_ibm_container_cluster_test.go
Closes #5611
```
=== RUN   TestAccIBMContainerClusterDataSource_basic
--- PASS: TestAccIBMContainerClusterDataSource_basic (1126.84s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes      1130.480s
I've executed a manual test too with the following steps
- created a classic cluster with 1 …
```
> move waitForCluster to the beginning of the cluster datasource read

- website/docs/d/is_vpn_gateway_connection.html.markdown
- website/docs/d/is_vpn_gateway_connections.html.markdown
- website/docs/r/is_vpn_gateway_connection.html.markdown
Relates OR Closes #5609
```
...
```
> Updated documents for vpn gateway connection

- website/docs/guides/binding-services.html.md
- website/docs/r/container_bind_service.html.markdown
We discourage using `ibm_container_bind_service` as it will be deprecated.
Replicating what `ibm_container_bind_service` does in several smaller steps.
> discourage use of ibm_container_bind_service

- ibm/acctest/acctest.go
- ibm/service/iampolicy/data_source_ibm_iam_policy_assignment_test.go
- ibm/service/iampolicy/resource_ibm_iam_policy_assignment.go
- ibm/service/iampolicy/resource_ibm_iam_policy_assignment_test.go
- website/docs/d/iam_policy_assignment.html.markdown
- website/docs/r/policy_assignment.html.markdown
> IAM Policy Assignment: S2S Policy Assignments ET and AG

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_workspace.go
- ibm/service/power/data_source_ibm_pi_workspaces.go
- ibm/service/power/ibm_pi_constants.go
- website/docs/d/pi_workspace.html.markdown
- website/docs/d/pi_workspaces.html.markdown
Update to 1.8.3
```
=== RUN   TestAccIBMPIWorkspaceDataSourceBasic
--- PASS: TestAccIBMPIWorkspaceDataSourceBasic (19.91s)
PASS
```
> [Datasource] Workspace NSG

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Release 1.71.0-beta0

- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_snapshots.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
> re-ordered catalog offering on is_snapshot(s)

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Release 1.71.0

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_backup_policy_jobs.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_attachments.go
- ibm/service/vpc/data_source_ibm_is_dedicated_host_groups.go
- ibm/service/vpc/data_source_ibm_is_dedicated_host_profiles.go
- ibm/service/vpc/data_source_ibm_is_dedicated_hosts.go
- ibm/service/vpc/data_source_ibm_is_floating_ips.go
- ibm/service/vpc/data_source_ibm_is_instance_groups.go
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/data_source_ibm_is_private_path_service_gateway_account_policies.go
- ibm/service/vpc/data_source_ibm_is_private_path_service_gateway_endpoint_gateway_bindings.go
- ibm/service/vpc/data_source_ibm_is_private_path_service_gateways.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interface_ips.go
- ibm/service/vpc/data_source_ibm_is_vpc_address_prefixes.go
- ibm/service/vpc/data_source_ibm_is_vpn_server_clients.go
- ibm/service/vpc/data_source_ibm_is_vpn_server_routes.go
- ibm/service/vpc/data_source_ibm_is_vpn_servers.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIbmIsDedicatedHostProfilesDataSourceBasic'
=== RUN   TestAccIbmIsDedicatedHostProfilesDataSourceBasic
--- PASS: TestAccIbmIsDedicatedHostProfilesDataSourceBasic (30.20s)
PASS
ok …
```
> migrated vpc-go-sdk to 0.62.0

- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_deployment.go
- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_plan.go
- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_product.go
- ibm/service/partnercentersell/resource_ibm_onboarding_iam_registration.go
- ibm/service/partnercentersell/resource_ibm_onboarding_iam_registration_test.go
- ibm/service/partnercentersell/resource_ibm_onboarding_product.go
> fix(partner center sell): fix patch nested fields

- ibm/service/database/resource_ibm_database.go
- website/docs/r/database.html.markdown
https://github.ibm.com/compose/App/issues/1523
- Remove force new when version changes 
- Validate the version on plan 
- Notify customer they should update version to match remote
```
...
```
Example of when db is changed on IBM side
Example of user trying to update minor version …
> Add version validation

- ibm/service/power/data_source_ibm_pi_sap_profile.go
- ibm/service/power/data_source_ibm_pi_sap_profiles.go
Out of acceptance tests:
```
--- PASS: TestAccIBMPISAPProfileDataSourceBasic (9.31s)
PASS
--- PASS: TestAccIBMPISAPProfilesDataSourceBasic (11.36s)
PASS
```
> Fix sap profile datasource warning

- website/docs/d/is_bare_metal_server_network_interface_floating_ip.markdown
- website/docs/d/is_bare_metal_server_network_interface_floating_ips.markdown
- website/docs/d/is_instance_disk.html.markdown
- website/docs/d/is_instance_disks.html.markdown
- website/docs/d/is_placement_group.html.markdown
- website/docs/d/is_placement_groups.html.markdown
- website/docs/r/is_instance_disk_management.html.markdown
> fixed documents for is datasources

- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template_test.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template_version.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template_version_test.go
> [Fix] enable commit while creating template/version

- website/docs/r/resource_instance.html.markdown
> Updates doc for `ibm_resource_instance` - "lite" is no longer a supported COS plan

- go.mod
- go.sum
- ibm/service/database/data_source_ibm_database_connection.go
Ticket: https://github.ibm.com/compose/App/issues/1471
- Bump go-sdk version
- Remove unused function
```
...
```
> update(cloud-databases): Bump sdk version

- website/docs/r/pi_capture.html.markdown
- website/docs/r/pi_image.html.markdown
- website/docs/r/pi_image_export.html.markdown
> Add Chenai to image documentation

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Release 1.72.0-beta0

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_datacenter.go
- ibm/service/power/data_source_ibm_pi_datacenter_test.go
- ibm/service/power/data_source_ibm_pi_datacenters.go
- ibm/service/power/data_source_ibm_pi_datacenters_test.go
- website/docs/d/pi_datacenter.html.markdown
- website/docs/d/pi_datacenters.html.markdown
pi_datacenters (d)
```
=== RUN   TestAccIBMPIDatacenterDataSourcePrivate
--- PASS: TestAccIBMPIDatacenterDataSourcePrivate (22.04s)
PASS
```
```
=== RUN   TestAccIBMPIDatacenterDataSourceBasic
--- PASS: TestAccIBMPIDatacenterDataSourceBasic (10.14s)
PASS
```
pi_datacenters (d)
```
=== RUN …
```
> [Datasource] Add power private datacenter capabilities

- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_cluster_network_attachment.html.markdown
- website/docs/r/is_instance_template.html.markdown
> fixed instance, instance template documents, alignment

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Release 1.72.0

- CHANGELOG.md
- version/version.go
Release minor version for breaking change of ICD
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5859
> Bump up version to 1.72.1

- CHANGELOG.md
- version/version.go
> Bump up version to 1.72.2

- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_volume_onboarding.go
- ibm/service/power/resource_ibm_pi_volume_onboarding_test.go
- website/docs/r/pi_volume_onboarding.html.markdown
```
--- PASS: TestAccIBMPIVolumeOnboardingbasic (17.47s)
PASS
```
> [Refactor] Resource Volume Onboarding

- examples/openshift-data-foundation/addon/4.17.0/README.md
- examples/openshift-data-foundation/addon/4.17.0/createaddon.sh
- examples/openshift-data-foundation/addon/4.17.0/createcrd.sh
- examples/openshift-data-foundation/addon/4.17.0/deleteaddon.sh
- examples/openshift-data-foundation/addon/4.17.0/deletecrd.sh
- examples/openshift-data-foundation/addon/4.17.0/ibm_odf_addon/main.tf
- examples/openshift-data-foundation/addon/4.17.0/main.tf
- examples/openshift-data-foundation/addon/4.17.0/ocscluster/main.tf
- examples/openshift-data-foundation/addon/4.17.0/schematics.tfvars
- examples/openshift-data-foundation/addon/4.17.0/updatecrd.sh
- examples/openshift-data-foundation/addon/4.17.0/updateodf.sh
- examples/openshift-data-foundation/addon/4.17.0/variables.tf
- examples/openshift-data-foundation/satellite/odf-local/4.17/README.md
- examples/openshift-data-foundation/satellite/odf-local/4.17/input.tfvars
- examples/openshift-data-foundation/satellite/odf-local/4.17/main.tf
- examples/openshift-data-foundation/satellite/odf-local/4.17/variables.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.17/README.md
- examples/openshift-data-foundation/satellite/odf-remote/4.17/input.tfvars
- examples/openshift-data-foundation/satellite/odf-remote/4.17/main.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.17/variables.tf
> ODF 4.17 initial support

- ibm/service/power/resource_ibm_pi_image_export.go
- ibm/service/power/resource_ibm_pi_image_export_test.go
- website/docs/r/pi_image_export.html.markdown
```
=== RUN   TestAccIBMPIImageExport
--- PASS: TestAccIBMPIImageExport (1748.92s)
PASS
```
> Refactor Image Export

- examples/ibm-logs-routing/README.md
- ibm/conns/config.go
- website/docs/guides/custom-service-endpoints.html.md
> Add Custom Endpoints for Logs Routing

- ibm/conns/config.go
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4843
> Fix the private endpoint construction based on CSE endpoints

- ibm/service/power/resource_ibm_pi_instance.go
Require system-type to be set if deployment-target is set.
> Add sap deployment target check

- ibm/service/power/resource_ibm_pi_spp_placement_group.go
- ibm/service/power/resource_ibm_pi_spp_placement_group_test.go
- website/docs/r/pi_spp_placement_group.html.markdown
```
=== RUN   TestAccIBMPISPPPlacementGroupBasic
--- PASS: TestAccIBMPISPPPlacementGroupBasic (1148.60s)
PASS
```
> Power SPPP Refactor

- ibm/service/power/data_source_ibm_pi_network_port.go
- ibm/service/power/resource_ibm_pi_network_port_attach.go
- website/docs/d/pi_network_port.html.markdown
- website/docs/r/pi_network_port_attach.html.markdown
> Deprecate network port data source and resource

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_host.go
- ibm/service/power/data_source_ibm_pi_host_test.go
- ibm/service/power/data_source_ibm_pi_hosts.go
- ibm/service/power/data_source_ibm_pi_hosts_test.go
- ibm/service/power/resource_ibm_pi_host.go
- ibm/service/power/resource_ibm_pi_host_group.go
- ibm/service/power/resource_ibm_pi_host_test.go
- ibm/service/power/resource_ibm_pi_instance.go
- website/docs/d/pi_host.html.markdown
- website/docs/d/pi_hosts.html.markdown
- website/docs/r/pi_host.html.markdown
- website/docs/r/pi_host_group.html.markdown
pi_host (r)
```
=== RUN   TestAccIBMIHostBasic
--- PASS: TestAccIBMIHostBasic (77.36s)
PASS
=== RUN   TestAccIBMIHostUserTags
--- PASS: TestAccIBMIHostUserTags (109.45s)
PASS
```
pi_host_group (r)
```
=== RUN   TestAccIBMPIHostGroupBasic
--- PASS: TestAccIBMPIHostGroupBasic (66.91s)
PASS
```
pi_host (d) …
> Granular CRN for dedicated hosts

- website/docs/r/pi_image.html.markdown
> [Documentation] Remove pi_image_name in pi_image resource catalog copy image example

- ibm/provider/provider.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_test.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profiles.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profiles_test.go
- website/docs/d/iam_trusted_profile.html.markdown
- website/docs/d/iam_trusted_profiles.html.markdown
```
$ make testacc TESTARGS
.
.
.
=== RUN   TestAccIBMIAMTrustedProfileDataSourceBasic
--- PASS: TestAccIBMIAMTrustedProfileDataSourceBasic (42.20s)
PASS
.
.
.
=== RUN   TestAccIBMIamTrustedProfilesDataSourceBasic
--- PASS: TestAccIBMIamTrustedProfilesDataSourceBasic (31.56s)
PASS
...
```
> new error messages for TP datasources

- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_link.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_links.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_links_test.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_link.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_link_test.go
- website/docs/d/iam_trusted_profile_link.html.markdown
- website/docs/r/iam_trusted_profile_link.html.markdown
```
$ make testacc TESTARGS
=== RUN   TestAccIBMIAMTrustedProfileLinkBasic
--- PASS: TestAccIBMIAMTrustedProfileLinkBasic (39.85s)
PASS
ok 
.
.
.
=== RUN   TestAccIBMIAMTrustedProfileLinkAllArgs
--- PASS: TestAccIBMIAMTrustedProfileLinkAllArgs (55.61s)
PASS
ok 
.
.
.
=== RUN …
```
> fix(identity) new error messages for TP link

- ibm/service/iamidentity/resource_ibm_iam_trusted_profile.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_test.go
- website/docs/r/iam_trusted_profile.html.markdown
```
$ make testacc 
=== RUN   TestAccIBMIamTrustedProfileBasic
--- PASS: TestAccIBMIamTrustedProfileBasic (79.41s)
PASS
.
.
.
=== RUN   TestAccIBMIamTrustedProfileAllArgs
--- PASS: TestAccIBMIamTrustedProfileAllArgs (73.85s)
PASS
...
```
> fix(identity) new error messages for TP resource

- ibm/service/vpc/data_source_ibm_is_share_snapshot.go
- ibm/service/vpc/data_source_ibm_is_share_snapshots.go
- website/docs/d/is_share_snapshot.html.markdown
- website/docs/r/is_share.html.markdown
- website/docs/r/is_share_snapshot.html.markdown
> fix(share-snap): Fix docs and missing item in data source

- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/catalogmanagement/data_source_ibm_cm_account.go
- ibm/service/catalogmanagement/data_source_ibm_cm_account_test.go
- ibm/service/catalogmanagement/data_source_ibm_cm_catalog.go
- ibm/service/catalogmanagement/resource_ibm_cm_account.go
- ibm/service/catalogmanagement/resource_ibm_cm_account_test.go
- ibm/service/catalogmanagement/resource_ibm_cm_catalog.go
- ibm/service/catalogmanagement/resource_ibm_cm_validation.go
- ibm/service/catalogmanagement/resource_ibm_cm_validation_test.go
- website/docs/d/cm_account.html.markdown
- website/docs/d/cm_catalog.html.markdown
- website/docs/r/cm_account.html.markdown
- website/docs/r/cm_catalog.html.markdown
<details>
<summary>Output from acceptance testing:</summary>
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMCmCatalogBasic -timeout 700m 
=== RUN   TestAccIBMCmCatalogBasic
--- PASS: TestAccIBMCmCatalogBasic (17.20s)
==> Checking that code complies …
```
> feat: new catalog account resource, fix validation

- ibm/service/iampolicy/resource_ibm_iam_authorization_policy.go
- ibm/service/iampolicy/resource_ibm_iam_authorization_policy_test.go
Signed-off-by: Hari Arla <hariarla@in.ibm.com>
Signed-off-by: Rajesh Pirati <rajesh.pirati@ibm.com>
Relates OR Closes #4016 
```
=== RUN   TestAccIBMIAMAuthorizationPolicyUpdate_Basic
--- PASS: TestAccIBMIAMAuthorizationPolicyUpdate_Basic (38.84s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/iampolicy …
```
> Support of update authorization policy

- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_claim_rule.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_claim_rule_test.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profiles_claim_rules.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profiles_claim_rules_test.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_claim_rule.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_claim_rule_test.go
```
=== RUN   TestAccIBMIAMTrustedProfileClaimRuleAllArgs
--- PASS: TestAccIBMIAMTrustedProfileClaimRuleAllArgs (115.52s)
PASS
ok  
.
.
.
=== RUN   TestAccIBMIAMTrustedProfileClaimRuleDataSourceAllArgs
--- PASS: …
```
> fix(identity) new error messages for TP claim rules

- website/docs/r/pag_instance.html.markdown
> Updating timeouts on pag_instance.html.markdown

- ibm/service/iamidentity/resource_ibm_iam_trusted_profile.go
> fix(identity) rolling back id to profile_id

- ibm/service/iamidentity/resource_ibm_iam_trusted_profile.go
> fix(identity) Trusted profile history field error

- ibm/service/power/resource_ibm_pi_network_security_group_rule.go
This NSG check prevents protocol of "icmp" and "all" to be set with destination and source ports. Currently, sb does not guard against it and just ignores it.
```
│ Error: failed to add rule to network security group cf25915e-3161-4afa-842d-12e011a9ac45: [POST /v1/network-security-groups/{network_security_group_id}/rules][500] v1NetworkSecurityGroupsRulesPostInternalServerError {"description":"unable to add network security group rule for network security group cf25915e-3161-4afa-842d-12e011a9ac45: unable to add network security group rule to network security group cf25915e31614afa842d12e011a9ac45 in workspace 1395da3700964b7b9960bbff6d12c65c: [POST /powernc/v2/nsg/add_rule_nsg/cloud-accounts/{cloudAccountID}/service-instances/{serviceInstanceID}/nsg/{nsg32}][500] …
```
> Add NSG protocol check

- ibm/service/schematics/resource_ibm_schematics_action.go
- ibm/service/schematics/resource_ibm_schematics_inventory.go
- ibm/service/schematics/resource_ibm_schematics_job.go
- ibm/service/schematics/resource_ibm_schematics_resource_query.go
ps: http://github.com/IBM-Cloud/terraform-provider-ibm/issues/6057
> removed validation of location for sch resources and ds

- ibm/service/power/resource_ibm_pi_network_security_group_action.go
- ibm/service/power/resource_ibm_pi_network_security_group_action_test.go
```
=== RUN   TestAccIBMPINetworkSecurityGroupActionBasicReverse
--- PASS: TestAccIBMPINetworkSecurityGroupActionBasicReverse (55.21s)
PASS
=== RUN   TestAccIBMPINetworkSecurityGroupActionBasic
--- PASS: TestAccIBMPINetworkSecurityGroupActionBasic (56.39s)
PASS
```
> [Resource] Fix NSG Action Crashes

- ibm/service/power/ibm_pi_constants.go
This PR removes unused constants in ibm_pi_constants.go.
> Remove unused constants in the code

- website/docs/r/is_vpn_gateway.html.markdown
Relates OR Closes #6049
```
...
```
> updated is_vpn_gateway documentation for public gateway

- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
> Added tdx confidential compute mode support for instance and template

- website/docs/r/is_network_acl_rule.html.markdown
> Updated documents for ibm_is_network_acl_rule

- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_deployment.go
- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_plan.go
- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_product.go
- ibm/service/partnercentersell/resource_ibm_onboarding_iam_registration.go
- website/docs/r/onboarding_catalog_deployment.html.markdown
- website/docs/r/onboarding_catalog_plan.html.markdown
- website/docs/r/onboarding_catalog_product.html.markdown
- website/docs/r/onboarding_iam_registration.html.markdown
- website/docs/r/onboarding_product.html.markdown
> feat(partner center sell): less restriction on global catalog object names

- ibm/service/vpc/resource_ibm_is_volume.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVolume_basic'
--- PASS: TestAccIBMISVolume_basic (93.74s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     95.623s
```
> fix: update issue on is_volume name update

- CHANGELOG.md
- version/version.go
> Bump up version to 1.77.1

- ibm/service/cis/data_source_ibm_cis_rulesets.go
- ibm/service/cis/resource_ibm_cis_ruleset.go
> fix(CIS): fix ep ruleset override enable issue

- ibm/service/vpc/data_source_ibm_is_flow_log.go
- ibm/service/vpc/data_source_ibm_is_flow_logs.go
- ibm/service/vpc/resource_ibm_is_flow_log.go
> enhancement: improved error handling for is_flow_log

- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_snapshot_clone.go
- ibm/service/vpc/data_source_ibm_is_snapshot_clones.go
- ibm/service/vpc/data_source_ibm_is_snapshot_consistency_group.go
- ibm/service/vpc/data_source_ibm_is_snapshot_consistency_groups.go
- ibm/service/vpc/data_source_ibm_is_snapshots.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
- ibm/service/vpc/resource_ibm_is_snapshot_consistency_group.go
> enhancement: improved error handling for vpc snapshot

- ibm/service/vpc/data_source_ibm_is_public_gateway.go
- ibm/service/vpc/data_source_ibm_is_public_gateways.go
- ibm/service/vpc/resource_ibm_is_public_gateway.go
> enhancement: improved error handling for vpc public gateway

- ibm/service/vpc/data_source_ibm_is_placement_group.go
- ibm/service/vpc/data_source_ibm_is_placement_groups.go
- ibm/service/vpc/resource_ibm_is_placement_group.go
> enhancement: improved error handling for vpc placement groups

- ibm/service/vpc/data_source_ibm_is_operating_system.go
- ibm/service/vpc/data_source_ibm_is_operating_systems.go
> enhancement: improved error handling for vpc operating system

- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_vpc.go
- ibm/service/vpc/data_source_ibm_is_vpc_address_prefix.go
- ibm/service/vpc/data_source_ibm_is_vpc_address_prefixes.go
- ibm/service/vpc/data_source_ibm_is_vpc_default_routing_table.go
- ibm/service/vpc/data_source_ibm_is_vpc_dns_resolution_binding.go
- ibm/service/vpc/data_source_ibm_is_vpc_dns_resolution_bindings.go
- ibm/service/vpc/data_source_ibm_is_vpc_routing_table.go
- ibm/service/vpc/data_source_ibm_is_vpc_routing_table_route.go
- ibm/service/vpc/data_source_ibm_is_vpc_routing_table_routes.go
- ibm/service/vpc/data_source_ibm_is_vpc_routing_tables.go
- ibm/service/vpc/data_source_ibm_is_vpcs.go
- ibm/service/vpc/resource_ibm_is_vpc.go
- ibm/service/vpc/resource_ibm_is_vpc_address_prefix.go
- ibm/service/vpc/resource_ibm_is_vpc_dns_resolution_binding.go
- ibm/service/vpc/resource_ibm_is_vpc_routing_table.go
- ibm/service/vpc/resource_ibm_is_vpc_routing_table_route.go
> enhancement: improved error handling for vpc

- ibm/service/dnsservices/resource_ibm_private_dns_glb_monitor.go
- website/docs/r/dns_glb_monitor.html.markdown
> fix(PDNS): Add GLB healthcheck 3XX, 4XX and 5XX responses

- website/docs/r/iam_access_group_template.html.markdown
- website/docs/r/iam_access_group_template_version.html.markdown
> fix(doc): iam access groups template example

- ibm/service/resourcecontroller/data_source_ibm_resource_instance.go
harinireddy@Harinis-MacBook-Pro resource-instance % terraform1.5 init       
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of ibm-cloud/ibm from the dependency lock file
- Using previously-installed ibm-cloud/ibm v1.65.0
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
harinireddy@Harinis-MacBook-Pro resource-instance % terraform1.5 apply …
> Migrate from bluemix-go to platform-go sdk for global catalog calls

- website/docs/r/trusted_profile_template.html.markdown
- website/docs/r/trusted_profile_template_assignment.html.markdown
> fix(doc): iam trusted profiles templates examples

- website/docs/r/iam_policy_template.html.markdown
- website/docs/r/iam_policy_template_version.html.markdown
> fix(doc): iam_policy_template example docs

- website/docs/r/account_settings_template.html.markdown
- website/docs/r/account_settings_template_assignment.html.markdown
> fix(doc): iam account settings template example docs

- ibm/service/hpcs/resource_ibm_hpcs_key_template.go
- ibm/service/hpcs/resource_ibm_hpcs_keystore.go
- ibm/service/hpcs/resource_ibm_hpcs_managed_key.go
- ibm/service/hpcs/resource_ibm_hpcs_vault.go
> fix: Correct missing instance_id and region after import

- ibm/conns/config.go
```
harinireddy@Harinis-MBP resource-instance % terraform1.5 apply
data.ibm_resource_instance.test4: Reading...
data.ibm_resource_instance.test3: Reading...
data.ibm_resource_instance.test: Reading...
data.ibm_resource_instance.test1: Reading...
data.ibm_resource_instance.test2: Reading...
data.ibm_resource_instance.test3: Read complete after 9s [id=crn:v1:bluemix:public:hs-crypto:us-south:a/1f7277194bb748cdb1d35fd8fb85a7cb:75ea4ef3-2bb4-4f29-bd0e-7e6623076593::]
data.ibm_resource_instance.test2: Read complete after 9s [id=crn:v1:bluemix:public:secrets-manager:eu-gb:a/1f7277194bb748cdb1d35fd8fb85a7cb:d53e26db-b7c1-461d-94e6-8de136174d04::]
data.ibm_resource_instance.test1: Read complete after 9s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/1f7277194bb748cdb1d35fd8fb85a7cb:c638ed …
```
> Use the same env key(bluemix-go) for global catalog and fix the path

- ibm/service/vpc/resource_ibm_is_security_group_target.go
> Fix ibm_is_security_group_target error message

- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_network.go
```
--- PASS: TestAccIBMPINetworkbasic (75.55s)
PASS
--- PASS: TestAccIBMPINetworkGatewaybasic (89.50s)
PASS
--- PASS: TestAccIBMPINetworkGatewaybasicSatellite (78.26s)
PASS
--- PASS: TestAccIBMPINetworkDHCPbasic (112.06s)
PASS
--- PASS: TestAccIBMPINetworkUserTags (81.36s)
PASS
--- PASS: …
```
> [Resource] Add retry to pi network create and delete

- ibm/conns/config.go
Fix the regression of constructing Global Catalog Prrivate endpoint
> Fix the regression of private endpoint for GC

- go.mod
- go.sum
- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_plan.go
- ibm/service/partnercentersell/resource_ibm_onboarding_catalog_product.go
- website/docs/r/onboarding_catalog_plan.html.markdown
- website/docs/r/onboarding_catalog_product.html.markdown
> feat(partner center sell): less restriction on catalog product media item

- ibm/service/eventstreams/resource_ibm_event_streams_topic.go
based on this document: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/guides/custom-service-endpoints
customer could configure their cloud endpoints via a file which take precedence of environment variables.
Event Streams's token provider needs to honor that configuration to access IAM endpoint to obtain bearer token.
Output from …
> fix: Event Streams tokenProvider needs to honor configuration for IAMEndpoint

- ibm/service/vpc/data_source_ibm_is_instance_group.go
- ibm/service/vpc/data_source_ibm_is_instance_group_manager.go
- ibm/service/vpc/data_source_ibm_is_instance_group_manager_action.go
- ibm/service/vpc/data_source_ibm_is_instance_group_manager_actions.go
- ibm/service/vpc/data_source_ibm_is_instance_group_manager_policies.go
- ibm/service/vpc/data_source_ibm_is_instance_group_manager_policy.go
- ibm/service/vpc/data_source_ibm_is_instance_group_managers.go
- ibm/service/vpc/data_source_ibm_is_instance_group_membership.go
- ibm/service/vpc/data_source_ibm_is_instance_group_memberships.go
- ibm/service/vpc/data_source_ibm_is_instance_groups.go
- ibm/service/vpc/resource_ibm_is_instance_group.go
- ibm/service/vpc/resource_ibm_is_instance_group_manager.go
- ibm/service/vpc/resource_ibm_is_instance_group_manager_action.go
- ibm/service/vpc/resource_ibm_is_instance_group_manager_policy.go
- ibm/service/vpc/resource_ibm_is_instance_group_membership.go
> enhancement: improved error handling for vpc instance group

- ibm/service/vpc/data_source_ibm_is_vpn_server.go
- ibm/service/vpc/data_source_ibm_is_vpn_server_client.go
- ibm/service/vpc/data_source_ibm_is_vpn_server_client_config.go
- ibm/service/vpc/data_source_ibm_is_vpn_server_clients.go
- ibm/service/vpc/data_source_ibm_is_vpn_server_route.go
- ibm/service/vpc/data_source_ibm_is_vpn_server_routes.go
- ibm/service/vpc/data_source_ibm_is_vpn_servers.go
- ibm/service/vpc/resource_ibm_is_vpn_server.go
- ibm/service/vpc/resource_ibm_is_vpn_server_client.go
- ibm/service/vpc/resource_ibm_is_vpn_server_route.go
> fix(vpnserver): update error toolchain for vpn servers

- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateway_ips.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateways.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway_ip.go
> fix(error-toolchain): update endpoint gateway resources and datasources

- ibm/provider/provider.go
- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip_patch.go
> fix: subnet reserved ip patch validation

- website/docs/index.html.markdown
Relates OR Closes #5040
```
...
```
> docs: fixed provider docs with image and profile changes

- website/docs/r/is_virtual_endpoint_gateway.html.markdown
> docs: fixed ibm_is_virtual_endpoint_gateway resource document

- website/docs/r/is_security_group.html.markdown
> fix ibm_is_security_group import description

- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
> enhancement: improved error handling for vpc instance template

- ibm/service/vpc/data_source_ibm_is_virtual_network_interface.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interface_floating_ip.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interface_floating_ips.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interface_ip.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interface_ips.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interfaces.go
- ibm/service/vpc/resource_ibm_is_virtual_network_interface.go
- ibm/service/vpc/resource_ibm_is_virtual_network_interface_floating_ip.go
- ibm/service/vpc/resource_ibm_is_virtual_network_interface_ip.go
> enhancement: improved error handling for vpc virtual network interfaces

- ibm/service/vpc/data_source_ibm_is_network_acl.go
- ibm/service/vpc/data_source_ibm_is_network_acl_rule.go
- ibm/service/vpc/data_source_ibm_is_network_acl_rules.go
- ibm/service/vpc/data_source_ibm_is_network_acls.go
- ibm/service/vpc/resource_ibm_is_network_acl_rule.go
- ibm/service/vpc/resource_ibm_is_networkacls.go
> enhancement: improved error handling for vpc network acl

- ibm/service/vpc/data_source_ibm_is_security_group.go
- ibm/service/vpc/data_source_ibm_is_security_group_rule.go
- ibm/service/vpc/data_source_ibm_is_security_group_rules.go
- ibm/service/vpc/data_source_ibm_is_security_group_target.go
- ibm/service/vpc/data_source_ibm_is_security_group_targets.go
- ibm/service/vpc/data_source_ibm_is_security_groups.go
- ibm/service/vpc/resource_ibm_is_security_group.go
- ibm/service/vpc/resource_ibm_is_security_group_rule.go
- ibm/service/vpc/resource_ibm_is_security_group_target.go
> enhancement: improved error handling for vpc security group

- CHANGELOG.md
- version/version.go
> Bump up version to 1.79.2

- ibm/service/cos/resource_ibm_cos_backup_policy.go
> Removing the unnecessary comments

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Bump up version to v1.80.0

- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_shared_processor_pool.go
- website/docs/r/pi_instance.html.markdown
- website/docs/r/pi_shared_processor_pool.html.markdown
> Update terraform docs with new systems

- .secrets.baseline
- CHANGELOG.md
- version/version.go
> Bump up version to V1.80.1

- CHANGELOG.md
- version/version.go
> Bump up version to 1.80.3

- ibm/service/directlink/data_source_ibm_dl_export_route_filter.go
- ibm/service/directlink/data_source_ibm_dl_export_route_filter_test.go
- ibm/service/directlink/data_source_ibm_dl_gateway.go
- ibm/service/directlink/data_source_ibm_dl_import_route_filter.go
- ibm/service/directlink/data_source_ibm_dl_import_route_filter_test.go
- ibm/service/directlink/data_source_ibm_dl_locations.go
- ibm/service/directlink/data_source_ibm_dl_route_report.go
- ibm/service/directlink/data_source_ibm_dl_routers.go
- ibm/service/directlink/resource_ibm_dl_gateway.go
- ibm/service/directlink/resource_ibm_dl_gateway_action.go
- ibm/service/directlink/resource_ibm_dl_gateway_virtual_connection.go
- ibm/service/directlink/resource_ibm_dl_provider_gateway.go
- ibm/service/directlink/resource_ibm_dl_route_report.go
> fix(directlink): update error toolchain changes for direct link

- CHANGELOG.md
- version/version.go
> Bump up version to 1.81.0-beta0

- ibm/acctest/acctest.go
- ibm/service/hpcs/data_source_ibm_hpcs.go
- ibm/service/hpcs/data_source_ibm_hpcs_test.go
```
$ export TESTARGS="-run TestAccIBMHPCSDatasourceBasic"
$ export HPCS_INSTANCE_NAME="HPCS - hefritz Test Issue 1039 2"
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMHPCSDatasourceBasic -timeout 700m
... …
```
> Support trusted profile token for hpcs

- CHANGELOG.md
- version/version.go
> Bump up version to 1.81.0

- CHANGELOG.md
- version/version.go
> Bump up version to 1.81.1

- website/docs/d/pi_volume_flash_copy_mappings_html.markdown
> Update Volume Flash Copy Doc

- CHANGELOG.md
- version/version.go
> bump up verison to 1.82.1

- go.mod
- go.sum
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_link.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_link.go
- website/docs/d/iam_trusted_profile_link.html.markdown
- website/docs/r/iam_trusted_profile_link.html.markdown
```
..
=== RUN   TestAccIBMIAMTrustedProfileLinkBasic
--- PASS: TestAccIBMIAMTrustedProfileLinkBasic (45.19s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/iamidentity	48.879s
..
...
```
> feat(identity): profile link additional param

- ibm/service/iampolicy/data_source_ibm_iam_service_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_service_policy.go
```
$   make testacc TEST=./ibm/service/iampolicy TESTARGS="-run TestAccIBMIAMServicePolicy"
...
=== RUN   TestAccIBMIAMServicePolicyDataSource_Basic
--- PASS: TestAccIBMIAMServicePolicyDataSource_Basic (86.86s)
=== RUN   TestAccIBMIAMServicePolicyDataSource_Multiple_Policies
--- PASS: …
```
> update service, trusted id policies

- ibm/service/power/data_source_ibm_pi_sap_profiles.go
- website/docs/d/pi_sap_profiles.html.markdown
@yussufsh and @hkantare please review this. I've added the "do not merge" label. It will be removed around the 22nd of September.
```
--- PASS: TestAccIBMPISAPProfilesDataSourceBasic (10.90s)
PASS
--- PASS: TestAccIBMPISAPProfilesDataSourceFilters (10.00s)
PASS
```
> Add sr3 profile to sap data source

- ibm/service/power/resource_ibm_pi_instance.go
- website/docs/r/pi_instance.html.markdown
@yussufsh and @hkantare  please review this. I've added the "do not merge" label. It will be removed around the 22nd of September.
Updates sap documentation.
> Update supported sap systems documentation

- website/docs/d/is_public_address_range.html.markdown
- website/docs/d/is_public_address_ranges.html.markdown
- website/docs/r/is_public_address_range.html.markdown
> docs(public-address-range): public address range SA to GA doc fix

- ibm/service/iamidentity/data_source_ibm_iam_user_mfa_enrollments.go
> removed unwanted print causing provider failure

- go.mod
- go.sum
- ibm/conns/config.go
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/6488
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/6487
> fix the refresh token issue

- CHANGELOG.md
- version/version.go
> Bump up version to 1.83.1

- ibm/service/catalogmanagement/resource_ibm_cm_account.go
- ibm/service/catalogmanagement/resource_ibm_cm_account_test.go
- website/docs/r/cm_account.html.markdown
- Fix to check the correct argument capitalization in the update for `hide_ibm_cloud_catalog`.
- Updated the docs for the cm_account resource to include the arguments and fix the attributes list.
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMCmAccountBasic -timeout 700m 
=== RUN …
```
> fix: correct argument capitalization, update cm account doc

- CHANGELOG.md
- version/version.go
> Bump up version to 1.83.2
