ibm/data_source_ibm_container_cluster_config_test.go
ibm/data_source_ibm_container_cluster_test.go
ibm/data_source_ibm_container_cluster_worker_test.go
ibm/provider_test.go
ibm/resource_ibm_container_bind_service_test.go
ibm/resource_ibm_container_cluster_test.go

Enhance the UAT for cluster to take inputs datacenter,vlan,machine type

Enhance the UAT for cluster to take inputs datacenter,vlan,machine type

---

ibm/resource_ibm_lb_vpx.go
website/docs/r/lb_vpx.html.markdown

set management_ip_address attribute on softlayer_lb_vpx resource

---

ibm/resource_ibm_lb_vpx_service.go
vendor/github.com/minsikl/netscaler-nitro-go/datatypes/datatypes.go
vendor/vendor.json
website/docs/r/lb_vpx_service.html.markdown

related issue:
https://github.com/softlayer/terraform-provider-softlayer/issues/169
related pull request:
https://github.com/softlayer/terraform-provider-softlayer/pull/174
depends on:
https://github.com/minsikl/netscaler-nitro-go/pull/1 ✅ 
~~https://github.com/softlayer/softlayer-go/pull/65~~

Support configuring usip setting for vpx service

---

website/docs/d/iam_user_policy.html.markdown

@ashishth09 All edits were transferred successfully from my fork to this branch! Looks great. Thanks for that. Made this PR for one file (d/iam_user_policy) that needed a final edit. 
I think /tree/doc-edits is ready to be merged otherwise.

update to d/iam_user_policy

---

website/docs/d/cloud_functions_action.html.markdown
website/docs/d/cloud_functions_package.html.markdown
website/docs/d/cloud_functions_rule.html.markdown
website/docs/d/cloud_functions_trigger.html.markdown
website/docs/index.html.markdown
website/docs/r/cloud_functions_action.html.markdown
website/docs/r/cloud_functions_package.html.markdown
website/docs/r/cloud_functions_rule.html.markdown
website/docs/r/cloud_functions_trigger.html.markdown

Copyedited functions docs

---

ibm/resource_ibm_network_vlan.go
website/docs/r/network_vlan.html.markdown

Return gateway IP and cidr of primary subnet when vlan is created

---

ibm/resource_ibm_container_cluster.go
website/docs/r/container_cluster.html.markdown

Make the org and space guid optional

---

ibm/resource_ibm_network_gateway.go
ibm/resource_ibm_network_gateway_vlan_attachment_test.go

Change default process name to INTEL_SINGLE_XEON_1270_3_50
Update the UAT of gateway vlan attachment to add the vlan id's

Gateway Fixes

---

examples/ibm-compute-public-ip/main.tf
examples/ibm-lb-vpx/main.tf
ibm/data_source_ibm_compute_vm_instance_test.go
ibm/resource_ibm_compute_autoscale_group_test.go
ibm/resource_ibm_compute_autoscale_policy_test.go
ibm/resource_ibm_compute_monitor_test.go
ibm/resource_ibm_compute_vm_instance_test.go
ibm/resource_ibm_firewall_policy_test.go
ibm/resource_ibm_firewall_test.go
ibm/resource_ibm_lb_service_test.go
ibm/resource_ibm_lb_vpx_ha_test.go
ibm/resource_ibm_lb_vpx_service_test.go
ibm/resource_ibm_network_interface_sg_attachment_test.go
ibm/resource_ibm_network_public_ip_test.go
ibm/resource_ibm_network_vlan_test.go
ibm/resource_ibm_storage_block_test.go
ibm/resource_ibm_storage_file_test.go
ibm/resource_ibm_subnet_test.go
website/docs/r/compute_autoscale_group.html.markdown
website/docs/r/compute_vm_instance.html.markdown

As softlayer has deprecated DEBIAN_7_64 , updating UATs with DEBIAN_8_64

update UATs with os_reference_code DEBIAN_8_64 

---

README.md

Change Documentation link to always reference latest version

---

ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_cluster_test.go
website/docs/r/container_cluster.html.markdown

Support for disk encryption

---

ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_cluster_test.go
ibm/validators.go
website/docs/r/container_cluster.html.markdown

Add attribute worker count which conflicts with workers attribute
Create the number of workers based on the worker count

Create workers for a cluster based on the count

---

ibm/resource_ibm_lbaas.go
ibm/resource_ibm_lbaas_test.go

Allow adding protocols more than 2 during creation

---

ibm/data_source_ibm_container_cluster.go
ibm/data_source_ibm_container_cluster_config.go
ibm/data_source_ibm_container_cluster_config_test.go
ibm/data_source_ibm_container_cluster_test.go
ibm/data_source_ibm_container_cluster_versions.go
ibm/data_source_ibm_container_cluster_versions_test.go
ibm/data_source_ibm_container_cluster_worker.go
ibm/data_source_ibm_container_cluster_worker_test.go
ibm/resource_ibm_container_bind_service.go
ibm/resource_ibm_container_bind_service_test.go
website/docs/d/container_cluster.html.markdown
website/docs/d/container_cluster_config.html.markdown
website/docs/d/container_cluster_versions.html.markdown
website/docs/d/container_cluster_worker.html.markdown
website/docs/r/container_bind_service.html.markdown

Make org and space optional for container datasources and resources
Fixes #184

Container API changes

---

ibm/resource_ibm_compute_vm_instance.go
ibm/resource_ibm_compute_vm_instance_test.go

make user_metadata as force_new for vm instance

Fix Issue #226

---

ibm/resource_ibm_compute_vm_instance.go
ibm/resource_ibm_compute_vm_instance_test.go
ibm/structures.go

=== RUN   TestAccIBMComputeVmInstance_PostWindowsInstallScriptUri
The ID is 55235183
--- PASS: TestAccIBMComputeVmInstance_PostWindowsInstallScriptUri (1969.79s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ibm/ibm	1971.957s
?   	github.com/terraform-providers/terraform-provider-ibm/version	[no test files]

Fix Issue #249

---

ibm/resource_ibm_compute_bare_metal.go

add post_install_script_uri for monthly bare metal

Fix Issue #260

---

examples/ibm-cluster/main.tf
ibm/data_source_ibm_container_cluster_test.go
website/docs/r/container_bind_service.html.markdown

UAT result
--- PASS: TestAccIBMContainerClusterDataSource_basic (1783.30s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ibm/ibm	1785.255s

Fix datasource cluster UAT

---

ibm/resource_ibm_lbaas_health_moitor.go
ibm/resource_ibm_lbaas_health_monitor_test.go
ibm/resource_ibm_lbaas_test.go
ibm/structures.go

=== RUN   TestAccIBMLbaas_with_more_protocols
--- PASS: TestAccIBMLbaas_with_more_protocols (442.89s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ibm/ibm	444.674s
Some tests for that resource will fail if this is not set correctly
=== RUN   TestAccIBMLbaas_Private
--- PASS: TestAccIBMLbaas_Private (661.98s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ibm/ibm	664.617s
--- PASS: TestAccIBMLbaasHealthMonitor_tcp (1283.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ibm/ibm	1285.096s

Fix Issue 286 

---

examples/ansible/ibm_ansible_dyn_inv/README.md
examples/ansible/ibm_ansible_dyn_inv/terraform_inv.py
examples/ansible/ibm_ansible_wordpress/README.md
examples/ansible/ibm_ansible_wordpress/inventory/terraform_inv.py
examples/ibm-website-single-region/main.tf

Minor updates to fix usage issues.

Updates to examples

---

website/docs/r/storage_file.html.markdown

- Fixed a bug in the ibm_storage_file script example.
- Changed knowledge layer links to IBM Doc links.

Fixed examples and links in ibm_storage_file doc

---

ibm/resource_ibm_container_cluster.go

fixing issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/484

fixing private cluster alb hanging

---

README.md

Adding basic usage instructions to the README

---

ibm/resource_ibm_compute_bare_metal.go
website/docs/r/compute_bare_metal.html.markdown

i have actively been using and testing this change with both monthly and hourly billing, so can confirm it works as expected on hardware that supports it; specifically, the monthly SINGLE_E31270_V6 and the hourly S1270V6_16GB_1X2TB_SATA_NORAID.

add Software Guard Extensions bare metal product

---

website/docs/r/database.html.markdown

Example to get etcd connection string was missing closing brace `}`

Updated doc

---

examples/ibm-cluster/cluster-standalone-workers/variables.tf

change the cluster default from "cluster" to "mycluster"

Update variables.tf 

---

website/docs/d/resource_group.html.markdown

reosource -> resource

---

ibm/resource_ibm_lbaas.go
ibm/resource_ibm_lbaas_health_monitor.go
ibm/resource_ibm_lbaas_test.go

Proposed fix: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/715

add HTTPS backend support for lbaas and health monitor

---

ibm/resource_ibm_is_security_group_rule.go
ibm/resource_ibm_is_subnet.go

Serialize creation of subnets in the same zone and creation/deletion of rules in the same security group.

Handle parallel provisioning of subnets and security group rules

---

ibm/resource_ibm_is_instance.go

The tfstate file will be more informative.

Update instance status while waiting

---

ibm/resource_ibm_cos_bucket.go
website/docs/r/cos_bucket.html.markdown

fix issue 816

---

examples/ibm-iam-policy/README.md
examples/ibm-iam-policy/main.tf
examples/ibm-iam-policy/variables.tf
examples/ibm-iam-policy/versions.tf
ibm/data_source_ibm_iam_service_id_test.go
ibm/data_source_ibm_iam_service_policy_test.go
ibm/data_source_ibm_iam_user_policy_test.go
ibm/resource_ibm_iam_access_group_members_test.go
ibm/resource_ibm_iam_access_group_policy_test.go
ibm/resource_ibm_iam_access_group_test.go
ibm/resource_ibm_iam_authorization.policy_test.go
ibm/resource_ibm_iam_service_id_test.go
ibm/resource_ibm_iam_service_policy_test.go
ibm/resource_ibm_iam_user_policy_test.go
website/docs/d/iam_service_policy.html.markdown
website/docs/d/iam_user_policy.html.markdown
website/docs/r/iam_access_group_members.html.markdown
website/docs/r/iam_access_group_policy.html.markdown
website/docs/r/iam_authorization_policy.html.markdown
website/docs/r/iam_service_policy.html.markdown
website/docs/r/iam_user_policy.html.markdown

IAM v0.12 : Test files & Examples

IAM v0.12 : Test files & Examples

---

ibm/provider.go
ibm/provider_test.go
ibm/resource_ibm_is_image.go
ibm/resource_ibm_is_image_test.go
vendor/github.ibm.com/Bluemix/riaas-go-client/clients/compute/image.go
website/docs/r/is_images.html.markdown
website/ibm.erb

This PR is to add support for image resource.

add create/update and delete functionality for image resource

---

examples/ibm-database/README.md
examples/ibm-database/main.tf
examples/ibm-database/network.tf
examples/ibm-database/provider.tf
examples/ibm-database/versions.tf
ibm/data_source_ibm_database_test.go
ibm/resource_ibm_database_elasticsearch_test.go
ibm/resource_ibm_database_etcd_test.go
ibm/resource_ibm_database_mongodb_test.go
ibm/resource_ibm_database_postgresql_test.go
ibm/resource_ibm_database_rabbitmq_test.go
ibm/resource_ibm_database_redis_test.go
website/docs/r/database.html.markdown

Upgraded & tested database examples, test files & DOC files

Database: Upgradation to v0.12

---

examples/ibm-cis/README.md
examples/ibm-cis/dns.tf
examples/ibm-cis/outputs.tf
examples/ibm-cis/provider.tf
examples/ibm-cis/variables.tf
examples/ibm-cis/versions.tf
ibm/data_source_ibm_cis_domain_test.go
ibm/data_source_ibm_cis_test.go
ibm/resource_ibm_cis_dns_record_test.go
ibm/resource_ibm_cis_domain_settings_test.go
ibm/resource_ibm_cis_domain_test.go
ibm/resource_ibm_cis_global_load_balancer_test.go
ibm/resource_ibm_cis_healthcheck_test.go
ibm/resource_ibm_cis_origin_pool_test.go
ibm/resource_ibm_cis_test.go

Upgraded CIS resources and data sources to v0.12

CIS : Terraform V0.12 Upgrade

---

examples/ibm-cos-bucket/main.tf
examples/ibm-cos-bucket/provider.tf
examples/ibm-cos-bucket/versions.tf
ibm/resource_ibm_cos_bucket_test.go
website/docs/d/cis_domain.html.markdown
website/docs/d/cos_bucket.html.markdown
website/docs/r/cis.html.markdown
website/docs/r/cis_dns_record.html.markdown
website/docs/r/cis_domain.html.markdown
website/docs/r/cis_domain_settings.html.markdown
website/docs/r/cis_global_load_balancer.html.markdown
website/docs/r/cis_healthcheck.html.markdown
website/docs/r/cis_origin_pool.html.markdown
website/docs/r/cos_bucket.html.markdown

Upgraded the test files, examples and DOCs
Note : CIS DOCs upgradation also part of this PR

COS : v0.12 upgrade

---

ibm/resource_ibm_lbaas.go

Added resource controller to lbaas resource.

Added resource controller to lbaas resource

---

ibm/resource_ibm_network_vlan.go

fixes a regression introduced in 0f263f7b747ff7d7446dd1bb98c9db36e5d0a56d

fix null pointer dereference with unnamed VLAN

---

ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_is_vpc.go
ibm/resource_ibm_resource_instance.go
ibm/structures.go

Resource Implicit Tagging supported for
1) container_cluster
2) container_vpc_cluster
3) is_vpc
4) Resource_instance

Resource Implicit Tagging Feature Support

---

ibm/resource_ibm_is_vpc.go

Improve the error message for VPC creation

---

ibm/resource_ibm_is_ssh_key.go

Improve the error message for key creation

---

go.mod
go.sum
ibm/resource_ibm_iam_user_invite.go
vendor/github.com/IBM-Cloud/bluemix-go/api/usermanagement/usermanagementv2/models.go
vendor/modules.txt
website/docs/r/iam_user_invite.html.markdown

This PR has fix for: [user_invite resource issue](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1114)

fixed user-invite resource

---

ibm/resource_ibm_iam_user_invite.go
vendor/github.com/IBM-Cloud/bluemix-go/api/usermanagement/usermanagementv2/models.go
vendor/vendor.json
website/docs/r/iam_user_invite.html.markdown

This PR includes the fix for user invite resource issue and documentation update.

User invite 1114

---

go.mod
go.sum
ibm/data_source_ibm_container_vpc_cluster.go
ibm/resource_ibm_container_vpc_cluster.go
website/docs/d/container_vpc_cluster.html.markdown
website/docs/r/container_vpc_cluster.html.markdown

The PR has the fix for
1. https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1167
2. https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1157

updated vpc data source and resource

---

ibm/data_source_ibm_container_vpc_cluster.go
ibm/resource_ibm_container_vpc_cluster.go
website/docs/d/container_vpc_cluster.html.markdown
website/docs/r/container_vpc_cluster.html.markdown

The PR has the fix for
1. https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1167
2. https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1157

Updated vpc resource and data source

---

ibm/resource_ibm_database.go

Solved problem calling to IBM API REST

New status by IBM

---

ibm/data_source_ibm_cis.go
ibm/data_source_ibm_database.go
ibm/resource_ibm_cis.go
ibm/resource_ibm_database.go
website/docs/d/cis.html.markdown
website/docs/d/database.html.markdown
website/docs/r/cis.html.markdown
website/docs/r/database.html.markdown

Added guid attribute to cis, database resource and data sources

Added guid attribute to cis, database resource and data sources

---

ibm/data_source_ibm_cis.go
ibm/data_source_ibm_database.go
ibm/resource_ibm_cis.go
ibm/resource_ibm_database.go
website/docs/d/cis.html.markdown
website/docs/d/database.html.markdown
website/docs/r/cis.html.markdown
website/docs/r/database.html.markdown

Support fo rGUID attribute in CIS and DATABASE resources and datasources

Support fo rGUID attribute in CIS and DATABASE resources and datasources

---

go.sum
ibm/resource_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket_test.go
website/docs/d/cos_bucket.html.markdown

Support for smart buakcet type in COS

Support for smart buakcet type in COS

---

ibm/resource_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket_test.go
website/docs/d/cos_bucket.html.markdown

COS bucket : Support new storage class smart

COS bucket : Support new staorage class smart

---

ibm/resource_ibm_is_instance.go

Allow deleting a non-existing instance

---

ibm/resource_ibm_is_subnet.go

Allow deleting a non-existing subnet

---

ibm/resource_ibm_is_vpc_address_prefix.go

Allow deleting a non-existing address prefix

---

ibm/resource_ibm_is_vpc.go

Allow deleting a non-existing VPC

---

go.mod
ibm/data_source_ibm_pi_instance.go
ibm/data_source_ibm_pi_network.go
ibm/resource_ibm_pi_capture.go
ibm/resource_ibm_pi_instance.go
website/docs/d/pi_instance.html.markdown
website/docs/r/pi_instance.html.markdown

Minor Changes to the pi_instance ( resource and datasource) 
Cleaned up additional code

Updated go.mod to include the power client

---

website/docs/r/cos_bucket.html.markdown

Updated Doc with new staorage class smart for COS bucket

Updated Doc with new staorage class smart for COS bucket

---

website/docs/r/cos_bucket.html.markdown

Updated COS Doc

---

examples/ibm-private-dns/README.md
examples/ibm-private-dns/main.tf
examples/ibm-private-dns/terraform.tfvars
go.mod
go.sum
ibm/config.go
ibm/provider.go
ibm/resource_ibm_private_dns_zones.go
ibm/resource_ibm_private_dns_zones_test.go
website/docs/r/private_dns_zone.html.markdown
website/ibm.erb

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/958

Private DNS Zone resource related changes

---

examples/ibm-private-dns/main.tf
ibm/provider.go
ibm/resource_ibm_private_dns_resource_record.go
ibm/resource_ibm_private_dns_resource_record_test.go
website/docs/r/private_dns_resource_record.html.markdown
website/ibm.erb

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/958

Private DNS resource record related changes

---

ibm/resource_ibm_private_dns_resource_record.go

ibm_dns_resource_record Change of TTL has error .name in body is a forbidden property
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1331

Fix for Issue 1331

---

ibm/resource_ibm_private_dns_resource_record.go

fix: name update issue with private dns resource record

---

vendor/github.com/IBM-Cloud/bluemix-go/api/schematics/workspace.go
vendor/vendor.json

This PR has fix for schematics output values issue : https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1345

updated schematics output values model

---

go.mod
go.sum
vendor/github.com/IBM-Cloud/bluemix-go/api/certificatemanager/certificate.go
vendor/github.com/IBM-Cloud/bluemix-go/api/schematics/workspace.go
vendor/github.com/IBM-Cloud/bluemix-go/models/certificate_manager.go
vendor/modules.txt

This PR has the fix for Schematics output values issue - https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1345

vendored latest bluemix-go sdk

---

examples/ibm-is-ng/main.tf
examples/ibm-is-vpc/main.tf
ibm/provider.go
ibm/resource_ibm_is_lb_listener.go
ibm/resource_ibm_is_lb_listener_policy.go
ibm/resource_ibm_is_lb_listener_policy_rule.go
ibm/resource_ibm_is_lb_listener_policy_rule_test.go
ibm/resource_ibm_is_lb_listener_policy_test.go
ibm/resource_ibm_is_lb_pool_member.go
website/docs/r/is_lb_listener_policy_rule.html.markdown

Support for resource lb_listener_policy_rule

Support for resource lb_listener_policy_rule

---

examples/ibm-is-ng/main.tf
examples/ibm-is-vpc/main.tf
ibm/provider.go
ibm/resource_ibm_is_lb_listener.go
ibm/resource_ibm_is_lb_listener_policy.go
ibm/resource_ibm_is_lb_listener_policy_rule.go
ibm/resource_ibm_is_lb_listener_policy_rule_test.go
ibm/resource_ibm_is_lb_listener_policy_test.go
ibm/resource_ibm_is_lb_pool_member.go
website/docs/r/is_lb_listener_policy_rule.html.markdown

Added support for
1) New resource lb listener policy rule
2) DiffSuppress function for pool_member, listener and policy

Support lb listener policy rule resource

---

ibm/resource_ibm_is_lb_listener_policy_rule_test.go
ibm/resource_ibm_is_lb_listener_policy_test.go
ibm/resource_ibm_is_lb_pool.go

v12 lb listener policy and rule test files

v12 lb listener policy and rule test files

---

ibm/resource_ibm_is_lb_listener_policy_rule_test.go
ibm/resource_ibm_is_lb_listener_policy_test.go
ibm/resource_ibm_is_lb_pool.go
website/docs/r/is_lb_pool.html.markdown

v11 lb listener policy and rule test files

v11 lb listener policy and rule test files

---

go.mod
go.sum
ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_vpc_worker_pool.go
ibm/resource_ibm_container_worker_pool.go
vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv1/clusters.go
vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv1/worker_pool.go
vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv2/clusters.go
vendor/modules.txt
website/docs/r/container_cluster.html.markdown
website/docs/r/container_worker_pool.html.markdown

This PR has:
1. Entitlement feature support for Openshift cluster on ibm_container_cluster and ibm_conatiner_workerpool resources.
2. Fix for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1360
3. Fix for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1406
4. Updated Datacenter info in state cluster read method.

Cluster & worker pool entitlement feature and fixes

---

examples/ibm-private-dns/main.tf
ibm/data_source_ibm_private_dns_zones.go
ibm/data_source_ibm_private_dns_zones_test.go
ibm/provider.go
website/docs/d/private_dns_zones.html.markdown
website/ibm.erb

Changes for List private dns zones

List pdnszones

---

ibm/data_source_ibm_private_dns_zones.go

Instance Id and Zone id are swapped in list pdns zones.

Swapping instance id and zone id

---

examples/ibm-private-dns/main.tf
ibm/data_source_ibm_private_dns_resource_records.go
ibm/data_source_ibm_private_dns_resource_records_test.go
ibm/provider.go
website/docs/d/private_dns_resource_records.html.markdown
website/ibm.erb

List private pdns resource records

list pdns resource records

---

ibm/data_source_ibm_resource_instance_test.go
ibm/data_source_ibm_resource_key_test.go
ibm/resource_ibm_iam_access_group_dynamic_rule_test.go
ibm/resource_ibm_iam_authorization.policy_test.go
ibm/resource_ibm_iam_service_policy_test.go
ibm/resource_ibm_iam_user_policy_test.go
ibm/resource_ibm_resource_instance_test.go
ibm/resource_ibm_resource_key_test.go

Test files for resource_instance and IAM

Test files for resource_instance and IAM

---

ibm/resource_ibm_container_worker_pool_zone_attachment.go
website/docs/r/container_worker_pool_zone_attachment.html.markdown

added wait_till_albs attribute in worker_pool_zone_attachment resource.

added wait_till_albs attribute

---

ibm/resource_ibm_container_worker_pool_zone_attachment.go
website/docs/r/container_worker_pool_zone_attachment.html.markdown

added wait_till_albs param

---

ibm/data_source_ibm_iam_service_policy_test.go
ibm/data_source_ibm_iam_user_policy_test.go
ibm/resource_ibm_iam_access_group_policy_test.go
ibm/resource_ibm_iam_service_policy_test.go
ibm/resource_ibm_iam_user_policy_test.go

IAM test case fixes

---

ibm/resource_ibm_is_security_group_rule.go
ibm/resource_ibm_is_security_group_rule_test.go

Security Group Rule fix: allow 'Any' type for ICMP, TCP, UDP

---

ibm/resource_ibm_is_floating_ip_test.go

Add a test case for #1521

---

ibm/data_source_ibm_container_vpc_cluster.go
vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv1/clusters.go
vendor/github.com/IBM-Cloud/power-go-client/clients/instance/ibm-pi-cloud-instance.go
vendor/github.com/IBM-Cloud/power-go-client/clients/instance/ibm-pi-instance.go
vendor/github.com/IBM-Cloud/power-go-client/clients/instance/ibm-pi-snapshot.go
vendor/github.com/IBM-Cloud/power-go-client/helpers/constants.go
vendor/modules.txt

This pr has the Fix for 
1. VPC cluster data source.(#1528 )
2. VPC cluster config data source.

fixed vpc cluster data sources for ROKS

---

examples/ibm-cluster/roks-on-vpc-gen2/README.md
examples/ibm-cluster/roks-on-vpc-gen2/cloud_object_store/cos_service.tf
examples/ibm-cluster/roks-on-vpc-gen2/cloud_object_store/outputs.tf
examples/ibm-cluster/roks-on-vpc-gen2/cloud_object_store/varaibles.tf
examples/ibm-cluster/roks-on-vpc-gen2/main.tf
examples/ibm-cluster/roks-on-vpc-gen2/provider.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/outputs.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/roks_on_vpc.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/variables.tf
examples/ibm-cluster/roks-on-vpc-gen2/variables.tf
examples/ibm-cluster/roks-on-vpc-gen2/versions.tf
go.mod
go.sum
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_container_vpc_cluster_test.go
vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv2/clusters.go
vendor/modules.txt
website/docs/r/container_vpc_cluster.html.markdown

This PR has
1.  fix for ROKS on VPC gen-2.(https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1543)
2. Updated Docs
3. Example

ROKS on VPC

---

examples/ibm-cluster/roks-on-vpc-gen2/README.md
examples/ibm-cluster/roks-on-vpc-gen2/cloud_object_store/cos_service.tf
examples/ibm-cluster/roks-on-vpc-gen2/cloud_object_store/outputs.tf
examples/ibm-cluster/roks-on-vpc-gen2/cloud_object_store/varaibles.tf
examples/ibm-cluster/roks-on-vpc-gen2/main.tf
examples/ibm-cluster/roks-on-vpc-gen2/provider.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/outputs.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/roks_on_vpc.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/variables.tf
examples/ibm-cluster/roks-on-vpc-gen2/variables.tf
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_container_vpc_cluster_test.go
vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv2/clusters.go
vendor/vendor.json
website/docs/r/container_vpc_cluster.html.markdown

Roks on vpc fix v11

---

examples/ibm-cluster/cluster-worker-pool-zone/README.md
examples/ibm-cluster/cluster-worker-pool-zone/main.tf
examples/ibm-cluster/cluster-worker-pool-zone/variables.tf
examples/ibm-cluster/vpc-classic-cluster/README.md
examples/ibm-cluster/vpc-classic-cluster/variables.tf
examples/ibm-cluster/vpc-gen2-cluster/README.md
examples/ibm-cluster/vpc-gen2-cluster/variables.tf

Cluster Doc README Update

---

examples/ibm-cluster/roks-on-vpc-gen2/README.md
examples/ibm-cluster/roks-on-vpc-gen2/main.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/roks_on_vpc.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/variables.tf
examples/ibm-cluster/roks-on-vpc-gen2/variables.tf

updated example

---

examples/ibm-transit-gateway/README.md
examples/ibm-transit-gateway/main.tf
examples/ibm-transit-gateway/terraform.tfvars
examples/ibm-transit-gateway/variables.tf
ibm/config.go
ibm/provider.go
ibm/resource_ibm_tg_gateway.go
ibm/resource_ibm_tg_gateway_test.go
website/docs/r/tg_gateway.html.markdown
website/ibm.erb

This PR adds support for Transit Gateway Creation

Transit Gateway Creation (resource) changes

---

ibm/data_source_ibm_private_dns_permitted_network.go
ibm/data_source_ibm_private_dns_resource_records.go
ibm/data_source_ibm_private_dns_zones.go
ibm/resource_ibm_private_dns_permitted_network.go
ibm/resource_ibm_private_dns_resource_record.go
ibm/resource_ibm_private_dns_zones.go
website/docs/r/private_dns_zone.html.markdown

Changes for defect 1624 - resource ibm_dns_zone instance_id takes the ibm_resource_instance.x.guid not the id

Defect 1624

---

examples/ibm-cluster/cluster-worker-pool-zone/main.tf
examples/ibm-cluster/cluster-worker-pool-zone/variables.tf
examples/ibm-cluster/vpc-classic-cluster/variables.tf
examples/ibm-cluster/vpc-gen2-cluster/variables.tf
go.sum

Updated Cluster examples

---

examples/ibm-transit-gateway/main.tf
ibm/data_source_ibm_tg_location.go
ibm/data_source_ibm_tg_location_test.go
ibm/provider.go
website/docs/d/tg_location.html.markdown
website/ibm.erb

Datasource changes of TG specific location with name

Tg location

---

examples/ibm-is-ng/main.tf
examples/ibm-is-vpc/main.tf
ibm/data_source_ibm_is_vpc.go
ibm/data_source_ibm_is_vpc_test.go
ibm/resource_ibm_is_vpc.go
ibm/resource_ibm_is_vpc_test.go
website/docs/d/is_vpc.html.markdown
website/docs/r/is_vpc.html.markdown

Given VPC name list dwon al lthe security groups and corresponding rules
Test result :
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
sg_rule_icmp = [
{
"group_id" = "r006-50a5383c-0750-4d2b-b544-a8e07f1bdc37"
"group_name" = "overlook-engraver-geologist-debtless-remember-unopposed"
"rules" = [
{
"code" = 0
"direction" = "outbound"
"ip_version" = "ipv4"
"port_max" = 0
"port_min" = 0
"protocol" = "all"
"remote" = "0.0.0.0/0"
"rule_id" = "r006-7f8157e7-98b9-4ef2-bfc8-60215e486f93"
"type" = 0
},
{
"code" = 0
"direction" = "inbound"
"ip_version" = "ipv4"
"port_max" = 0
"port_min" = 0
"protocol" = "all"
"remote" = "overlook-engraver-geologist-debtless-remember-unopposed"
"rule_id" = "r006-02cdd951-1399-4975-ae29-c73976f57e6e"
"type" = 0
},
]
},
{
"group_id" = …

Given VPC name list dwon al lthe security groups and corresponding rules

---

ibm/resource_ibm_resource_instance.go
ibm/resource_ibm_service_instance.go
website/docs/r/resource_instance.html.markdown
website/docs/r/service_instance.html.markdown

Added Dashboard url in tfstate file
ISSUE : https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1682

Issue: 1682 Added Dashboard url in tfstate file

---

ibm/resource_ibm_is_lb.go

Correct spelling error

---

ibm/resource_ibm_container_vpc_cluster.go
website/docs/r/container_vpc_cluster.html.markdown

This PR is in reference to  #1681 
I ported over the feature from the `ibm_container_cluster resource`.

flag to control if workers are reloaded

---

ibm/resource_ibm_container_cluster.go

fixed issue with gateway enabled cluster

fixed issue with gateway enabled cluster

---

.github/workflows/go.yml
examples/ibm-ansible-samples/ibm_ansible_dyn_inv/README.md
examples/ibm-ansible-samples/ibm_ansible_dyn_inv/terraform_inv.py

Updated the ansible dynamic inventory sample to support terraform v0.12 tfstate file format

tfstate syntax version 4 support

---

ibm/data_source_ibm_iam_users.go
ibm/data_source_ibm_iam_users_test.go
ibm/provider.go
website/docs/d/iam_users.html.markdown

DataSource: Fetch all invited users profile
Test Results:

DataSource: Fetch all invited users profile

---

examples/ibm-cos-bucket/README.md
examples/ibm-cos-bucket/main.tf
examples/ibm-cos-bucket/variables.tf
examples/ibm-resource-instance/README.md
examples/ibm-resource-instance/main.tf
examples/ibm-resource-instance/variables.tf

Updated README DOC  for cos bucket and resource instance

README UPDATE: COS Bucket & Resource Instance

---

go.sum
ibm/data_source_ibm_iam_user_policy.go
ibm/data_source_ibm_iam_user_policy_test.go
ibm/data_source_ibm_iam_user_profile.go
ibm/data_source_ibm_iam_user_profile_test.go
ibm/resource_ibm_iam_access_group_members.go
ibm/resource_ibm_iam_user_policy.go
ibm/resource_ibm_iam_user_settings.go
ibm/resource_ibm_iam_user_settings_test.go
ibm/structures.go

Fix for ip restriction https://github.ibm.com/csenablement/hamiltonde…

Fix for ip restriction for IBM clould from Invited account

---

examples/ibm-is-flow-log/README.md
examples/ibm-is-flow-log/main.tf
examples/ibm-is-flow-log/variables.tf
ibm/provider.go
ibm/resource_ibm_is_flow_log.go
ibm/resource_ibm_is_flow_log_test.go
website/docs/r/is_flow_log.html.markdown
website/ibm.erb

Added resource for vpc flow logs.

---

ibm/resource_ibm_is_flow_log.go
ibm/resource_ibm_is_flow_log_test.go

Fix the bug in flowlog resource active parameter

Flowlog resource active parameter

---

ibm/resource_ibm_pi_network_port.go

Fixes #1823
Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>

Using the helpers contants

---

ibm/resource_ibm_is_flow_log_test.go

Added Flow log test case COS Authorization policy for jenkins job

Flow log test case COS Authorization permission

---

ibm/resource_ibm_pi_instance.go

Fixes #1833
Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>

Check and include the virtual cores

---

examples/ibm-cluster/cluster-standalone-workers/main.tf
examples/ibm-cluster/cluster-worker-pool-zone/main.tf
examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/roks_on_vpc.tf
examples/ibm-cluster/vpc-classic-cluster/main.tf
examples/ibm-cluster/vpc-gen2-cluster/main.tf

Updated cluster examples with crk key_id in kms_config

Updated cluster examples with crk key_id in kms_config

---

ibm/resource_ibm_is_instance_template.go

fix for - https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1886

fix for issue 1886

---

ibm/resource_ibm_pi_instance.go

Use network ids as list

---

ibm/resource_ibm_is_instance_group.go
ibm/resource_ibm_is_instance_group_manager.go
website/docs/r/is_instance_group.html.markdown

This PR has the fix for 
1. autoscale resource validator functions.
2. Handling the instance count update scenario for managed instance group.

vpc-autoscale fixes

---

examples/ibm-is-vpc/main.tf
ibm/provider.go
ibm/resource_ibm_is_lb.go
ibm/resource_ibm_is_lb_pool_member.go
ibm/resource_ibm_is_lb_pool_member_test.go
ibm/resource_ibm_is_lb_test.go
website/docs/r/is_lb.html.markdown
website/docs/r/is_lb_pool_member.html.markdown

Network Load Balancer resource changes

Nlb changes

---

ibm/resource_ibm_cdn.go

Github Issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1925

Return appropriate error message from CDN delete function

---

ibm/resource_ibm_pi_instance.go

Handle instance error condition

---

ibm/resource_ibm_is_instance_group.go
website/docs/r/is_instance_group.html.markdown

updated instance group 'name' argument

updated instance group 'name' argument

---

ibm/data_source_ibm_database.go
ibm/data_source_ibm_database_test.go
website/docs/d/database.html.markdown
website/docs/r/database.html.markdown

Connects to #1985 
What's included:
- Support for writing certificate to local file
- Test
- Documentation
- Minor typo fix

feat(data_source_ibm_database): Add cert_file_path

---

go.mod
go.sum
ibm/resource_ibm_cos_bucket.go
vendor/github.com/IBM/ibm-cos-sdk-go-config/common/version.go
vendor/github.com/IBM/ibm-cos-sdk-go-config/resourceconfigurationv1/resource_configuration_v1.go
vendor/modules.txt

COS_BUCKET: Fix for empty allowed_ip

---

go.mod
go.sum
ibm/data_source_ibm_pi_network_port.go
ibm/resource_ibm_pi_network_port.go
ibm/resource_ibm_pi_network_port_attach.go
website/docs/r/pi_network_port.html.markdown

Updated the network_port to include the public_ip

---

go.mod
go.sum
ibm/data_source_ibm_dl_gateway.go
ibm/data_source_ibm_dl_gateways.go
ibm/data_source_ibm_dl_locations.go
ibm/data_source_ibm_dl_offering_speeds.go
ibm/resource_ibm_dl_gateway.go

Changes for enhanced security in Direct Link Gateway

Changes for enhanced security in DL Gateway

---

ibm/data_source_ibm_is_image.go
ibm/data_source_ibm_is_images.go
ibm/provider_test.go
ibm/resource_ibm_is_image.go
ibm/resource_ibm_is_image_test.go
website/docs/d/is_image.html.markdown
website/docs/d/is_images.html.markdown
website/docs/r/is_images.html.markdown

Changes for VPC Encrypted Image

VPC Encrypted Image changes

---

ibm/resource_ibm_event_streams_topic_test.go

1. remove destroy check for existing instance
2. refine the instance destroy check to avoid nil instance

test: remove destroy check for existing instance

---

examples/ibm-is-vpc/main.tf
ibm/resource_ibm_is_instance.go
ibm/resource_ibm_is_instance_template.go
ibm/resource_ibm_is_subnet.go
ibm/resource_ibm_is_vpc_routing_table.go
ibm/resource_ibm_is_vpc_routing_table_route.go
ibm/resource_ibm_is_vpc_routing_table_route_test.go
ibm/resource_ibm_is_vpc_routing_table_test.go
website/docs/r/is_instance.html.markdown
website/docs/r/is_instance_template.html.markdown
website/docs/r/is_subnet.html.markdown
website/docs/r/is_vpc_routing_table.html
website/docs/r/is_vpc_routing_table_route.html
website/ibm.erb

Custom Route, Anti Spoofing, Ingress Terraform provider support

Custom Route, Anti Spoofing, Ingress Terraform provider support

---

ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_vpc_cluster.go

The PR addresses the kube_version and update_all_workers issue.
Kube version upgrade cases:
cluster created with version x.
* case-1:
Change in `kube_version` x to version y and `update_all_workers` is set to default value false.
on terraform apply - only kube version change is identified and only the master node's version is updated to y.
* case-2:
master node version is y, worker nodes are in version x and update_all_worker_nodes is set to true.
on terraform apply, since no change in the kube_version master update is excluded and  goes to update_all_worker_node.
if there is version difference between master and any of the worker node, that node will be updated.
* case-3:	
kube_version of master and worker nodes is y, `update_all_workers` is set to true. user updates the kube_version …

kube_version update changes

---

go.mod
go.sum
ibm/resource_ibm_iam_user_invite.go
vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv1/clusters.go
vendor/github.com/IBM-Cloud/bluemix-go/api/iamuum/iamuumv2/access_group.go
vendor/modules.txt
website/docs/r/iam_user_invite.html.markdown

user_invite: Fetch IAM policies & access groups for invited users

---

website/docs/r/private_dns_permitted_network.html.markdown
website/docs/r/private_dns_resource_record.html.markdown

private dns documentation change from id to guid

private dns documentation change from id to guid

---

examples/ibm-direct-link/main.tf
ibm/data_source_ibm_dl_gateway_test.go
ibm/data_source_ibm_dl_gateways_test.go
ibm/resource_ibm_dl_gateway.go
ibm/resource_ibm_dl_gateway_test.go
ibm/resource_ibm_dl_gateway_virtual_connection_test.go
website/docs/d/dl_gateway.html.markdown
website/docs/d/dl_gateways.html.markdown
website/docs/r/dl_gateway.html.markdown
website/docs/r/is_lb.html.markdown
website/docs/r/is_lb_listener.html.markdown
website/docs/r/is_lb_listener_policy.html.markdown
website/docs/r/is_lb_listener_policy_rule.html.markdown

Direct Link Connect test case failure, bgp_base_cidr optional field, NLB documentation

Direct Link Connect test case failure, bgp_base_cidr optional field, NLB documentation

---

examples/ibm-cos-bucket/README.md
examples/ibm-cos-bucket/main.tf
examples/ibm-cos-bucket/variables.tf
ibm/data_source_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket_test.go
ibm/structures.go
website/docs/d/cos_bucket.html.markdown
website/docs/r/cos_bucket.html.markdown

- Added support for COS expire.  expire_rule attributed added to resource_ibm_cos_bucket
- Expire rules limit each set to 1,000
closes #1590 
closed #2068

Cos expire

---

ibm/resource_ibm_cos_bucket.go

Added jp_osa to the endpoints and region_location parameters. This way the resource creation won't fail.

Added jp_osa

---

ibm/structures.go

Fix Issue #2151

---

ibm/data_source_ibm_is_subnet.go

issue 2058 Update data_source_ibm_is_subnet.go

---

ibm/data_source_ibm_dl_ports.go
ibm/data_source_ibm_dl_ports_test.go
website/docs/d/dl_ports.html.markdown

Fix for issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2175

added location param and pagination to directlink ports

---

ibm/provider_test.go
ibm/resource_ibm_is_lb_listener.go
ibm/resource_ibm_is_lb_listener_policy.go
ibm/resource_ibm_is_lb_listener_policy_rule.go
ibm/resource_ibm_is_lb_pool.go
ibm/resource_ibm_is_lb_pool_member.go

issue 2168 Handle LB creation with counter greater than 1

---

website/docs/d/pi_cloud_instance.html.markdown
website/docs/d/pi_image.html.markdown
website/docs/d/pi_images.html.markdown
website/docs/d/pi_instance.html.markdown
website/docs/d/pi_instance_ip.html.markdown
website/docs/d/pi_instance_volumes.html.markdown
website/docs/d/pi_key.html.markdown
website/docs/d/pi_network.html.markdown
website/docs/d/pi_public_network.html.markdown
website/docs/d/pi_tenant.html.markdown
website/docs/d/pi_volume.html.markdown
website/docs/r/pi_image.html.markdown
website/docs/r/pi_instance.html.markdown
website/docs/r/pi_key.html.markdown
website/docs/r/pi_network.html.markdown
website/docs/r/pi_network_port.html.markdown
website/docs/r/pi_snapshot.html.markdown
website/docs/r/pi_volume.html.markdown

Doc Update: Region and Zone Info for PI

---

examples/ibm-is-ng/main.tf
ibm/data_source_ibm_is_volume_profile.go
ibm/data_source_ibm_is_volume_profile_test.go
ibm/data_source_ibm_is_volume_profiles.go
ibm/data_source_ibm_is_volume_profiles_test.go
ibm/provider.go
ibm/provider_test.go
website/docs/d/is_volume_profile.html.markdown
website/docs/d/is_volume_profiles.html.markdown
website/ibm.erb

issue 1992 added data source for volume profile

---

website/docs/r/container_vpc_cluster.html.markdown
website/docs/r/is_lb_listener_policy.html.markdown
website/docs/r/is_virtual_endpoint_gateway_ip.html.markdown

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2229
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2224
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2169

Doc Fix: is_lb_listener_policy and container_vpc_cluster resources

---

ibm/data_source_ibm_iam_service_policy.go
ibm/data_source_ibm_iam_service_policy_test.go
ibm/data_source_ibm_iam_user_policy.go
ibm/data_source_ibm_iam_user_policy_test.go
website/docs/d/iam_service_id.html.markdown
website/docs/d/iam_service_policy.html.markdown
website/docs/d/iam_user_policy.html.markdown

Adding sort feature in terraform provider ibm
Co-authored-by: Rajesh Pirati <Rajesh.Pirati@ibm.com>
Co-authored-by: Rudrasish Pradhan <rudrasish.pradhan@ibm.com>
Co-authored-by: Bhavana Bellamgari <bhavana.bellamgari@ibm.com>

Adding sort feature in terraform

---

ibm/resource_ibm_container_addons.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2295

Fix: Show diff on version update

---

ibm/data_source_ibm_container_cluster.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2300

Fix #2300: Skip list ALbs on free cluster

---

ibm/data_source_ibm_is_lb.go
ibm/resource_ibm_is_lb.go
ibm/resource_ibm_is_lb_test.go
website/docs/d/is_lb.html.markdown
website/docs/r/is_lb.html.markdown

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2228

Allow Logging feature of ibm_is_lb to be controlled via terraform #2228

---

ibm/data_source_ibm_is_subnet.go
ibm/resource_ibm_is_subnet.go
ibm/resource_ibm_is_subnet_test.go
website/docs/d/is_subnet.html.markdown
website/docs/r/is_subnet.html.markdown

added tag support for ibm_is_subnet

enhancement:tag support for subnet

---

ibm/resource_ibm_container_addons.go
ibm/resource_ibm_container_cluster_test.go
ibm/resource_ibm_container_vpc_worker_pool.go

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2346

Fix: cluster addons

---

ibm/data_source_ibm_is_security_group.go
ibm/data_source_ibm_is_security_group_test.go
ibm/resource_ibm_is_security_group.go
ibm/resource_ibm_is_security_group_test.go
website/docs/d/is_security_group.html.markdown
website/docs/r/is_security_group.html.markdown

Added tagging support for security group

enhancement: added tag support for is_security_group

---

ibm/data_source_ibm_is_lb.go
ibm/resource_ibm_is_lb.go
ibm/resource_ibm_is_lb_test.go
website/docs/d/is_lb.html.markdown
website/docs/r/is_lb.html.markdown

https://jiracloud.swg.usma.ibm.com:8443/browse/UI-15674

lb and sg integration

---

ibm/resource_ibm_is_vpc.go

Fix for  [2364](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2364)

enhancement: added regex validation for tags

---

ibm/data_source_ibm_is_vpc_routing_table_routes.go
ibm/resource_ibm_is_vpc_routing_table_route.go
website/docs/d/is_vpc_routing_table_routes.html.markdown
website/docs/r/is_vpc_routing_table_route.html.markdown

Add vpn connection as next hop for a vpc routing table route

---

ibm/resource_ibm_is_lb.go

@hkantare Can you please review this PR

[Enhancement] lb update supporting sg change

---

website/allowed-subcategories.txt

IAM is an acronym for "Identity and Access Management". Currently the "Management" piece is missing. Adding this to the subcategory.
Reference: https://cloud.ibm.com/docs/account?topic=account-iamoverview

Update IAM name

---

go.mod
go.sum
ibm/provider.go
ibm/resource_ibm_ob_logging.go
ibm/resource_ibm_ob_logging_test.go
ibm/resource_ibm_ob_monitoring.go
ibm/resource_ibm_ob_monitoring_test.go
website/docs/r/ob_logging.html.markdown
website/docs/r/ob_monitoring.html.markdown

Observability plugin support

---

ibm/resource_ibm_cos_bucket.go

Fix: cos_bucket

---

website/docs/r/ob_logging.html.markdown

Corrected ob logging doc

---

ibm/resource_ibm_is_dedicated_host.go

issue 2446 dedicated host destroying on failed state handled

---

ibm/data_source_ibm_is_dedicated_hosts.go
website/docs/d/is_dedicated_hosts.html.markdown

Description and doc modified for dedicated hosts data source host group attribute

---

website/docs/r/container_cluster.html.markdown
website/docs/r/pi_instance.html.markdown

Doc Fix for container_cluster and pi_instance

---

examples/ibm-Catalog Management/README.md
examples/ibm-Catalog Management/main.tf
examples/ibm-Catalog Management/outputs.tf
examples/ibm-Catalog Management/variables.tf
examples/ibm-Catalog Management/versions.tf
ibm/data_source_ibm_cm_catalog.go
ibm/data_source_ibm_cm_catalog_test.go
ibm/data_source_ibm_cm_offering.go
ibm/data_source_ibm_cm_offering_instance.go
ibm/data_source_ibm_cm_offering_instance_test.go
ibm/data_source_ibm_cm_offering_test.go
ibm/data_source_ibm_cm_version.go
ibm/data_source_ibm_cm_version_test.go
ibm/provider.go
ibm/resource_ibm_cm_catalog.go
ibm/resource_ibm_cm_catalog_test.go
ibm/resource_ibm_cm_offering.go
ibm/resource_ibm_cm_offering_instance_test.go
ibm/resource_ibm_cm_offering_test.go
ibm/resource_ibm_cm_version.go
ibm/resource_ibm_cm_version_test.go
website/allowed-subcategories.txt
website/docs/d/cm_catalog.html.markdown
website/docs/d/cm_offering.html.markdown
website/docs/d/cm_offering_instance.html.markdown
website/docs/d/cm_version.html.markdown
website/docs/r/cm_catalog.html.markdown
website/docs/r/cm_offering.html.markdown
website/docs/r/cm_offering_instance.html.markdown
website/docs/r/cm_version.html.markdown

You can run the acceptance tests with the following environment variables-
export CATMGMT_CLUSTERID="<cluster-id-roks-cluster>"
export CATMGMT_CLUSTERREGION="<region-of-roks-cluster>"
export TESTARGS="-run TestAccIBMCm"
export IBMCLOUD_IAM_API_ENDPOINT="https://iam.test.cloud.ibm.com"
export IBMCLOUD_CATALOG_MANAGEMENT_API_ENDPOINT="https://dev-cm.globalcatalog.test.cloud.ibm.com/api/v1-beta"

Support content management offerings, versions, catalogs

---

.secrets.baseline
examples/ibm-iam_identity/README.md
examples/ibm-iam_identity/main.tf
examples/ibm-iam_identity/outputs.tf
examples/ibm-iam_identity/variables.tf
examples/ibm-iam_identity/versions.tf
ibm/config.go
ibm/data_source_ibm_iam_account_settings.go
ibm/data_source_ibm_iam_account_settings_test.go
ibm/provider.go
ibm/resource_ibm_iam_account_settings.go
ibm/resource_ibm_iam_account_settings_test.go
website/docs/d/iam_account_settings.html.markdown
website/docs/r/iam_account_settings.html.markdown

Implement Account Setting api for terraform. 
https://cloud.ibm.com/apidocs/iam-identity-token-api#getaccountsettings

Implement IAM Account Settings resource

---

examples/ibm-enterprise-management/README.md
examples/ibm-enterprise-management/main.tf
examples/ibm-enterprise-management/outputs.tf
examples/ibm-enterprise-management/variables.tf
examples/ibm-enterprise-management/versions.tf
examples/test-enterprise/test.tf
examples/test-enterprise/variables.tf
ibm/config.go
ibm/data_source_ibm_enterprise_account_groups.go
ibm/data_source_ibm_enterprise_account_groups_test.go
ibm/data_source_ibm_enterprise_accounts.go
ibm/data_source_ibm_enterprise_accounts_test.go
ibm/data_source_ibm_enterprises.go
ibm/data_source_ibm_enterprises_test.go
ibm/provider.go
ibm/provider_test.go
ibm/resource_ibm_enterprise.go
ibm/resource_ibm_enterprise_account.go
ibm/resource_ibm_enterprise_account_group.go
ibm/resource_ibm_enterprise_account_group_test.go
ibm/resource_ibm_enterprise_account_test.go
ibm/resource_ibm_enterprise_test.go
ibm/validators.go
website/docs/d/enterprise_account_groups.html.markdown
website/docs/d/enterprise_accounts.html.markdown
website/docs/d/enterprises.html.markdown
website/docs/r/enterprise.html.markdown
website/docs/r/enterprise_account.html.markdown
website/docs/r/enterprise_account_group.html.markdown

@kavya498 @hkantare @meer-nasser-ali Could you please review this PR?

Add Support for Enterprise Management

---

ibm/provider.go
ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_dl_gateway.go
ibm/resource_ibm_dl_provider_gateway.go
ibm/resource_ibm_is_floating_ip.go
ibm/resource_ibm_is_flow_log.go
ibm/resource_ibm_is_image.go
ibm/resource_ibm_is_instance.go
ibm/resource_ibm_is_instance_group.go
ibm/resource_ibm_is_lb.go
ibm/resource_ibm_is_networkacls.go
ibm/resource_ibm_is_public_gateway.go
ibm/resource_ibm_is_security_group.go
ibm/resource_ibm_is_ssh_key.go
ibm/resource_ibm_is_subnet.go
ibm/resource_ibm_is_virtual_endpoint_gateway.go
ibm/resource_ibm_is_volume.go
ibm/resource_ibm_is_vpn_gateway.go
ibm/resource_ibm_resource_instance.go
ibm/resource_ibm_tg_gateway.go

added tag regex validation for all other resources supporting tag creation

added tag regex validation for all supported resources

---

website/docs/index.html.markdown

Updated the right IBM Cloud docs link to view the resources and data sources.

Updated the IBM Cloud Terraform Docs link

---

examples/ibm-cos-bucket/README.md
examples/ibm-cos-bucket/main.tf
examples/ibm-cos-bucket/variables.tf
ibm/data_source_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket_test.go
ibm/structures.go
website/docs/d/cos_bucket.html.markdown
website/docs/r/cos_bucket.html.markdown

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1880

added support for cos retention

---

go.mod
go.sum

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2358

Support: CMS certificates Pagination

---

ibm/data_source_ibm_is_vpn_gateways.go
ibm/resource_ibm_is_vpn_gateway.go
website/docs/d/is_vpn_gateways.html.markdown
website/docs/r/is_vpn_gateway.html.markdown

issue 2382 added private ip attributes to vpn gateway

---

ibm/data_source_ibm_cis_certificates.go

Fix cis primary certificate

---

go.mod
ibm/data_source_ibm_enterprise_account_groups.go
ibm/data_source_ibm_enterprise_accounts.go
website/docs/d/enterprise_account_groups.html.markdown
website/docs/d/enterprise_accounts.html.markdown
website/docs/d/enterprises.html.markdown
website/docs/r/enterprise.html.markdown
website/docs/r/enterprise_account.html.markdown
website/docs/r/enterprise_account_group.html.markdown

**Test Cases (Data source) :**
**Data source for account groups:**
=== RUN TestAccIbmAccountGroupsDataSourceBasic
--- PASS: TestAccIbmAccountGroupsDataSourceBasic (49.13s)
PASS
ok github.com/IBM-Cloud/terraform-provider-ibm/ibm 51.633s
testing: warning: no tests to run
PASS
ok github.com/IBM-Cloud/terraform-provider-ibm/ibm/internal/hashcode 0.594s [no tests …

Enterprise Management : Pagination changes and documentation updated

---

examples/ibm-is-ng/main.tf
ibm/data_source_ibm_is_public_gateways.go
ibm/data_source_ibm_is_public_gateways_test.go
ibm/provider.go
website/docs/d/is_public_gateways.html.markdown

--- PASS: TestAccIBMISPublicGatewaysDatasource_basic (122.53s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	126.115s

feature: added support for public gateways datasource

---

go.mod
go.sum
ibm/data_source_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket.go
ibm/structures.go

fix cos-retention rule

---

go.mod
go.sum
ibm/resource_ibm_is_instance_template_test.go
website/docs/r/is_instance_template.html.markdown

Closes #2198 
```
$ make testacc TESTARGS='-run=TestAccIBMISInstanceTemplate_basic'
...
```

added a note for vol attachment and added test case for instance template

---

README.md

add Terraform Registry instruction steps

---

go.mod
go.sum

Bump Up Bluemix-go latest

---

ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_container_vpc_worker_pool.go
ibm/resource_ibm_container_worker_pool.go

Enhance: 404 check in cluster and workerpool resources

---

ibm/data_source_ibm_satellite_location.go
ibm/resource_ibm_satellite_location.go
ibm/resource_ibm_satellite_location_test.go
website/docs/d/satellite_location.html.markdown
website/docs/r/satellite_location.html.markdown

add wait logic for satellite location creation

---

go.mod

Bump Up go version: 1.12 ==> 1.15

---

website/docs/d/iam_account_settings.html.markdown

Doc Fix: #2484

---

ibm/resource_ibm_is_subnet_reserved_ip.go
website/docs/d/is_subnet_reserved_ips.html.markdown
website/docs/r/is_subnet_reserved_ip.html.markdown

Doc Fix: Reserved IP

---

ibm/config.go
ibm/data_source_ibm_secrets_manager_secret.go
ibm/data_source_ibm_secrets_manager_secrets.go

Fix: Environment variables for Endpoints

---

website/docs/r/is_subnet_reserved_ip.html.markdown

Doc Fix: reservedIP

---

.github/workflows/release.yml
.goreleaser.yml

Add goreleaser and release workflow

---

ibm/provider_test.go
ibm/resource_ibm_is_instance.go
ibm/resource_ibm_is_instance_test.go
website/docs/r/is_instance.html.markdown

Relates OR Closes #2465 
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-14664
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstance_profile' 
```

[Feature] Instance Resize

---

ibm/resource_ibm_is_lb_listener_policy_rule.go
ibm/resource_ibm_is_lb_listener_policy_rule_test.go
website/docs/r/is_lb_listener_policy_rule.html.markdown

Relates OR Closes #0
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-15699
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISLBListenerPolicyRule_basic'
```

[Enhancement] Loadbalancer Parameter based routing

---

ibm/config.go

Relates  #2527
Workaround Fix.

Fix: PI Session

---

ibm/resource_ibm_resource_instance.go
ibm/resource_ibm_resource_key.go
website/docs/r/resource_key.html.markdown

Relates https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2182#issuecomment-824350837

Fix: resource_key and resource_instance resources

---

ibm/config.go

Fix: Visibility

---

common/github.ibm.com/ibmcloud/kubernetesservice-go-sdk/kubernetesserviceapiv1/kubernetes_service_api_v1.go
ibm/data_source_ibm_satellite_host_script.go

Remove authorization parameter from Attach Host script method

---

ibm/resource_ibm_is_instance.go

Relates OR Closes #2541 
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstance_profile' 
```

bugfix instance resize

---

examples/ibm-cos-bucket/README.md
examples/ibm-cos-bucket/main.tf
examples/ibm-cos-bucket/variables.tf
go.mod
go.sum
ibm/data_source_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket_test.go
ibm/structures.go
website/docs/d/cos_bucket.html.markdown
website/docs/r/cos_bucket.html.markdown

added support for request metrics in metrics monitoring

added support for cos sysdig v2(request metrics)

---

ibm/data_source_ibm_satellite_host_script.go

Fix: satellite host script for azure support

---

ibm/resource_ibm_is_instance_group_manager.go

nil check for instance group manager

---

ibm/resource_ibm_is_instance.go

```
$  make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstance_profile'
```

Enhancement: Instance restaring after Resize

---

website/docs/r/is_virtual_endpoint_gateway.html.markdown

Closes [UI-15973](https://jiracloud.swg.usma.ibm.com:8443/browse/UI-15973)

Updated the docs to replace ibm-dns-server2 with ibm-ntp-server

---

.secrets.baseline
ibm/resource_ibm_database.go

Suppress the diff on plan_validation

---

ibm/resource_ibm_is_vpc_routing_table_route.go

Fix: Import Crash

---

ibm/resource_ibm_is_vpc_routing_table.go
ibm/resource_ibm_is_vpc_routing_table_route.go

Fix: Routing table

---

website/docs/d/is_public_gateway.html.markdown
website/docs/d/is_public_gateways.html.markdown

Impacts #2549 but may not closes it.

Updated the public gateway docs as per the actual output and code

---

website/docs/r/is_image.html.markdown

Doc FIx: is_image

---

CHANGELOG.md

Remove: 1.22.1

---

website/docs/d/account.html.markdown
website/docs/d/api_gateway.html.markdown
website/docs/d/app.html.markdown
website/docs/d/app_domain_private.html.markdown
website/docs/d/app_domain_shared.html.markdown
website/docs/d/app_route.html.markdown
website/docs/d/database.html.markdown
website/docs/d/org.html.markdown
website/docs/d/org_quota.html.markdown
website/docs/d/service_instance.html.markdown
website/docs/d/service_key.html.markdown
website/docs/d/service_plan.html.markdown
website/docs/d/space.html.markdown
website/docs/r/api_gateway_endpoint.html.markdown
website/docs/r/api_gateway_endpoint_subscription.html.markdown
website/docs/r/app.html.markdown
website/docs/r/app_domain_private.html.markdown
website/docs/r/app_domain_shared.html.markdown
website/docs/r/app_route.html.markdown
website/docs/r/database.html.markdown
website/docs/r/org.html.markdown
website/docs/r/service_instance.html.markdown
website/docs/r/service_key.html.markdown
website/docs/r/space.html.markdown

Cloud docs resources and datasource of API, CF, DB migration to Registry docs 

---

ibm/data_source_ibm_is_image.go

Warn if image is deprecated

---

examples/ibm-is-ng/main.tf
go.mod
go.sum
ibm/data_source_ibm_is_instance_templates.go
ibm/provider_test.go
ibm/resource_ibm_is_instance.go
ibm/resource_ibm_is_instance_template.go
ibm/resource_ibm_is_instance_test.go
website/docs/r/is_instance.html.markdown
website/docs/r/is_instance_template.html.markdown

added Instance placement target options

---

examples/ibm-satellite/main.tf
examples/ibm-satellite/modules/location/main.tf
examples/ibm-satellite/modules/location/provider.tf
examples/ibm-satellite/modules/location/variables.tf
examples/ibm-satellite/variables.tf
ibm/data_source_ibm_satellite_location.go
ibm/data_source_ibm_satellite_location_test.go
ibm/provider.go
ibm/resource_ibm_satellite_location.go
ibm/resource_ibm_satellite_location_test.go
ibm/structures.go
website/docs/d/satellite_location.html.markdown
website/docs/r/satellite_location.html.markdown

Update satellite location resource

---

ibm/config.go
ibm/resource_ibm_database.go
ibm/resource_ibm_database_elasticsearch_test.go
ibm/resource_ibm_database_etcd_test.go
ibm/resource_ibm_database_mongodb_test.go
ibm/resource_ibm_database_postgresql_test.go
ibm/resource_ibm_database_rabbitmq_test.go
ibm/resource_ibm_database_redis_test.go

Fix for following issue
https://github.ibm.com/blueprint/schematics-support-tickets/issues/248

Fix : Wait for Database task timeout

---

ibm/config.go
ibm/utils.go

Support: CR visibility

---

ibm/resource_ibm_network_vlan.go

Increase NotFoundChecks #2613

---

ibm/resource_ibm_is_vpc.go
ibm/structures.go

new error response sample:
```
Error: Error while creating VPC {
│     "Message": "Provided Name (xyz) is not unique",
│     "StatusCode": 400,
│     "Result": {
│         "errors": [
│             {
│                 "code": "validation_unique_failed",
│                 "message": "Provided Name (xyz) is not unique",
│                 "target": {
│                     "name": "name",
│                     "type": "field",
│                     "value": "xyzzy"
│                 }
│             }
│         ],
│         "trace": "xyz"
│     }
│ }
...
```

enhancement: removed headers and raw result from response for error scenario

---

ibm/resource_ibm_cis.go
ibm/resource_ibm_database.go
ibm/resource_ibm_resource_instance.go

Fix: Remove resource from statefile for pending_reclamation state

---

go.mod
go.sum
ibm/data_source_ibm_cm_offering_instance.go
ibm/data_source_ibm_cm_offering_instance_test.go
ibm/resource_ibm_cm_offering_instance.go
website/docs/d/cm_offering_instance.html.markdown
website/docs/r/cm_offering_instance.html.markdown

```
--- PASS: TestAccIBMCmOfferingInstance (36.12s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm (cached)
testing: warning: no tests to run
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/internal/hashcode       (cached) [no tests to run]
testing: warning: no tests to run …
```

update catalog management offering instance

---

website/docs/r/container_addons.html.markdown

Doc Fix: Cluster Addons

---

go.mod
go.sum

Relates OR Closes #2651
```
--- PASS: TestAccIBMContainer_ClusterConfigDataSourceBasic (31.37s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	44.548s
```

Fix: cluster config

---

website/docs/d/is_vpn_gateways.html.markdown

doc fix: DS vpn gateway issue 2629

---

website/docs/r/is_instance.html.markdown
website/docs/r/is_volume.html.markdown
website/docs/r/is_vpc.html.markdown

documentation fix for volume encryption and vpc

---

website/docs/d/dns_glb_monitors.html.markdown
website/docs/d/dns_glb_pools.html.markdown
website/docs/d/dns_glbs.html.markdown
website/docs/d/dns_permitted_networks.html.markdown
website/docs/d/dns_resource_records.html.markdown
website/docs/d/dns_zones.html.markdown
website/docs/d/enterprise_account_groups.html.markdown
website/docs/d/enterprise_accounts.html.markdown
website/docs/d/enterprises.html.markdown
website/docs/d/event_streams_topic.html.markdown
website/docs/d/function_action.html.markdown
website/docs/d/function_namespace.html.markdown
website/docs/d/function_package.html.markdown
website/docs/d/function_rule.html.markdown
website/docs/d/function_trigger.html.markdown
website/docs/r/dns_glb.html.markdown
website/docs/r/dns_glb_monitor.html.markdown
website/docs/r/dns_glb_pool.html.markdown
website/docs/r/dns_permitted_network.html.markdown
website/docs/r/dns_resource_record.html.markdown
website/docs/r/dns_zone.html.markdown
website/docs/r/enterprise.html.markdown
website/docs/r/enterprise_account.html.markdown
website/docs/r/enterprise_account_group.html.markdown
website/docs/r/event_streams_topic.html.markdown
website/docs/r/function_action.html.markdown
website/docs/r/function_namespace.html.markdown
website/docs/r/function_package.html.markdown
website/docs/r/function_rule.html.markdown
website/docs/r/function_trigger.html.markdown

Patch 2: Edited DNS_EnterMgt_Evtstrm_funcs ds and r

---

ibm/resource_ibm_container_addons.go

Support: cluster addon version update during create

---

examples/ibm-is-ng/main.tf
ibm/data_source_ibm_is_instance_templates.go
ibm/provider_test.go
ibm/resource_ibm_is_instance_template.go
ibm/resource_ibm_is_instance_template_test.go
ibm/structures.go
website/docs/d/is_instance_templates.html.markdown
website/docs/r/is_instance_template.html.markdown

Support data volume in instance group.

---

website/docs/r/cr_namespace.html.markdown
website/docs/r/cr_retention_policy.html.markdown

DocFix: #2685

---

.secrets.baseline
website/docs/r/resource_instance.html.markdown

add dbaas example

---

ibm/resource_ibm_is_vpc.go

Fix: is_vpc resource

---

ibm/data_source_ibm_satellite_host_script.go

Added VMWare Host Provider to Satellite Host Attach Script

---

.secrets.baseline
website/docs/d/pi_instance.html.markdown
website/docs/r/pi_instance.html.markdown

Patch 5: updated only pi_instance file

---

examples/ibm-is-ng/main.tf
ibm/data_source_ibm_is_operating_system.go
ibm/data_source_ibm_is_operating_system_test.go
ibm/data_source_ibm_is_operating_systems.go
ibm/data_source_ibm_is_operating_systems_test.go
ibm/provider.go
website/docs/d/is_operating_system.html.markdown
website/docs/d/is_operating_systems.html.markdown

=== RUN   TestAccIBMISOperatingSystemDataSource_basic
--- PASS: TestAccIBMISOperatingSystemDataSource_basic (33.41s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	36.900s
=== RUN   TestAccIBMISOperatingSystemsDataSource_basic
--- PASS: TestAccIBMISOperatingSystemsDataSource_basic (27.85s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	30.597s

feature: is_operating_system datasource

---

.secrets.baseline
website/docs/r/resource_instance.html.markdown

Update dbaas example

---

.secrets.baseline
website/allowed-subcategories.txt

Add App Configuration subcategory

---

ibm/provider.go

Fix: ibm_resource_tag in provider.go

---

ibm/data_source_ibm_satellite_host_script.go

Fixed typo that prevented host_attach_script from completing.

---

ibm/data_source_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket.go
ibm/structures.go
website/docs/r/cos_bucket.html.markdown

Updated documentation and read operation

fix: COS updated object versioning & retention rule

---

go.mod
go.sum
ibm/data_source_ibm_is_instance_group_manager_action.go
ibm/data_source_ibm_is_instance_group_manager_actions.go
ibm/resource_ibm_is_instance.go
ibm/resource_ibm_is_instance_group_manager.go
ibm/resource_ibm_is_instance_group_manager_action.go

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstanceGroupManagerAction_basic'
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstanceGroupManagerAction_basic_autoscale'
```

MigrationPR: VPC-GO-SDK version to v0.7.0

---

ibm/config.go

Fix: errEmptyBluemixCredentials on generated SDK clients

---

ibm/resource_ibm_is_instance_group_manager_policy.go
ibm/resource_ibm_is_lb_listener.go
ibm/resource_ibm_is_lb_listener_policy.go
ibm/resource_ibm_is_lb_listener_policy_rule.go
ibm/resource_ibm_is_lb_pool.go
ibm/resource_ibm_is_lb_pool_member.go
ibm/resource_ibm_is_security_group_network_interface_attachment.go
ibm/resource_ibm_is_virtual_endpoint_gateway_ip.go
ibm/resource_ibm_is_vpc_address_prefix.go
ibm/resource_ibm_is_vpc_route.go
ibm/resource_ibm_is_vpc_routing_table.go
ibm/resource_ibm_is_vpc_routing_table_route.go
ibm/resource_ibm_is_vpn_gateway_connections.go

fix: added check for ID in is_resources on import

---

website/docs/r/iam_api_key.html.markdown

DocFix: IAM APIKey

---

examples/ibm-secrets-manager/README.md
website/docs/d/secrets_manager_secret.html.markdown
website/docs/d/secrets_manager_secrets.html.markdown

DocFix: Secretes Manager

---

website/docs/r/iam_access_group_policy.html.markdown
website/docs/r/iam_authorization_policy.html.markdown
website/docs/r/iam_service_policy.html.markdown
website/docs/r/iam_user_invite.html.markdown
website/docs/r/iam_user_policy.html.markdown

DocFix: Provide link to service specific roles

---

ibm/data_source_ibm_is_lbs.go

Support for Load balancer Pagination
```
...
```

Add Pagination support for LB list

---

ibm/resource_ibm_kms_key.go
ibm/resource_ibm_kms_key_alias.go
ibm/resource_ibm_kms_key_rings.go
ibm/structures.go

* Able to utilise private Endpoints and create various kms resource in private environment.
Output

KMS Private Endpoint url Bug Fix

---

go.mod
go.sum
ibm/data_source_ibm_cm_offering_instance.go
ibm/data_source_ibm_cm_offering_instance_test.go
ibm/resource_ibm_cm_offering_instance.go
ibm/resource_ibm_cm_offering_instance_test.go
website/docs/d/cm_offering_instance.html.markdown
website/docs/r/cm_offering_instance.html.markdown

```
$ make testacc TESTARGS='-run=TestAccIBMCmOfferingInstance'
=== RUN   TestAccIBMCmOfferingInstanceDataSource
--- PASS: TestAccIBMCmOfferingInstanceDataSource (56.18s)
=== RUN   TestAccIBMCmOfferingInstance
--- PASS: TestAccIBMCmOfferingInstance (49.15s)
...
```

update catalog offering instance resource and datasource

---

ibm/resource_ibm_iam_service_id.go
ibm/resource_ibm_iam_service_id_test.go
website/docs/r/iam_service_id.html.markdown

```
=== RUN   TestAccIBMIAMServiceID_Basic
--- PASS: TestAccIBMIAMServiceID_Basic (61.18s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	64.073s
```
```
=== RUN   TestAccIBMIAMServiceID_import
--- PASS: TestAccIBMIAMServiceID_import (26.53s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	29.004s
```
Closes #2560

Migrate: Service Id resource to Platform-go-SDK

---

ibm/resource_ibm_is_ike_policy_test.go
ibm/resource_ibm_is_image_test.go
ibm/resource_ibm_is_ipsec_policy_test.go
ibm/resource_ibm_is_networkacls_test.go
ibm/resource_ibm_is_public_gateway_test.go
ibm/resource_ibm_is_security_group_rule_test.go
ibm/resource_ibm_is_security_group_test.go
ibm/resource_ibm_is_ssh_key_test.go
ibm/resource_ibm_is_subnet_network_acl_attachment_test.go
ibm/resource_ibm_pi_image_test.go
ibm/resource_ibm_pi_instance_test.go
ibm/resource_ibm_pi_key_test.go
ibm/resource_ibm_pi_network_port_attach_test.go
ibm/resource_ibm_pi_network_port_test.go
ibm/resource_ibm_pi_network_test.go
ibm/resource_ibm_pi_snapshot_test.go
ibm/resource_ibm_pi_volume_test.go

code-cleanup : removed print statements from test files

---

examples/ibm-is-ng/main.tf
examples/ibm-is-ng/variables.tf
ibm/data_source_ibm_is_image.go
ibm/data_source_ibm_is_images.go
ibm/resource_ibm_is_image.go
ibm/resource_ibm_is_image_test.go
website/docs/d/is_image.html.markdown
website/docs/d/is_images.html.markdown
website/docs/r/is_image.html.markdown

```
=== RUN   TestAccIBMISImage_fromVolume
--- PASS: TestAccIBMISImage_fromVolume (616.05s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	620.377s
...
```

Feature: image from volume

---

website/docs/r/is_security_group_rule.html.markdown

Document update : is_security_group_rule.html.markdown

---

ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_vpc_cluster.go

Fix: Update worker for ROKS cluster

---

website/docs/r/cis_rate_limit.html.markdown

DocFix: #2764

---

ibm/data_source_ibm_is_ssh_key.go
website/docs/d/is_ssh_key.html.markdown

https://jiracloud.swg.usma.ibm.com:8443/browse/UI-16697
make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISSSHKeyDatasource_basic'

Added filter support for SSH Keys

---

website/docs/r/is_virtual_endpoint_gateway.html.markdown

Doc update: added notes in endpoint gateway reserved ip

---

examples/ibm-cos-bucket/README.md
examples/ibm-cos-bucket/main.tf
examples/ibm-cos-bucket/variables.tf
ibm/data_source_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket.go
ibm/resource_ibm_cos_bucket_test.go
website/docs/d/cos_bucket.html.markdown
website/docs/r/cos_bucket.html.markdown

Added Hard Quota support for COS

Added COS quota support

---

ibm/data_source_ibm_satellite_host_script.go

Fix: Add script for google

---

ibm/data_source_ibm_container_cluster_config.go

Add retry to download the cluster config

---

examples/ibm-iam_identity-apikeys/main.tf
examples/ibm-iam_identity-apikeys/outputs.tf
ibm/data_source_ibm_iam_api_key.go
ibm/resource_ibm_iam_api_key.go
website/docs/d/iam_api_key.html.markdown
website/docs/r/iam_api_key.html.markdown

terraform: add save to file feature to apikeys resource #5062

---

ibm/resource_ibm_kms_key.go

Fix: kms_key resource

---

website/docs/d/iam_role_actions.html.markdown
website/docs/r/iam_custom_role.html.markdown

DocFix: Add example to custom role

---

ibm/data_source_ibm_cis_rate_limit.go
ibm/resource_ibm_cis_rate_limit.go

Fix: cis_ratelimit resource #2770

---

website/docs/r/is_subnet.html.markdown
website/docs/r/tg_connection.html.markdown

Fix the docs

---

ibm/resource_ibm_iam_access_group_policy.go
ibm/resource_ibm_iam_service_policy.go
ibm/resource_ibm_iam_user_policy.go

Fix: retry on access_group_policy

---

ibm/data_source_ibm_is_subnet.go
ibm/data_source_ibm_is_subnet_test.go
ibm/resource_ibm_is_subnet.go
website/docs/d/is_subnet.html.markdown

Relates OR Closes #2739 
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISSubnetDatasource_basic'
```

Bugfix: VPCName added to subnet

---

website/docs/r/is_lb_listener.html.markdown

Relates OR Closes 
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-17347
https://ibm-cloudplatform.slack.com/archives/C53NF5MB4/p1623413328310500

Documentation correction for lblistener

---

go.mod
go.sum

Latest bluemix-go

---

ibm/data_source_ibm_satellite_host_script.go

fix script for gcp

---

.secrets.baseline
go.mod
go.sum
ibm/validators.go

Removed references of strfmt uuid bcz of vulnerability

---

ibm/resource_ibm_is_security_group.go

https://jiracloud.swg.usma.ibm.com:8443/browse/UI-17041
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISSecurityGroup_basic'
```

Bugfix: Detach targets before deleting security group

---

ibm/provider.go
ibm/resource_ibm_pi_volume.go
website/docs/r/pi_image.html.markdown
website/docs/r/pi_volume.html.markdown

Relates OR Closes #2518
```
2021/06/30 21:02:26 Configuring SoftLayer Session with API key
2021/06/30 21:02:26 Configuring IBM Cloud Session with API key
2021/06/30 21:02:26 [INFO] Configured Region: us-south
2021/06/30 21:02:28 Configuring SoftLayer Session with API key
2021/06/30 21:02:28 …
```

Support: affinity in ibm_pi_volume

---

ibm/data_source_ibm_database.go

Fix: ibm_database datasource

---

go.mod
go.sum

Bumpup: terraform-plugin-sdk to 2.7.0

---

ibm/resource_ibm_is_instance_group.go
ibm/resource_ibm_is_instance_group_test.go
website/docs/r/is_instance_group.html.markdown

https://jiracloud.swg.usma.ibm.com:8443/browse/UI-17348
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstanceGroup_basic_loadbalancer'
```

Instance Group with Lb correction

---

.secrets.baseline
go.mod
go.sum
ibm/config.go
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_is_virtual_endpoint_gateway.go
ibm/resource_ibm_is_vpc_routing_table_route.go
ibm/resource_ibm_private_dns_glb_pool.go

Vulnerable Package dgrijalva jwt-go references removed

---

ibm/resource_ibm_is_instance.go

Output from the changes:
```
Error: Instance (xxxxxx-xxxxx-xxxx-xxxx-xxxxx) went into failed state during the operation 
│  [WARNING] Running terraform apply again will remove the tainted instance and attempt to create the instance again replacing the previous configuration
│ 
│   with ibm_is_instance.this,
│   on vpc.tf line 18, in resource "ibm_is_instance" "this":
│   18: resource "ibm_is_instance" "this" {
...
```

bug-handle-instance-failure

---

ibm/resource_ibm_is_instance.go

fix: skip setting volumes in is_instance

---

scripts/detect_secrets.sh

Fix the URL typo

---

README.md

Project needn't be in GOPATH with go modules

---

website/docs/r/kms_key_alias.html.markdown

naming of Key Management services

---

ibm/resource_ibm_pi_instance.go
website/docs/r/pi_instance.html.markdown

Relates OR Closes #2787
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2787#issuecomment-870077411

add storage Type to pi_instance

---

website/docs/guides/common.html.markdown

Removes the empty guides folder

---

ibm/data_source_ibm_is_volume.go
ibm/data_source_ibm_is_volume_profile.go
ibm/data_source_ibm_is_volume_profiles.go
ibm/resource_ibm_is_volume.go
ibm/resource_ibm_is_volume_test.go

code cleanup: is_volumes gen1 cleanup

---

ibm/data_source_ibm_is_ssh_key.go
ibm/resource_ibm_is_ssh_key.go
ibm/resource_ibm_is_ssh_key_test.go

```
=== RUN   TestAccIBMISSSHKey_basic
--- PASS: TestAccIBMISSSHKey_basic (88.04s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 91.764s
```
```
=== RUN   TestAccIBMISSSHKeyDatasource_basic
--- PASS: TestAccIBMISSSHKeyDatasource_basic (42.59s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 45.479s
```

gen1 code cleanup for ssh keys

---

ibm/data_source_ibm_is_vpc.go

```
=== RUN   TestAccIBMISVPCDatasource_basic
--- PASS: TestAccIBMISVPCDatasource_basic (128.99s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 132.593s
```
```
=== RUN   TestAccIBMISVPCDatasource_securityGroup
--- PASS: TestAccIBMISVPCDatasource_securityGroup (123.49s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 127.701s
```

removed required and forced new attribute from sg id

---

ibm/resource_ibm_is_networkacls.go
ibm/resource_ibm_is_networkacls_test.go

code-cleanup gen1 Network ACLs

---

ibm/data_source_ibm_is_floating_ip.go
ibm/resource_ibm_is_floating_ip.go
ibm/resource_ibm_is_floating_ip_test.go

Gen1 Code Cleanup - Floating Ips

---

ibm/data_source_ibm_is_public_gateway.go
ibm/resource_ibm_is_public_gateway.go
ibm/resource_ibm_is_public_gateway_test.go

gen 1 cleanup public gateways

---

ibm/resource_ibm_is_vpn_gateway.go
ibm/resource_ibm_is_vpn_gateway_test.go

```
=== RUN   TestAccIBMISVPNGateway_basic
--- PASS: TestAccIBMISVPNGateway_basic (333.16s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 343.294s
```
```
=== RUN   TestAccIBMISVPNGateway_route
--- PASS: TestAccIBMISVPNGateway_route (342.11s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 348.415s
```

gen1 code cleanup for vpn gateway

---

ibm/resource_ibm_is_vpn_gateway_connection_test.go
ibm/resource_ibm_is_vpn_gateway_connections.go

```
=== RUN   TestAccIBMISVPNGatewayConnection_basic
--- PASS: TestAccIBMISVPNGatewayConnection_basic (770.10s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 775.599s
```
```
=== RUN   TestAccIBMISVPNGatewayConnection_route
--- PASS: TestAccIBMISVPNGatewayConnection_route (584.35s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 588.636s
```

gen1 code cleanup for vpn gateway connection

---

ibm/resource_ibm_is_ike_policy.go
ibm/resource_ibm_is_ike_policy_test.go

Gen1 code cleanup for IKE policy

---

ibm/data_source_ibm_is_image.go
ibm/data_source_ibm_is_images.go
ibm/resource_ibm_is_image.go
ibm/resource_ibm_is_image_test.go

Images: Gen1 code clean

---

website/docs/r/cos_bucket.html.markdown
website/docs/r/iam_access_group_policy.html.markdown
website/docs/r/iam_service_policy.html.markdown
website/docs/r/iam_user_policy.html.markdown

DocFix: IAM Policies

---

ibm/resource_ibm_is_security_group.go
ibm/resource_ibm_is_security_group_network_interface_attachment.go
ibm/resource_ibm_is_security_group_network_interface_attachment_test.go
ibm/resource_ibm_is_security_group_rule.go
ibm/resource_ibm_is_security_group_rule_test.go
ibm/resource_ibm_is_security_group_target.go
ibm/resource_ibm_is_security_group_test.go
website/docs/r/is_security_group.html.markdown

gen1 cleanup is security group

---

ibm/resource_ibm_is_ipsec_policy.go
ibm/resource_ibm_is_ipsec_policy_test.go

Gen1 code cleanup for IPSec policy

---

ibm/data_source_ibm_is_region.go
ibm/data_source_ibm_is_zone.go
ibm/data_source_ibm_is_zones.go

Gen1 code cleanup for region, zone and zones datasource

---

ibm/resource_ibm_is_vpc_route.go
ibm/resource_ibm_is_vpc_route_test.go

Code Cleanup Gen1 - vpc_route

---

ibm/data_source_ibm_is_lb.go
ibm/data_source_ibm_is_lbs.go
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_is_lb.go
ibm/resource_ibm_is_lb_listener.go
ibm/resource_ibm_is_lb_listener_policy.go
ibm/resource_ibm_is_lb_listener_policy_rule.go
ibm/resource_ibm_is_lb_listener_policy_rule_test.go
ibm/resource_ibm_is_lb_listener_policy_test.go
ibm/resource_ibm_is_lb_listener_test.go
ibm/resource_ibm_is_lb_pool.go
ibm/resource_ibm_is_lb_pool_member.go
ibm/resource_ibm_is_lb_pool_member_test.go
ibm/resource_ibm_is_lb_pool_test.go
ibm/resource_ibm_is_lb_test.go

Loadbalancer : Gen1 code clean

---

ibm/resource_ibm_is_instance_volume_attachment.go

bug : updated the order of setting attachment id

---

ibm/resource_ibm_is_instance_volume_attachment.go

bug :  null check for device on volume attachments

---

ibm/resource_ibm_container_vpc_cluster.go

```
resource "ibm_container_vpc_cluster" "cluster" {
flavor                          = "bx2.4x16"
kube_version                    = "1.19.12"
name                            = "test-new"
vpc_id                          = "<vpc id>"
worker_count                    = 1
zones {
name      = "us-east-1"
subnet_id = "<subnet id>"
}
lifecycle { …
```

Fix: 404 on default worker pool upon terraform refresh

---

ibm/resource_ibm_is_volume.go
ibm/resource_ibm_is_volume_test.go

Relates OR Closes #2869
```
--- PASS: TestAccIBMISVolume_basic (138.22s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 142.027s
```
```
=== RUN   TestAccIBMISVolumeAttachmentDelete_basic
--- PASS: TestAccIBMISVolumeAttachmentDelete_basic (472.34s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 476.001s
```

enhancement: added attachments delete on volume deletion

---

ibm/data_source_ibm_is_security_group.go
ibm/data_source_ibm_is_security_group_target.go
ibm/data_source_ibm_is_security_group_targets.go

Relates OR Closes #2868 
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISSecurityGroupDatasource_basic'
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISSecurityGroupTargets_basic'
```

Pagination support for Security Group and Security Group Target

---

ibm/data_source_ibm_is_instance_group_manager.go
ibm/data_source_ibm_is_instance_group_manager_action.go
ibm/data_source_ibm_is_instance_group_manager_actions.go
ibm/data_source_ibm_is_instance_group_manager_policies.go
ibm/data_source_ibm_is_instance_group_manager_policy.go
ibm/data_source_ibm_is_instance_group_managers.go
ibm/data_source_ibm_is_instance_group_membership.go
ibm/data_source_ibm_is_instance_group_memberships.go

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstanceGroupManagerPolicies_dataBasic'
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISInstanceGroupManagerAction_dataBasic'
```

Pagination support Instance Group Manager and Its Child Resources

---

ibm/data_source_ibm_is_lb.go

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISLBDatasource_basic'
```

Bugfix : Pagination support for Loadbalancer

---

ibm/data_source_ibm_is_ssh_key.go

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISSSHKeyDatasource_basic'
```

Bugfix: Pagination support for SSH Key

---

ibm/data_source_ibm_is_ssh_key.go
ibm/data_source_ibm_is_volume_profiles.go

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISVolumeProfilesDataSource_basic'
```

Bugfix: Pagination support for volume profiles

---

ibm/data_source_ibm_is_subnet.go

```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMISSubnetDatasource_basic'
```

Bugfix: Pagination support for Subnet

---

ibm/resource_ibm_is_virtual_endpoint_gateway_ip.go
website/docs/r/is_virtual_endpoint_gateway.html.markdown
website/docs/r/is_virtual_endpoint_gateway_ip.html.markdown

VPE resource fixes

---

ibm/resource_ibm_satellite_location.go

Added validation to managed_from attribute

---

ibm/config.go

Fix: IAM Visibility in config.go

---

ibm/resource_ibm_container_cluster.go
ibm/resource_ibm_container_vpc_cluster.go
ibm/resource_ibm_container_vpc_worker_pool.go
ibm/resource_ibm_container_worker_pool.go

Fix: taints

---

examples/ibm-satellite/cluster.tf
examples/ibm-satellite/host.tf
examples/ibm-satellite/instance.tf
examples/ibm-satellite/main.tf
examples/ibm-satellite/variables.tf
ibm/resource_ibm_satellite_cluster.go

Fixed kube version update issue in satellite cluster

---

examples/ibm-is-ng/main.tf
ibm/data_source_ibm_is_vpcs.go
ibm/data_source_ibm_is_vpcs_test.go
ibm/provider.go
website/docs/d/is_vpcs.html.markdown

```
=== RUN   TestAccIBMISVPCsDatasource_basic
--- PASS: TestAccIBMISVPCsDatasource_basic (158.16s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 163.191s
```

feature-is-vpcs

---

ibm/data_source_ibm_is_instance.go
ibm/data_source_ibm_is_instances.go
ibm/resource_ibm_is_instance.go
website/docs/d/is_instance.html.markdown
website/docs/d/is_instances.html.markdown
website/docs/r/is_instance.html.markdown

added status_reasons for is_instance resource and datasource

---

ibm/data_source_ibm_is_dedicated_host_groups.go
ibm/data_source_ibm_is_dedicated_host_profiles.go
ibm/data_source_ibm_is_dedicated_hosts.go

pagination support for dedicated hosts datasources

---

ibm/resource_ibm_event_streams_topic.go

fix for : https://ibm-cloudplatform.slack.com/archives/C53NF5MB4/p1627398101328100

fix: return error when topic creation failed

---

ibm/data_source_ibm_is_virtual_endpoint_gateway.go
ibm/resource_ibm_is_virtual_endpoint_gateway.go
website/docs/d/is_virtual_endpoint_gateway.html.markdown
website/docs/r/is_virtual_endpoint_gateway.html.markdown

Add parameter IP Address to VPE

---

website/docs/r/container_worker_pool.html.markdown

DocFix: remove region from example

---

ibm/resource_ibm_container_vpc_worker_pool.go
ibm/resource_ibm_container_worker_pool.go
website/docs/r/container_vpc_worker_pool.html.markdown
website/docs/r/container_worker_pool.html.markdown

Added pool id comouted argument

---

website/docs/d/dns_custom_resolver_forwarding_rules.html.markdown
website/docs/d/dns_custom_resolvers.html.markdown
website/docs/r/resource_instance.html.markdown

Doc updates

---

website/docs/r/dns_custom_resolver_forwarding_rule.html.markdown
website/docs/r/hpcs.html.markdown

Doc FIx: DNS Forwarding rule

---

website/docs/d/hpcs.html.markdown

Use the correct service name "Hyper Protect Crypto Services"

Update the service name

---

ibm/resource_ibm_database.go

Fix: print error in ICD resource

---

ibm/data_source_ibm_is_vpc.go

Relates OR Closes #2855
```
=== RUN   TestAccIBMISVPCDatasource_basic
--- PASS: TestAccIBMISVPCDatasource_basic (109.02s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 114.042s
```
```
=== RUN   TestAccIBMISVPCDatasource_securityGroup
--- PASS: TestAccIBMISVPCDatasource_securityGroup (120.24s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 125.008s
```

bug: added missing rule_id in tcp/udp and vpcId in sg filtering on ibm_is_vpc datasource

---

ibm/data_source_ibm_is_endpoint_gateway_targets.go

```
=== RUN   TestAccIBMISEndpointGatewayTargetsDataSource_basics
--- PASS: TestAccIBMISEndpointGatewayTargetsDataSource_basics (32.38s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 36.105s
```

added pagination support for endpoint gateway targets datasource

---

examples/ibm-is-ng/main.tf
ibm/resource_ibm_is_lb_pool.go
ibm/resource_ibm_is_lb_pool_test.go
ibm/structures.go
website/docs/r/is_lb_pool.html.markdown

Feature: lb cookie session persistence

---

.legal.yaml

This file is required for the OSS approval process.

Added the .legal.yaml

---

ibm/data_source_ibm_is_security_group.go
ibm/data_source_ibm_resource_group.go
ibm/structures.go
website/docs/d/resource_group.html.markdown

```=== RUN   TestAccIBMResourceGroupDataSource_Basic
--- PASS: TestAccIBMResourceGroupDataSource_Basic (33.94s)
=== RUN   TestAccIBMResourceGroupDataSource_Default_false
--- PASS: TestAccIBMResourceGroupDataSource_Default_false (2.36s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	39.743s$ make testacc …
```

Migrate: ibm_resource_group datasource to platform SDK

---

examples/ibm-hpcs-crypto/README.md
examples/ibm-hpcs-crypto/main.tf
examples/ibm-hpcs-crypto/output.tf
examples/ibm-hpcs-crypto/provider.tf
examples/ibm-hpcs-crypto/variables.tf

Update: HPCS example

---

ibm/resource_ibm_pi_instance.go

Fixes #2939
Relates OR Closes #2939

WIP: Not change VirtualCores and ProcType during Memmory and Processors update

---

ibm/config.go
ibm/resource_ibm_iam_authorization.policy_test.go
ibm/resource_ibm_iam_authorization_policy.go

Relates OR Closes #2926
```
=== RUN   TestAccIBMIAMAuthorizationPolicy_Basic
--- PASS: TestAccIBMIAMAuthorizationPolicy_Basic (23.04s)
=== RUN   TestAccIBMIAMAuthorizationPolicy_Resource_Instance
--- PASS: TestAccIBMIAMAuthorizationPolicy_Resource_Instance (65.80s)
=== RUN   TestAccIBMIAMAuthorizationPolicy_Resource_Group
--- …
```

Migrate: authorisation policy to platform-go-SDK

---

examples/ibm-is-ng/main.tf
ibm/data_source_ibm_is_instance_template.go
ibm/data_source_ibm_is_instance_template_test.go
ibm/data_source_ibm_is_instance_templates_test.go
ibm/provider.go
website/docs/d/is_instance_template.html.markdown
website/docs/d/is_instance_templates.html.markdown

```
=== RUN   TestAccIBMISInstanceTemplate_dataBasic
--- PASS: TestAccIBMISInstanceTemplate_dataBasic (154.84s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 160.066s
```
```
=== RUN   TestAccIBMISInstanceTemplates_dataBasic
--- PASS: TestAccIBMISInstanceTemplates_dataBasic (139.19s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 142.796s
```

added support for instance template datasource

---

ibm/resource_ibm_certificate_manager_order.go

Relates OR Closes https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2944

Fix: Reduce delay from 1m to 10s on cmr_order resource

---

ibm/data_source_ibm_is_instances.go
ibm/data_source_ibm_is_instances_test.go
ibm/resource_ibm_is_instance_group_test.go
website/docs/d/is_instances.html.markdown

filter instances datasource by instance group

---

ibm/resource_ibm_is_instance.go

added a new resource check on name update which was tainting the is_instance resource

---

ibm/resource_ibm_container_vpc_cluster.go

Fix: VPC cluster resource

---

ibm/resource_ibm_pi_instance.go

Update pi_instance virtual cores and processors after checking the capability

---

ibm/resource_ibm_is_vpc.go

Relates OR Closes #2982
```
...
```

added a vpcid filter on listing sg on resource_is_vpc read

---

ibm/data_source_ibm_database_test.go
ibm/resource_ibm_database.go
ibm/resource_ibm_database_elasticsearch_test.go
ibm/resource_ibm_database_etcd_test.go
ibm/resource_ibm_database_mongodb_test.go
ibm/resource_ibm_database_postgresql_test.go
ibm/resource_ibm_database_rabbitmq_test.go
ibm/resource_ibm_database_redis_test.go

Fix ibm_database: Enhance error handling

---

ibm/resource_ibm_kms_key.go
website/docs/r/kms_key.html.markdown

Minor Docs changes to be going with KeyPolicy Resource

Minor Textual Changes

---

website/docs/r/is_snapshot.html.markdown

updated ibm_is_snapshot resource document to include the timeout details

---

ibm/resource_ibm_is_instance_template.go

added an empty string check which was throwing validation length failed error

---

website/docs/r/resource_instance.html.markdown

Fix the instance description of Hyper Protect

---

website/docs/d/cis_filters.html.markdown
website/docs/d/dns_custom_resolver_forwarding_rules.html.markdown
website/docs/d/dns_custom_resolvers.html.markdown
website/docs/d/hpcs.html.markdown
website/docs/d/is_instance_volume_attachment.html.markdown
website/docs/d/is_instance_volume_attachments.html.markdown
website/docs/d/is_network_acl_rule.html.markdown
website/docs/d/is_snapshot.html.markdown
website/docs/d/is_snapshots.html.markdown
website/docs/d/is_vpc_address_prefixes.html.markdown
website/docs/d/is_vpcs.html.markdown
website/docs/d/tg_gateway.html.markdown
website/docs/r/cis_filter.html.markdown
website/docs/r/cm_offering_instance.html.markdown
website/docs/r/cos_bucket.html.markdown
website/docs/r/dns_custom_resolver.html.markdown
website/docs/r/dns_custom_resolver_forwarding_rule.html.markdown
website/docs/r/dns_custom_resolver_location.html.markdown
website/docs/r/hpcs.html.markdown
website/docs/r/is_instance_volume_attachment.html.markdown
website/docs/r/is_network_acl_rule.html.markdown
website/docs/r/is_snapshot.html.markdown
website/docs/r/tg_connection.html.markdown

Updated the docs fix for release 1.29 1.28 and 1.27

Doc fix release1.29_1.28_1.27

---

website/docs/d/appid_application.html.markdown
website/docs/d/appid_application_roles.html.markdown
website/docs/d/appid_application_scopes.html.markdown
website/docs/d/appid_redirect_urls.html.markdown
website/docs/d/appid_role.html.markdown
website/docs/d/appid_token_config.html.markdown
website/docs/r/appid_application.html.markdown
website/docs/r/appid_application_roles.html.markdown
website/docs/r/appid_application_scopes.html.markdown
website/docs/r/appid_redirect_urls.html.markdown
website/docs/r/appid_role.html.markdown
website/docs/r/iam_account_settings.html.markdown

DocFix: #2984

---

ibm/resource_ibm_is_lb_listener_policy.go

```
$ make testacc TESTARGS='-run=TestAccIBMISLBListenerPolicy_basic'
...
```

fix: setting listener policy rule values

---

website/docs/r/is_instance_volume_attachment.html.markdown

fixed the header for is_instance_volume_attachment doc

---

ibm/resource_ibm_iam_access_group_members.go

Relates OR Closes #2905
```
$ make testacc TESTARGS='-run=TestAccIBMIAMDynamicRuleimport'
=== RUN   TestAccIBMIAMDynamicRuleimport
--- PASS: TestAccIBMIAMDynamicRuleimport (27.55s)
...
```
```
$ make testacc TESTARGS='-run=TestAccIBMIAMAccessGroupMember_Basic'
=== RUN   TestAccIBMIAMAccessGroupMember_Basic
--- PASS: …
```

setting serviceIds and IBMIds in read method

---

website/docs/r/is_vpc_routing_table.html.markdown
website/docs/r/is_vpc_routing_table_route.html.markdown

DocUpdate: add routing table route example

---

ibm/resource_ibm_is_network_acl_rule.go

changed the validator invoked in nacl rule

---

website/docs/r/app_config_environment.html.markdown
website/docs/r/app_config_feature.html.markdown
website/docs/r/cdn.html.markdown

patch1 updated cdn and app config desc

---

ibm/data_source_ibm_pi_instance.go
website/docs/d/pi_instance.html.markdown
website/docs/r/pi_instance.html.markdown

Fixes #3053
Relates OR Closes #3053
```
...
```

Change the instance attribute types

---

go.mod
go.sum
ibm/resource_ibm_pi_instance.go
ibm/resource_ibm_pi_network.go
website/docs/r/pi_instance.html.markdown

Add support for vSCSI pi_instance deployment

---

ibm/provider.go
ibm/resource_ibm_is_instance.go
ibm/resource_ibm_is_instance_template.go
ibm/resource_ibm_is_instance_volume_attachment.go

added name validation at missing places

---

ibm/resource_ibm_is_security_group_rule.go

Added direction to SG rule which was showing a change on import

---

website/docs/r/is_security_group_rule.html.markdown

Relates OR Closes #3062
```
...
```

doc update: security group rule import update

---

examples/ibm-satellite/modules/route/versions.tf

Fixed satellite route example issue

---

ibm/data_source_ibm_iam_service_policy.go
ibm/data_source_ibm_iam_user_policy.go
ibm/resource_ibm_iam_authorization.policy_test.go
ibm/resource_ibm_iam_authorization_policy.go
ibm/resource_ibm_iam_service_policy.go
ibm/resource_ibm_iam_service_policy_test.go
ibm/resource_ibm_iam_user_policy.go
ibm/resource_ibm_iam_user_policy_test.go
website/docs/d/iam_service_policy.html.markdown
website/docs/d/iam_user_policy.html.markdown
website/docs/r/iam_authorization_policy.html.markdown
website/docs/r/iam_service_policy.html.markdown
website/docs/r/iam_user_policy.html.markdown

added description support for policy create/update

---

ibm/resource_ibm_resource_instance.go

Ignore 410-gone status during deletion

---

ibm/resource_ibm_is_instance_volume_attachment.go

fix: encryption crn for volume attachment

---

ibm/data_source_ibm_is_virtual_endpoint_gateways.go
website/docs/d/is_virtual_endpoint_gateways.html.markdown

fix: endpoint gateways data source

---

ibm/resource_ibm_function_namespace.go

Fix: function namespace

---

go.mod
go.sum
ibm/data_source_ibm_is_instance.go

upgraded the vpc-go-sdk version to use the latest 0.10.0 

---

ibm/data_source_ibm_is_floating_ip.go
ibm/data_source_ibm_is_instance_group.go
ibm/data_source_ibm_is_lb.go
ibm/data_source_ibm_is_security_group_target.go
ibm/data_source_ibm_is_security_group_targets.go
ibm/data_source_ibm_is_virtual_endpoint_gateway.go
ibm/data_source_ibm_is_virtual_endpoint_gateways.go
ibm/resource_ibm_is_instance_group.go
ibm/resource_ibm_is_instance_template.go
ibm/resource_ibm_is_lb.go
ibm/resource_ibm_is_security_group_target.go
ibm/resource_ibm_is_virtual_endpoint_gateway.go
website/docs/d/is_floating_ip.html.markdown
website/docs/d/is_instance_group.html.markdown
website/docs/d/is_lb.html.markdown
website/docs/d/is_security_group_target.html.markdown
website/docs/d/is_security_group_targets.html.markdown
website/docs/d/is_virtual_endpoint_gateway.html.markdown
website/docs/d/is_virtual_endpoint_gateways.html.markdown
website/docs/r/is_instance_group.html.markdown
website/docs/r/is_instance_template.html.markdown
website/docs/r/is_lb.html.markdown
website/docs/r/is_security_group_target.html.markdown
website/docs/r/is_virtual_endpoint_gateway.html.markdown

added missing crn to vpc resources

---

ibm/resource_ibm_container_addons.go
ibm/structures.go

Fix: update cluster addons

---

ibm/resource_ibm_is_instance_volume_attachment.go
ibm/resource_ibm_is_instance_volume_attachment_test.go
ibm/resource_ibm_is_volume.go
ibm/resource_ibm_is_volume_test.go
ibm/structures.go
website/docs/r/is_instance_volume_attachment.html.markdown
website/docs/r/is_volume.html.markdown

```
=== RUN   TestAccIBMISVolumeUpdateCapacity_basic
--- PASS: TestAccIBMISVolumeUpdateCapacity_basic (446.44s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 453.405s
```
```
=== RUN …
```

added changes for expandable volumes

---

website/docs/r/container_cluster.html.markdown
website/docs/r/resource_key.html.markdown

DocFix: resource key and container cluster

---

examples/ibm-scc/findings/README.md
examples/ibm-scc/findings/main.tf
examples/ibm-scc/findings/outputs.tf
examples/ibm-scc/findings/variables.tf
examples/ibm-scc/findings/versions.tf
go.mod
go.sum
ibm/config.go
ibm/data_source_ibm_scc_si_note.go
ibm/data_source_ibm_scc_si_note_test.go
ibm/data_source_ibm_scc_si_notes.go
ibm/data_source_ibm_scc_si_notes_test.go
ibm/data_source_ibm_scc_si_providers.go
ibm/data_source_ibm_scc_si_providers_test.go
ibm/provider.go
ibm/provider_test.go
ibm/resource_ibm_scc_si_note.go
ibm/resource_ibm_scc_si_note_test.go
website/allowed-subcategories.txt
website/docs/d/scc_si_note.html.markdown
website/docs/d/scc_si_notes.html.markdown
website/docs/d/scc_si_providers.html.markdown
website/docs/r/scc_si_note.html.markdown

```
make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMSccSi -timeout 700m
?       github.com/IBM-Cloud/terraform-provider-ibm     [no test files]
[WARN] Set the environment variable IBM_APPID_TENANT_ID for …
```

Add support for SCC SI findings resource

---

ibm/config.go
ibm/data_source_ibm_iam_access_group.go
ibm/resource_ibm_iam_access_group.go
ibm/resource_ibm_iam_access_group_dynamic_rule.go
ibm/resource_ibm_iam_access_group_dynamic_rule_test.go
ibm/resource_ibm_iam_access_group_members.go
ibm/resource_ibm_iam_access_group_members_test.go
ibm/resource_ibm_iam_access_group_test.go
ibm/resource_ibm_iam_user_invite.go
ibm/resource_ibm_push_notification_chrome.go
ibm/resource_ibm_resource_group.go
ibm/structures.go

Migration - Access Group Services from bluemix-go library to Platform SDK

---

website/docs/d/scc_si_note.html.markdown
website/docs/d/scc_si_notes.html.markdown
website/docs/d/scc_si_providers.html.markdown
website/docs/r/scc_si_note.html.markdown

Scc doc update

---

.github/workflows/release.yml

This change fixes the TODO comment and replaces `paultyng/ghaction-import-gpg` with `hashicorp/ghaction-import-gpg`.

Updated to hashicorp/ghaction-import-gpg

---

ibm/resource_ibm_is_instance.go

bug: suppressing the change in wait_before_delete  on import of is_instance which showed update in place

---

ibm/resource_ibm_is_instance_volume_attachment.go

added retry for 409 error in ibm_is_instance_volume_attachment

---

go.mod
go.sum

Support: service API Key for cluster config

---

ibm/resource_ibm_is_floating_ip.go

Relates OR Closes #3110
```
...
```

added a check to see if old target is new resource, in such cases forcing a new floating ip

---

ibm/resource_ibm_is_instance_volume_attachment.go

Relates OR Closes #3089
```
...
```

added fix for update for volume name on attachments

---

website/docs/d/satellite_endpoint.html.markdown
website/docs/d/satellite_link.html.markdown
website/docs/r/satellite_endpoint.html.markdown
website/docs/r/satellite_link.html.markdown

DocFix: Satellite Link and Endpoint resources

---

ibm/resource_ibm_is_vpc.go

Relates OR Closes  #3082
```
...
```

Suppressing null address_prefix_management on import

---

examples/ibm-is-ng/main.tf
ibm/data_source_ibm_is_regions.go
ibm/data_source_ibm_is_regions_test.go
ibm/provider.go
website/docs/d/is_regions.html.markdown

```
=== RUN   TestAccIBMISRegionsDataSource_basic
--- PASS: TestAccIBMISRegionsDataSource_basic (38.74s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 42.166s
```

added datasource for is_regions, list of regions

---

ibm/data_source_ibm_is_instance.go
ibm/data_source_ibm_is_instances.go
ibm/resource_ibm_is_instance.go
website/docs/d/is_instance.html.markdown
website/docs/d/is_instances.html.markdown
website/docs/r/is_instance.html.markdown

Feature: gpu for instance

---

ibm/resource_ibm_pi_instance.go
ibm/resource_ibm_pi_instance_test.go
website/docs/r/pi_instance.html.markdown

Relates OR Closes #3102
```
$ make testacc TESTARGS='-run=TestAccIBMPIInstanceNetwork'
=== RUN   TestAccIBMPIInstanceNetwork
--- PASS: TestAccIBMPIInstanceNetwork (1096.89s)
PASS
...
```

Allow setting ip address with network for power instance

---

ibm/resource_ibm_is_instance.go

Changed IsNewResource to id null check. 

---

website/docs/r/is_image.html.markdown
website/docs/r/is_lb_pool.html.markdown
website/docs/r/is_ssh_key.html.markdown
website/docs/r/is_volume.html.markdown

replaced underscore with hyphen in name of is resources

---

website/docs/d/container_storage_attachment.html.markdown
website/docs/r/container_storage_attachment.html.markdown

Fixing document name issues

---

website/docs/d/cis_filters.html.markdown
website/docs/d/cos_bucket_object.html.markdown
website/docs/d/iam_api_key.html.markdown
website/docs/d/is_dedicated_host_disk.html.markdown
website/docs/d/is_dedicated_host_disks.html.markdown
website/docs/d/is_endpoint_gateway_targets.html.markdown
website/docs/d/is_network_acl_rule.html.markdown
website/docs/d/is_security_group_targets.html.markdown
website/docs/r/cis_filter.html.markdown
website/docs/r/cos_bucket_object.html.markdown
website/docs/r/cr_retention_policy.html.markdown
website/docs/r/iam_api_key.html.markdown
website/docs/r/is_dedicated_host_disk_management.html.markdown
website/docs/r/is_network_acl_rule.html.markdown
website/docs/r/is_security_group_target.html.markdown
website/docs/r/resource_tag.html.markdown

Updated the description of v1.250 and v1.27.0 release

---

ibm/resource_ibm_is_lb.go

Relates OR Closes #3006
```
$ make testacc TESTARGS='-run=TestAccIBMISLB_basic_securityGroups'
```
Tested with the below configuration:
provider "ibm" {
ibmcloud_api_key = var.ibmcloud_api_key
ibmcloud_timeout = 300
region           = var.vpc_region
}
resource "ibm_is_vpc" "vpc" {
name           = "${var.resources_prefix}-vpc" …

Load Balancer cannot be updated because its status is 'UPDATE_PENDING'

---

go.mod
go.sum
ibm/data_source_ibm_is_instance_profile.go
ibm/data_source_ibm_is_instance_profiles.go
website/docs/d/is_instance_profile.html.markdown
website/docs/d/is_instance_profiles.html.markdown

feature: gpu for instance profile datasource

---

ibm/config.go

Support: default headers for service client

---

ibm/resource_ibm_pi_key.go

Related to https://ibm-argonauts.slack.com/archives/C53NF5MB4/p1632329565322900

Fix: nil pointer on pi_key

---

go.mod
go.sum
ibm/data_source_ibm_database.go
ibm/resource_ibm_database.go
website/docs/d/database.html.markdown
website/docs/r/database.html.markdown

Relates OR Closes #3278 #1428
```
=== RUN   TestAccIBMDatabaseInstance_Postgres_Basic
=== PAUSE TestAccIBMDatabaseInstance_Postgres_Basic
=== CONT  TestAccIBMDatabaseInstance_Postgres_Basic
--- PASS: TestAccIBMDatabaseInstance_Postgres_Basic (1614.06s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	1617.583s
=== RUN …
```

Support: ICD configuration  #3278 #1428

---

ibm/config.go
ibm/resource_ibm_iam_authorization.policy_test.go
ibm/resource_ibm_iam_authorization_policy.go
website/docs/r/iam_authorization_policy.html.markdown

Added optional query parameters source_service_name & policy_type to v2/roles

---

ibm/resource_ibm_container_alb.go
website/docs/r/container_alb.html.markdown

Fix: container_alb resource

---

ibm/resource_ibm_ob_logging.go
ibm/resource_ibm_ob_monitoring.go

adding custom retry to fix the enabling of logging and moniotirg

---

ibm/config.go

Update bluemix-go user-agent and enable logger

---

go.mod
go.sum
ibm/data_source_ibm_pi_catalog_images.go
ibm/data_source_ibm_pi_dhcp.go
ibm/data_source_ibm_pi_dhcp_test.go
ibm/data_source_ibm_pi_dhcps.go
ibm/data_source_ibm_pi_dhcps_test.go
ibm/provider.go
ibm/provider_test.go
ibm/resource_ibm_pi_dhcp.go
ibm/resource_ibm_pi_dhcp_test.go
website/docs/d/pi_catalog_images.html.markdown
website/docs/d/pi_dhcp.html.markdown
website/docs/d/pi_dhcps.html.markdown
website/docs/r/pi_dhcp.html.markdown

```
=== RUN   TestAccIBMPIDhcpServersDataSourceBasic
--- PASS: TestAccIBMPIDhcpServersDataSourceBasic (28.40s)
PASS
=== RUN   TestAccIBMPIDhcpDataSourceBasic
--- PASS: TestAccIBMPIDhcpDataSourceBasic (13.29s)
PASS
=== RUN   TestAccIBMPIDhcpbasic
--- PASS: TestAccIBMPIDhcpbasic (403.33s)
PASS
...
```

Add support for DHCP service

---

go.mod
go.sum

chore(deps): Update ibm-hpcs-tke-sdk

---

ibm/data_source_ibm_pi_cloud_connection.go
ibm/data_source_ibm_pi_cloud_connection_test.go
ibm/provider.go
ibm/provider_test.go
ibm/resource_ibm_pi_cloud_connection.go
ibm/resource_ibm_pi_cloud_connection_test.go
website/docs/d/pi_cloud_connection.html.markdown
website/docs/r/pi_cloud_connection.html.markdown

```
=== RUN   TestAccIBMPICloudConnectionbasic
--- PASS: TestAccIBMPICloudConnectionbasic (468.20s)
PASS
=== RUN   TestAccIBMPICloudConnectionNetworks
--- PASS: TestAccIBMPICloudConnectionNetworks (676.91s)
PASS
=== RUN   TestAccIBMPICloudConnectionVPC
--- PASS: …
```

Add Power cloud connections resource and data source

---

ibm/resource_ibm_iam_access_group_members.go
ibm/resource_ibm_iam_user_invite.go
ibm/resource_ibm_org.go
ibm/resource_ibm_space.go

set force_new for access group id and hash on set

---

website/docs/d/schematics_action.html.markdown
website/docs/d/schematics_inventory.html.markdown
website/docs/d/schematics_job.html.markdown
website/docs/d/schematics_output.html.markdown
website/docs/d/schematics_resource_query.html.markdown
website/docs/r/schematics_action.html.markdown
website/docs/r/schematics_job.html.markdown
website/docs/r/schematics_workspace.html.markdown

DocFix: Schematics resources and datasources

---

ibm/config.go

added logger logic to print all the logs on trace

---

ibm/provider.go
ibm/resource_ibm_pi_ike_policy.go
ibm/resource_ibm_pi_ike_policy_test.go
ibm/resource_ibm_pi_ipsec_policy.go
ibm/resource_ibm_pi_ipsec_policy_test.go
ibm/resource_ibm_pi_vpn_connection.go
ibm/resource_ibm_pi_vpn_connection_test.go
website/docs/r/pi_vpn_connection.html.markdown
website/docs/r/pi_vpn_ike_policy.html.markdown
website/docs/r/pi_vpn_ipsec_policy.html.markdown

```
=== RUN   TestAccIBMPIIKEPolicyBasic
--- PASS: TestAccIBMPIIKEPolicyBasic (113.01s)
PASS
=== RUN   TestAccIBMPIIPSecPolicyBasic
--- PASS: TestAccIBMPIIPSecPolicyBasic (55.34s)
PASS
=== RUN   TestAccIBMPIVPNConnectionBasic
--- PASS: TestAccIBMPIVPNConnectionBasic …
```

PI VPN connections and policies resources

---

ibm/resource_ibm_cos_bucket.go

reference:- 
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3359

COS: Objectversioning& MPU

---

ibm/data_source_ibm_secrets_manager_secret.go
ibm/data_source_ibm_secrets_manager_secrets.go

Fix: private endpoint for secrets manager

---

website/docs/d/is_instance_network_interfaces.html.markdown
website/docs/d/is_instance_template.html.markdown
website/docs/r/is_instance.html.markdown

resubmitted v1360 release udpated docs

---

ibm/resource_ibm_is_security_group_target.go

```
--- PASS: TestAccIBMISSecurityGroupTarget_basic (613.02s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	617.188s
```

fix: added wait logic for security group target 

---

website/docs/d/is_floating_ips.html.markdown
website/docs/d/is_flow_log.html.markdown
website/docs/d/is_network_acl.html.markdown
website/docs/d/is_network_acls.html.markdown
website/docs/d/pi_cloud_connection.html.markdown
website/docs/d/pi_dhcp.html.markdown
website/docs/d/pi_dhcps.html.markdown
website/docs/d/scc_si_occurrence.html.markdown
website/docs/d/scc_si_occurrences.html.markdown
website/docs/d/schematics_inventory.html.markdown
website/docs/d/schematics_resource_query.html.markdown
website/docs/r/is_instance_action.html.markdown
website/docs/r/is_security_group_network_interface_attachment.html.markdown
website/docs/r/pi_cloud_connection.html.markdown
website/docs/r/pi_dhcp.html.markdown
website/docs/r/scc_si_occurrence.html.markdown
website/docs/r/schematics_inventory.html.markdown
website/docs/r/schematics_resource_query.html.markdown

docs update for v1360 release

---

ibm/data_source_ibm_iam_access_group_policy.go
ibm/data_source_ibm_iam_access_group_policy_test.go
ibm/provider.go
website/docs/d/iam_access_group_policy.html.markdown

datasource for access group policies

---

ibm/data_source_ibm_is_instances_test.go
ibm/resource_ibm_is_floating_ip_test.go
ibm/resource_ibm_is_instance_test.go
website/docs/r/is_subnet.html.markdown

```
=== RUN   TestAccIBMISFloatingIP_basic
--- PASS: …
```

added acceptance test cases for floating ip and instance

---

ibm/data_source_ibm_is_snapshot_test.go
ibm/data_source_ibm_is_snapshots.go
ibm/data_source_ibm_is_snapshots_test.go
website/docs/d/is_snapshots.html.markdown

```
=== RUN   TestAccIBMISSnapshotsDatasource_basic
--- PASS: TestAccIBMISSnapshotsDatasource_basic (325.54s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 329.430s
```

added filters to snapshot collection datasource

---

ibm/config.go
ibm/provider.go

Support: profile_id in provider.go

---

ibm/resource_ibm_is_instance_test.go

updated resource_ibm_is_instance_test, rebase
