- ibm/data_source_ibm_container_cluster_test.go
Cannot bind a service instance to cluster if the name does not adhere to regex * [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?.
> Fix for issue with service instance name

- ibm/provider_test.go
- ibm/resource_ibm_compute_vm_instance.go
- ibm/resource_ibm_compute_vm_instance_test.go
- website/docs/r/compute_vm_instance.html.markdown
User can control on which dedicated host the VSI should be placed
> Add dedicated host name and id attribue to ibm_compute_vm_instance

- ibm/resource_ibm_compute_vm_instance_test.go
Dedicated Host VM doesn't have [10,20 GB] disks
> Fix Dedicated Host testcases

- README.md
[IBM Provider documentation] was pointing to https://ibm-bluemix.github.io/tf-ibm-docs which is not accessible. Changes to docs at https://ibm-cloud.github.io/tf-ibm-docs/v0.6.0/
> Fixed broken link in README.md file.

- ibm/resource_ibm_storage_block.go
- ibm/resource_ibm_storage_block_test.go
- ibm/resource_ibm_storage_file.go
- website/docs/r/storage_block.html.markdown
Test results
Harinis-MacBook-Pro:terraform-provider-ibm hkantare$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMStorageBlock'
TF_ACC=1 go test ./ibm -v -run=TestAccIBMStorageBlock -timeout 700m
[WARN] Set the environment variable IBM_ID1 for testing ibm_space resource Some tests for that resource will fail if this is not set correctly
[WARN] Set the environment variable IBM_ID2 for testing ibm_space resource Some tests for that resource will …
> Fix issue #180

- ibm/config.go
- ibm/data_source_ibm_iam_user_policy.go
- ibm/provider.go
- ibm/resource_ibm_iam_user_policy.go
- ibm/resource_ibm_iam_user_policy_test.go
- ibm/resource_ibm_resource_key.go
- ibm/resource_ibm_resource_key_test.go
- ibm/structures.go
- ibm/validators.go
- website/docs/r/resource_key.html.markdown
- website/ibm.erb
Harinis-MacBook-Pro:terraform-provider-ibm hkantare$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMResourceKey'
TF_ACC=1 go test ./ibm -v -run=TestAccIBMResourceKey -timeout 700m
[WARN] Set the environment variable IBM_ID1 for testing ibm_space resource Some tests for that resource will fail if this is not set correctly
[WARN] Set the environment variable IBM_ID2 for testing ibm_space resource Some tests for that resource will fail if this is …
> Add resource support for resource key

- ibm/data_source_ibm_resource_key.go
- ibm/data_source_ibm_resource_key_test.go
- ibm/provider.go
- website/docs/d/resource_key.html.markdown
- website/ibm.erb
Harinis-MacBook-Pro:terraform-provider-ibm hkantare$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMResourceKeyDataSource'
TF_ACC=1 go test ./ibm -v -run=TestAccIBMResourceKeyDataSource -timeout 700m
[WARN] Set the environment variable IBM_ID1 for testing ibm_space resource Some tests for that resource will fail if this is not set correctly
[WARN] Set the environment variable IBM_ID2 for testing ibm_space resource Some tests for that resource …
> Add datasource support for resource key

- ibm/resource_ibm_container_cluster.go
- ibm/resource_ibm_container_cluster_test.go
=== RUN   TestAccIBMContainerCluster_nosubnet_false
--- PASS: TestAccIBMContainerCluster_nosubnet_false (1630.78s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ibm/ibm
> Wait for subnet to be available when no_subnet is false

- ibm/provider.go
- ibm/resource_ibm_dns_secondary.go
- ibm/resource_ibm_dns_secondary_test.go
- website/docs/r/dns_secondary.html.markdown
- website/ibm.erb
```
=== RUN   TestAccIBMDnsSecondary_Basic
--- PASS: TestAccIBMDnsSecondary_Basic (76.62s)
=== RUN   TestAccIBMDnsSecondary_Basic_Tags
--- PASS: TestAccIBMDnsSecondary_Basic_Tags (54.55s)
=== RUN   TestAccIBMDnsSecondary_Import
--- PASS: TestAccIBMDnsSecondary_Import (41.73s)
PASS
ok      github.com/terraform-providers/terraform-provider-ibm/ibm    174.511s
```
> Add support for IBM dns secondary zone

- ibm/data_source_ibm_lbaas_test.go
Use ibm_lbaas_server_instance_attachment resource to attach a server instance to lbaas
> Fix Lbaas datasource UAT

- ibm/provider.go
- ibm/resource_ibm_iam_service_policy.go
- ibm/resource_ibm_iam_service_policy_test.go
- ibm/structures.go
- website/docs/r/iam_service_policy.html.markdown
- website/ibm.erb
[WARN] Set the environment variable IBM_COMPUTE_VM_INSTANCE_IMAGE_ID for testing the ibm_compute_vm_instance resource. The image should be replicated in the Washington 4 datacenter. Some tests for that resource will fail if this is not set correctly
=== RUN   TestAccIBMIAMServicePolicy_Basic
--- PASS: TestAccIBMIAMServicePolicy_Basic (109.14s)
=== RUN   TestAccIBMIAMServicePolicy_With_Service
--- PASS: TestAccIBMIAMServicePolicy_With_Service (93.01s)
=== RUN   TestAccIBMIAMServicePolicy_With_ResourceInstance
--- PASS: TestAccIBMIAMServicePolicy_With_ResourceInstance (96.33s)
=== RUN   TestAccIBMIAMServicePolicy_With_Resource_Group
--- PASS: TestAccIBMIAMServicePolicy_With_Resource_Group (69.65s)
=== RUN   TestAccIBMIAMServicePolicy_With_Resource_Type
--- PASS: …
> Add resource support for IAM Service Policy

- ibm/data_source_ibm_compute_bare_metal.go
- ibm/resource_ibm_compute_bare_metal.go
- website/docs/d/compute_bare_metal.html.markdown
- website/docs/r/compute_bare_metal.html.markdown
these ip address ids are needed as input for e.g. ibm_lb_service
also note: i removed "guestNetworkComponentBinding[ipAddressId]" from "primaryVersion6IpAddressRecord" in the object masks in {data,resource}_ibm_compute_bare_metal because they didn't seem to be used.
please let me know if acceptance tests for this are expected, which i didn't write because the existing ip address attributes did not have acceptance tests either.
> add computed ip address ids to compute_bare_metal

- website/docs/r/subnet.html.markdown
1. Changed `subnet` to `subnet_cidr` in the static subnet example.
2. Added portable subnet configuration example.
> Changed subnet to subnet_cidr in the subnet doc

- .travis.yml
- README.md
- ibm/auth_helpers.go
- ibm/config.go
- ibm/data_source_ibm_container_cluster_versions.go
- main.go
This commit changes the import path to match the upstream Github path.
This makes the project Go-idiomatic and also go-gettable.
closes #373
> Change the import path to match the real import path

- website/docs/r/container_cluster.html.markdown
Terraform expects `machine_type`:
```
Error: ibm_container_cluster.swiftype-misc: : invalid or unknown key: machinetype
```
> Fix erroneous occurence of `machinetype` in docs

- ibm/resource_ibm_resource_key.go
- Check if resourceKey.Parameters["role_crn"] is nil. 
- Use resourceKey.Credentials["iam_role_crn"] when resourceKey.Parameters["role_crn"] is nil.
- This fix resolves the issue #451.
> Check nil value to retrive role_crn without crash 

- ibm/data_source_ibm_resource_key.go
- Check if key.Parameters["role_crn"] is nil.
- Use key.Credentials["iam_role_crn"] when key.Parameters["role_crn"]  is nil.
This fix is related to issue #451.
> Check nil value to retrive role_crn for data_source_ibm_resource_key

- ibm/resource_ibm_network_vlan.go
We are experiencing issues provisioning VLANs on SoftLayer.  Because this error is unhandled, it crashes Terraform when attempting to access `*vlan.Id` later in the code.  This change returns the error safely.
> handle error when retrieving vlan order

- ibm/resource_ibm_compute_vm_instance.go
Support the following three different configurations:
1) data center only
```
datacenter_choice = [
{
datacenter      = "dal12"
}
```
2) public and private network
```
datacenter_choice = [
{
datacenter      = "dal12"
public_vlan_id  = 1111111
private_vlan_id = 222222
}
```
3) private network only(for private network only VM)
```
datacenter_choice = [
{
datacenter      = "dal12"
private_vlan_id = 222222
}
```
If public_vlan_id is provided but, private_vlan_id is not provided to datacenter_choice, SoftLayer generates validation error. Example:
```
* ibm_compute_vm_instance.vm2: Error ordering virtual guest: SoftLayer_Exception_Public: Only the frontend VLAN was specified. Please specify the backend VLAN as well. (HTTP 500)
```
This PR is related to #592
> Support private network only VM configuration for datacenter_choice

- ibm/resource_ibm_is_instance.go
This week, I have got many errors like this while provisioning instances.
```
* ibm_is_instance.vsi1[52]: 1 error occurred:
* ibm_is_instance.vsi1.52: context deadline exceeded
```
The root cause is a delay in retrieving the volume information of the boot volume of the instance (which is being fixed), but the error message could have been more informative.
```
* ibm_is_instance.vsi2[35]: 1 error occurred:
* ibm_is_instance.vsi2.35: Error while retrieving boot volume r134-750ca059-f042-11e9-8d96-feff0b50d71b for instance 0738_f8ea7bf2-ee72-493d-a6d0-793f908f4192: context deadline exceeded
```
Possibly the messages for the other kinds of errors can be more informative as well.
> Improve the error message of boot volume retrieval

- ibm/resource_ibm_is_vpc_address_prefix.go
Serialize creation/deletion of address prefixes in the same VPC to avoid a concurrency problem.
> Handle parallel provisioning of VPC address prefixes

- website/docs/d/pi_network.html.markdown
The example uses 'powerinstanceid' as an argument instead of
'pi_cloud_instance_id' to reference the service instance.
> Fix doc for 'pi_network'

- examples/ibm-is-vpc/main.tf
Without stating the dependency, this error may be encountered: "Cannot find subnet containing next hop address".
> Add subnet1 as dependency for route1

- examples/ibm-is-vpc/main.tf
As port speed is set by image profile as per https://cloud.ibm.com/docs/vpc?topic=vpc-pricing-for-vpc#base-instance-prices, perhaps we should remove setting it statically inside primary_network_interface?
> Remove port speed

- ibm/resource_ibm_is_vpc.go
If an existing cloud VPC resource is imported by id
(i.e. 'terraform import ADDR ID') _any_ subsequent changes to the VPC
will force the creation of a new resource. The 'is_default' parameter
cannot be set by the user since it's deprecated which forces a plan diff
of 'is_default: "" => "false" (forces new resource)'.
> Remove default value from 'Removed' parameter

- ibm/resource_ibm_is_vpn_gateway.go
When the specified VPN gateway does not exist, the API returns not "not_found" but "vpn_gateway_not_found".  The acceptance test should cover the case where Terraform checks non-existing ibm_is_vpn_gateway.
I've tested this fix on the terraform_v0.12 branch.  Probably this fix should be applied to the master branch, too.
> Fix the error code of non existing ibm_is_vpn_gateway

- ibm/resource_ibm_is_vpn_gateway_connections.go
The same as #936, but for ibm_is_vpn_gateway_connection.
> Fix the error code of non existing ibm_is_vpn_gateway_connection

- ibm/resource_ibm_is_ike_policy.go
- ibm/resource_ibm_is_ipsec_policy.go
The same as #936, but for ibm_is_ipsec_policy and  ibm_is_ike_policy.
> Fix the error code of non existing IPSec and IKE policies

- ibm/resource_ibm_is_vpn_gateway_connections.go
The API returns `vpn_gateway_not_found` when a VPN connection in a VPN gateway is queried about but when the gateway does not exist.
> Fix the error code of non existing VPN gateway when querying about a connection

- ibm/resource_ibm_container_vpc_cluster.go
- ibm/resource_ibm_container_vpc_worker_pool.go
- vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv2/workers.go
- vendor/vendor.json
- website/docs/r/container_vpc_cluster.html.markdown
- website/docs/r/container_vpc_worker_pool.html.markdown
VPC Cluster resources : ibm_container_vpc_cluster & ibm_container_vpc_worker_pool
Update : Supporting terraform_v0.11.x
1. Cluster and Worker pool resizing 
2. Updating Kube version
Issue:  https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1004
> VPC cluster resources update: Kubernetes version and cluster resize - v11

- ibm/data_source_ibm_container_cluster.go
Fix for ibm_container_cluster data source for openshift v4.3
> Fix for ibm_container_cluster data source for openshift v4.3

- ibm/data_source_ibm_container_cluster.go
Fix for ibm_container_cluster for openshift v4.3
> Fix for ibm_container_cluster for openshift v4.3

- ibm/resource_ibm_is_floating_ip.go
Sometimes users need to destroy a resource without refresh `terraform destroy -refresh=false` for various reasons. Even when the resource does not exist any more, the delete operation should be considered successful.
This PR allows deletion of a non-existing FIP.  It is already allowed for a security group rule:
https://github.com/IBM-Cloud/terraform-provider-ibm/blob/b9fb8aeedd852071061c680ec4cfb18f9fde503b/ibm/resource_ibm_is_security_group_rule.go#L286-L296
> Consider it successful to delete a non-existing FIP

- ibm/data_source_ibm_is_vpc.go
- ibm/resource_ibm_is_vpc.go
- website/docs/d/is_vpc.html.markdown
- website/docs/r/is_vpc.html.markdown
This PR introduces subnets attribute in vpc resource and data sources. Attribute will fetch the subnets associated with VPC resource with the below info.
```
"subnets.#": "1",
"subnets.0.available_ipv4_address_count": "251",
"subnets.0.id": "0717-9345f93b-9140-4053-88cd-393fd69f89dd",
"subnets.0.name": "test-vpc",
"subnets.0.status": "available",
"subnets.0.total_ipv4_address_count": "256",
```
> added support for vpc subnets list

- go.sum
- ibm/data_source_ibm_is_vpc.go
- ibm/resource_ibm_is_vpc.go
- website/docs/d/is_vpc.html.markdown
- website/docs/r/is_vpc.html.markdown
This PR provides the support to list the subnets info associated with the vpc resource in the terraform state file
```
"subnets": [
{
"available_ipv4_address_count": 247,
"id": "4c1b0db5-a8be-44bd-a148-0cf0a7a80ba2",
"name": "test-2",
"status": "available",
"total_ipv4_address_count": 256
},
{
"available_ipv4_address_count": 248,
"id": "9e35de54-7550-476a-919d-992826487379",
"name": "test-1",
"status": "available",
"total_ipv4_address_count": 256
},
{
"available_ipv4_address_count": 247,
"id": "72d58212-b4ce-4a61-8a79-1cf392db3a32",
"name": "test-0",
"status": "available",
"total_ipv4_address_count": 256
}
],
```
> added support for network subnets in vpc resource and data source

- examples/ibm-private-dns/main.tf
- ibm/provider.go
- ibm/resource_ibm_private_dns_permitted_network.go
- ibm/resource_ibm_private_dns_permitted_network_test.go
- website/docs/r/private_dns_permitted_network.html.markdown
- website/ibm.erb
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/958
> Private DNS Permitted Network related changes

- ibm/resource_ibm_container_worker_pool_zone_attachment.go
Connects to #1372 
This change will allow `ibm_container_worker_pool_zone_attachment` to wait until ALBs to be associated, if created in a new zone.
> fix: ibm_container_worker_pool_zone_attachment should wait for ALBs

- go.mod
- go.sum
- ibm/data_source_ibm_schematics_workspace.go
- ibm/structures.go
- vendor/github.com/IBM-Cloud/bluemix-go/api/schematics/workspace.go
- vendor/github.com/go-openapi/errors/.travis.yml
- vendor/github.com/go-openapi/strfmt/time.go
- vendor/github.com/go-openapi/swag/.travis.yml
- vendor/github.com/go-openapi/validate/.travis.yml
- vendor/modules.txt
- website/docs/d/schematics_workspace.html.markdown
The PR has the fix ibm_schematics_workspace data source attributes update:
1. location
2. description
3. CRN and 
4. catalog reference -  item_id, item_name, item_url and offering_version.
The output from terraform state file would look like below.
```
"attributes": {
"catalog_ref": {
"item_id": "1082e7d2-5e2f-0a11-a3bc-f88a8e1931fc.f49ae2d5-1c4a-4189-b922-a3b7ebe44194-global",
"item_name": "etcd",
"item_url": "/catalog/content/etcd?kind=iks\u0026version=3.4.7",
"offering_version": "3.4.7"
},
"crn": "crn:v1:bluemix:public:schematics:us-south:a/96fe4b4beb8947bf85223e69dab47878:774d14ce-f57a-4cb4-bd90-2b4512ff8115:workspace:etcd-04-28-2020-4651dcad-af60-49",
"description": "",
"id": "etcd-04-28-2020-4651dcad-af60-49",
"is_frozen": false,
"is_locked": false,
"location": "US",
"name": …
```
> data source : ibm_schematics_workspace attributes update

- ibm/resource_ibm_private_dns_resource_record.go
> Changes to lock resource record id and zone id

- ibm/resource_ibm_cos_bucket.go
when location info is not provided in cos_bucket resource, resource forms invalid URL and throws below error.
```
020/05/22 13:56:36 [DEBUG] ibm_cos_bucket.ansible_20200522-132444: apply errored, but we're indicating that via the Error pointer rather than returning it: RequestError: send request failed
caused by: Put https://s3..amazonaws.com/test_ansible_bucket_example: dial tcp: lookup s3..amazonaws.com: no such host
2020/05/22 13:56:36 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: RequestError: send request failed
caused by: Put https://s3..amazonaws.com/test_ansible_bucket_example: dial tcp: lookup s3..amazonaws.com: no such host
2020/05/22 13:56:36 [ERROR] <root>: eval: *terraform.EvalSequence, err: RequestError: send request failed
caused by: Put …
```
> handle location info

- ibm/resource_ibm_is_security_group_rule.go
> Gen1-Security Group Rule fix: allow 'Any' type for ICMP, TCP, UDP

- ibm/resource_ibm_is_floating_ip.go
FIP without a target causes a panic in the plugin.
```
resource "ibm_is_floating_ip" "fip1" {
name    = "myfip"
zone    = "us-south-1"
}
```
```
2020-06-03T15:26:58.585-0500 [DEBUG] plugin.terraform-provider-ibm: panic: interface conversion: vpcv1.FloatingIPTargetIntf is nil, not *vpcv1.FloatingIPTarget
2020-06-03T15:26:58.585-0500 [DEBUG] plugin.terraform-provider-ibm:
2020-06-03T15:26:58.585-0500 [DEBUG] plugin.terraform-provider-ibm: goroutine 417 [running]:
2020-06-03T15:26:58.585-0500 [DEBUG] plugin.terraform-provider-ibm: github.com/IBM-Cloud/terraform-provider-ibm/ibm.fipGet(0xc0003eb9d0, 0x21a9500, 0xc000d6a000, 0xc000f79950, 0x29, 0x0, 0x0)
2020-06-03T15:26:58.585-0500 [DEBUG] plugin.terraform-provider-ibm:     /home/rodaira/go/src/github.com/IBM-Cloud/terraform-provider-ibm/ibm/r …
```
> Handle FIP without target correctly

- ibm/resource_ibm_is_instance_test.go
I propose to add one more step that attaches the volume again, so that the test covers the case in which TF destroys an instance with a data volume.
> Add a test case for #1594 #1595

- examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/roks_on_vpc.tf
Ref: https://cloud.ibm.com/docs/openshift?topic=openshift-getting-started#vpc-gen2-gs. Step 2b:  "In the Inbound rules section, click New rule."
Closes https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1604
> ibm-cluster ROKS gen2: ibm_is_security_group_rule should be inbound

- examples/ibm-cluster/roks-on-vpc-gen2/roks_on_vpc/roks_on_vpc.tf
This enhancement to the ROKS gen2 VPC example adds two public gateways and links to the two subnets, so the OpenShift web console is available immediately after provisioning.
> Add public gateways and link to subnets to ROKS gen2 example.

- go.sum
- ibm/data_source_ibm_is_vpc.go
- ibm/resource_ibm_is_vpc.go
- ibm/resource_ibm_is_vpc_test.go
In VPC, argument "remote" could be a ip address, CIDR block or security group ID.  It comes as map[string]interface{}. 
Added a check over the remote before looping through the map.  Based on the key ( could be id, address or cidr_block ) populating the remote value.
> Handling Interface nil pointer exception for remote argument

- ibm/resource_ibm_container_vpc_cluster.go
- website/docs/r/container_vpc_cluster.html.markdown
This allows for setting the default worker labels when using the `ibm_container_vpc_cluster` resource to create a cluster.
> set labels on default worker pool

- examples/ibm-is-vpc/main.tf
- ibm/data_source_ibm_is_security_group.go
- ibm/data_source_ibm_is_security_group_test.go
- ibm/provider.go
- website/docs/d/is_security_group.html.markdown
Test results
Apply complete! Resources: 6 added, 0 changed, 0 destroyed.
Outputs:
sg_rules = [
{
"code" = 0
"direction" = "inbound"
"ip_version" = "ipv4"
"port_max" = 0
"port_min" = 0
"protocol" = "all"
"remote" = "127.0.0.1"
"rule_id" = "r006-ddfd256c-b3e7-4b97-9794-f16590bef872"
"type" = 0
},
{
"code" = 0
"direction" = "inbound"
"ip_version" = "ipv4"
"port_max" = 807
"port_min" = 805
"protocol" = "udp"
"remote" = "127.0.0.1"
"rule_id" = "r006-053ba215-813b-4242-8201-f3bf38a7fd0a"
"type" = 0
},
{
"code" = 0
"direction" = "inbound"
"ip_version" = "ipv4"
"port_max" = 22
"port_min" = 22
"protocol" = "tcp"
"remote" = "0.0.0.0/0"
"rule_id" = "r006-e540c4a8-37a5-490b-a2b3-4a21c042adb3"
"type" = 0
},
{
"code" = 0
"direction" = "inbound"
"ip_version" = "ipv4"
"port_max" = 0
"port_min" = 0 …
> New PR for security group Rules

- ibm/resource_ibm_container_alb_cert.go
- website/docs/r/container_alb_cert.html.markdown
This PR adds wait logic in alb certificate destroy function for issue [1712](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1712l)
> added wait logic for alb certificate deletion

- go.sum
- ibm/data_source_ibm_is_floating_ip.go
- ibm/data_source_ibm_is_floating_ip_test.go
- ibm/provider.go
- website/docs/d/is_floating_ip.html.markdown
> DS: VPC Floating IP

- go.mod
- ibm/data_source_ibm_pi_instance.go
- ibm/data_source_ibm_pi_volume.go
- ibm/resource_ibm_pi_instance.go
- ibm/resource_ibm_pi_volume.go
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_volume.html.markdown
- website/docs/r/pi_instance.html.markdown
- website/docs/r/pi_network_port.html.markdown
- website/docs/r/pi_volume.html.markdown
Power VS now has the capability to set the virtual cores as well. Updated the pi_instance code to take input in virtual cores.
> Added virtual cores capability

- ibm/resource_ibm_kms_key.go
HPCS doesn't support all the same regions that Key Protect does and during initialization of the HPCS Client, an error occurs since the region is invalid if using `ibm_kms_key.go` with Key Protect.
This PR moves the HPCS Endpoint API into the section that specifically uses it so during a Key Protect use case, the error does not cause failure.
> Fix ibm_kms_key to work with Key Protect

- go.mod
- go.sum
- ibm/resource_ibm_container_cluster.go
- ibm/resource_ibm_container_vpc_cluster.go
- vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv1/clusters.go
- vendor/github.com/IBM-Cloud/bluemix-go/api/container/containerv2/clusters.go
- vendor/modules.txt
- website/docs/r/container_cluster.html.markdown
- website/docs/r/container_vpc_cluster.html.markdown
This PR has fix for : https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1847
An optional param `force_delete_storage`can be specified to remove the storage PVCs associated with cluster, during cluster deletion.
> Force delete storage

- go.mod
- go.sum
To support launching (ICD) IBM Cloud Databases resources inside
`eu-fr2` the endpoint was added to the `bluemix-go` library. To get this
support added to this Terraform provider we need to bump the version of
the library used.
> Bump bluemix-go to add `eu-fr2` ICD endpoint

- examples/ibm-event-streams/README.md
- examples/ibm-event-streams/main.tf
updating document and example for supported parameters.
> update supported parameters for Event Streams

- examples/ibm-is-vpc/main.tf
- ibm/provider.go
- ibm/resource_ibm_is_subnet_network_acl_attachment.go
- ibm/resource_ibm_is_subnet_network_acl_attachment_test.go
- website/docs/r/is_subnet_network_acl_attachment.html.markdown
- website/ibm.erb
Resource ibm subnet network acl attachment
> Subnet nwacl changes

- examples/ibm-cluster/roks-on-vpc-gen2/variables.tf
The current example for ROKs on VPC gen 2 will correctly create the cluster but will fail when adding kms to the cluster. This due to the fact that the kube version supplied in the variables.tf file, 4.3_openshift which is incompatible with kms. According to IBM cloud documentation the version of Openshift should be 4.4 to support kms. 
The change to kube version would fix it, as I have done here.  However I personally think there should be a different example created that includes kms which is separate from the standard ROKs cluster creation.
> Changed kube version to be 4.4 so the kms will work.

- ibm/resource_ibm_kms_key.go
- ibm/resource_ibm_kms_key_test.go
- website/docs/r/kms_key.html.markdown
Description : Added expiration date functionality to key creation in ibm_kms_key and made appropriate changes in test file for testing.
> Added expiration date field to ibm_kms_key resource

- .github/CONTRIBUTING.md
- ibm/resource_ibm_iam_access_group_test.go
This PR fixes a minor error in the "CheckDestroy" method of the IAM Access Groups resource test file.
According to the [Terraform docs](https://www.terraform.io/docs/extend/testing/acceptance-tests/testcase.html#checkdestroy), the CheckDestroy method should:
> return an error if any resources remain.
As originally coded, the CheckDestroy method would not return an error if `err == nil`, but a get that returns `err == nil` indicates that the requested resource still exists (and was returned).
> fix: IAM access groups test CheckDestroy method

- go.sum
- ibm/resource_ibm_container_cluster.go
- ibm/resource_ibm_container_vpc_cluster.go
- website/docs/r/container_cluster.html.markdown
- website/docs/r/container_vpc_cluster.html.markdown
This PR addresses the following issues for the moment:
- https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1978
- https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1969
- https://github.com/IBM-Cloud/terraform-provider-ibm/issues/1952
In this PR, both `ibm_container_cluster` and `ibm_container_vpc_cluster` resources updates the kube versions of worker node  by setting the `update_all_workers` field to true. 
To handle the wait time for worker node updation, new param `wait_for_worker_update` is introduced. If the cluster has more number of nodes and user not intended to wait till all the the nodes updated, `wait_for_worker_update` can be set to false.
We are working on new resource design to handle the IKS cluster update where the resource would be able to handle major, …
> IKS cluster resources to handle Kube version update.

- ibm/resource_ibm_app_domain_private_test.go
- ibm/resource_ibm_app_domain_shared_test.go
- ibm/resource_ibm_app_route_test.go
- ibm/resource_ibm_cis_test.go
- ibm/resource_ibm_compute_autoscale_group_test.go
- ibm/resource_ibm_compute_autoscale_policy_test.go
- ibm/resource_ibm_compute_dedicated_host_test.go
- ibm/resource_ibm_compute_placement_group_test.go
- ibm/resource_ibm_container_addons_test.go
- ibm/resource_ibm_container_alb_cert_test.go
- ibm/resource_ibm_container_alb_test.go
- ibm/resource_ibm_container_cluster_test.go
- ibm/resource_ibm_container_vpc_alb_test.go
- ibm/resource_ibm_container_vpc_cluster_test.go
- ibm/resource_ibm_container_vpc_worker_pool_test.go
- ibm/resource_ibm_container_worker_pool_test.go
- ibm/resource_ibm_database_postgresql_test.go
- ibm/resource_ibm_event_streams_topic_test.go
- ibm/resource_ibm_iam_access_group_dynamic_rule_test.go
- ibm/resource_ibm_iam_custom_role_test.go
- ibm/resource_ibm_iam_service_id_test.go
- ibm/resource_ibm_iam_user_policy_test.go
- ibm/resource_ibm_resource_group_test.go
- ibm/resource_ibm_resource_instance_test.go
- ibm/resource_ibm_resource_key_test.go
- ibm/resource_ibm_service_instance_test.go
- ibm/resource_ibm_service_key_test.go
This PR fixes the `Destroy` method in a number of the test files to follow the updated pattern for error checking introduced in PR #1988
> fix: Update error check in test Destroy methods

- examples/ibm-event-streams/main.tf
- ibm/resource_ibm_event_streams_topic_test.go
- website/docs/r/event_streams_topic.html.markdown
document and test update for new provision parameter `kms_key_crn` in Event Streams
contribute to: https://github.ibm.com/mhub/zh/issues/1677
> add provision parameter kms_key_crn for Event Streams

- ibm/resource_ibm_event_streams_topic_test.go
this change breaks our test
https://github.com/IBM-Cloud/terraform-provider-ibm/commit/bf33718b21ed7a88f64319a28a33cfee889b098a#diff-db14e0ef8c2849b7a8ce8b65b7abce6763b7d12f1fa4f86b007d0527fce1308fR308
Because we support reclamation, after instance is deleted,
`rsContClient.ResourceServiceInstance().GetInstance` still returns 200, but `instance.state=pending_reclamation`
> check instance state after destroy

- ibm/data_source_ibm_cis.go
- ibm/data_source_ibm_database.go
- ibm/data_source_ibm_resource_instance.go
- ibm/resource_ibm_cis.go
- ibm/resource_ibm_container_worker_pool.go
- ibm/resource_ibm_database.go
- ibm/resource_ibm_resource_instance.go
- ibm/structures.go
The PR creates a helper method to get the default resource group and employs this method in several data source and resources that previously replicated this code.
> refactor: add method to get default resource group

- go.mod
- go.sum
- ibm/resource_ibm_kms_key.go
- ibm/resource_ibm_kms_key_test.go
- ibm/structures.go
- ibm/validators.go
- vendor/github.com/IBM/keyprotect-go-client/.travis.yml
- vendor/github.com/IBM/keyprotect-go-client/CONTRIBUTING.md
- vendor/github.com/IBM/keyprotect-go-client/README.md
- vendor/github.com/IBM/keyprotect-go-client/iam/iam.go
- vendor/github.com/IBM/keyprotect-go-client/import_token.go
- vendor/github.com/IBM/keyprotect-go-client/instances.go
- vendor/github.com/IBM/keyprotect-go-client/keys.go
- vendor/github.com/IBM/keyprotect-go-client/kp.go
- vendor/github.com/IBM/keyprotect-go-client/policy.go
- vendor/github.com/IBM/keyprotect-go-client/registrations.go
- vendor/modules.txt
- website/docs/r/kms_key.html.markdown
- Updated keyprotect-go-client from 0.3.5 to 0.5.2
- Added key policies functionality so that user can specify key policy configuration while creating key
> Key policies for ibm_kms_key resource

- website/docs/r/kms_key.html.markdown
Description: Adding an example for Importing a Key. There was no example on how to import a Key to Key Protect using Terraform as pointed out by an user.
> Add example for Importing a Key

- ibm/resource_ibm_pi_instance.go
Before the instance destroy was returning immediately leading to failures in deleting the dependent resources such as network used by the instance. This will also fix the resource taint issue with smooth apply after taint.
Fixes #2046
Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>
> Handle the delete instance flow correctly

- ibm/data_source_ibm_container_cluster.go
- website/docs/d/container_cluster.html.markdown
Hi there, 
a lot of services are bound to our Kubernetes cluster. Everytime we run the Terraform scripts the ibm_container_cluster data source is executed which fetches all bounded services. In our case this leads to a very long execution time as the API does not respond very fast when there are more than 100 services bound to the cluster (actually it even results in timeout exceptions).
As we do not even need the information about all bounded services I would like to introduce the possibility to add an additional variable to filter for specific namespaces.
This should improve the overall performance of the data source and also the reliability.
The default value still remains as an empty string, so the changes should be backwards compatible.
In case of any questions, don't hesitate to …
> Added input to ibm container data source in order to skip listing bounded services

- ibm/data_source_ibm_is_instance.go
The VPC instance data source (`ibm_is_instance`) SSH private key passphrase parameter should be marked as a sensitive value to prevent logging.
> Private key passphrase should be marked sensitive

- ibm/resource_ibm_kms_key.go
- ibm/resource_ibm_kms_key_test.go
Behaviour: Code was failing when trying to create only Rotation policy or Dual Auth Delete Policy.
> Fix: Creating key with only rotation policy or dual auth policy

- ibm/structures.go
This PR adds two small helper methods that will be useful in providers that use the generated Go SDKs.
The generated Go SDKs use `*int64` for all integer types, but Terraform uses `int`, so we need to do this small conversion for every int value received from the SDK that we want to store into the Terraform state.
Likewise, the generated Go SDKs use either `*float32` or `*float64` for float types, based on size, but Terraform uses `float64` always.  So we need to convert `*float32` to `float64` (`ResourceData.Set` automatically dereferences `*float64` to `float64`, so we don't need a helper for that).
> Add helper functions for generated SDKs

- examples/ibm-hpcs-crypto/main.tf
This PR is to resolve the ISSUE : [ISSUE-2121](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2121)
It was frequently observed that there were intermittent failures when `hpcs_init` script runs right after `ibm_resource_instance` `hpcs_instance` was created.
This PR is adding `time_sleep` in between them.
> ISSUE-2121: add sleep in ibm-hpcs-crypto example

- ibm/resource_ibm_is_vpc_routing_table_route.go
- website/docs/r/is_vpc_routing_table_route.html.markdown
vpc routing table route name is optional, it is failing with error, when not provided
> vpc routing table route name optional field is failing, when not provided

- website/docs/index.html.markdown
link doesn't work, updating to our index of supported resources
> fix broken link for IBM docs in Terraform Registry

- go.sum
- ibm/resource_ibm_container_cluster.go
- ibm/resource_ibm_container_vpc_cluster.go
- website/docs/r/container_cluster.html.markdown
- website/docs/r/container_vpc_cluster.html.markdown
The current IKS cluster resources supports only Major and Minor version update. This PR supports the PATCH update supports.
The `patch_version` parameter can be used to achieve the same. This parameter can be used to Update Patch version. If  `patch_version`  is set to required version and if there is a change in the worker node's Patch version and input Patch version, the worker node will be updated.
> added support for patch update for cluster worker nodes

- ibm/resource_ibm_storage_block.go
- ibm/resource_ibm_storage_block_test.go
- ibm/resource_ibm_storage_file.go
- website/docs/r/storage_block.html.markdown
Resolves #1491 
**Use case:**
* The LUN Id is required for creating a `kubernetes_persistent_volume` resource for the IBM Cloud [Block Storage Attacher](https://cloud.ibm.com/docs/openshift?topic=openshift-utilities#block_storage_attacher) plug-in.
EDIT: Where should the documentation changes be made? I just realised that the markdown change I made for the output parameters wouldn't get picked up as it's a completely different structure to the [published docs](https://cloud.ibm.com/docs/terraform?topic=terraform-infrastructure-resources#storage-block)
> Expose LUN Id of Block volume

- ibm/data_source_ibm_event_streams_topic.go
- ibm/resource_ibm_event_streams_topic.go
tested this scenario:
1. create Event Streams instance and topic
```
$terraform apply -auto-approve 
data.ibm_resource_group.group: Refreshing state...
ibm_resource_instance.es_instance_1: Creating...
ibm_resource_instance.es_instance_1: Still creating... [10s elapsed]
ibm_resource_instance.es_instance_1: Creation complete after 16s [id=crn:v1:bluemix:public:messagehub:us-south:a/2b658d1bce63465653497228f9736952:0f97b516-4059-4f64-ab08-a629da76c74e::]
ibm_event_streams_topic.es_topic_1: Creating...
ibm_event_streams_topic.es_topic_1: Creation complete after 5s [id=crn:v1:bluemix:public:messagehub:us-south:a/2b658d1bce63465653497228f9736952:0f97b516-4059-4f64-ab08-a629da76c74e:topic:my-es-topic]
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```
2. delete topic
```
$bx es init …
```
> Event Streams fix: reset Id to be empty when topic does not exist

- ibm/config.go
This PR creates an IAM authenticator when the IAM key is available, since this will be more robust than using the Bearer Token  authenticator.  The IAM authenticator will obtain and refresh the bearer token as needed.
> Use IAM Autheticator rather than BearerToken when possible

- ibm/data_source_ibm_is_vpc.go
- ibm/resource_ibm_is_vpc.go
- website/docs/d/is_vpc.html.markdown
- website/docs/r/is_vpc.html.markdown
Added an output parameter "default_routing_table" which returns the id of the default routing table created
> Enhancement : added default routing table id to output parameters of ibm_is_vpc

- ibm/resource_ibm_is_lb.go
- website/docs/d/is_lb.html.markdown
- website/docs/r/is_lb.html.markdown
> Logging not supported for Network Loadbalancer

- ibm/resource_ibm_is_lb_listener.go
- ibm/resource_ibm_is_lb_listener_test.go
- ibm/resource_ibm_is_lb_pool.go
- ibm/resource_ibm_is_lb_pool_test.go
- website/docs/r/is_lb_listener.html.markdown
- website/docs/r/is_lb_pool.html.markdown
=== RUN   TestAccIBMISLBPool_basic
--- PASS: TestAccIBMISLBPool_basic (569.11s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 570.401s
=== RUN   TestAccIBMISLBListener_basic
--- PASS: TestAccIBMISLBListener_basic (605.86s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 607.333s
> add proxy_protocol feature for load_balancer

- ibm/resource_ibm_is_networkacls.go
- ibm/resource_ibm_is_networkacls_test.go
- website/docs/r/is_network_acl.html.markdown
=== RUN   TestNetworkACLGen1
siv  map[ibm_is_network_acl.isExampleACL:Type = ibm_is_network_acl ibm_is_vpc.testacc_vpc:Type = ibm_is_vpc]
--- PASS: TestNetworkACLGen1 (87.78s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	91.492s
=== RUN   TestNetworkACLGen2
siv  map[ibm_is_network_acl.isExampleACL:Type = ibm_is_network_acl ibm_is_vpc.testacc_vpc:Type = ibm_is_vpc]
--- PASS: TestNetworkACLGen2 (79.80s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	82.648s
> enhancement : added tag support for network ACL

- ibm/resource_ibm_is_ike_policy.go
- ibm/resource_ibm_is_ipsec_policy.go
- ibm/validators.go
- website/docs/r/is_ike_policy.html.markdown
- website/docs/r/is_ipsec_policy.html.markdown
added DH group 19 and sha512 changes for ike policy and ipsec policy as per the SDK changes
> enhancement: added DH group 19 and sha 512 support for TFP

- ibm/resource_ibm_is_vpc_address_prefix.go
- ibm/resource_ibm_is_vpc_address_prefix_test.go
- ibm/resource_ibm_is_vpc_routing_table_route.go
- ibm/validators.go
Custom BYOIP changes, added reserved ip validation for cidrs and delegate_vpc to allowed values of action
> enhancement: Custom BYOIP changes

- ibm/config.go
Default endpoint should not include `/v2`
> Fix the default RC endpoint

- ibm/resource_ibm_cos_bucket.go
- website/docs/r/cos_bucket.html.markdown
Relates to #2148
Added the new `ca-tor` region to the list of endpoints; those are already available at `s3.ca-tor.cloud-object-storage.appdomain.cloud` and `s3.private.ca-tor.cloud-object-storage.appdomain.cloud`.
> Added ca-tor to the list

- ibm/resource_ibm_database.go
- ibm/resource_ibm_database_elasticsearch_test.go
- ibm/resource_ibm_database_etcd_test.go
- ibm/resource_ibm_database_mongodb_test.go
- ibm/resource_ibm_database_postgresql_test.go
- ibm/resource_ibm_database_rabbitmq_test.go
- ibm/resource_ibm_database_redis_test.go
- website/docs/r/database.html.markdown
New Features for postgres and elasticsearch.:
- Validation is now performed during the plan phase instead of apply
- Horizontal scaling with new attributes `node_count`,  `node_memory_allocation_mb`, `node_disk_allocation_mb`, `node_cpu_allocation_count`
- Deployments can switch between `memory_` to `node_`
- Validation during plan can be enabled for all …
> Database node support

- ibm/resource_ibm_cis_dns_record.go
- ibm/resource_ibm_cis_dns_record_test.go
- website/docs/d/cis_dns_records.html.markdown
- website/docs/r/cis_dns_record.html.markdown
Closes #2535
```
$ make testacc TESTARGS='-run=TestAccIBMCisDNSRecord_PTR'
...
=== RUN   TestAccIBMCisDNSRecord_PTR
--- PASS: TestAccIBMCisDNSRecord_PTR (22.92s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 26.516s
testing: warning: no tests to run
PASS
ok …
```
> feat(ibm_cis_dns_record): Support PTR DNS records

- ibm/data_source_ibm_is_subnet_reserved_ip.go
- ibm/data_source_ibm_is_subnet_reserved_ips.go
- ibm/resource_ibm_is_subnet_reserved_ip.go
- ibm/resource_ibm_is_subnet_reserved_ip_test.go
- website/docs/d/is_subnet_reserved_ip.html.markdown
- website/docs/d/is_subnet_reserved_ips.html.markdown
- website/docs/r/is_subnet_reserved_ip.html.markdown
```
(venv) astha@Asthas-MacBook-Pro:~/go/src/github.com/IBM-Cloud/terraform-provider-ibm$ TF_ACC=1 go test -v -run=TestAccIBMISSubnetReservedIPResource_basic ./ibm
=== RUN   TestAccIBMISSubnetReservedIPResource_basic
--- PASS: TestAccIBMISSubnetReservedIPResource_basic (105.43s)
PASS
ok …
```
> Support virtual endpoint gateway as target to subnet reserved IP

- ibm/resource_ibm_is_networkacls.go
- ibm/resource_ibm_is_networkacls_test.go
In the is_networkacls resource, ICMP type was incorrectly being set to the value of the ICMP code field. This results in the state being continually out of sync with resources when ICMP type is set to a different value to code.
This PR sets the type correctly and modifies the networkacl tests to validate this. Without the fix, the tests fail because Terraform creates a non-empty plan after the initial test step that creates the `is_networkacls`:
without the fix:
```
resource_ibm_is_networkacls_test.go:40: Step 1/1 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
~ …
```
> Fix ICMP type in is_networkacls

- ibm/resource_ibm_is_instance_group.go
- ibm/resource_ibm_is_lb.go
The bug was while deleting the instance_groups, we need to check if the load balancer is active or not. If not, then wait for the load balancer to be active and then delete the instance groups. Otherwise raise the error. 
Jira Task: https://jiracloud.swg.usma.ibm.com:8443/browse/UI-14859
**Bug Description**
Destroy fails with
 
```
{{Error: Error Deleting the InstanceGroup: Load Balancer r006-c66bd695-f88b-4c7d-a4a5-ed69637d021b provisioning_status must be active to delete instance group
{
"StatusCode": 409,
"Headers":
{ ..., "X-Request-Id": [ "9bc944a6-9297-448c-97e1-742c0d1856da" ], "X-Xss-Protection": [ "1; mode=block" ] }
,
"Result": {
"errors": [
{
"code": "conflict_field",
"message": "Load Balancer r006-c66bd695-f88b-4c7d-a4a5-ed69637d021b provisioning_status must be active to …
```
> UI-14859: Instance Group Delete Bugfix

- ibm/resource_ibm_is_vpc_address_prefix.go
- ibm/resource_ibm_is_vpc_address_prefix_test.go
- website/docs/r/is_vpc_address_prefix.html.markdown
Relates OR Closes #2282
```
--- PASS: TestAccIBMISVPCAddressPrefix_basic (192.30s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	196.098s
--- PASS: TestAccIBMISVPCAddressPrefix_InvalidCidr (0.53s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	3.251s
...
```
> added support to make the prefix as default in vpc

- go.mod
- go.sum
- ibm/data_source_ibm_dl_offering_speeds.go
- ibm/data_source_ibm_dl_offering_speeds_test.go
- ibm/data_source_ibm_dl_routers.go
- ibm/data_source_ibm_dl_routers_test.go
- website/docs/d/dl_offering_speeds.html.markdown
- website/docs/d/dl_routers.html.markdown
```
This PR addresses the following changes to direct link service:
1. Add the capabilities for offering speeds which provides the metered and unmetered billing options for that offering speed
2. Add the capabilities for router representing the macsec and non-macsec capable router
```
```
$ make testacc …
```
> feat: adds the capabilities for routers and offering speeds for direct link service

- ibm/structures.go
This PR adds a utility function `sepIdParts` which is an extension of the `idParts` function but with a custom separator parameter.
This is used by new SDKs generated by the Terraform SDK generator in order to support resource IDs that may use alternate separators besides the `/` separator.
> Added utility function to split an ID on a custom separator

- .secrets.baseline
- examples/ibm-iam_identity/README.md
- ibm/data_source_ibm_iam_account_settings.go
- ibm/data_source_ibm_iam_account_settings_test.go
- ibm/resource_ibm_iam_account_settings.go
- ibm/resource_ibm_iam_account_settings_test.go
- website/docs/d/iam_account_settings.html.markdown
- website/docs/r/iam_account_settings.html.markdown
Update provider to include a new parameter `max_sessions_per_identity` in the [Account Settings API](https://cloud.ibm.com/apidocs/iam-identity-token-api#updateaccountsettings)
Relevant tests are passing.
> Add new API param to provider

- go.mod
- go.sum
- ibm/data_source_ibm_container_cluster_config.go
```
=== RUN   TestAccIBMContainer_ClusterConfigDataSourceBasic
2021/05/13 11:33:09 Configuring SoftLayer Session with API key
2021/05/13 11:33:09 Configuring IBM Cloud Session with API key
2021/05/13 11:33:09 [INFO] Configured Region: us-south
2021/05/13 11:33:15 Configuring SoftLayer Session with API …
```
> Support: cluster_config for satellite clusters

- ibm/config.go
- ibm/data_source_ibm_iam_roles.go
- ibm/resource_ibm_iam_access_group_policy.go
- ibm/resource_ibm_iam_access_group_policy_test.go
- ibm/resource_ibm_iam_service_policy.go
- ibm/resource_ibm_iam_service_policy_test.go
- ibm/resource_ibm_iam_user_policy.go
- ibm/resource_ibm_iam_user_policy_test.go
- ibm/structures.go
- website/docs/r/iam_access_group_dynamic_rule.html.markdown
- website/docs/r/iam_access_group_policy.html.markdown
- website/docs/r/iam_authorization_policy.html.markdown
- website/docs/r/iam_service_policy.html.markdown
- website/docs/r/iam_user_policy.html.markdown
Relates OR Closes #2533
```
RUN   TestAccIBMIAMAccessGroupPolicy_Basic
--- PASS: TestAccIBMIAMAccessGroupPolicy_Basic (47.60s)
=== RUN   TestAccIBMIAMAccessGroupPolicy_With_Service
--- PASS: TestAccIBMIAMAccessGroupPolicy_With_Service (49.90s)
=== RUN   TestAccIBMIAMAccessGroupPolicy_With_ResourceInstance
--- PASS: …
```
> Support: IAM Policies Operator

- ibm/data_source_ibm_satellite_host_script.go
```
make testacc TESTARGS='-run=TestAccXXX'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccXXX -timeout 700m
?   	github.com/IBM-Cloud/terraform-provider-ibm	[no test files]
[WARN] Set the environment variable IBM_ORG for …
```
> update azure script to grow root volume group

- ibm/resource_ibm_is_instance_group.go
- ibm/resource_ibm_is_instance_group_manager_policy.go
> fix: instance group manager policy synchronization

- website/docs/d/cr_namespaces.html.markdown
Signed-off-by: James Hart <jhart@uk.ibm.com>
When delivering the updated container-registry provider, the datasource was updated, but its docs were not.
N/A - documentation only
> Bring cr_namespaces datasource doc in line with provider

- ibm/resource_ibm_kms_key.go
**Current Behavior**
When they are trying to create/manage keys using terraform. 
With a user who's been given minimal permissions from their perspective for key management, i.e Reader and Writer
They run into permission issues, since terraform attempts to read the policies for the key as well(example terraform block below).
(Reader+Writer works fine for creating keys using API's)
So, we need to find a way to decouple the key_policy operation through terraform based on user privilege. 
resource "ibm_kms_key" "key" {
instance_id = ibm_resource_instance.kp_instance.guid
key_name       = "key"
standard_key   = false
expiration_date = "2020-12-05T15:43:46Z"
}
resource "ibm_kms_key" "key" {
instance_id = ibm_resource_instance.kp_instance.guid
key_name       = "key"
standard_key   = false …
> Create Key With Writer Role Assignment.

- go.mod
- go.sum
Signed-off-by: James Hart <jhart@uk.ibm.com>
The only change is adding a mapping for the `ca-tor` region (to `ca.icr.io` container-registry).
> Bump container-registry SDK version to 0.0.13

- ibm/data_source_ibm_resource_instance.go
```
$terraform show
data "ibm_resource_instance" "logdna_instance" {
crn                     = "crn:v1:bluemix:public:logdna:us-south:a/4448261269a14562b839e0a3019ed980:cad272c8-fcf7-4e3a-8bcf-07b1e294b316::"
extensions              = {}
guid                    = "cad272c8-fcf7-4e3a-8bcf-07b1e294b316"
id                      = …
```
> Support: tags in resource_instance datasource

- ibm/resource_ibm_firewall.go
- ibm/resource_ibm_ipsec_vpn.go
- ibm/resource_ibm_lb.go
- ibm/resource_ibm_lb_vpx.go
- ibm/resource_ibm_network_public_ip.go
- ibm/resource_ibm_network_vlan.go
- ibm/resource_ibm_ssl_certificate.go
- ibm/resource_ibm_storage_evault.go
- ibm/resource_ibm_storage_file.go
- ibm/resource_ibm_subnet.go
> Fix the NotFound Checks if the resource is still provisioning

- ibm/data_source_ibm_schematics_workspace.go
- ibm/data_source_ibm_schematics_workspace_test.go
Update template_env_settings to complex type instead of TypeMap
```
$ make testacc TESTARGS='-run=TestAccIBMSchematicsWorkspaceDataSourceBasic'
TF_ACC=1 go test ./ibm -v -run=TestAccIBMSchematicsWorkspaceDataSourceBasic -timeout 700m
[WARN] Set …
```
> Fix : Update template_env_settings to complex type instead of TypeMap

- ibm/structures.go
This PR adds two helper functions for converting Date and DateTime objects into strings.  These methods are needed for services that use the generated IBM SDKs, which expose `date` and `date-time` properties in the API as Date and DateTime objects.
> Add date/datetime helpers

- go.mod
- go.sum
> Fix: cluster config

- ibm/data_source_ibm_resource_tag_test.go
- ibm/resource_ibm_resource_tag.go
- ibm/resource_ibm_resource_tag_test.go
```
anilkumarnagaraj@anis-MacBook-Pro terraform-provider-ibm % make testacc TEST=./ibm TESTARGS='-run=TestAccResourceTag'      
TF_ACC=1 go test ./ibm -v -run=TestAccResourceTag -timeout 700m
[WARN] Set …
```
> Fixed resource_tag crn validation issue

- go.sum
- ibm/resource_ibm_iam_access_group_policy.go
- ibm/resource_ibm_iam_access_group_policy_test.go
- ibm/resource_ibm_iam_authorization.policy_test.go
- ibm/resource_ibm_iam_authorization_policy.go
- ibm/resource_ibm_iam_service_policy.go
- ibm/resource_ibm_iam_service_policy_test.go
- ibm/resource_ibm_iam_user_policy.go
- ibm/resource_ibm_iam_user_policy_test.go
Closes #2703 
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccXXX -timeout 700m
?   	github.com/IBM-Cloud/terraform-provider-ibm	[no test files]
[WARN] Set the environment variable IBM_ORG for testing …
```
> Fix: Add changes to resources Exists and test cases to be aware of Soft deleted policies

- ibm/resource_ibm_database.go
Id is set after the wait logic so d.Id() will not work in the error
> Fix: Id of database in error

- ibm/resource_ibm_api_gateway_endpoint.go
- ibm/resource_ibm_api_gateway_endpoint_subscription.go
- ibm/resource_ibm_container_bind_service.go
- ibm/resource_ibm_container_vpc_worker_pool.go
- ibm/resource_ibm_container_worker_pool.go
- ibm/resource_ibm_container_worker_pool_zone_attachment.go
- ibm/resource_ibm_dl_gateway_virtual_connection.go
- ibm/resource_ibm_iam_access_group_dynamic_rule.go
- ibm/resource_ibm_iam_access_group_policy.go
- ibm/resource_ibm_iam_service_policy.go
- ibm/resource_ibm_iam_user_policy.go
- ibm/resource_ibm_kms_key_alias.go
- ibm/resource_ibm_kms_key_rings.go
- ibm/resource_ibm_ob_logging.go
- ibm/resource_ibm_ob_monitoring.go
- ibm/resource_ibm_pi_image.go
- ibm/resource_ibm_pi_key.go
- ibm/resource_ibm_pi_network.go
- ibm/resource_ibm_pi_snapshot.go
- ibm/resource_ibm_pi_volume.go
- ibm/resource_ibm_private_dns_glb.go
- ibm/resource_ibm_private_dns_glb_monitor.go
- ibm/resource_ibm_private_dns_glb_pool.go
- ibm/resource_ibm_private_dns_permitted_network.go
- ibm/resource_ibm_private_dns_resource_record.go
- ibm/resource_ibm_private_dns_zones.go
- ibm/resource_ibm_resource_tag.go
- ibm/resource_ibm_satellite_host.go
- ibm/resource_ibm_tg_gateway_connection.go
> Fix: Panics on Import

- .gitignore
- go.mod
- go.sum
- ibm/data_source_ibm_dl_gateway.go
- ibm/data_source_ibm_dl_gateways.go
- ibm/resource_ibm_dl_gateway.go
- website/docs/d/dl_gateway.html.markdown
- website/docs/d/dl_gateways.html.markdown
- website/docs/r/dl_gateway.html.markdown
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMDLGateway_basic'
TF_ACC=1 go test ./ibm -run=TestAccIBMDLGateway_basic -timeout 700m
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	70.421s
```
```
$ make testacc TEST=./ibm …
```
> feat: adding MD5 authentication key for Direct link Resources, DataSources and Documents

- ibm/data_source_ibm_resource_group.go
Relates OR Closes #2808 
```
=== RUN   TestAccIBMResourceGroupDataSource_Basic
--- PASS: TestAccIBMResourceGroupDataSource_Basic (38.58s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	40.710s
...
```
> Fix: Resource group crash

- ibm/data_source_ibm_pi_network.go
- ibm/data_source_ibm_pi_public_network.go
- ibm/resource_ibm_pi_instance.go
- website/docs/r/pi_instance.html.markdown
Relates OR Closes #1154, #1701
> Add Migratable to pi_instance

- website/docs/d/cr_namespaces.html.markdown
- website/docs/r/cr_namespace.html.markdown
- website/docs/r/cr_retention_policy.html.markdown
> Registry doc updates

- ibm/data_source_ibm_is_vpc_address_prefix.go
- ibm/data_source_ibm_is_vpc_address_prefix_test.go
- ibm/provider.go
- website/docs/d/is_vpc_address_prefix.html.markdown
Relates OR Closes #2594 
https://jiracloud.swg.usma.ibm.com:8443/browse/UI-16837
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIbmIsVpcAddressPrefixDataSourceBasic'
```
> Datasource and Documentation for VPC Address Prefix

- ibm/resource_ibm_container_bind_service.go
- ibm/resource_ibm_container_bind_service_test.go
It was not setting required `cluster_name_id` property and so after import terraform was flagging all bindings to be re-created due to "new" `cluster_name_id` setting. I double checked terraform state after import and all resources had `null` for `cluster_name_id`
```bash
Terraform v0.15.4
on darwin_amd64
```
Output from acceptance …
> fix: set required cluster_name_id attribute

- ibm/data_source_ibm_is_vpc.go
> bug: added a null check for default names in is_vpc datasource

- examples/ibm-is-ng/main.tf
- examples/ibm-is-ng/variables.tf
- ibm/data_source_ibm_is_vpc_address_prefixes.go
- ibm/data_source_ibm_is_vpc_address_prefixes_test.go
- ibm/provider.go
- website/docs/d/is_vpc_address_prefixes.html.markdown
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIbmIsVpcAddressPrefixesDataSourceBasic'
```
> Correction to VPC address prefixes

- ibm/data_source_ibm_is_instance_templates.go
- ibm/data_source_ibm_is_security_group.go
- ibm/data_source_ibm_is_subnet.go
- ibm/data_source_ibm_is_subnets.go
- ibm/data_source_ibm_is_vpc.go
- ibm/resource_ibm_is_instance.go
- ibm/resource_ibm_is_security_group.go
- ibm/resource_ibm_is_security_group_rule.go
- ibm/resource_ibm_is_subnet.go
- ibm/resource_ibm_is_vpc.go
- website/docs/d/is_security_group.html.markdown
- website/docs/d/is_subnet.html.markdown
- website/docs/d/is_vpc.html.markdown
- website/docs/r/is_security_group.html.markdown
- website/docs/r/is_vpc.html.markdown
> Removed IPV6 References in vpc resources

- ibm/resource_ibm_is_subnet.go
> bug - subnet destroy retry when attached resources in use

- ibm/data_source_ibm_is_subnet.go
- ibm/resource_ibm_is_subnet.go
- ibm/structures.go
- website/docs/d/is_subnet.html.markdown
- website/docs/r/is_subnet.html.markdown
Subnet - access management support
```
$ make testacc TESTARGS='-run=TestAccIBMISSubnet_basic'
$ make testacc TESTARGS='-run=TestAccIBMISSubnetDatasource_basic'
```
> Subnet - access management tags support

- ibm/data_source_ibm_is_security_group.go
> added error statement if security group with name is not found in datasource

- ibm/data_source_ibm_cm_catalog.go
- ibm/data_source_ibm_cm_catalog_test.go
- ibm/resource_ibm_cm_catalog.go
- website/docs/d/cm_catalog.html.markdown
- website/docs/r/cm_catalog.html.markdown
Exposes catalog type as per api: https://cloud.ibm.com/apidocs/resource-catalog/private-catalog#create-catalog
```
export TESTARGS="-run TestAccIBMCmCatalog"
make testacc                                                             ✔  10326  11:27:25
==> Checking that code complies with gofmt …
```
> feat: expose catalog type for catalog management

- ibm/resource_ibm_is_subnet.go
> adding a condition to check err during destroy retry

- ibm/resource_ibm_container_vpc_cluster_test.go
make testacc TEST=./ibm TESTARGS='-run=TestAccIBMContainerVpcClusterBasic'
TF_ACC=1 go test ./ibm -v -run=TestAccIBMContainerVpcClusterBasic -timeout 700m
[WARN] Set the environment variable IBM_ID1 for testing ibm_space resource Some tests for that resource will fail if this is not set correctly
[WARN] Set the environment variable IBM_ID2 for testing ibm_space resource Some tests for that resource will fail if this is not set correctly
[WARN] Set …
> Fix the testcase for VPC Cluster

- examples/ibm-cluster/vpc-gen2-cluster/variables.tf
Kube_version variable block is edited with the type and description.
```
...
```
> deleted the default kube_version

- ibm/resource_ibm_is_floating_ip.go
- website/docs/r/is_floating_ip.html.markdown
Relates OR Closes #2911
Output :
```
ibm_is_floating_ip.this: Refreshing state... [id=xxxx-xxxx-xxxx-xxxxx-xxxxxx-xxx]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
-/+ resource …
```
> force new floating ip when there is a change in target zone

- website/docs/d/cm_catalog.html.markdown
- website/docs/d/cm_offering.html.markdown
- website/docs/d/cm_offering_instance.html.markdown
- website/docs/d/cm_version.html.markdown
> docFix: catalog management

- ibm/resource_ibm_is_virtual_endpoint_gateway.go
Closes #2923 
Run the below test with very long ips name
ips  {
subnet   =  "0726-2f03f187-5854-4f10-80f0-4e57b7c0442f"
name        = "test-reserved-ip1-hi-what-is-the-error-i-dont-know-test-reserved-ip1-hi-what-is-the-error-i-dont-know-test-reserved-ip1-hi-what-is-the-error-i-dont-know-test-reserved-ip1-hi-what-is-the-error-i- …
> VPE gateway creation suppresses error message

- ibm/resource_ibm_satellite_location.go
> remove location validator, this is handled via the api

- ibm/data_source_ibm_appid_application_roles.go
- ibm/data_source_ibm_appid_application_roles_test.go
- ibm/data_source_ibm_appid_token_config.go
- ibm/provider.go
- ibm/resource_ibm_appid_application_roles.go
- ibm/resource_ibm_appid_application_roles_test.go
- ibm/resource_ibm_appid_token_config.go
- website/docs/d/appid_application_roles.html.markdown
- website/docs/r/appid_application_roles.html.markdown
- website/docs/r/appid_application_scopes.html.markdown
Reopening this with cleaner history
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMAppIDApplicationRoles* -timeout 700m
=== RUN …
```
> AppID application roles

- ibm/data_source_ibm_appid_redirect_urls.go
- ibm/data_source_ibm_appid_redirect_urls_test.go
- ibm/provider.go
- ibm/resource_ibm_appid_redirect_urls.go
- ibm/resource_ibm_appid_redirect_urls_test.go
- website/docs/d/appid_redirect_urls.html.markdown
- website/docs/r/appid_redirect_urls.html.markdown
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMAppIDRedirectURLs* -timeout 700m
=== RUN   TestAccIBMAppIDRedirectURLsDataSource_basic
--- PASS: …
```
> AppID redirect urls datasource/resource

- ibm/data_source_ibm_iam_user_profile.go
- website/docs/d/iam_user_profile.html.markdown
Relates OR Closes #2940
```data "ibm_iam_user_profile" "user_profle" {
account_id           = "XXX"
allowed_ip_addresses = [
"",
]
email                = "XX@in.ibm.com"
firstname            = "XX"
iam_id               = "XX@in.ibm.com"
ibm_id               = "IBMid-XXX"
id                   = "XX@in.ibm.com"
lastname …
```
> Include the IBM ID in the ibm_iam_user_profile data source #2940

- examples/ibm-satellite/README.md
- examples/ibm-satellite/modules/cluster/README.md
- ibm/data_source_ibm_satellite_cluster_test.go
- ibm/data_source_ibm_satellite_cluster_worker_pool_test.go
- ibm/data_source_ibm_satellite_host_script.go
- ibm/data_source_ibm_satellite_location.go
- ibm/resource_ibm_satellite_cluster.go
- ibm/resource_ibm_satellite_cluster_test.go
- ibm/resource_ibm_satellite_cluster_worker_pool_test.go
- ibm/resource_ibm_satellite_location.go
- website/docs/r/satellite_cluster.html.markdown
anilkumarnagaraj@anis-MacBook-Pro terraform-provider-ibm % make testacc TEST=./ibm TESTARGS='-run=TestAccSatelliteLocation'
TF_ACC=1 go test ./ibm -v -run=TestAccSatelliteLocation -timeout 700m …
> Added retry logic to get location information

- .secrets.baseline
- ibm/data_source_ibm_appid_apm.go
- ibm/data_source_ibm_appid_apm_test.go
- ibm/provider.go
- ibm/resource_ibm_appid_apm.go
- ibm/resource_ibm_appid_apm_test.go
- ibm/resource_ibm_appid_token_config.go
- website/docs/d/appid_apm.html.markdown
- website/docs/r/appid_apm.html.markdown
APM documentation: https://cloud.ibm.com/apidocs/app-id/management#get-cloud-directory-advanced-password-management
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run …
```
> Add AppID APM datasource and resource

- ibm/data_source_ibm_appid_theme_text.go
- ibm/data_source_ibm_appid_theme_text_test.go
- ibm/provider.go
- ibm/resource_ibm_appid_theme_text.go
- ibm/resource_ibm_appid_theme_text_test.go
- website/docs/d/appid_theme_text.html.markdown
- website/docs/r/appid_theme_text.html.markdown
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccThemeText* -timeout 700m
=== RUN   TestAccThemeTextDataSource_basic
--- PASS: TestAccThemeTextDataSource_basic …
```
> feat: add appid theme text datasource and resource

- ibm/data_source_ibm_appid_action_url.go
- ibm/data_source_ibm_appid_action_url_test.go
- ibm/provider.go
- ibm/resource_ibm_appid_action_url.go
- ibm/resource_ibm_appid_action_url_test.go
- website/docs/d/appid_action_url.html.markdown
- website/docs/r/appid_action_url.html.markdown
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMAppIDActionURL* -timeout 700m
=== RUN   TestAccIBMAppIDActionURLDataSource_basic
--- PASS: …
```
> feat: add appid action url datasource and resource

- ibm/data_source_ibm_appid_theme_color.go
- ibm/data_source_ibm_appid_theme_color_test.go
- ibm/provider.go
- ibm/resource_ibm_appid_theme_color.go
- ibm/resource_ibm_appid_theme_color_test.go
- website/docs/d/appid_theme_color.html.markdown
- website/docs/r/appid_theme_color.html.markdown
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccThemeColor* -timeout 700m
=== RUN   TestAccThemeColorDataSource_basic
--- PASS: TestAccThemeColorDataSource_basic …
```
> feat: add appid theme color datasource and resource

- ibm/resource_ibm_is_vpc.go
- ibm/resource_ibm_is_vpc_test.go
- website/docs/r/is_vpc.html.markdown
Relates OR Closes #2994
```
=== RUN   TestAccIBMISVPC_basic
--- PASS: TestAccIBMISVPC_basic (228.74s)
=== RUN   TestAccIBMISVPC_basic_apm
--- PASS: TestAccIBMISVPC_basic_apm (162.74s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 395.146s
```
> added forcenew for address_prefix_management in ibm_is_vpc

- ibm/data_source_ibm_is_image.go
- website/docs/d/is_image.html.markdown
> feature: added support for identifier in is_image datasource

- ibm/data_source_ibm_appid_roles.go
- ibm/data_source_ibm_appid_roles_test.go
- ibm/provider.go
- website/docs/d/appid_roles.html.markdown
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMAppIDRolesDataSource_basic -timeout 700m
=== RUN   TestAccIBMAppIDRolesDataSource_basic
--- PASS: …
```
> feat: add appid roles datasource

- .secrets.baseline
- ibm/data_source_ibm_appid_applications.go
- ibm/data_source_ibm_appid_applications_test.go
- ibm/provider.go
- website/docs/d/appid_applications.html.markdown
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMAppIDApplicationsDataSource_basic -timeout 700m
=== RUN   TestAccIBMAppIDApplicationsDataSource_basic
--- PASS: …
```
> feat: add appid applications datasource

- ibm/data_source_ibm_is_volume.go
- ibm/resource_ibm_is_volume.go
```
--- PASS: TestAccIBMISVolume_basic (194.51s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 197.854s
```
> Removed dereferencing in resource group name for is_volume resource and datasource which was throwing nil pointer dereference

- go.mod
- go.sum
- ibm/resource_ibm_container_vpc_cluster.go
- ibm/resource_ibm_ob_logging.go
- ibm/resource_ibm_ob_monitoring.go
- website/docs/r/ob_logging.html.markdown
- website/docs/r/ob_monitoring.html.markdown
> Add wait for master ready before cluster integrations

- ibm/data_source_ibm_cis_global_load_balancers.go
- ibm/resource_ibm_cis_global_load_balancer.go
- ibm/resource_ibm_cis_global_load_balancer_test.go
- website/docs/d/cis_global_load_balancers.html.markdown
- website/docs/r/cis_global_load_balancer.html.markdown
```
...
```
TF_ACC=1 go test ./ibm -v -run=TestAccIBMCisGlb_CreateAfterManualDestroy -timeout 700m
[WARN] Set the environment variable IBM_APPID_TENANT_ID for testing AppID resources, AppID tests will …
> Adding Steering_Policy property

- ibm/data_source_ibm_is_volume.go
- ibm/resource_ibm_is_volume.go
- website/docs/d/is_volume.html.markdown
- website/docs/r/is_volume.html.markdown
Relates OR Closes #2500
```
--- PASS: TestAccIBMISVolume_basic (187.41s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 191.234s
```
> removed computed from encryption_key and added encryption_type for is_volume

- website/docs/d/appid_action_url.html.markdown
- website/docs/r/appid_action_url.html.markdown
Fix AppID action_url links in documentation
> fix: make sure appid action url label is properly indented

- ibm/data_source_ibm_is_vpc.go
- ibm/data_source_ibm_is_vpcs.go
- ibm/resource_ibm_is_vpc.go
- website/docs/d/is_vpc.html.markdown
- website/docs/d/is_vpcs.html.markdown
- website/docs/r/is_vpc.html.markdown
Relates OR Closes #3029
```
...
```
> added crn for is_vpc resource and datasource in default sg and network acl

- .secrets.baseline
- ibm/resource_ibm_database.go
- ibm/resource_ibm_database_cassandra_test.go
- ibm/resource_ibm_database_edb_test.go
- ibm/resource_ibm_database_mogodb_enterprise_test.go
- ibm/structures.go
- website/docs/r/database.html.markdown
Relates OR Closes #2590
rebased and updated secret baseline to this PR https://github.com/IBM-Cloud/terraform-provider-ibm/pull/2591
> Support: Enterprise DB, Enterprise Mongo, Cassandra Databases

- ibm/resource_ibm_is_instance_volume_attachment.go
- ibm/resource_ibm_is_instance_volume_attachment_test.go
- ibm/resource_ibm_is_volume.go
- ibm/resource_ibm_is_volume_test.go
- ibm/structures.go
- website/docs/r/is_instance_volume_attachment.html.markdown
- website/docs/r/is_volume.html.markdown
```
=== RUN   TestAccIBMISInstanceVolumeAttachment_basic
--- PASS: TestAccIBMISInstanceVolumeAttachment_basic (454.50s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 458.238s
```
```
--- …
```
> added changes for adjustable iops and volume profile

- ibm/data_source_ibm_is_instance.go
- ibm/data_source_ibm_is_instances.go
- ibm/data_source_ibm_is_public_gateway.go
- ibm/data_source_ibm_is_public_gateways.go
- ibm/data_source_ibm_is_ssh_key.go
- ibm/resource_ibm_is_floating_ip.go
- ibm/resource_ibm_is_image.go
- ibm/resource_ibm_is_instance.go
- ibm/resource_ibm_is_instance_template.go
- ibm/resource_ibm_is_public_gateway.go
- ibm/resource_ibm_is_ssh_key.go
- ibm/resource_ibm_is_subnet_network_acl_attachment.go
- ibm/resource_ibm_is_vpn_gateway.go
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/d/is_public_gateway.html.markdown
- website/docs/d/is_public_gateways.html.markdown
- website/docs/d/is_ssh_key.html.markdown
- website/docs/d/is_volume.html.markdown
- website/docs/r/is_floating_ip.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_public_gateway.html.markdown
- website/docs/r/is_ssh_key.html.markdown
- website/docs/r/is_vpn_gateway.html.markdown
> fixed documents for missing crn

- website/docs/r/is_instance.html.markdown
> added a document update regarding allow_ip_spoofing on network interfaces for VSIs

- ibm/resource_ibm_event_streams_schema.go
- ibm/resource_ibm_event_streams_topic.go
Includes:
- Refactor to use `getInstanceDetails` function for both topic and schema
- This way the latest `ResourceControllerV2APIclient` is used even for topic.
> event streams: refactor common getInstanceDetails function

- ibm/provider_test.go
- ibm/resource_ibm_is_instance.go
- ibm/resource_ibm_is_instance_test.go
- ibm/resource_ibm_is_security_group_network_interface_attachment.go
- ibm/resource_ibm_is_security_group_network_interface_attachment_test.go
- website/docs/r/is_security_group_network_interface_attachment.html.markdown
> updated security group target APIs

- ibm/data_source_ibm_satellite_location.go
- ibm/resource_ibm_satellite_location.go
- ibm/structures.go
- website/docs/d/satellite_location.html.markdown
Added zones parameter to immutable list
Added hosts parameter to satellite location data source
anilkumarnagaraj@anis-MacBook-Pro terraform-provider-ibm % make testacc TEST=./ibm TESTARGS='-run=TestAccSatelliteLocation'
TF_ACC=1 go test ./ibm -v -run=TestAccSatelliteLocation -timeout 700m
[WARN] Set the environment variable IBM_APPID_TENANT_ID for testing AppID resources, AppID tests will fail if this is not set …
> Fix for satellite location resource

- ibm/resource_ibm_appid_token_config.go
Fix for AppID token configuration resource, destination_claim property was wrongly marked as required
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMAppIDTokenConfigDataSource_basic -timeout 700m
=== RUN   TestAccIBMAppIDTokenConfigDataSource_basic
--- PASS: …
```
> fix: appid token config destination_claim should be optional

- .secrets.baseline
- ibm/data_source_ibm_appid_cloud_directory_user.go
- ibm/data_source_ibm_appid_cloud_directory_user_test.go
- ibm/data_source_ibm_appid_user_roles.go
- ibm/data_source_ibm_appid_user_roles_test.go
- ibm/provider.go
- ibm/provider_test.go
- ibm/resource_ibm_appid_cloud_directory_user.go
- ibm/resource_ibm_appid_cloud_directory_user_test.go
- ibm/resource_ibm_appid_user_roles.go
- ibm/resource_ibm_appid_user_roles_test.go
- website/docs/d/appid_cloud_directory_user.html.markdown
- website/docs/d/appid_user_roles.html.markdown
- website/docs/r/appid_cloud_directory_user.html.markdown
- website/docs/r/appid_user_roles.html.markdown
* Add AppID user roles datasource and resource
* Switch original user creation API to `signup` api, this allows creating user's profile at the same time. Without user profile there is no way to assign user roles
* Add new computed property `subject` to user resource. This identifier is used when modifying user roles
* Fix user `display_name` property type, set computed flag
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help …
> Add AppID user roles datasource and resource

- examples/ibm-cis/main.tf
- go.mod
- go.sum
- ibm/config.go
- ibm/resource_ibm_cis_dns_record_test.go
- ibm/resource_ibm_cis_domain_settings.go
- ibm/resource_ibm_cis_domain_settings_test.go
- ibm/resource_ibm_cis_global_load_balancer_test.go
- ibm/resource_ibm_cis_healthcheck_test.go
- ibm/resource_ibm_cis_origin_pool_test.go
> Removing CisAP Blumix Dependency

- ibm/config.go
- ibm/resource_ibm_iam_authorization.policy_test.go
- ibm/resource_ibm_iam_authorization_policy.go
```
=== RUN   TestAccIBMIAMAuthorizationPolicyDelegatorRole
2021/09/30 19:37:37 Configuring SoftLayer Session with API key
2021/09/30 19:37:37 Configuring IBM Cloud Session with API key
2021/09/30 19:37:37 [INFO] Configured Region: us-south
2021/09/30 19:37:41 Configuring SoftLayer Session with API key …
```
> Revert authorisation policy role migration

- ibm/resource_ibm_is_floating_ip.go
> dereferencing of rg id, name and target update in floating ip

- ibm/data_source_ibm_database.go
Relates OR Closes https://ibm-argonauts.slack.com/archives/C53NF5MB4/p1633057823397600
```
kavya@Kavyas-MacBook-Pro ~/g/s/g/I/terraform-provider-ibm (platform-go-sdk) [2]> make testacc TEST=./ibm TESTARGS='-run=TestAccIBMDatabaseDataSource_basic'
TF_ACC=1 go test ./ibm …
```
> Fix: ibm_database datasource

- website/docs/r/is_vpn_gateway.html.markdown
- website/docs/r/is_vpn_gateway_connection.html.markdown
> updated docs and examples for vpn gateway and gateway connections

- ibm/data_source_ibm_pi_catalog_images.go
- ibm/data_source_ibm_pi_image.go
- ibm/data_source_ibm_pi_images.go
- ibm/data_source_ibm_pi_instance.go
- ibm/data_source_ibm_pi_instance_volumes.go
- ibm/data_source_ibm_pi_volume.go
- ibm/resource_ibm_pi_instance.go
- ibm/resource_ibm_pi_volume.go
- ibm/resource_ibm_pi_volume_test.go
- website/docs/d/pi_catalog_images.html.markdown
- website/docs/d/pi_image.html.markdown
- website/docs/d/pi_images.html.markdown
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instance_volumes.html.markdown
- website/docs/d/pi_volume.html.markdown
- website/docs/r/pi_instance.html.markdown
- website/docs/r/pi_volume.html.markdown
Relates OR Closes #3266
```
=== RUN   TestAccIBMPIInstanceNetwork
--- PASS: TestAccIBMPIInstanceNetwork (1063.70s)
PASS
=== RUN   TestAccIBMPIInstanceDataSource_basic
--- PASS: TestAccIBMPIInstanceDataSource_basic (61.89s)
PASS
=== RUN …
```
> Support storage pool and affinity for instance and volume

- ibm/structures.go
I had a bug in my previous PR to add support for node-local-dns label on IKS workers https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3232. The result was the labels for node-local-dns were still being ignored. I've tested this locally now and confirms it works.
All that is changed is the grouping of the OR statements. Here is how I've tested locally 
```
Nash $ cat main.go
package main
import (
"fmt"
"strings"
)
func main() {
SystemIBMLabelPrefix := "ibm-cloud.kubernetes.io/"
KubernetesLabelPrefix := "kubernetes.io/"
K8sLabelPrefix := "k8s.io/"
labels := make(map[string]string)
labels["node-type"] = "worker"
labels["ibm-cloud.kubernetes.io/node-local-dns-enabled"] = "true"
labels["ibm-cloud.kubernetes.io/worker-pool"] = "example"
for k, v := range labels {
if …
```
> Fix logic in IgnoreSystemLabels

- .pre-commit-config.yaml
- .secrets.baseline
- go.mod
- go.sum
Signed-off-by: James Hart <jhart@uk.ibm.com>
Updates the container-registry-go-sdk dependency to 0.0.14. This is partially a hygiene update, but also adds support for the br.icr.io registry instance in `br-sao`.
I've also updated the pre-commit hook config and secrets baseline to use the latest version of the detect-secrets tool.
Output from acceptance …
> Bump cr SDK version, hygiene and br-sao support

- ibm/data_source_ibm_cm_catalog.go
- ibm/data_source_ibm_cm_catalog_test.go
- ibm/resource_ibm_cm_catalog.go
- ibm/resource_ibm_cm_catalog_test.go
- website/docs/d/cm_catalog.html.markdown
- website/docs/r/cm_catalog.html.markdown
Support resource groups in catalog resources
```
make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMCmCatalog -timeout 700m
?       github.com/IBM-Cloud/terraform-provider-ibm     [no test files] …
```
> add resource group to cm_catalog resource and datasource

- go.mod
- go.sum
- ibm/config.go
Relates OR Closes #3187 #3294
```
=== RUN   TestAccIBMResourceGroupDataSource_Basic
--- PASS: TestAccIBMResourceGroupDataSource_Basic (31.69s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	33.977s
=== RUN   TestAccIBMResourceInstanceBasic
--- PASS: TestAccIBMResourceInstanceBasic (169.33s)
PASS
ok …
```
> Fix: Incorrect response from SDK #3187 #3294

- ibm/data_source_ibm_is_instance.go
- ibm/data_source_ibm_is_instance_profile.go
- ibm/data_source_ibm_is_instance_profiles.go
- ibm/data_source_ibm_is_instance_template.go
- ibm/data_source_ibm_is_instance_templates.go
- ibm/data_source_ibm_is_instances.go
- ibm/data_source_ibm_is_volume.go
- ibm/resource_ibm_is_instance.go
- ibm/resource_ibm_is_instance_template.go
- ibm/resource_ibm_is_instance_test.go
- ibm/resource_ibm_is_volume.go
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instance_profile.html.markdown
- website/docs/d/is_instance_profiles.html.markdown
- website/docs/d/is_instance_template.html.markdown
- website/docs/d/is_instance_templates.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/d/is_volume.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
- website/docs/r/is_volume.html.markdown
> Feature: instance bandwidth

- ibm/data_source_ibm_compute_reserved_capacity.go
- ibm/resource_ibm_compute_reserved_capacity.go
- website/docs/r/compute_reserved_capacity.html.markdown
> Add force_create to create reserved capacity with exisitng name

- examples/ibm-is-ng/main.tf
- ibm/data_source_ibm_is_network_acl.go
- ibm/data_source_ibm_is_network_acl_test.go
- ibm/data_source_ibm_is_network_acls.go
- ibm/data_source_ibm_is_network_acls_test.go
- ibm/provider.go
- website/docs/d/is_network_acl.html.markdown
- website/docs/d/is_network_acls.html.markdown
```
$ make testacc TESTARGS='-run=TestAccIBMIsNetworkACLDataSourceBasic'
=== RUN   TestAccIBMIsNetworkACLDataSourceBasic
--- PASS: TestAccIBMIsNetworkACLDataSourceBasic (93.58s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 95.790s
$ make testacc …
```
> datasource for network acl and network acl collection

- ibm/resource_ibm_pi_instance.go
- ibm/resource_ibm_pi_volume.go
- ibm/resource_ibm_pi_volume_test.go
Relates OR Closes #3322
```
--- PASS: TestAccIBMPIVolumebasic (494.91s)
PASS
...
```
> Allow volume update when in-use

- website/docs/d/scc_si_notes.html.markdown
- website/docs/d/scc_si_occurrences.html.markdown
- website/docs/r/scc_si_note.html.markdown
- website/docs/r/scc_si_occurrence.html.markdown
Community Note
Please vote on this pull request by adding a 👍 reaction to the original pull request comment to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
Relates OR Closes #0
```
$ make testacc TESTARGS='-run=TestAccIBMSccSi'
...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccIBMSccSi -timeout 700m
?       github.com/IBM-Cloud/terraform-provider-ibm     [no test files]
=== RUN   TestAccIBMSccSiNoteDataSourceBasic
--- PASS: TestAccIBMSccSiNoteDataSourceBasic (23.33s)
=== RUN …
```
> IBM SCC SI - Docs Correction

- ibm/resource_ibm_is_subnet_network_acl_attachment.go
Relates OR Closes #3277
```
=== RUN   TestAccIBMISSubnetNetworkACLAttachment_basic
--- PASS: TestAccIBMISSubnetNetworkACLAttachment_basic (116.18s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 119.621s
```
> fix: set network acl in subnet network acl attachment

- .secrets.baseline
- go.mod
- go.sum
- ibm/config.go
- ibm/utils.go
Signed-off-by: James Hart <jhart@uk.ibm.com>
The dependency update changes the public default region to global.
This PR also alters the private default and adds ca-tor and br-sao to the list of private regions.
```
$ TF_ACC=1 go test ./ibm -v -run="TestAccIBMCr.*" -timeout 700m
...
=== RUN …
```
> Update container-registry SDK and fix default region

- examples/ibm-cos-bucket/README.md
- examples/ibm-cos-bucket/main.tf
- examples/ibm-cos-bucket/variables.tf
- go.mod
- go.sum
- ibm/data_source_ibm_cos_bucket.go
- ibm/resource_ibm_cos_bucket.go
- ibm/resource_ibm_cos_bucket_test.go
- ibm/structures.go
- ibm/validators.go
- website/docs/d/cos_bucket.html.markdown
- website/docs/r/cos_bucket.html.markdown
COS Objectversioning ph2 & abort incomplete MPU:----
-  Incomplete multi-part upload cleanup. 
-  Object Expiration for Versioned Buckets New Lifecycle Functionality
-  Non-Current Version Expiration Lifecycle
-  Expiration Lifecycle behavior on versioning-enabled buckets
-  Expired Object Delete Marker Lifecycle
> COS: Added support for Noncurrent version expiration, EODM & abort incomplete MPU

- ibm/data_source_ibm_iam_service_policy.go
- ibm/data_source_ibm_iam_trusted_profile_policy.go
- ibm/data_source_ibm_iam_user_policy.go
- ibm/resource_ibm_iam_access_group_policy.go
- ibm/resource_ibm_iam_access_group_policy_test.go
- ibm/resource_ibm_iam_service_policy.go
- ibm/resource_ibm_iam_service_policy_test.go
- ibm/resource_ibm_iam_trusted_profile_policy.go
- ibm/resource_ibm_iam_trusted_profile_policy_test.go
- ibm/resource_ibm_iam_user_policy.go
- ibm/resource_ibm_iam_user_policy_test.go
- ibm/structures.go
- website/docs/r/iam_access_group_policy.html.markdown
- website/docs/r/iam_service_policy.html.markdown
- website/docs/r/iam_trusted_profile_policy.html.markdown
- website/docs/r/iam_user_policy.html.markdown
> Added new resource attribute service_type for access policies

- website/docs/r/is_instance.html.markdown
- website/docs/r/is_subnet.html.markdown
> doc fix for instance and subnet

- go.mod
- go.sum
- ibm/data_source_ibm_is_ssh_key.go
- ibm/resource_ibm_is_vpn_gateway_connections.go
- website/docs/d/is_ssh_key.html.markdown
```
--- PASS: TestAccIBMISSSHKeyDatasource_basic (54.68s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 58.873s
```
```
--- PASS: TestAccIBMISVPNGatewayConnection_basic (920.64s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 925.649s
```
```
--- PASS: …
```
> enhancement: sdk migration to use 0.14.0 version of vpc-go-sdk

- ibm/data_source_ibm_pi_catalog_images.go
- ibm/data_source_ibm_pi_catalog_images_test.go
- ibm/data_source_ibm_pi_image.go
- ibm/data_source_ibm_pi_images.go
- ibm/data_source_ibm_pi_instance.go
- ibm/resource_ibm_pi_instance.go
- ibm/resource_ibm_pi_instance_test.go
- website/docs/d/pi_catalog_images.html.markdown
- website/docs/d/pi_image.html.markdown
- website/docs/d/pi_images.html.markdown
- website/docs/d/pi_instance.html.markdown
- website/docs/r/pi_instance.html.markdown
Signed-off-by: Chase Austin [chase@ibm.com](mailto:chase@ibm.com)
```
--- PASS: TestAccIBMPIInstanceBasic (1032.71s)
PASS
=== RUN   TestAccIBMPIInstanceNetwork
--- PASS: TestAccIBMPIInstanceNetwork (1001.32s)
PASS
=== RUN   TestAccIBMPIInstanceVTL
--- PASS: TestAccIBMPIInstanceVTL (754.28s) …
```
> Add support for VTL

- ibm/resource_ibm_event_streams_topic.go
when terraform state is out of sync with topic state, error could happen when re-apply the configuration.
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2275
> fix: Event Streams: do not return error when topic exists in creation

- ibm/resource_ibm_cos_bucket.go
- ibm/resource_ibm_cos_bucket_test.go
```
make test
go test -i $(go list ./... |grep -v 'vendor') || exit 1
go test: -i flag is deprecated
echo $(go list ./... |grep -v 'vendor') | \
xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 …
```
> ibm_cos_bucket: support regions with a numerical suffix

- ibm/data_source_ibm_cos_bucket.go
> reuse the same regex expression defined for resource

- ibm/data_source_ibm_resource_tag.go
- ibm/data_source_ibm_resource_tag_test.go
- ibm/resource_ibm_resource_tag.go
- ibm/structures.go
- website/docs/d/resource_tag.html.markdown
Relates OR Closes #3287
```
--- PASS: TestAccResourceTagDataSourceTagType (14.07s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	16.807s
```
> Fix #3287: retrieve access_tags using ibm_resource_tag datasource

- .secrets.baseline
- ibm/data_source_ibm_resource_key.go
- ibm/resource_ibm_resource_key.go
- ibm/resource_ibm_resource_key_test.go
- website/docs/d/resource_key.html.markdown
- website/docs/r/resource_key.html.markdown
Relates OR Closes  #2180 #1860 #1741
```
=== RUN   TestAccIBMResourceKey_Basic
--- PASS: TestAccIBMResourceKey_Basic (65.29s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm	68.247s
...
```
> Fix #2180 #1860 #1741: support credentials_json in resource_key resource and datasource

- ibm/resource_ibm_resource_key.go
- ibm/resource_ibm_resource_key_test.go
- website/docs/r/resource_key.html.markdown
Relates OR Closes #1387 #1232
```
=== RUN   TestAccIBMResourceKey_Basic
--- PASS: TestAccIBMResourceKey_Basic (63.89s)
=== RUN   TestAccIBMResourceKey_With_Tags
--- PASS: TestAccIBMResourceKey_With_Tags (71.76s)
=== RUN   TestAccIBMResourceKey_Parameters
--- PASS: TestAccIBMResourceKey_Parameters (64.45s)
PASS
ok …
```
> Fix #1387 #1232: made role as optional argument

- ibm/resource_ibm_kms_key.go
- ibm/resource_ibm_kms_key_policies.go
Bug Fix for Policy crash when utilising CRN for instance_id #3351
> Bug Fix Policy

- website/docs/d/dns_permitted_networks.html.markdown
- website/docs/d/dns_resource_records.html.markdown
- website/docs/d/dns_zones.html.markdown
- website/docs/r/dns_permitted_network.html.markdown
- website/docs/r/dns_zone.html.markdown
> DocFix: dns services

- .secrets.baseline
- examples/ibm-satellite/README.md
- examples/ibm-satellite/cluster.tf
- examples/ibm-satellite/instance.tf
- examples/ibm-satellite/modules/cluster/README.md
- examples/ibm-satellite/modules/cluster/main.tf
- examples/ibm-satellite/modules/cluster/variables.tf
- examples/ibm-satellite/variables.tf
- ibm/data_source_ibm_satellite_cluster_worker_pool_zone_attachment.go
- ibm/data_source_ibm_satellite_cluster_worker_pool_zone_attachment_test.go
- ibm/provider.go
- ibm/resource_ibm_satellite_cluster.go
- ibm/resource_ibm_satellite_cluster_worker_pool.go
- ibm/resource_ibm_satellite_cluster_worker_pool_zone_attachment.go
- ibm/resource_ibm_satellite_cluster_worker_pool_zone_attachment_test.go
- ibm/resource_ibm_satellite_location.go
- ibm/structures.go
- website/docs/d/satellite_cluster_worker_pool_zone_attachment.html.markdown
- website/docs/r/satellite_cluster_worker_pool_zone_attachment.html.markdown
```
$ make testacc TESTARGS='-run=TestAccIbmSatelliteClusterWorkerPoolZoneAttachmentAllArgs'
TF_ACC=1 go test ./ibm -v -run=TestAccIbmSatelliteClusterWorkerPoolZoneAttachmentAllArgs -timeout 700m …
```
> add workerpool zone attachment resource

- ibm/resource_ibm_iam_access_group.go
- ibm/resource_ibm_iam_access_group_test.go
Relates OR Closes #3476
```
=== RUN   TestAccIBMIAMAccessGroup_Basic
--- PASS: TestAccIBMIAMAccessGroup_Basic (46.91s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 49.282s
testing: warning: no tests to run
PASS
ok …
```
> added nil value to id in case of 404 in read context of ag #3476

- ibm/service/vpc/data_source_ibm_is_vpc.go
Relates OR Closes #3506
```
--- PASS: TestAccIBMISVPCDatasource_basic (110.15s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     112.334s
```
> fix(is_vpc) : Subnet pagination fix in is_vpc datasource

- ibm/service/power/resource_ibm_pi_cloud_connection.go
Relates OR Closes #3497 
```
=== RUN   TestAccIBMPICloudConnectionbasic
--- PASS: TestAccIBMPICloudConnectionbasic (617.65s)
=== RUN   TestAccIBMPICloudConnectionNetworks
--- PASS: TestAccIBMPICloudConnectionNetworks (871.92s)
PASS
```
> fix: panic while creating cloud connections

- ibm/service/power/resource_ibm_pi_ipsec_policy.go
- ibm/service/power/resource_ibm_pi_ipsec_policy_test.go
- ibm/service/power/resource_ibm_pi_vpn_connection_test.go
- website/docs/r/pi_vpn_ipsec_policy.html.markdown
Fixes #3515
Relates OR Closes #3515
```
=== RUN   TestAccIBMPIIPSecPolicyBasic
--- PASS: TestAccIBMPIIPSecPolicyBasic (72.22s)
=== RUN   TestAccIBMPIVPNConnectionBasic
--- PASS: TestAccIBMPIVPNConnectionBasic (672.77s)
PASS
...
```
> fix: Remove hmac-md5-96 authentication from IPSec VPN policy

- ibm/service/power/resource_ibm_pi_ike_policy.go
- ibm/service/power/resource_ibm_pi_ipsec_policy.go
- website/docs/r/pi_vpn_ike_policy.html.markdown
- website/docs/r/pi_vpn_ipsec_policy.html.markdown
- IKEPolicy
- Removed des-cbc encryption
- Updated docs
- IPSecPolicy
- Removed des-cbc encryption
- Updated docs
```
=== RUN   TestAccIBMPIIKEPolicyBasic
--- PASS: TestAccIBMPIIKEPolicyBasic (53.10s)
=== RUN   TestAccIBMPIIPSecPolicyBasic
--- PASS: TestAccIBMPIIPSecPolicyBasic (28.76s)
```
> Update IKEPolicy and IPSecPolicy encryption/authentication

- go.mod
- go.sum
- ibm/service/kubernetes/data_source_ibm_container_cluster.go
- ibm/service/kubernetes/data_source_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_cluster.go
- ibm/service/kubernetes/resource_ibm_container_cluster_test.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster_test.go
- website/docs/d/container_cluster.html.markdown
- website/docs/d/container_vpc_cluster.html.markdown
- website/docs/r/container_cluster.html.markdown
- website/docs/r/container_vpc_cluster.html.markdown
```
=== RUN   TestAccIBMContainerClusterImageSecuritySetting
--- PASS: TestAccIBMContainerClusterImageSecuritySetting (5032.82s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes    5033.837s
=== RUN   TestAccIBMContainerVpcClusterImageSecuritySetting
--- PASS: …
```
> add image security enforcement functionality

- ibm/service/vpc/resource_ibm_is_subnet.go
> log improvement: subnet delete retry logs

- ibm/service/vpc/resource_ibm_is_security_group_rule.go
```
--- PASS: TestAccIBMISSecurityGroupRule_basic (117.41s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 121.412s
```
> fix(sg-rule): added a check to check if remote sg id exists in is_security_group_rule

- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
Currently, provision parameters which accept a slice of string as a string didn't have ability to reset/handle an empty slice. 
This PR will add a check for empty slice and return an empty slice if true.
> add check for empty slice

- examples/ibm-is-ng/main.tf
- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_vpc_address_prefix.go
- ibm/service/vpc/data_source_ibm_is_vpc_address_prefix_test.go
- ibm/service/vpc/resource_ibm_is_vpc_address_prefix.go
- website/docs/d/is_vpc_address_prefix.html.markdown
- website/docs/d/is_vpc_address_prefixes.html.markdown
- website/docs/r/is_vpc_address_prefix.html.markdown
```
$ make testacc TEST=./ibm TESTARGS='-run=TestAccIBMIsVPCAddressPrefixDataSourceBasic'
=== RUN   TestAccIBMIsVPCAddressPrefixDataSourceBasic
--- PASS: TestAccIBMIsVPCAddressPrefixDataSourceBasic (208.82s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 213.191s
...
```
> feature: Datasource vpc address prefix

- ibm/service/iamidentity/resource_ibm_iam_service_id.go
> Fix #3529 Enhance service_id error message

- .secrets.baseline
- ibm/conns/config.go
> Add support to use the new IAMAuthenticatior for token

- ibm/flex/structures.go
anilkumarnagaraj@anis-MacBook-Pro terraform-provider-ibm % make testacc TEST=./ibm TESTARGS='-run=TestAccSatelliteLocation_Basic'
TF_ACC=1 go test ./ibm -v -run=TestAccSatelliteLocation_Basic -timeout 700m …
> Fixed satellite location immutable error

- ibm/service/power/resource_ibm_pi_network.go
- ibm/service/power/resource_ibm_pi_network_test.go
- website/docs/r/pi_network.html.markdown
```
=== RUN   TestAccIBMPINetworkDNSBasic
--- PASS: TestAccIBMPINetworkDNSBasic (127.91s)
PASS
```
> add network update support

- ibm/service/power/resource_ibm_pi_image.go
- website/docs/r/pi_image.html.markdown
- website/docs/r/pi_instance.html.markdown
```
=== RUN   TestAccIBMPIImagebasic
--- PASS: TestAccIBMPIImagebasic (220.52s)
=== RUN   TestAccIBMPIImageCOSPublicImport
--- PASS: TestAccIBMPIImageCOSPublicImport (1863.67s)
PASS
```
> Support storage pool and affinity while importing image

- go.mod
- go.sum
Relates OR Closes #3596
```
--- PASS: TestAccIBMPIVolumebasic (217.16s)
=== RUN   TestAccIBMPIVolumePool
--- PASS: TestAccIBMPIVolumePool (116.78s)
PASS
```
> Fix for ibm_pi_volume response

- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
Hello. This change has been added so that Terraform can detect when a workerk pool is removed, but its information is still returned if you check through the ID.
Even after deleting a worker pool, GetWorkerPool is not returned error, because the [API](ttps://containers.cloud.ibm.com/global/v2/vpc/getWorkerPool) continues to respond with 200 and pass JSON in this kind:
<details>
```json
{
"id": "[PRIVATE DATA HIDDEN]-2f686a6",
"poolName": "test-pool",
"flavor": "bx2.4x16",
"labels": {
"ibm-cloud.kubernetes.io/worker-pool-id": "[PRIVATE DATA HIDDEN]-2f686a6",
"test": "test"
},
"taints": null,
"workerCount": 1,
"isolation": "public",
"provider": "vpc-gen2",
"isBalanced": true,
"autoscaleEnabled": false,
"openshiftLicense": "",
"lifecycle": {
"desiredState": "deleted",
"actualState": …
```
> Add a check for "Deleted" status of the VPC worker pool

- website/docs/r/is_security_group_target.html.markdown
doc support for endpoint gateway identifier
```
...
```
> Added doc support for endpoint gateway identifier into security group target.

- ibm/flex/structures.go
- ibm/service/iampolicy/resource_ibm_iam_access_group_policy_test.go
Relates OR Closes #3646 
**satellite service specific role "Satellite Link Source and Endpoint Controller" using resource_attributes argument**
**Access-Group policies**
**User Policies**
**Service Policies**
**Trusted Policies**
> Fixing resource_attributes to support the service specific roles

- ibm/service/vpc/data_source_ibm_is_endpoint_gateway_targets.go
- website/docs/d/is_endpoint_gateway_targets.html.markdown
```
--- PASS: TestAccIBMISEndpointGatewayTargetsDataSource_basics (31.51s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 34.487s
```
> fix(egts): endpoint gateways target datasource fix, interchanging the order and including other targets

- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- website/docs/r/is_instance.html.markdown
Relates OR Closes #2205
```
--- PASS: TestAccIBMISInstance_ResizeBoot (269.09s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc	271.042s
```
```
--- PASS: TestAccIBMISInstance_basicwithipv4 (195.62s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     691.706s
```
```
--- PASS: …
```
> feature(is_instance): resize boot volume

- ibm/acctest/acctest.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_placement_group_test.go
- website/docs/r/pi_instance.html.markdown
Add code to allow SAP create with a placement group
and include document statements with the restrictions
that apply with placement groups on instance deployment
=== RUN   TestAccIBMPIPlacementGroupBasic
--- PASS: TestAccIBMPIPlacementGroupBasic (2150.42s)
PASS
> Add code to allow SAP create with a placement group

- ibm/service/vpc/data_source_ibm_is_instance.go
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_template_test.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/data_source_ibm_is_instance_test.go
- ibm/service/vpc/data_source_ibm_is_instances.go
- ibm/service/vpc/data_source_ibm_is_instances_test.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instance_template.html.markdown
- website/docs/d/is_instance_templates.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/d/is_subnet.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
```
$ make testacc TESTARGS='-run=TestAccIBMISInstance_withAvailablePolicy'
$ make testacc TESTARGS='-run=TestAccIBMISInstanceTemplate_withAvilablePolicy'
$ make testacc TESTARGS='-run=TestAccIBMISInstanceTemplate_dataBasic'
$ make testacc TESTARGS='-run=TestAccIBMISInstanceTemplates_dataBasic'
$ make testacc TESTARGS='-run=TestAccIBMISInstanceDataSource_basic'
$ make testacc TESTARGS='-run=TestAccIBMISInstancesDataSource_basic'
```
> VM Host Failure - Available Policy Development

- ibm/provider/provider.go
- ibm/service/vpc/resource_ibm_is_subnet_routing_table_attachment.go
- ibm/service/vpc/resource_ibm_is_subnet_routing_table_attachment_test.go
- website/docs/r/is_subnet_routing_table_attachment.html.markdown
```
--- PASS: TestAccIBMISSubnetRoutingTableAttachment_basic (112.57s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     115.989s
```
>  enhancement(subnet): added support for ibm_is_subnet_routing_table_attachment

- ibm/service/dnsservices/data_source_ibm_private_dns_custom_resolver_forwarding_rules_test.go
- ibm/service/dnsservices/data_source_ibm_private_dns_custom_resolver_test.go
- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver.go
- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver_forwarding_rule.go
- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver_forwarding_rule_test.go
- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver_location_test.go
- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver_test.go
- website/docs/r/dns_custom_resolver.html.markdown
- website/docs/r/dns_custom_resolver_forwarding_rule.html.markdown
Output:
**terraform show**
```
2022-02-15T11:23:30.580+0530 [DEBUG] plugin: plugin exited
resource "ibm_dns_custom_resolver" "test" {
custom_resolver_id = "5ef15a45-73b2-4780-9af3-6f67d2e2dcbd"
description        = "new test CR TF-1"
enabled            = true
health             = "HEALTHY"
high_availability  = true
id                 = "5ef15a45-73b2-4780-9af3-6f67d2e2dcbd:d515a480-a702-4837-9f40-6c0c285262fd"
instance_id        = "d515a480-a702-4837-9f40-6c0c285262fd"
name               = "testCR-TF-New"
rules              = [
{
description = "default forwarding rule"
forward_to  = [
"161.26.0.9",
]
match       = "*"
rule_id     = "6542f018-bcd8-4423-801e-74224565c7da"
type        = "default"
},
{
description = "Regla1"
forward_to  = [
"10.10.10.8",
]
match       = "prueba.dns"
rule_id …
```
> default forwarding rule in custom resolver issue:115

- ibm/flex/structures.go
- ibm/service/iamaccessgroup/data_source_ibm_iam_access_group.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_members.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_members_test.go
- website/docs/d/iam_access_group.html.markdown
- website/docs/r/iam_access_group_members.html.markdown
```[INFO] Set the environment variable IBM_CONTAINER_CLUSTER_NAME for ibm_container_nlb_dns resource or datasource else tests will fail if this is not set correctly
=== RUN   TestAccIBMIAMAccessGroupDataSource_Basic
--- PASS: TestAccIBMIAMAccessGroupDataSource_Basic (70.87s)
=== RUN …
```
> update tp member in ag

- ibm/service/vpc/data_source_ibm_is_security_groups.go
- ibm/service/vpc/data_source_ibm_is_security_groups_test.go
- website/docs/d/is_security_groups.html.markdown
```
--- PASS: TestAccIBMIsSecurityGroupsDataSourceBasic (39.18s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     41.840s
```
> fix(security_groups): removed deprecated network interfaces field from security groups list datasource

- ibm/service/vpc/data_source_ibm_is_region.go
- ibm/service/vpc/data_source_ibm_is_region_test.go
- website/docs/d/is_region.html.markdown
Relates OR Closes #1258
```
--- PASS: TestAccIBMISRegionDataSource_basic (35.59s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 40.186s
```
> enhancement(is_region): made name as optional in ibm_is_region datasource

- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_instance_ip.go
- ibm/service/power/data_source_ibm_pi_instances.go
1. Removed deprecated attributes:
- `Addresses`->`Networks`
- `IP`->`IPAddress`
2. Additional check for dynamic network address where IPAddress is " ".
```
=== RUN   TestAccIBMPIInstanceIPDataSource_basic
--- PASS: …
```
> Support dynamic network type address

- examples/ibm-scc/admin/main.tf
- ibm/provider/provider.go
- ibm/service/scc/data_source_ibm_scc_account_location_settings.go
- ibm/service/scc/data_source_ibm_scc_account_location_settings_test.go
- ibm/service/scc/data_source_ibm_scc_account_locations.go
- ibm/service/scc/data_source_ibm_scc_account_locations_test.go
- ibm/service/scc/data_source_ibm_scc_account_notification_settings.go
- ibm/service/scc/data_source_ibm_scc_account_notification_settings_test.go
- ibm/service/scc/resource_ibm_scc_account_settings.go
- ibm/service/scc/resource_ibm_scc_account_settings_test.go
- ibm/service/scc/resource_ibm_scc_account_settings_validator.go
- website/docs/d/scc_account_location.html.markdown
- website/docs/d/scc_account_location_settings.html.markdown
- website/docs/d/scc_account_notification_settings.html.markdown
- website/docs/r/scc_account_settings.html.markdown
- changed the provider to accommodate the changes needed for the service scc
- added the better validation for the testing
- added a new datasource named notification_settings
```
go test -i $(go list …
```
> IBM Security and Compliance Center Update(SCC) Admin Update

- ibm/service/vpc/resource_ibm_is_lb_pool_member.go
- ibm/service/vpc/resource_ibm_is_lb_pool_member_test.go
- website/docs/r/is_lb_pool_member.html.markdown
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISLBPoolMember_basic_opt_weight_check'
=== RUN   TestAccIBMISLBPoolMember_basic_opt_weight_check
--- PASS: TestAccIBMISLBPoolMember_basic_opt_weight_check (807.13s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc …
```
> Added fix for lb pool member weight (optional attribute)  assigned 0 when not provided

- ibm/service/vpc/resource_ibm_is_ssh_key.go
- ibm/service/vpc/resource_ibm_is_ssh_key_test.go
Relates OR Closes #3639
```
--- PASS: TestAccIBMISSSHKey_Newlinebasic (49.17s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     50.847s
```
```
--- PASS: TestAccIBMISSSHKey_basic (61.91s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     63.003s
```
> fix(sshkey): add DiffSuppressFunc for public key for ibm_is_ssh_key resource

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_cassandra_test.go
- ibm/service/database/resource_ibm_database_elasticsearch_test.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_database_redis_test.go
- website/docs/r/database.html.markdown
Add support for scaling database resources by group ID See: https://cloud.ibm.com/apidocs/cloud-databases-api/cloud-databases-api-v5#setdeploymentscalinggroup
- Adds a TypeSet `group` that specifies resource scaling values per group
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstance'
...
--- …
```
> feature(Cloud Databases): Group scaling

- ibm/service/vpc/resource_ibm_is_lb_listener.go
- ibm/service/vpc/resource_ibm_is_lb_listener_test.go
- website/docs/r/is_lb.html.markdown
- website/docs/r/is_lb_listener.html.markdown
```
--- PASS: TestAccIBMISNLBPortRangeListener_basic (975.93s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 980.482s
```
```
--- PASS: TestAccIBMISNLBRouteModeListener_basic (820.60s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     824.920s
```
> feature(lb) : support for port range for public network load balancers

- ibm/service/scc/resource_ibm_scc_posture_collector.go
- ibm/service/scc/resource_ibm_scc_posture_collector_test.go
- ibm/service/scc/resource_ibm_scc_posture_credential.go
- ibm/service/scc/resource_ibm_scc_posture_credential_test.go
- ibm/service/scc/resource_ibm_scc_posture_scope.go
- ibm/service/scc/resource_ibm_scc_posture_scope_test.go
Create scope issue
```
...
```
> SCC-PostureManagement Create scope issue

- .secrets.baseline
- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_mongodb_enterprise_test.go
- website/docs/r/database.html.markdown
A MongoDB Enterprise will crash at provision time if groups with a `group_id` other than `member` (`bi_connector`, `analytics`) is defined. 
This PR will
- use the correct deployment type (`mongodbee`) for MongoDB enterprise
- fix provisioning scaling math with correct nodeCount per group
- add test case for MongoDB Enterprise Edition with scaled bi_connector, analytics groups  
Example: 
```hcl
resource "ibm_database" "mongo_test" {
name                = "testing-mongo-db-enterprise"
service             = "databases-for-mongodb"
plan                = "enterprise"
location            = "us-east"
group {
group_id = "analytics"
members {
allocation_count = 1
}
}
group {
group_id = "bi_connector"
members {
allocation_count = 1
}
}
timeouts {
create = "3h"
delete = "2h"
}
}
```
```sh
$ …
```
> fix(Cloud Databases): fix group scaling crash during provisioning

- ibm/service/power/data_source_ibm_pi_keys.go
- ibm/service/power/data_source_ibm_pi_sap_profiles.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_dhcp.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_placement_group.go
- ibm/service/power/resource_ibm_pi_volume.go
- ibm/service/power/resource_ibm_pi_vpn_connection.go
Most of the argument/attribute names for the power package are defined in an external helpers package.
Some of these constants are currently being defined in specific data_source files.
This PR moves the power argument/attribute constants defined in the terraform repo  to a singular constant file.
In the future, more PR's will consolidate all external/internal power argument/attribute constants into the new constants file
Files affected
- data_source_ibm_pi_keys.go
- data_source_ibm_pi_sap_profiles.go
- resource_ibm_pi_dhcp.go
- resource_ibm_pi_instance.go
- resource_ibm_pi_placement_group.go
- resource_ibm_pi_volume.go
- resource_ibm_pi_vpn_connection.go
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and …
> Relocating all power constants to one file

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- website/docs/r/database.html.markdown
totals should be calculated based on current member nodeCount
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstance.*Group'
--- PASS: TestAccIBMDatabaseInstance_Elasticsearch_Group (1255.33s)
--- PASS: TestAccIBMDatabaseInstancePostgresGroup (2314.72s)
--- PASS: …
```
> fix(Cloud Databases): remove nodeCount update during group validation

- ibm/service/vpc/data_source_ibm_is_subnet_reserved_ip.go
- ibm/service/vpc/data_source_ibm_is_subnet_reserved_ips.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_action.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip.go
- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip_test.go
- website/docs/r/is_bare_metal_server.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_subnet_reserved_ip.html.markdown
```
--- PASS: TestAccIBMISSubnetReservedIPResource_address (116.45s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     118.131s
```
> fix(reserved ip) : bare metal server reserved ip multi nic changes, doc fix

- ibm/service/power/resource_ibm_pi_network.go
- ibm/service/power/resource_ibm_pi_network_test.go
- website/docs/r/pi_network.html.markdown
```
=== RUN   TestAccIBMPINetworkbasic
--- PASS: TestAccIBMPINetworkbasic (48.84s)
PASS
=== RUN   TestAccIBMPINetworkGatewaybasic
--- PASS: TestAccIBMPINetworkGatewaybasic (54.00s)
PASS
...
```
> Add gateway & ip_address_range attribute for network resource

- ibm/service/vpc/data_source_ibm_is_vpc_routing_table_route.go
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMIBMIsVPCRoutingTableRouteDataSourceBasic'
=== RUN   TestAccIBMIBMIsVPCRoutingTableRouteDataSourceBasic
--- PASS: TestAccIBMIBMIsVPCRoutingTableRouteDataSourceBasic (83.64s)
PASS
ok …
```
> Bug route by name

- .secrets.baseline
- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_mongodb_enterprise_test.go
- website/docs/d/database.html.markdown
- website/docs/r/database.html.markdown
Adds support for multiple user types (`database`, `ops_manager`, `read_only_replica`) for the IBM Database Resource 
See https://cloud.ibm.com/apidocs/cloud-databases-api/cloud-databases-api-v5#createdatabaseuser
Output from acceptance testing: 
```sh
$ make testacc TESTARGS='-run=TestAccIBMMongoDBEnterprise'
...
--- PASS: …
```
> enhancement(Cloud Databases): add support for User types, roles 

- ibm/service/atracker/atracker_utils.go
- ibm/service/atracker/data_source_ibm_atracker_routes.go
- ibm/service/atracker/data_source_ibm_atracker_targets.go
Fixes some of the datasources not returning the correct results between the two api versions.  Now explicitly calls the api for targets (since the version 2 version returns all targets across regions where as version 1 only returns current region).  Routes fixed to ensure that it doesn't crash on version 1.
Output from acceptance …
> update to ensure v1 behaviour for atracker

- ibm/service/iampolicy/data_source_ibm_iam_access_group_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_authorization_policies.go
- ibm/service/iampolicy/data_source_ibm_iam_service_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_trusted_profile_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_user_policy.go
- ibm/service/iampolicy/resource_ibm_iam_access_group_policy.go
- ibm/service/iampolicy/resource_ibm_iam_access_group_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_authorization_policy.go
- ibm/service/iampolicy/resource_ibm_iam_authorization_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_service_policy.go
- ibm/service/iampolicy/resource_ibm_iam_service_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_trusted_profile_policy.go
- ibm/service/iampolicy/resource_ibm_iam_trusted_profile_policy_test.go
- ibm/service/iampolicy/resource_ibm_iam_user_policy.go
- ibm/service/iampolicy/resource_ibm_iam_user_policy_test.go
- website/docs/d/iam_access_group_policy.html.markdown
- website/docs/d/iam_authorization_policy.html.markdown
- website/docs/d/iam_service_policy.html.markdown
- website/docs/d/iam_trusted_profile_policy.html.markdown
- website/docs/d/iam_user_policy.html.markdown
- website/docs/r/iam_access_group_policy.html.markdown
- website/docs/r/iam_authorization_policy.html.markdown
- website/docs/r/iam_service_policy.html.markdown
- website/docs/r/iam_trusted_profile_policy.html.markdown
- website/docs/r/iam_user_policy.html.markdown
Relates OR Closes #3224 
**service policy output**
**access-group policies**
**user policies**
**Trusted profile policies**
**Authorization policies**
**DataSource**
> Support of Transaction-Id

- ibm/service/kms/data_source_ibm_kms_key_policies.go
- ibm/service/kms/resource_ibm_kms_key_alias.go
- ibm/service/kms/resource_ibm_kms_key_alias_test.go
- ibm/service/kms/resource_ibm_kms_key_policies.go
- ibm/service/kms/resource_ibm_kms_key_policies_test.go
- website/docs/d/kms_key_policies.html.markdown
- website/docs/r/kms_key_alias.html.markdown
- website/docs/r/kms_key_policies.html.markdown
- website/docs/r/kp_key.html.markdown
Added alias support for KeyPolicies management
> Alias support for Key Policies

- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver.go
- website/docs/r/dns_custom_resolver.html.markdown
> fix : ibm_dns_custom_resolver locations 

- go.mod
- go.sum
- ibm/acctest/acctest.go
- ibm/service/kubernetes/data_source_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/data_source_ibm_container_vpc_worker_pool_test.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool_test.go
- website/docs/d/container_vpc_cluster_worker_pool.html.markdown
- website/docs/r/container_vpc_worker_pool.html.markdown
```
=== RUN   TestAccIBMContainerVpcClusterWorkerPoolDedicatedHost
--- PASS: TestAccIBMContainerVpcClusterWorkerPoolDedicatedHost (585.88s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes	586.976s
=== RUN   TestAccIBMContainerVPCClusterWorkerPoolDataSource_dedicatedhost
--- …
```
> host pool ID for worker pool resource and data source

- ibm/service/kubernetes/data_source_ibm_container_vpc_cluster_worker.go
- ibm/service/kubernetes/data_source_ibm_container_vpc_cluster_worker_test.go
- website/docs/d/container_vpc_cluster_worker.html.markdown
```
❯ make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainerVPCClusterWorkerDataSource_dedicatedhost'
=== RUN   TestAccIBMContainerVPCClusterWorkerDataSource_dedicatedhost
--- PASS: TestAccIBMContainerVPCClusterWorkerDataSource_dedicatedhost (54.33s)
PASS
ok …
```
> Add host pool ID to VPC worker data source

- ibm/service/power/data_source_ibm_pi_key.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_key.go
- website/docs/d/pi_key.html.markdown
- website/docs/r/pi_key.html.markdown
Fixes #3770
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>
Relates OR Closes #3770
```
=== RUN TestAccIBMPIKeyDataSource_basic 
--- PASS: TestAccIBMPIKeyDataSource_basic (15.12s) 
=== RUN TestAccIBMPIKey _basic 
--- PASS: TestAccIBMPIKey_basic (49.23s) 
PASS
```
> clean up pi_key resource and data source

- go.sum
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_instance.go
- website/docs/r/pi_instance.html.markdown
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>
```
=== RUN   TestAccIBMPISAPInstance
--- PASS: TestAccIBMPISAPInstance (649.23s)
PASS
...
```
> Support SAP deployment type

- ibm/service/vpc/resource_ibm_is_security_group_rule.go
> fix(ibm_is_security_group_rule): ignore 404 during destroy

- examples/ibm-private-dns/main.tf
- website/docs/r/dns_glb.html.markdown
Enabled argument of glb resource was not mentioned in the doc.
Original Issue# https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3818
**Testing**
**1st.** Build was successful
Log : 
rahul.gahlautibm.com@Rahuls-MacBook-Pro terraform-provider-ibm % git branch
master
* pdns_doc_rg
rahul.gahlautibm.com@Rahuls-MacBook-Pro terraform-provider-ibm % make fmt
gofmt -w $(find .  -path ./.direnv -prune -false -o -name '*.go' |grep -v vendor)
rahul.gahlautibm.com@Rahuls-MacBook-Pro terraform-provider-ibm % make build
go vet .
go install
rahul.gahlautibm.com@Rahuls-MacBook-Pro terraform-provider-ibm % 
**2nd.** Tested the enabled flag with true and false and without mentioning it in tf.
Result : expected.
when not mentioned by …
> Enabled argument of glb resource was not mentioned in the doc

- ibm/service/vpc/resource_ibm_is_instance_network_interface.go
> fix: instance network interface mutex sync

- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
Relates OR Closes  #3819
```
=== RUN   TestAccIBMISInstanceSnapshotRestore_forcenew
--- PASS: TestAccIBMISInstanceSnapshotRestore_forcenew (657.48s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     659.240s
```
```
--- PASS: TestAccIBMISInstanceSnapshotRestore_basic (356.79s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     358.436s
```
```
--- PASS: TestAccIBMISInstance_rip (216.26s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     217.620s
```
```
--- PASS: TestAccIBMISInstance_basic (338.99s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     340.842s …
```
> fix(ibm_is_instance) : fixed force new on change in snapshot in boot_volume

- ibm/service/kubernetes/resource_ibm_container_storage_attachment.go
- ibm/service/kubernetes/resource_ibm_container_storage_attachment_test.go
```
$ export TESTARGS="-run TestAccIBMContainerVpcClusterWorkerVolumeAttachment_Basic"
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMContainerVpcClusterWorkerVolumeAttachment_Basic -timeout 700m
...
=== RUN …
```
> fix ibm_container_storage_attachment import

- ibm/service/iampolicy/resource_ibm_iam_user_invite.go
Relates OR Closes [3863](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3863)
```
...
```
> Fix: user invite invited_users issue

- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_images.go
- ibm/service/vpc/data_source_ibm_is_images_test.go
- website/docs/d/is_images.html.markdown
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISImageDataSource_With_FilterStatus'
=== RUN   TestAccIBMISImageDataSource_With_FilterStatus
--- PASS: TestAccIBMISImageDataSource_With_FilterStatus (44.18s)
PASS …
```
> enhancement: filter by status in IS images data source

- go.mod
- go.sum
- ibm/conns/config.go
- Updates the `platform-services-go-sdk` package version from `0.25.1` to 0.26.1`
- Minor code change from `contextbasedrestrictionsv1.Options` to `contextbasedrestrictionsv1.ContextBasedRestrictionsV1Options`
- Otherwise, the package version enables atracker to use regions `eu-de`, `eu-gb` and `au-syd` …
> updated platform-services-go-sdk version to 0.26.1

- ibm/service/dnsservices/resource_ibm_private_dns_resource_record.go
This code fix has reduced the time for 1000 dns resource records from 32 mins to 8-10 mins.
> Added multithreading for 49 requests in dns resource records

- ibm/flex/structures.go
- ibm/service/vpc/resource_ibm_is_instance.go
- website/docs/r/is_instance.html.markdown
> instance profile patch enhancement

- ibm/service/cis/resource_ibm_cis_waf_group.go
- ibm/service/cis/resource_ibm_cis_waf_group_test.go
- website/docs/d/cis_waf_groups.html.markdown
- website/docs/r/cis_waf_group.html.markdown
Issue - https://github.ibm.com/NetworkTribe/CIS_Support/issues/2342
Fix - 
Added a new field to be passed as a part of config - `check_mode`
> cis waf group settings fix

- examples/ibm-cis/main.tf
- website/docs/r/cis_domain_settings.html.markdown
Issue - https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3736
> added note for default cipher values

- ibm/service/vpc/resource_ibm_is_vpc_route.go
- website/docs/d/is_vpc_routing_table_routes.html.markdown
- website/docs/r/is_vpc_route.html.markdown
Deprecation msg for vpc_route resource and doc, correction in vpc_routing_table_route.
```
...
```
> Deprecation of `ibm_is_vpc_route` resource & correction for `ibm_is_vpc_routing_table_route` 

- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float_test.go
```
=== RUN   TestAccIBMISBareMetalServerNetworkInterfaceAllowFloat_basic
--- PASS: TestAccIBMISBareMetalServerNetworkInterfaceAllowFloat_basic (47.90s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     49.662s
```
```
=== RUN …
```
> fix(bare_metal_server_network_interface_allow_float) : updated GetOk to GetOkExists for nat and allow ip spoofing

- ibm/service/power/data_source_ibm_pi_key.go
- ibm/service/power/data_source_ibm_pi_keys.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_key.go
- website/docs/d/pi_key.html.markdown
- website/docs/d/pi_keys.html.markdown
- website/docs/r/pi_key.html.markdown
```
=== RUN   TestAccIBMPIKeyDataSource_basic
--- PASS: TestAccIBMPIKeyDataSource_basic (9.88s)
=== RUN   TestAccIBMPIKeysDataSourceBasic
--- PASS: TestAccIBMPIKeysDataSourceBasic (9.32s)
=== RUN   TestAccIBMPIKey_basic
--- PASS: TestAccIBMPIKey_basic (11.11s)
```
- Using new Argument/Attribute naming …
> Made Changes to PI Keys

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
- website/docs/r/is_bare_metal_server.markdown
>  fix(is_bare_metal_server): removed nics with allow float from server nics

- go.mod
- go.sum
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_dhcp.go
- ibm/service/power/resource_ibm_pi_dhcp_test.go
- website/docs/r/pi_dhcp.html.markdown
Add SNAP enabled bool for DHCP create function
=== RUN   TestAccIBMPIDhcpSNAT
--- PASS: TestAccIBMPIDhcpSNAT (374.02s)
PASS
```
...
```
> Add SNAT enabled bool for DHCP create function

- ibm/acctest/acctest.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance_test.go
- website/docs/r/pi_instance.html.markdown
```
--- PASS: TestAccIBMPIInstanceBasic (414.38s)
PASS
...
```
> Terraform Support for EPIC offering Create flow

- examples/ibm-cloudant-database/README.md
- examples/ibm-cloudant/README.md
Document the minimum necessary IAM roles to use the `ibm_cloudant` resource/data-source and `ibm_cloudant_database` resource/data-source.
> Add Cloudant IAM minimum role notes

- ibm/service/power/resource_ibm_pi_cloud_connection.go
- website/docs/d/pi_cloud_connection.html.markdown
- website/docs/r/pi_cloud_connection.html.markdown
Fix duplicate VPC entries in cloud connection create
operation.
=== RUN   TestAccIBMPICloudConnectionVPC
--- PASS: TestAccIBMPICloudConnectionVPC (376.75s)
PASS
...
```
> Fix duplicate VPC entries in cloud conn create

- ibm/flex/structures.go
```
=== RUN   TestAccIBMResourceInstanceBasic
--- PASS: TestAccIBMResourceInstanceBasic (208.27s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/resourcecontroller	210.254s
```
> fix: account_id issue when service id apikey is used

- examples/ibm-is-ng/main.tf
- ibm/service/vpc/resource_ibm_is_backup_policy_plan.go
- website/docs/r/is_backup_policy_plan.html.markdown
`delete_over_count` cannot be `0, is allowed to set to `null`.
Output testing:
```
resource "ibm_is_backup_policy" "is_backup_policy" {
match_user_tags = ["tag-0"]
name            = "backup-policy"
}
resource "ibm_is_backup_policy_plan" "is_backup_policy_plan_import" {
backup_policy_id = ibm_is_backup_policy.is_backup_policy.id
name …
```
> Delete Over Count Bug Fix

- ibm/service/cis/data_source_ibm_cis_domain.go
- ibm/service/cis/resource_ibm_cis_domain.go
- ibm/service/cis/resource_ibm_cis_firewall_rules.go
- website/docs/r/cis_firewall_rules.html.markdown
Problem statement - 
- On deletion of Firewall Rules, the filter is not removed automatically.
Issue - https://github.ibm.com/NetworkTribe/CIS_Support/issues/2515
> CIS - Delete filter on deletion of Firewall Rules 

- go.mod
- go.sum
- ibm/service/satellite/data_source_ibm_satellite_host_script.go
- ibm/service/satellite/data_source_ibm_satellite_host_script_test.go
- website/docs/d/satellite_attach_host_script.html.markdown
Closes https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3838
```
=== RUN   TestAccIBMSatelliteAttachHostScriptDataSourceBasic
--- PASS: TestAccIBMSatelliteAttachHostScriptDataSourceBasic (799.33s)
=== RUN   TestAccIBMSatelliteAttachHostScriptDataSourceBasicCoreos
--- PASS: …
```
> coreos host attach support

- ibm/service/vpc/resource_ibm_is_vpn_server.go
- website/docs/r/is_vpn_server.html.markdown
```
resource "ibm_is_vpn_server" "is_vpn_server" {
certificate_crn = "crn:v1:staging:public:secrets-manager:eu-gb:a/efe5afc483594adaa8325e2b4d1290df:27835509-694d-4742-8a77-c02cc7e067d0:secret:601250e1-e800-6e99-dfd2-2dbadd52f060"
client_authentication  {
method = "certificate"
client_ca_crn = …
```
> Documentation Fix

- ibm/service/vpc/resource_ibm_is_security_group.go
- ibm/service/vpc/resource_ibm_is_security_group_test.go
```
--- PASS: TestAccIBMISSecurityGroup_basic (113.34s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     116.254s
```
> fix(security_group): added wait logic to wait for target removal to avoid 409

- examples/ibm-iam-accessgroups/README.md
- examples/ibm-iam-accessgroups/main.tf
- examples/ibm-iam-accessgroups/variables.tf
- examples/ibm-iam-accessgroups/versions.tf
- go.sum
- ibm/provider/provider.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_account_settings.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_account_settings_test.go
- website/docs/r/iam_access_group_account_settings.html.markdown
This PR creates a new resource for access group account settings.
```
$ make testacc TESTARGS='-run=TestAccIBMIAMAccessGroupAccountSettingsBasic'
$ make testacc TESTARGS='-run=TestAccIBMIAMAccessGroupAccountSettingsUpdates'
```
...
```
resource "ibm_iam_access_group_account_settings" …
```
> New access group setting resource

- ibm/flex/structures.go
- ibm/service/database/data_source_ibm_database.go
- website/docs/d/database.html.markdown
`key_protect_key_id` is deprecated and has been replaced by `backup_encryption_key_crn`. Refactored code to add deprecated to `key_protect_key_id`. Updated docs as well.
Note that functionally no changes have been made.
```
--- PASS: …
```
> Deprecate key_protect_key_id

- website/docs/d/is_lb_listener.html.markdown
- website/docs/d/is_lb_listeners.html.markdown
- website/docs/r/is_lb_listener.html.markdown
> Lb secret manger support

- website/docs/d/database.html.markdown
Typo in the key_protect_key_id deprecation docs
N/A
> key_protect_key_id doc typo fix

- .secrets.baseline
- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_elasticsearch_test.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_database_redis_test.go
Closes #3964
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstance'
...
--- PASS: TestAccIBMDatabaseInstanceRabbitmqImport (417.42s)
--- PASS: TestAccIBMDatabaseInstanceRedisImport (578.39s)
--- PASS: TestAccIBMDatabaseInstance_Redis_Basic (648.49s)
--- PASS: TestAccIBMDatabaseInstancePostgresImport (1056.90s)
--- PASS: …
```
> fix(Cloud Databases): use V5 total math for group update request

- ibm/service/vpc/resource_ibm_is_vpc.go
- website/docs/r/is_vpc.html.markdown
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVPC_basic'
=== RUN   TestAccIBMISVPC_basic
--- PASS: TestAccIBMISVPC_basic (127.63s)
=== RUN   TestAccIBMISVPC_basic_apm
--- PASS: TestAccIBMISVPC_basic_apm (93.25s)
PASS
ok …
```
> removed deprecation message for default_network_acl

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
Closes https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3964
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstance'
--- PASS: TestAccIBMDatabaseInstanceElasticsearchImport (472.41s)
--- PASS: TestAccIBMDatabaseInstanceEtcdImport (726.60s)
--- PASS: TestAccIBMDatabaseInstanceMongodbBasic (1102.86s)
--- PASS: …
```
> fix(Cloud Databases): fix Members & CPU update checks

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- ibm/service/vpc/resource_ibm_is_instance_volume_attachment.go
- ibm/service/vpc/resource_ibm_is_instance_volume_attachment_test.go
- website/docs/d/is_instance_template.html.markdown
- website/docs/d/is_instance_templates.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
- website/docs/r/is_instance_volume_attachment.html.markdown
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstanceTemplate_WithVolumeAttachmentUserTag'
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_bootVolumeUserTags'
$ make testacc TEST=./ibm/service/vpc …
```
> User Tags in Instance, Inst Temp, Inst Vol Attmnt

- go.mod
- go.sum
- ibm/service/power/resource_ibm_pi_volume.go
- ibm/service/power/resource_ibm_pi_volume_test.go
- website/docs/r/pi_volume.html.markdown
```
--- PASS: TestAccIBMPIVolumebasic (130.20s)
PASS
=== RUN   TestAccIBMPIVolumePool
--- PASS: TestAccIBMPIVolumePool (94.04s)
PASS
=== RUN   TestAccIBMPIVolumeGRS
--- PASS: TestAccIBMPIVolumeGRS (188.75s)
PASS
```
> Add replication enabled attribute in pi volume resource

- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- website/docs/r/is_instance_template.html.markdown
- website/docs/r/is_instance_volume_attachment.html.markdown
- website/docs/r/is_volume.html.markdown
```
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstanceTemplate_basic'
=== RUN   TestAccIBMISInstanceTemplate_basic
--- PASS: TestAccIBMISInstanceTemplate_basic (154.13s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc	155.995s
make testacc …
```
> instance template vol attachment fix with doc

- website/docs/d/app_config_segment.html.markdown
- website/docs/d/app_config_segments.html.markdown
- website/docs/r/app_config_segment.html.markdown
```
...
```
The appconfig segments docs the resource and datasource is created outside the subcategory In external DOC
https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/app_config_segment
the segment should be subcategory of the …
> space is missing after the description for segment

- go.mod
- ibm/provider/provider.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interface_reserved_ip.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interface_reserved_ip_test.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interface_reserved_ips.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interface_reserved_ips_test.go
- website/docs/d/is_bare_metal_server_network_interface_reserved_ip.html.markdown
- website/docs/d/is_bare_metal_server_network_interface_reserved_ips.html.markdown
…
```
--- PASS: TestAccIBMISBareMetalServerNICReservedIPs_basic (24.93s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     26.748s
```
```
--- PASS: TestAccIBMISBareMetalServerNICReservedIP_basic (25.82s)
PASS …
```
> enhancement(bare_metal_server): added support for bare metal server nic ip datasource(s)

- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instance_network_interface.html.markdown
- website/docs/d/is_instance_network_interfaces.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_network_interface.html.markdown
> fix(doc): fixed documentation on deprecation of primary_ipv4_address on is_instance

- ibm/service/kms/data_source_ibm_kms_key.go
- ibm/service/kms/data_source_ibm_kms_key_policies.go
- ibm/service/kms/data_source_ibm_kms_key_policies_test.go
- ibm/service/kms/data_source_ibm_kms_key_rings.go
- ibm/service/kms/data_source_ibm_kms_key_rings_test.go
- ibm/service/kms/data_source_ibm_kms_keys.go
- ibm/service/kms/resource_ibm_kms_key.go
- ibm/service/kms/resource_ibm_kms_key_alias.go
- ibm/service/kms/resource_ibm_kms_key_alias_test.go
- ibm/service/kms/resource_ibm_kms_key_policies.go
- ibm/service/kms/resource_ibm_kms_key_policies_test.go
- ibm/service/kms/resource_ibm_kms_key_rings.go
- ibm/service/kms/resource_ibm_kms_key_rings_test.go
- ibm/service/kms/resource_ibm_kms_key_test.go
Code Refactoring and removal of small bugs. 
- Key Policies :
- Adding of `flex.ResourceControllerURL` in schema which is later being set in the read function.
- Fixing `TestAccIBMKmsDataSourceKeyPolicy_basicNew`
- Remove `resourceIBMKmsKeyRead(d, meta)` from update function when there is error in policy creation
- Key Rings :
- /ibm/service/kms/resource_ibm_kms_key_rings.go : line 92 :
> Might cause nil pointer dereference if `instanceData` is nil
```
instanceData, resp, err := rsConClient.GetResourceInstance(&resourceInstanceGet)
instanceCRN := instanceData.CRN
if err != nil || instanceData == nil {
return fmt.Errorf("[ERROR] Error retrieving resource instance: %s with resp code: %s", err, resp)
}
```
* Please vote on this pull request by adding a 👍 …
> Code refactoring

- website/docs/d/is_backup_policies.html.markdown
- website/docs/d/is_backup_policy.html.markdown
- website/docs/d/is_floating_ips.html.markdown
- website/docs/d/is_flow_log.html.markdown
- website/docs/d/is_flow_logs.html.markdown
- website/docs/d/is_ike_policies.html.markdown
- website/docs/d/is_ike_policy.html.markdown
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_ipsec_policies.html.markdown
- website/docs/d/is_ipsec_policy.html.markdown
- website/docs/d/is_lb.html.markdown
- website/docs/d/is_lbs.html.markdown
- website/docs/d/is_network_acl.html.markdown
- website/docs/d/is_network_acls.html.markdown
- website/docs/d/is_security_groups.html.markdown
- website/docs/d/is_ssh_keys.html.markdown
- website/docs/d/is_subnet_reserved_ip.html.markdown
- website/docs/d/is_subnet_reserved_ips.html.markdown
- website/docs/d/is_subnets.html.markdown
- website/docs/d/is_volumes.html.markdown
- website/docs/d/is_vpn_gateway.html.markdown
- website/docs/d/is_vpn_server.html.markdown
- website/docs/d/is_vpn_server_route.html.markdown
- website/docs/d/is_vpn_server_routes.html.markdown
- website/docs/d/is_vpn_servers.html.markdown
- website/docs/r/is_backup_policy.html.markdown
- website/docs/r/is_subnet_network_acl_attachment.html.markdown
- website/docs/r/is_subnet_reserved_ip.html.markdown
- website/docs/r/is_vpn_gateway.html.markdown
- website/docs/r/is_vpn_server.html.markdown
> Doc corrections for resource group to intimate id and subnet floating ip changes

- go.mod
- go.sum
- ibm/acctest/acctest.go
- ibm/provider/provider.go
- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_shared_processor_pool.go
- ibm/service/power/data_source_ibm_pi_shared_processor_pool_test.go
- ibm/service/power/data_source_ibm_pi_shared_processor_pools.go
- ibm/service/power/data_source_ibm_pi_shared_processor_pools_test.go
- ibm/service/power/data_source_ibm_pi_spp_placement_group.go
- ibm/service/power/data_source_ibm_pi_spp_placement_group_test.go
- ibm/service/power/data_source_ibm_pi_spp_placement_groups.go
- ibm/service/power/data_source_ibm_pi_spp_placement_groups_test.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance_test.go
- ibm/service/power/resource_ibm_pi_network.go
- ibm/service/power/resource_ibm_pi_shared_processor_pool.go
- ibm/service/power/resource_ibm_pi_spp_placement_group.go
- ibm/service/power/resource_ibm_pi_spp_placement_group_test.go
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instances.html.markdown
- website/docs/d/pi_shared_processor_pool.html.markdown
- website/docs/d/pi_shared_processor_pools.html.markdown
- website/docs/d/pi_spp_placement_group.html.markdown
- website/docs/d/pi_spp_placement_groups.html.markdown
- website/docs/r/pi_instance.html.markdown
- website/docs/r/pi_shared_processor_pool.html.markdown
- website/docs/r/pi_spp_placement_group.html.markdown
Add shared processor pool & SPP placement groups
resource and data ebjects along with the ability
to add instances to a SPP
```
=== RUN   TestAccIBMPISPPPlacementGroupBasic
--- PASS: TestAccIBMPISPPPlacementGroupBasic (2181.41s)
PASS
=== RUN   TestAccIBMPISharedProcessorPoolsDataSourceBasic
--- PASS: …
```
> Add shared processor pool & SPP placement groups

- ibm/service/vpc/resource_ibm_is_vpn_gateway.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_test.go
fix(ibm_is_vpn_gateway): reordered the setting of id in ibm_is_vpn_gateway resource to taint the resource properly
```
--- PASS: TestAccIBMISVPNGateway_taint (765.14s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     767.070s
```
```
--- PASS: TestAccIBMISVPNGateway_basic …
```
> fix(ibm_is_vpn_gateway): reordered the setting of id in ibm_is_vpn_gateway resource to taint the resource properly

- ibm/service/database/data_source_ibm_database_connection.go
- ibm/service/database/resource_ibm_database.go
Relates OR Closes [#4014](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4014)
- Update validation schema to latest validation methods
```
$make test
go test -timeout=30s -parallel=4 github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/database github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/directlink …
```
> Update schema validation to latest schema methods

- ibm/flex/flatten.go
- ibm/service/power/data_source_ibm_pi_storage_pool_capacity.go
- ibm/service/power/data_source_ibm_pi_storage_pools_capacity.go
- ibm/service/power/data_source_ibm_pi_storage_type_capacity.go
- ibm/service/power/data_source_ibm_pi_storage_types_capacity.go
- ibm/service/power/data_source_ibm_pi_system_pools.go
- website/docs/d/pi_system_pools.markdown
Add fix for storage capacity & system pool output
=== RUN   TestAccIBMPIStorageTypeCapacityDataSourceBasic
--- PASS: TestAccIBMPIStorageTypeCapacityDataSourceBasic (20.74s)
PASS
=== RUN   TestAccIBMPISystemPoolsDataSourceBasic
--- PASS: TestAccIBMPISystemPoolsDataSourceBasic (11.97s)
PASS
```
$ make …
```
> Add fix for storage capacity & system pool output

- go.mod
- go.sum
- ibm/conns/config.go
- updates the go platform sdk version to include a new bug fix for atracker endpoints
- Allows `IBMCLOUD_ATRACKER_API_ENDPOINT` to override missing urls even for missing service regions in atracker
```
```Vans-MacBook-Pro:terraform-provider-ibm vbui$ make fmt && make testacc TEST=./ibm/service/atracker …
> fixes the endpoint; updates go sdk

- ibm/service/vpc/resource_ibm_is_vpn_gateway_connection_test.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connections.go
- website/docs/r/is_vpn_gateway_connection.html.markdown
```
--- PASS: TestAccIBMISVPNGatewayConnection_ike_ipsec_null_patch (544.89s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     546.422s
```
>  fix(vpn_gateway_connection): adding support to null patch ike_policy and ipsec_policy on vpn_gateway_connection

- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float_test.go
```
=== RUN   TestAccIBMISBareMetalServerNetworkInterfaceAllowFloat_rip_basic
--- PASS: TestAccIBMISBareMetalServerNetworkInterfaceAllowFloat_rip_basic (57.33s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     59.239s
```
```
=== RUN …
```
> fix(bare_metal_server_network_interface_allow_float) : reordered the wait logic in bare metal nics

- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float_test.go
- website/docs/r/is_bare_metal_server_network_interface_allow_float.markdown
- website/docs/r/is_bare_metal_server_network_interface_floating_ip.markdown
> enhancement(bare_metal_server_network_interface_allow_float) : added new floating_bare_metal_server attribute

- examples/ibm-is-ng/main.tf
- ibm/service/vpc/data_source_ibm_is_image.go
- ibm/service/vpc/data_source_ibm_is_image_test.go
- ibm/service/vpc/data_source_ibm_is_images.go
- ibm/service/vpc/data_source_ibm_is_images_test.go
- ibm/service/vpc/data_source_ibm_is_instance.go
- ibm/service/vpc/data_source_ibm_is_instances.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_network_interface.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
- website/docs/d/is_image.html.markdown
- website/docs/d/is_images.html.markdown
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/r/is_instance.html.markdown
```
=== RUN   TestAccIBMISImageDataSource_catalog
--- PASS: TestAccIBMISImageDataSource_catalog (69.42s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     71.190s
```
```
--- PASS: TestAccIBMISInstance_catalog (208.08s)
PASS
ok …
```
> feature(is_instance) : added support for catalog images for enterprises

- ibm/service/iamaccessgroup/resource_ibm_iam_access_group.go
```
$ make testacc TESTARGS='-run=TestAccIBMIAMAccessGroup_Basic'
```
```
make testacc TESTARGS='-run=TestAccIBMIAMAccessGroup_Import'
```
> fix(iam-access-groups): added retry logic for access groups read

- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interface.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_network_interfaces.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float_test.go
```
=== RUN   TestAccIBMISBareMetalServerNetworkInterfaceAllowFloat_rip_basic
--- PASS: TestAccIBMISBareMetalServerNetworkInterfaceAllowFloat_rip_basic (59.70s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     62.540s
```
```
=== RUN …
```
> fix(bm-nic): added check for 0.0.0.0 reserved ip on nic availability

- ibm/service/satellite/data_source_ibm_satellite_host_script.go
Custom code is overwriting part of the attach script in some locations, causing the attach script to fail.
This update provides a change to insert the custom code rather than overwriting a line in the attach script. In addition, it changes else/if loop to case for easier code readability and maintenance.
```
make testacc …
```
> Fix attach script loop for satellite host attach

- ibm/service/kms/resource_ibm_kms_key.go
Description: This fix would allow users to provide endpoint url without "/api/v2/keys" without breaking backward compatibility.
Signed-off-by: Siddharth Mishra <siddharth.mishra2@ibm.com>
```
...
```
> Fix endpoint URL

- ibm/service/vpc/resource_ibm_is_network_acl_rule.go
- ibm/service/vpc/resource_ibm_is_network_acl_rule_test.go
- website/docs/r/is_network_acl_rule.html.markdown
```
$ make testacc TESTARGS='-run=TestNetworkACLRule_basicBeforeRule'
=== RUN   TestNetworkACLRule_basicBeforeRule
--- PASS: TestNetworkACLRule_basicBeforeRule (106.00s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     107.521s
...
```
> acl before rule patch

- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_appconfig.go
- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_artifactory.go
- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_artifactory_test.go
- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_keyprotect.go
- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_secretsmanager.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_appconfig.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_artifactory.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_artifactory_test.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_keyprotect.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_secretsmanager.go
- website/docs/d/cd_toolchain_tool_appconfig.html.markdown
- website/docs/d/cd_toolchain_tool_artifactory.html.markdown
- website/docs/d/cd_toolchain_tool_keyprotect.html.markdown
- website/docs/d/cd_toolchain_tool_secretsmanager.html.markdown
- website/docs/r/cd_toolchain_tool_appconfig.html.markdown
- website/docs/r/cd_toolchain_tool_artifactory.html.markdown
- website/docs/r/cd_toolchain_tool_keyprotect.html.markdown
- website/docs/r/cd_toolchain_tool_secretsmanager.html.markdown
```
make testacc TEST=./ibm/service/cdtoolchain TESTARGS='-run=TestAccIBMCdToolchainToolArtifactory*'
TF_ACC=1 go test ./ibm/service/cdtoolchain -v -run=TestAccIBMCdToolchainToolArtifactory* -timeout 700m
=== RUN …
```
> Rename Artifactory param & description updates

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_database_redis_test.go
Users cannot edit their database configuration on database creation. This PR allows users to do so.
```
$ make testacc TEST=./ibm/service/database TESTARGS='-run=TestAccIBMDatabaseInstancePostgresBasic'
--- PASS: TestAccIBMDatabaseInstancePostgresBasic
PASS
ok …
```
> feat(Cloud Databases): Allow users to edit configuration on database creation

- ibm/service/database/resource_ibm_database.go
We currently do not wait for the scaling task to complete. This causes bad UX and does not allow the user to find out if their task was successful or if an error has occurred. This error was the result of a bad status code.
```
...
```
> bug(Cloud Databases): Wait for scaling task to complete

- examples/ibm-cd-tekton-pipeline/README.md
- examples/ibm-cd-tekton-pipeline/main.tf
- examples/ibm-cd-tekton-pipeline/variables.tf
Small update to clean up the ibm-cd-tekton-pipeline example from the examples folder
```
TF_ACC=1 go test ./ibm/service/cdtektonpipeline -v …
```
> chore(tekton): clean up ibm-cd-tekton-pipeline example

- ibm/flex/structures.go
- ibm/service/vpc/data_source_ibm_is_volume.go
- ibm/service/vpc/data_source_ibm_is_volumes.go
- ibm/service/vpc/resource_ibm_is_volume.go
- website/docs/d/is_volume.html.markdown
- website/docs/d/is_volumes.html.markdown
- website/docs/r/is_volume.html.markdown
Please fine the test results :
```
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVolume_basic'
```
```
resource "ibm_is_volume" "storage" {
name        = "volume-access-tags-testing"
profile     = "10iops-tier"
zone        = "us-south-1"
access_tags = ["tfp:ussouth", "tfp:eude"]
}
data …
```
> Access Tags for Volumes

- ibm/service/power/resource_ibm_pi_volume_test.go
- ibm/service/vpc/resource_ibm_is_lb_pool.go
- ibm/service/vpc/resource_ibm_is_lb_pool_test.go
- website/docs/r/is_lb_pool.html.markdown
Our team has internally reviewed the PR and please find the PR : https://github.com/ibm-vpc/terraform-provider-ibm/pull/186 for the results of the testing..
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISLBPool_portnullable'
```
> LoadBalancerPool HealthMonitor Port Nullable

- ibm/flex/structures.go
- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_snapshots.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
- website/docs/d/is_snapshot.html.markdown
- website/docs/d/is_snapshots.html.markdown
- website/docs/r/is_snapshot.html.markdown
Please find the testing results in PR https://github.com/ibm-vpc/terraform-provider-ibm/pull/43
```
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSnapshot_basic'
```
```
resource "ibm_is_snapshot" "testacc_snapshot" {
name          = "sunitha-snapshot"
source_volume = "r006-159e42ba-cff8-4448-965b-e618c12e9a4c"
access_tags   = …
```
> added tagging and access tags support for is_snapshot

- ibm/flex/structures.go
- ibm/service/satellite/resource_ibm_satellite_cluster_test.go
- ibm/service/satellite/resource_ibm_satellite_cluster_worker_pool.go
- ibm/service/satellite/resource_ibm_satellite_cluster_worker_pool_test.go
- website/docs/r/satellite_cluster.html.markdown
- website/docs/r/satellite_cluster_worker_pool.html.markdown
Four main changes:
- change worker pool host label to force new. It is not possible to update host labels on an existing worker pool after creation,
- fix length of array that creates a blank entry on read. example:
```  # ibm_satellite_cluster_worker_pool.create_wp will be updated in-place
~ resource "ibm_satellite_cluster_worker_pool" "create_wp" {
~ host_labels        = [
- "",
]
id                 = "cdqf4juw0bl3s7phl9vg/cdqf4juw0bl3s7phl9vg-bddb143"
name               = "test"
```
- update docs to clarify correct formatting of host labels
- update test due to errors w/duplicate ibm provider. since now using the default provider, switching regions to us-south
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-is …
> Clarify worker_pool host_label usage and fix blank entry in array

- go.mod
- go.sum
- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain.go
- website/docs/d/cd_toolchain.html.markdown
- website/docs/r/cd_toolchain.html.markdown
```
make testacc TEST=./ibm/service/cdtoolchain
TF_ACC=1 go test ./ibm/service/cdtoolchain -v  -timeout 700m
=== RUN   TestAccIBMCdToolchainDataSourceBasic
--- PASS: TestAccIBMCdToolchainDataSourceBasic (48.55s)
=== RUN …
```
> Remove tags from toolchain

- ibm/service/power/data_source_ibm_pi_volume_group_storage_details.go
- ibm/service/power/resource_ibm_pi_volume_group.go
- ibm/service/power/resource_ibm_pi_volume_group_action.go
- ibm/service/power/resource_ibm_pi_volume_group_action_test.go
- ibm/service/power/resource_ibm_pi_volume_group_test.go
- website/docs/r/pi_volume_group_action.html.markdown
…_source_ibm_pi_volume_group_storage_details resources
```
=== RUN   TestAccIBMPIVolumeGroupStorageDetailsDataSourceBasic
--- PASS: TestAccIBMPIVolumeGroupStorageDetailsDataSourceBasic (169.73s)
PASS
=== RUN   TestAccIBMPIVolumeGroupActionbasic
--- PASS: …
```
> GRS Fix: fixed pi_volume_group_action, pi_volume_group & data pi_volume_group_storage_details resources

- ibm/flex/structures.go
- ibm/service/database/data_source_ibm_database.go
- ibm/service/database/resource_ibm_database.go
Related Issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4220
This PR:
- Removes the bluemix-go sdk dependency for supporting the deprecated whitelist attribute
- Uses `PUT /v5/ibm/deployments/{id}/allowlists/ip_addresses` endpoint for setting allowlists
```
make testacc …
```
> feat(Cloud Databases): remove bluemix-go dependency for allowlist

- ibm/service/globaltagging/resource_ibm_resource_tag.go
Removed usage of direct tags API for retrieving tags using resource CRN
```
...
```
> Removed usage of direct tags API for retrieving tags using resource CRN

- ibm/service/catalogmanagement/resource_ibm_cm_catalog.go
This PR is fixing a regression in the catalog resource.  The `resource_group_id` field should be optional, this was changed when code was regenerated recently and we need to fix it as soon as possible because it is breaking teams. Thanks.
issue here: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4216
> fix: make resource_group_id optional for catalogs

- ibm/service/vpc/data_source_ibm_is_dedicated_host.go
- ibm/service/vpc/data_source_ibm_is_dedicated_hosts.go
- ibm/service/vpc/data_source_ibm_is_image.go
- ibm/service/vpc/data_source_ibm_is_images.go
- ibm/service/vpc/data_source_ibm_is_instance.go
- ibm/service/vpc/data_source_ibm_is_instances.go
- ibm/service/vpc/data_source_ibm_is_ssh_key.go
- ibm/service/vpc/data_source_ibm_is_ssh_keys.go
- ibm/service/vpc/resource_ibm_is_dedicated_host.go
- ibm/service/vpc/resource_ibm_is_image.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_ssh_key.go
- website/docs/d/is_dedicated_host.html.markdown
- website/docs/d/is_dedicated_hosts.html.markdown
- website/docs/d/is_image.html.markdown
- website/docs/d/is_images.html.markdown
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/d/is_ssh_key.html.markdown
- website/docs/d/is_ssh_keys.html.markdown
- website/docs/r/is_dedicated_host.html.markdown
- website/docs/r/is_image.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_ssh_key.html.markdown
Please find the test results here : https://github.com/ibm-vpc/terraform-provider-ibm/pull/175
```
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSSHKey_basic'
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_basic'
make testacc TEST=./ibm/service/vpc …
```
> AccessTags for DedicatedHost,Image,Instance,SSHKey

- ibm/service/satellite/data_source_ibm_satellite_host_script.go
The recent bom change for RHEL8 means we don't need to set the python version anymore. Comment it out because it's causing us issues (attach script uses 3.9, forcing it down to 3.8 is no good)
> Dont set python in rhel8 satellite script

- examples/ibm-iam_identity/main.tf
- examples/ibm-iam_identity/versions.tf
- go.sum
- ibm/service/iamidentity/data_source_ibm_iam_account_settings.go
- ibm/service/iamidentity/data_source_ibm_iam_account_settings_test.go
- ibm/service/iamidentity/resource_ibm_iam_account_settings.go
- ibm/service/iamidentity/resource_ibm_iam_account_settings_test.go
- website/docs/d/iam_account_settings.html.markdown
- website/docs/r/iam_account_settings.html.markdown
> IAM Identity: account settings

- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
> wait for virtual endpoint gateway to be available after creation

- ibm/service/vpc/data_source_ibm_is_bare_metal_servers.go
- ibm/service/vpc/data_source_ibm_is_dedicated_host.go
- ibm/service/vpc/data_source_ibm_is_dedicated_host_group.go
- ibm/service/vpc/data_source_ibm_is_dedicated_host_groups.go
- ibm/service/vpc/data_source_ibm_is_dedicated_hosts.go
- ibm/service/vpc/data_source_ibm_is_floating_ips.go
- ibm/service/vpc/data_source_ibm_is_flow_logs.go
- ibm/service/vpc/data_source_ibm_is_network_acl_rules.go
- ibm/service/vpc/data_source_ibm_is_public_gateways.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateways.go
- ibm/service/vpc/data_source_ibm_is_vpc_routing_tables.go
- ibm/service/vpc/data_source_ibm_is_vpcs.go
- ibm/service/vpc/data_source_ibm_is_vpn_gateway_connections.go
- ibm/service/vpc/data_source_ibm_is_vpn_gateways.go
- website/docs/d/is_bare_metal_servers.markdown
- website/docs/d/is_dedicated_host_groups.html.markdown
- website/docs/d/is_dedicated_hosts.html.markdown
- website/docs/d/is_floating_ips.html.markdown
- website/docs/d/is_flow_logs.html.markdown
- website/docs/d/is_network_acl_rules.html.markdown
- website/docs/d/is_public_gateways.html.markdown
- website/docs/d/is_virtual_endpoint_gateways.html.markdown
- website/docs/d/is_vpc_routing_tables.html.markdown
- website/docs/d/is_vpcs.html.markdown
- website/docs/d/is_vpn_gateways.html.markdown
> added filters in vpc service data sources

- ibm/service/kubernetes/resource_ibm_container_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
Closes #4214
```
% make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainerVpcClusterEnvvar'
...
=== RUN   TestAccIBMContainerVpcClusterEnvvar
--- PASS: TestAccIBMContainerVpcClusterEnvvar (1493.94s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes      1495.348s
% make …
```
> add critical as a pending cluster state

- ibm/flex/structures.go
Removed direct call to tagging API to retrieve single resource tags using resource CRN
```
...
```
> Removed direct call to tagging API to retrieve single resource tags

- ibm/flex/structures.go
Fixes issue with older worker pools that do not have os label applied and were hitting out of bounds error (because there were no host labels on the worker pool): `panic: runtime error: makeslice: len out of range`
Since we cannot know the number of labels, change is to start with a slice of size 0 and increase slice length as number of labels increases. …
> change from fixed to to append new line to slice

- ibm/service/vpc/resource_ibm_is_instance.go
- website/docs/r/is_instance.html.markdown
> added auto delete for vsi boot volume

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/data_source_ibm_is_volume.go
- ibm/service/vpc/data_source_ibm_is_volumes.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_volume.go
- ibm/service/vpc/resource_ibm_is_volume_test.go
- website/docs/d/is_volume.html.markdown
- website/docs/d/is_volumes.html.markdown
- website/docs/r/is_volume.html.markdown
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVolume_snapshot'
```
ENV : 
https://us-south-genesis-dal-dev83.iaasdev.cloud.ibm.com/v1
Template:
resource "ibm_is_volume" "storage" {
name    = "sunitha-volume"
profile = "general-purpose"
zone    = "us-south-1"
source_snapshot= …
> Volume From Snapshot Development And Migration PR

- ibm/service/power/resource_ibm_pi_instance.go
> Fix ibm pi instance update wait for status

- ibm/acctest/acctest.go
- ibm/service/vpc/resource_ibm_is_networkacls.go
- ibm/service/vpc/resource_ibm_is_networkacls_test.go
- website/docs/r/is_network_acl.html.markdown
```
=== RUN   TestNetworkACLResourceGroupUpdate
--- PASS: TestNetworkACLResourceGroupUpdate (220.13s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     225.381s
```
> fix(networkacl) : made name optional to allow create_before_destroy

- ibm/service/appid/resource_ibm_appid_cloud_directory_user.go
Test results
```
harinireddy@Harinis-MacBook-Pro appid % terraform12-1 apply
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
+ resource "ibm_appid_cloud_directory_user" "user" {
+ active         = true
+ create_profile = true
+ display_name   = (known after apply)
+ id             = (known after apply)
+ meta           = (known after apply)
+ password       = (sensitive value)
+ status         = "PENDING"
+ subject        = (known after apply)
+ tenant_id      = "fb3829f0-dc61-446e-b683-f89c22229fbb"
+ user_id        = (known after apply)
+ user_name      = "HariniReddy"
+ email {
+ primary = true
+ value   = "hkantare@in.ibm.com"
}
}
Plan: 1 to add, 0 to change, 0 to …
```
> Fix ibm_appid_cloud_directory_user missing userName

- ibm/service/database/data_source_ibm_database.go
- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_redis_test.go
Refactor of  `auto_scaling` to use `cloud-databases-go-sdk` instead of the `bluemix-go` sdk.
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstanceRedisImport'
PASS: TestAccIBMDatabaseInstanceRedisImport
...
```
> refactor(Cloud Databases) autoscaling uses cloud-databases-go-sdk 

- website/docs/r/cm_object.html.markdown
This is a small documentation fix for the ibm_cm_object resource.  The description for the parent_id argument was incorrect.
> fix: documentation fix for ibm_cm_object resource

- go.mod
- go.sum
Bump to latest `continuous-delivery-go-sdk` to pick up a fix in the Go SDK that affects the terraform provider for cd-tekton-pipeline
```
--- PASS: TestAccIBMCdTektonPipelineDefinitionDataSourceBasic (80.59s)
=== RUN   TestAccIBMCdTektonPipelinePropertyDataSourceBasic
--- PASS: TestAccIBMCdTektonPipelinePropertyDataSourceBasic (61.55s)
=== RUN   TestAccIBMCdTektonPipelinePropertyDataSourceAllArgs
--- PASS: TestAccIBMCdTektonPipelinePropertyDataSourceAllArgs …
```
> chore(tekton): bump Tekton Go SDK version

- ibm/service/dnsservices/resource_ibm_private_dns_custom_resolver_location.go
> [Deprecate][ibm_dns_custom_resolver_location] : Retain schema and remove code

- ibm/service/vpc/resource_ibm_is_vpc_route.go
- website/docs/r/is_vpc_route.html.markdown
> Remove deprecated resource notification for VPC route resource

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_instance.go
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/data_source_ibm_is_instances.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- website/docs/d/is_instance.html.markdown
- website/docs/d/is_instance_template.html.markdown
- website/docs/d/is_instance_templates.html.markdown
- website/docs/d/is_instances.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
```
$ make testacc TESTARGS='-run=TestAccIBMISInstance_metadata_service'
=== RUN   TestAccIBMISInstance_metadata_service
--- PASS: TestAccIBMISInstance_metadata_service (321.05s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     322.309s
...
```
```
$ make testacc TESTARGS='-run=TestAccIBMISInstanceTemplate_metadata_service'
=== RUN   TestAccIBMISInstanceTemplate_metadata_service
--- PASS: TestAccIBMISInstanceTemplate_metadata_service (97.90s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     99.207s
```
> Feature: metadata post ga changes in instance and templates

- ibm/conns/config.go
Currently, in order to use the IBM provider to manager classic infrastructure resources you must either configure the provider manually with `iam_token` and `iam_refresh_token` variables, or you must provide api-specific credentials via the `iaas_classic_username` and `iaas_classic_api_key` variables. However, it should be reasonable when using `ibmcloud_api_key` for the provider to passthrough the access and refresh tokens received as part of the IBM Cloud session.
It seemed like the original code had been in-place to do that, but it was incorrectly guarded by a non-nil check of
`sess.SoftLayerSession.IAMToken` rather than a check to confirm that explicit iaas credentials hadn't been provided already.
* Please vote on this pull request by adding a 👍 …
> fix: pass ibm cloud session token along to iaas

- examples/ibm-is-ng/main.tf
- ibm/service/vpc/data_source_ibm_is_backup_policy_plan.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plan_test.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plans.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plans_test.go
- ibm/service/vpc/resource_ibm_is_backup_policy_plan.go
- ibm/service/vpc/resource_ibm_is_backup_policy_plan_test.go
- website/docs/d/is_backup_policy_plan.html.markdown
- website/docs/d/is_backup_policy_plans.html.markdown
- website/docs/r/is_backup_policy_plan.html.markdown
```
=== RUN   TestAccIBMIsBackupPolicyPlanClonesBasic
--- PASS: TestAccIBMIsBackupPolicyPlanClonesBasic (279.41s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     282.187s
```
```
=== RUN …
```
> enhancement(clone): support for backup policy plan clone

- ibm/service/catalogmanagement/data_source_ibm_cm_offering.go
- ibm/service/catalogmanagement/data_source_ibm_cm_version.go
- ibm/service/catalogmanagement/resource_ibm_cm_offering.go
- ibm/service/catalogmanagement/resource_ibm_cm_version.go
- website/docs/d/cm_version.html.markdown
- website/docs/r/cm_validation.html.markdown
- website/docs/r/cm_version.html.markdown
Some products will be onboarded with a modules section that was not previously supported by the terraform provider, adding the parameters to the version resource metadata fixes the issue.
There were more metadata fields added by the API than expected, these have all been added to the resources and data sources to support cm onboarding.
Also added `x_auth_token` to the docs for the cm version resource, and created the `cm_validation` docs.
> fix: add fields to version metadata for onboarding fix

- ibm/acctest/acctest.go
- ibm/service/cos/resource_ibm_cos_bucket_object.go
- ibm/service/cos/resource_ibm_cos_bucket_object_test.go
- ibm/service/cos/resource_ibm_cos_replication_configuration.go
--- PASS: TestAccIBMCOSBucketObject_Versioning_Enabled (28.20s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	29.700s
--- PASS: TestAccIBMCOSBucketObject_Versioning_Enabled_Sequential_Upload (31.11s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	32.475s
--- PASS: TestAccIBMCOSBucketObject_Overwriting (28.31s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	29.701s
> Object versioning and bucket replication fix

- ibm/service/kubernetes/resource_ibm_container_worker_pool.go
```
% make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainerWorkerPoolBasic'
TF_ACC=1 go test ./ibm/service/kubernetes -v -run=TestAccIBMContainerWorkerPoolBasic -timeout 700m
...
=== RUN …
```
> call WorkerPoolUpdate at the end of create

- ibm/service/catalogmanagement/resource_ibm_cm_object.go
- ibm/service/catalogmanagement/resource_ibm_cm_object_test.go
- website/docs/r/cm_validation.html.markdown
small doc fix for validation resource, I missed the parent parameter for the nested list.
Fix also includes a fix for tags not being idempotent when generated from api.  My last PR for this was closed somehow before being merged.
> docs: small doc fix for validation resource

- ibm/service/power/resource_ibm_pi_instance.go
```
--- PASS: TestAccIBMPIInstanceBasic (407.27s)
PASS
```
> Fix to allow memory / processor updates to server instances in either shutdown or active state

- ibm/service/power/resource_ibm_pi_instance_action.go
- ibm/service/power/resource_ibm_pi_instance_action_test.go
Relates OR Closes #4400
```
=== RUN   TestAccIBMPIInstanceAction
--- PASS: TestAccIBMPIInstanceAction (278.82s)
PASS
=== RUN   TestAccIBMPIInstanceActionHardReboot
--- PASS: TestAccIBMPIInstanceActionHardReboot (109.64s)
PASS
...
```
> No need to take instance action if already in state

- website/docs/r/pi_network.html.markdown
> Update pi_network documentation to provide information about default DNS configurations

- ibm/service/power/resource_ibm_pi_instance_action.go
```
=== RUN   TestAccIBMPIInstanceAction
--- PASS: TestAccIBMPIInstanceAction (334.29s)
PASS
...
```
> Use resource timeout instead of hardcoded value in instance action

- website/docs/r/cos_bucket.html.markdown
This is a fix for the following GitHub issues:
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4069
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3615
> Documentation corrections for COS

- examples/ibm-secrets-manager/README.md
- examples/ibm-secrets-manager/main.tf
- examples/ibm-secrets-manager/variables.tf
- go.mod
- go.sum
- website/docs/d/sm_secret_group.html.markdown
- Updated Secrets manager SDK version number
- Some documentation fixes
```
...
```
> Secrets Manager fixes

- ibm/service/vpc/resource_ibm_is_instance_group.go
- ibm/service/vpc/resource_ibm_is_instance_group_test.go
```
$ make testacc TESTARGS='-run=TestAccIBMISInstanceGroup_basic'
=== RUN   TestAccIBMISInstanceGroup_basic
--- PASS: TestAccIBMISInstanceGroup_basic (169.23s)
=== RUN   TestAccIBMISInstanceGroup_basic_loadbalancer
--- PASS: TestAccIBMISInstanceGroup_basic_loadbalancer (644.16s)
PASS
ok …
```
> set instance_count in instance group read

- ibm/service/catalogmanagement/data_source_ibm_cm_offering.go
- ibm/service/catalogmanagement/data_source_ibm_cm_version.go
- ibm/service/catalogmanagement/resource_ibm_cm_object.go
- ibm/service/catalogmanagement/resource_ibm_cm_object_test.go
- ibm/service/catalogmanagement/resource_ibm_cm_offering.go
- ibm/service/catalogmanagement/resource_ibm_cm_validation.go
- ibm/service/catalogmanagement/resource_ibm_cm_version.go
- ibm/service/catalogmanagement/resource_ibm_cm_version_test.go
- website/docs/r/cm_offering.html.markdown
- website/docs/r/cm_validation.html.markdown
- website/docs/r/cm_version.html.markdown
- Deployable Architecture support: Can now add deployable architecture information to a version such as diagrams, features, dependencies, etc.
- Deprecation: Can now deprecate offerings and versions via a Terraform argument
- Usage: Can now specify usage text on a version
- Configuration values: Can now specify and manage deployment/configuration variables for a version
- Publishing: Can now publish/unpublish offerings
- Terraform version override: Can now specify a terraform override version per offering version
* Please do not leave "+1" or …
> feat: Catalog Management enhancements

- ibm/service/kubernetes/resource_ibm_container_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster_test.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool_test.go
- ibm/service/kubernetes/resource_ibm_container_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_worker_pool_test.go
```
% make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainerVpcClusterEnvvar'
TF_ACC=1 go test ./ibm/service/kubernetes -v -run=TestAccIBMContainerVpcClusterEnvvar -timeout 700m
...
=== RUN …
```
> refactor how we set and update the taints on worker pools

- ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_servers.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
- website/docs/d/is_bare_metal_server.markdown
- website/docs/d/is_bare_metal_servers.markdown
- website/docs/r/is_bare_metal_server.markdown
```
=== RUN   TestAccIBMISBareMetalServer_SecureBoot_tpm
--- PASS: TestAccIBMISBareMetalServer_SecureBoot_tpm (1467.54s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     1469.590s
```
> enhancement(tpm): support for bare metal secure boot and tpm

- ibm/service/transitgateway/resource_ibm_tg_gateway_connection_action.go
This PR fixes a bug in ibm_tg_connection action. ibm_tg_connection_action was failing when the ibm_tg_connection involved was not created yet but worked for existing connections.
The bug was in a customdiff implementation that validates/checks for changes in the connection_action resource block. An action on a transit gateway can only be performed once. Once submitted, the cross account connection is either approved or rejected. This presented problems if the resource block changed, because the terraform state would delete but the backend would throw errors, and the terraform state would be out of sync. This background explains why a customdiff was needed.
A bug in connection action's customdiff was in how we are checking for action changes. Fixes were made so that:
- Creating a new …
> fix: check state for ibm_tg_connection_action correctly

- ibm/service/secretsmanager/resource_ibm_sm_secret_group.go
> Fix regex used for validating a secrer group name

- .secrets.baseline
- ibm/service/cloudant/resource_ibm_cloudant.go
- website/docs/d/cloudant.html.markdown
- website/docs/r/cloudant.html.markdown
Due to a throttling of capacity change operation on the back-end side it can take a number of hours to complete. This makes an instance creation operation for the instances requested with a large capacity to fail on a timeout even though the instance itself get provisioned.
This PR changes what parameters block we are using to report the capacity of the instance, allowing for the capacity change to catch up asynchronously.
This PR addresses an issue raised in https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4356
* Please do not leave …
> refactor(cloudant): handle capacity change duration more gracefully

- ibm/service/database/data_source_ibm_database_connection.go
- ibm/service/database/data_source_ibm_database_connection_test.go
- website/docs/d/database_connection.html.markdown
`certificate_root` is a part of the getconnection API in the IBM Cloud Databases API v5 as seen here: https://cloud.ibm.com/apidocs/cloud-databases-api/cloud-databases-api-v4#getconnection
We need to incorporate this within our Terraform Provider so that users could use this parameter.
```
$ make …
```
> Added certificate_root for data_source_ibm_database_connection

- ibm/flex/diff_supress_funcs.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger.go
Suppress change detection for Tekton Trigger Events that occurs due to the order of items in the array being inconsistent.
Making use of this workaround: https://github.com/hashicorp/terraform-plugin-sdk/issues/477#issuecomment-1238807249
```
$ make testacc TEST=./ibm/service/cdtektonpipeline …
```
> fix(tekton): sorting issue for events

- ibm/service/vpc/data_source_ibm_is_lb_listeners.go
- ibm/service/vpc/resource_ibm_is_lb_listener.go
- website/docs/d/is_lb_listener.html.markdown
- website/docs/d/is_lb_listeners.html.markdown
- website/docs/r/is_lb_listener.html.markdown
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISLBListener_connTimeout'
```
Scenarios 1:
```
resource "ibm_is_lb_listener" "listener1" {
lb                    = ibm_is_lb.application_01.id
port                  = 9087
protocol              = "http"
accept_proxy_protocol = true
/* …
```
> Idle Connection Timeout FIx

- website/docs/r/database.html.markdown
As part of elasticsearch enterprise GA we need to add a sample in our docs so users know how to provision an elasticsearch enterprise instance.
I've gone ahead and added a working sample for users.
> Add sample Elasticsearch enterprise instance for Docs

- ibm/service/vpc/resource_ibm_is_public_gateway.go
- ibm/service/vpc/resource_ibm_is_public_gateway_test.go
Relates OR Closes #1627
```
=== RUN   TestAccIBMISPublicGateway_resource_group_change
--- PASS: TestAccIBMISPublicGateway_resource_group_change (264.73s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     267.472s
```
> fix(public_gateway): added retry logic for public gateway deletion

- ibm/acctest/acctest.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profiles.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profiles_test.go
> don't throw exception for list TP datsource when there is no TP in the account

- ibm/acctest/acctest.go
- ibm/service/vpc/resource_ibm_is_image.go
- ibm/service/vpc/resource_ibm_is_image_test.go
```
=== RUN   TestAccIBMISImage_error
--- PASS: TestAccIBMISImage_error (11.21s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     13.286s
```
> fix(image) : added length check for volume attachments

- ibm/service/vpc/data_source_ibm_is_subnet_reserved_ip.go
- ibm/service/vpc/data_source_ibm_is_subnet_reserved_ip_test.go
- ibm/service/vpc/data_source_ibm_is_subnet_reserved_ips.go
- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip.go
- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip_test.go
- website/docs/d/is_subnet_reserved_ip.html.markdown
- website/docs/d/is_subnet_reserved_ips.html.markdown
- website/docs/r/is_subnet_reserved_ip.html.markdown
```
=== RUN   TestAccIBMISSubnetReservedIP_targetCrn
--- PASS: TestAccIBMISSubnetReservedIP_targetCrn (130.95s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     133.121s
```
```
=== RUN   TestAccIBMISSubnetReservedIPResource_targetCrn
--- PASS: …
```
> enhancement(reserved_ips): added support for target crn

- ibm/service/vpc/data_source_ibm_is_lb_profiles.go
- ibm/service/vpc/data_source_ibm_is_lb_profiles_test.go
- website/docs/d/is_lb_profiles.html.markdown
```
=== RUN   TestAccIBMISLBProfilesDatasource_filter
--- PASS: TestAccIBMISLBProfilesDatasource_filter (15.25s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     17.474s
```
> enhancement(lb_profiles): added name filter to get only one profile

- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateway_test.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateways.go
- ibm/service/vpc/data_source_ibm_is_virtual_endpoint_gateways_test.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway_test.go
- website/docs/d/is_virtual_endpoint_gateway.html.markdown
- website/docs/d/is_virtual_endpoint_gateways.html.markdown
- website/docs/r/is_virtual_endpoint_gateway.html.markdown
Relates OR Closes #4466
```
=== RUN   TestAccIBMISVirtualEndpointGateway_ServiceEndpoints
--- PASS: TestAccIBMISVirtualEndpointGateway_ServiceEndpoints (110.31s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     111.882s
```
```
=== RUN   TestAccIBMISVirtualEndpointGatewayDataSource_service_endpoints …
```
> enhancement(endpoint_gateway): added support for service endpoints

- .secrets.baseline
- examples/ibm-code-engine/README.md
- examples/ibm-code-engine/main.tf
- examples/ibm-code-engine/outputs.tf
- examples/ibm-code-engine/variables.tf
- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/codeengine/resource_ibm_code_engine_app.go
- ibm/service/codeengine/resource_ibm_code_engine_secret.go
- ibm/service/codeengine/resource_ibm_code_engine_secret_test.go
- website/docs/r/code_engine_secret.html.markdown
Relates OR Closes #4431
```
$ make testacc                                                 
TF_ACC=1 go test -v $(go list ./... |grep -v 'vendor') 
?       github.com/IBM-Cloud/terraform-provider-ibm     [no test files]
?       github.com/IBM-Cloud/terraform-provider-ibm/ibm/acctest [no test files]
? …
```
> Add Code engine secret resource

- ibm/service/vpc/data_source_ibm_is_vpc_routing_table_route_test.go
- ibm/service/vpc/resource_ibm_is_vpc_routing_table_route.go
```
=== RUN   TestAccIBMISVPCRoutingTableRoutesDataSource_basic
--- PASS: TestAccIBMISVPCRoutingTableRoutesDataSource_basic (113.38s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     115.492s
```
```
=== RUN   TestAccIBMIBMIsVPCRoutingTableRouteDataSourceBasic
--- PASS: …
```
> fix(vpc-rt-route): fixed changes shown on creator attribute

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
Relates OR Closes #4479
```
...
```
> fix(bm): patch of security groups on bare metal server nics

- ibm/service/vpc/resource_ibm_is_security_group_rule.go
- ibm/service/vpc/resource_ibm_is_security_group_rule_test.go
- website/docs/r/is_security_group_rule.html.markdown
Relates OR Closes #4051 
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSecurityGroupRule_basic'
```
Error : Initially if code is not specified then the value would be `0` as shown below, instead it should be `any`
There is no diff when compared with master branch binary
After changes the output:
``` …
```
> Security Group Rule ICMP Type, Code -> Any

- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
Manage lifecycle of `ibm_container_vpc_worker_pool` resource when cluster is deleted.
To avoid below mentioned issues.
```
2023/04/24 08:49:38 Terraform refresh | Error: [ERROR] Error getting container vpc workerpool: Request failed with status code: 404, ServerErrorResponse: {"incidentID":"3d0113c7-40b6-4ce0-9d8c-59384ed4acff","code":"G0004","description":"The specified cluster could not be found. If applicable, make sure that you target the correct account and resource group.","type":"General","recoveryCLI":"To list the clusters you have access to, run 'ibmcloud ks cluster ls'. To list the resource groups that you have access to, run 'ibmcloud resource groups'. To target the resource group, run 'ibmcloud target -g \u003cresource_group\u003e'."}
2023/04/24 08:49:38 Terraform refresh | …
```
> fix: lifecycle of ibm_container_vpc_worker_pool when cluster is deleted

- ibm/service/kms/resource_ibm_kms_key.go
in response to this ticket https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4536
endpoint_type is something that decides how the resource is created/updated, it is not an actual property of the key.  it should not create a new resource if the user decides to use a different endpoint(public/private) on a later date
Output …
> disable creating new resource when endpoint type changes

- go.mod
- go.sum
- ibm/service/kubernetes/data_source_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/data_source_ibm_container_vpc_worker_pool_test.go
- ibm/service/kubernetes/data_source_ibm_container_worker_pool.go
- ibm/service/kubernetes/data_source_ibm_container_worker_pool_test.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool_test.go
- ibm/service/kubernetes/resource_ibm_container_worker_pool.go
- website/docs/d/container_vpc_cluster_worker_pool.html.markdown
- website/docs/d/container_worker_pool.html.markdown
- website/docs/r/container_vpc_worker_pool.html.markdown
- website/docs/r/container_worker_pool.html.markdown
```
% make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainerVpcClusterWorkerPoolEnvvar'
TF_ACC=1 go test ./ibm/service/kubernetes -v -run=TestAccIBMContainerVpcClusterWorkerPoolEnvvar -timeout 700m
...
--- PASS: …
```
> suppress resize for autoscaled workerpools

- website/docs/r/is_vpc_routing_table_route.html.markdown
Relates OR Closes #4559 
```
...
```
> Example rectification

- .secrets.baseline
- examples/ibm-code-engine/README.md
- examples/ibm-code-engine/main.tf
- examples/ibm-code-engine/outputs.tf
- examples/ibm-code-engine/variables.tf
- ibm/provider/provider.go
- ibm/service/codeengine/data_source_ibm_code_engine_app.go
- ibm/service/codeengine/data_source_ibm_code_engine_app_test.go
- ibm/service/codeengine/data_source_ibm_code_engine_build.go
- ibm/service/codeengine/data_source_ibm_code_engine_build_test.go
- ibm/service/codeengine/data_source_ibm_code_engine_config_map.go
- ibm/service/codeengine/data_source_ibm_code_engine_config_map_test.go
- ibm/service/codeengine/data_source_ibm_code_engine_job.go
- ibm/service/codeengine/data_source_ibm_code_engine_job_test.go
- ibm/service/codeengine/data_source_ibm_code_engine_secret.go
- ibm/service/codeengine/data_source_ibm_code_engine_secret_test.go
- ibm/service/codeengine/resource_ibm_code_engine_app.go
- website/docs/d/code_engine_app.html.markdown
- website/docs/d/code_engine_build.html.markdown
- website/docs/d/code_engine_config_map.html.markdown
- website/docs/d/code_engine_job.html.markdown
- website/docs/d/code_engine_project.html.markdown
- website/docs/d/code_engine_secret.html.markdown
This PR adds new data sources for IBM Cloud Code Engine for already existing resources:
- `apps`
- `builds`
- `config_maps`
- `jobs`
- `secrets`
```
$ make testacc                                                           
TF_ACC=1 go test -v $(go list ./... |grep -v 'vendor') 
? …
```
> Code engine add data sources

- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_allow_float_test.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_floating_ip_test.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_interface_test.go
```
=== RUN   TestAccIBMISBareMetalServerNetworkInterface_pci_nic_delete
--- PASS: TestAccIBMISBareMetalServerNetworkInterface_pci_nic_delete (1823.55s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     1826.228s
```
```
=== RUN …
```
> fix(bm) : pci nic deletion change

- ibm/service/database/data_source_ibm_database.go
- ibm/service/database/resource_ibm_database.go
- website/docs/d/database.html.markdown
- website/docs/r/database.html.markdown
Relates to: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4339
Deprecates `auto_scaling` `cpu`  from the `ibm_database` resource and data source, as this is not supported by Cloud Databases. This attribute will be removed in the future.
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstance_Redis_Basic'
... …
```
> feat(Cloud Databases): Deprecate auto_scaling cpu attribute

- examples/ibm-cd-tekton-pipeline/versions.tf
- go.mod
- go.sum
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_property.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_property_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_property.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_property_test.go
- website/docs/d/cd_tekton_pipeline.html.markdown
- website/docs/d/cd_tekton_pipeline_property.html.markdown
- website/docs/d/cd_tekton_pipeline_trigger.html.markdown
- website/docs/d/cd_tekton_pipeline_trigger_property.html.markdown
- website/docs/r/cd_tekton_pipeline.html.markdown
- website/docs/r/cd_tekton_pipeline_property.html.markdown
- website/docs/r/cd_tekton_pipeline_trigger.html.markdown
- website/docs/r/cd_tekton_pipeline_trigger_property.html.markdown
Add force new to `property` `type`field in Tekton 
```
--- …
```
> Tekton: Improved property type handling

- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain.go
- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_test.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_test.go
- website/docs/d/cd_toolchain.html.markdown
- website/docs/r/cd_toolchain.html.markdown
```
make testacc TEST=./ibm/service/cdtoolchain TESTARGS="-run=TestAccIBMCdToolchainDataSource"
TF_ACC=1 go test ./ibm/service/cdtoolchain -v -run=TestAccIBMCdToolchainDataSource -timeout 60m
=== RUN   TestAccIBMCdToolchainDataSourceBasic
--- …
```
> Tagging for CD Toolchains

- examples/openshift-data-foundation/addon/README.md
- examples/openshift-data-foundation/addon/createaddon.sh
- examples/openshift-data-foundation/addon/createcrd.sh
- examples/openshift-data-foundation/addon/deleteaddon.sh
- examples/openshift-data-foundation/addon/deletecrd.sh
- examples/openshift-data-foundation/addon/ibm_odf_addon/main.tf
- examples/openshift-data-foundation/addon/main.tf
- examples/openshift-data-foundation/addon/ocscluster/main.tf
- examples/openshift-data-foundation/addon/schematics.tfvars
- examples/openshift-data-foundation/addon/updateodf.sh
- examples/openshift-data-foundation/vpc-worker-replace/README.md
- examples/openshift-data-foundation/vpc-worker-replace/main.tf
- examples/openshift-data-foundation/vpc-worker-replace/provider.tf
- examples/openshift-data-foundation/vpc-worker-replace/variables.tf
- examples/openshift-data-foundation/vpc-worker-replace/versions.tf
Examples Terraform Templates for ODF add-on and worker replace
```
...
```
> Documentation for Openshift-Data-Foundation Add-on & VPC Worker Replace

- examples/ibm-cos-bucket/main.tf
- examples/ibm-key-protect/README.md
- examples/ibm-key-protect/main.tf
- examples/ibm-kms/README.md
- examples/ibm-kms/main.tf
- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket_test.go
- ibm/service/kms/resource_ibm_kms_key_test.go
- website/docs/d/cos_bucket.html.markdown
- website/docs/d/kms_key.html.markdown
- website/docs/d/kms_keys.html.markdown
- website/docs/d/kp_key.html.markdown
- website/docs/r/cos_bucket.html.markdown
- website/docs/r/kms_key.html.markdown
- website/docs/r/kms_key_alias.html.markdown
- website/docs/r/kms_key_with_policy_overrides.html.markdown
- website/docs/r/kp_key.html.markdown
Test results :
--- PASS: TestAccIBMCOSKPKmsParamValid (84.76s)
PASS
ok [github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](https://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos) 86.384s
--- PASS: TestAccIBMCOSKPKmsParamWithInvalidCRN (49.70s)
PASS
ok [github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](https://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos) 51.390s
--- PASS: TestAccIBMCOSHPCSKmsParamWithInvalidCRN (44.35s)
PASS
ok [github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](https://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos) 114.080s
--- PASS: TestAccIBMCOSHPCSKmsParamWithInvalidCRN (44.35s)
PASS
ok [github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](https://github.com/IBM-Cloud/terraform-provider-ib …
> Adding changes for replacement of key_protect parameter and adding the fix for 3394

- ibm/service/atracker/resource_ibm_atracker_route_test.go
- website/docs/r/atracker_route.html.markdown
- website/docs/r/atracker_settings.html.markdown
- website/docs/r/atracker_target.html.markdown
```
$ make fmt && make testacc TEST=./ibm/service/atracker TESTARGS='-run=TestAccIBMAtracker.*'
gofmt -w $(find .  -path ./.direnv -prune -false -o -name '*.go' |grep -v vendor)
TF_ACC=1 go test ./ibm/service/atracker -v -run=TestAccIBMAtracker.* -timeout 700m
=== RUN …
```
> Adding more examples and test cases for Atracker

- website/docs/r/iam_access_group_policy.html.markdown
Closes #4540 
It looks like an unclosed code block was accidentally added to the docs for the `ibm_iam_service_policy` resource in PR #4455. This closes that code block to fix the formatting.
> Fix unclosed code block in r/iam_access_group_policy docs

- ibm/service/power/data_source_ibm_pi_dhcp.go
- ibm/service/power/data_source_ibm_pi_dhcps.go
- ibm/service/power/resource_ibm_pi_dhcp.go
This will prevent plugin crashes on nil dhcp network id.
Relates OR Closes #4683
```
=== RUN   TestAccIBMPIDhcpServersDataSourceBasic
--- PASS: TestAccIBMPIDhcpServersDataSourceBasic (34.38s)
=== RUN   TestAccIBMPIDhcpDataSourceBasic
--- PASS: TestAccIBMPIDhcpDataSourceBasic (17.36s)
PASS
...
```
> handle nil network id in dhcp detail

- examples/ibm-enterprise-management/README.md
- examples/ibm-enterprise-management/main.tf
- examples/ibm-enterprise-management/variables.tf
- examples/test-enterprise/variables.tf
- go.mod
- go.sum
- ibm/service/enterprise/resource_ibm_enterprise_account.go
- ibm/service/enterprise/resource_ibm_enterprise_account_test.go
- website/docs/r/enterprise_account.html.markdown
Added trait field in enterprise child account schema
make testacc TEST=./ibm/service/enterprise TESTARGS='-run=TestAccIbmEnterpriseAccountBasic'
...
make testacc TEST=./ibm/service/enterprise TESTARGS='-run=TestAccIbmEnterpriseImportAccountBasic'
> added trait field in enterprise child account

- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger.go
- website/docs/d/cd_tekton_pipeline.html.markdown
- website/docs/d/cd_tekton_pipeline_trigger.html.markdown
- website/docs/r/cd_tekton_pipeline.html.markdown
- website/docs/r/cd_tekton_pipeline_trigger.html.markdown
Simplify the CRON regex values used for validation in tekton timed trigger resources. The new regex allows all valid CRON characters, and the backend API will handle the more detailed validation requirements of the CRON field
```
$ make testacc TEST=./ibm/service/cdtektonpipeline …
```
> Tekton simplify CRON validation

- ibm/flex/structures.go
- ibm/service/database/data_source_ibm_database.go
- website/docs/d/database.html.markdown
We deprecated the `key_protect_key_id` in this PR: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3939
We will no long support the use of `key_protect_key_id` and we will remove it.
For more details please see the following blog post: https://www.ibm.com/cloud/blog/announcements/new-features-and-rearchitecturing-of-ibm-cloud-databasess-terraform-provider about deprecated attributes
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and …
> Remove Key Protect ID and Transition to v5 API

- ibm/acctest/acctest.go
- ibm/service/vpc/resource_ibm_is_lb_pool_member.go
- ibm/service/vpc/resource_ibm_is_lb_pool_member_test.go
Relates OR Closes #4630
```
=== RUN   TestAccIBMISLBPoolMember_basic_network_target_address
--- PASS: TestAccIBMISLBPoolMember_basic_network_target_address (1278.09s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     1280.283s
```
> fix(4630): added computed to lb pool member target id and address

- ibm/service/kubernetes/resource_ibm_container_cluster.go
compiled a new version, created a classic cluster
```
2023-07-20T09:07:14.949+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/ibm-cloud/ibm/1.55.0/darwin_amd64/terraform-provider-ibm_v1.55.0 pid=99995
2023-07-20T09:07:14.949+0200 [DEBUG] provider: plugin …
```
> always read and set datacentervalue

- website/docs/d/metrics_router_targets.html.markdown
- website/docs/r/metrics_router_route.html.markdown
- website/docs/r/metrics_router_settings.html.markdown
- website/docs/r/metrics_router_target.html.markdown
As part of the PR, changing the subcategory from **IBM Cloud Metrics Routing API Version 3** to **IBM Cloud Metrics Routing**
Right now its like below -
> Doc Fix: Updated service name - IBM Cloud Metrics Routing

- website/docs/d/metrics_router_routes.html.markdown
As part of the PR, changing the subcategory from IBM Cloud Metrics Routing API Version 3 to IBM Cloud Metrics Routing of ibm_metrics_router_targets
> Doc fix: Updated subcategory of ibm_metrics_router_targets

- ibm/service/vpc/resource_ibm_is_backup_policy_plan.go
- ibm/service/vpc/resource_ibm_is_backup_policy_plan_test.go
- website/docs/r/is_backup_policy_plan.html.markdown
Relates OR Closes #4734
```
=== RUN   TestAccIBMIsBackupPolicyPlanCRC
--- PASS: TestAccIBMIsBackupPolicyPlanCRC (212.31s)
=== RUN   TestAccIBMIsBackupPolicyPlanCRCNullDeleteOverCount
--- PASS: TestAccIBMIsBackupPolicyPlanCRCNullDeleteOverCount …
```
> fixed(backup_policy_plan): delete_over_count null issue fixed

- website/docs/r/pi_image.html.markdown
- website/docs/r/pi_instance.html.markdown
Relates OR Closes #4679
```
...
```
> Update ibm_pi_instance Doc

- ibm/service/schematics/resource_ibm_schematics_workspace.go
This allows for creation of workspaces with terraform version 1.4. 
Long term I'd argue that this regexp should validate that the version is structurally correct, but allow for any integer and then fail due to underlying API call, otherwise every new minor release of TF support in the service requires a change here
> allow ibm_schematics_workspace template_type 1.4

- website/docs/r/sm_private_certificate.html.markdown
> Fix documentation of Secrets Manager private certificate resource

- go.mod
- go.sum
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_property_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger_property_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_property.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_property_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_property.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_property_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_test.go
- website/docs/d/cd_tekton_pipeline.html.markdown
- website/docs/d/cd_tekton_pipeline_definition.html.markdown
- website/docs/d/cd_tekton_pipeline_property.html.markdown
- website/docs/d/cd_tekton_pipeline_trigger.html.markdown
- website/docs/d/cd_tekton_pipeline_trigger_property.html.markdown
- website/docs/r/cd_tekton_pipeline.html.markdown
- website/docs/r/cd_tekton_pipeline_definition.html.markdown
- website/docs/r/cd_tekton_pipeline_property.html.markdown
- website/docs/r/cd_tekton_pipeline_trigger.html.markdown
- website/docs/r/cd_tekton_pipeline_trigger_property.html.markdown
- Add support for favorite triggers in Tekton pipeline
- Also includes some documentation updates
```
TF_ACC=1 go test ./ibm/service/cdtektonpipeline -v …
```
> fix(tekton): Trigger updates

- ibm/service/transitgateway/resource_ibm_tg_gateway_route_report.go
```
There was issue TGW Route report resource block , because that  , it was failing during the re-apply of the same config 
Error: doesn't support update
2023/08/24 12:18:53 Terraform apply | 
2023/08/24 12:18:53 Terraform apply |   with ibm_tg_route_report.rclone_transit_gateway_route_report,
2023/08/24 12:18:53 Terraform apply |   on main.tf line 69, in resource "ibm_tg_route_report" "rclone_transit_gateway_route_report":
2023/08/24 12:18:53 Terraform apply |   69: resource "ibm_tg_route_report" "rclone_transit_gateway_route_report" {
2023/08/24 12:18:53 Terraform apply | 
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and …
> feat: Fixed TGW Route report update issue  dependency: None

- ibm/service/kubernetes/data_source_ibm_container_cluster_versions.go
- ibm/service/kubernetes/data_source_ibm_container_cluster_versions_test.go
- website/docs/d/container_cluster_versions.html.markdown
Adding new 2 attribute references: `default_kube_version` and `default_openshift_version` to `ibm_container_cluster_versions` data lookup
These attributes have a value of default kube and ocp versions in IBM Cloud Kubernetes Service clusters.
Relates  [#4720](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4720)
``` …
```
> feat: add default cluster versions to cluster versions data source

- go.mod
- go.sum
- ibm/service/power/resource_ibm_pi_cloud_connection.go
> Retry cloud connection create/update when vpc is unavailable

- examples/ibm-cos-bucket-object/README.md
- examples/ibm-cos-bucket-object/main.tf
- examples/ibm-cos-bucket/README.md
- examples/ibm-cos-bucket/main.tf
- ibm/flex/structures.go
- ibm/provider/provider.go
- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/data_source_ibm_cos_bucket_object.go
- ibm/service/cos/resource_ibm_cos_bucket_object.go
- ibm/service/cos/resource_ibm_cos_bucket_website_configuration.go
- ibm/service/cos/resource_ibm_cos_bucket_website_configuration_test.go
- website/docs/d/cos_bucket.html.markdown
- website/docs/d/cos_bucket_object.html.markdown
- website/docs/r/cos_bucket_object.html.markdown
- website/docs/r/cos_bucket_website_configuration.html.markdown
Acceptance testing :
--- PASS: TestAccIBMCosBucket_Website_Configuration_Bucket_Basic (106.76s)
PASS
ok [github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](https://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos) 109.208s
--- PASS: TestAccIBMCosBucket_Website_Configuration_Bucket_Basic (85.53s)
PASS
ok [github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](https://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos) 87.162s
--- PASS: TestAccIBMCosBucket_Website_Configuration_Bucket_Index_Document_Only (85.16s)
PASS
ok [github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](https://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos) 86.551s
--- PASS: TestAccIBMCosBucket_Website_Configuration_Bucket_With_Routing_Rules (93.82s)
PASS
ok …
> Adding support for COS Static Web hosting

- .secrets.baseline
- examples/ibm-satellite/README.md
- examples/ibm-satellite/assignment.tf
- examples/ibm-satellite/configuration.tf
- examples/ibm-satellite/modules/assignment/README.md
- examples/ibm-satellite/modules/assignment/main.tf
- examples/ibm-satellite/modules/assignment/provider.tf
- examples/ibm-satellite/modules/assignment/variables.tf
- examples/ibm-satellite/modules/configuration/README.md
- examples/ibm-satellite/modules/configuration/main.tf
- examples/ibm-satellite/modules/configuration/provider.tf
- examples/ibm-satellite/modules/configuration/variables.tf
- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/satellite/data_source_ibm_satellite_storage_assignment.go
- ibm/service/satellite/data_source_ibm_satellite_storage_assignment_test.go
- ibm/service/satellite/data_source_ibm_satellite_storage_configuration.go
- ibm/service/satellite/data_source_ibm_satellite_storage_configuration_test.go
- ibm/service/satellite/resource_ibm_satellite_storage_assignment.go
- ibm/service/satellite/resource_ibm_satellite_storage_assignment_test.go
- ibm/service/satellite/resource_ibm_satellite_storage_configuration.go
- ibm/service/satellite/resource_ibm_satellite_storage_configuration_test.go
- website/docs/d/satellite_storage_assignment.html.markdown
- website/docs/d/satellite_storage_configuration.html.markdown
- website/docs/r/satellite_storage_assignment.html.markdown
- website/docs/r/satellite_storage_configuration.html.markdown
Now allow users to create and manage the lifecycle of storage configurations and assignments through terraform.
Data sources added
- ibm_satellite_storage_configuration
- ibm_satellite_storage_assignment
Resources added
- ibm_satellite_storage_configuration
- ibm_satellite_storage_assignment
Documentation, Unit Tests and the Website changes are added as per
**With this you can create storage configurations that can be consistently assigned, updated, and managed across the clusters, service clusters, and cluster groups in your satellite location.**
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this …
> Terraform Support for Satellite Storage Configurations & Assignments

- go.mod
- go.sum
- ibm/service/kubernetes/data_source_ibm_container_cluster_config.go
- ibm/service/kubernetes/data_source_ibm_container_cluster_config_test.go
- website/docs/d/container_cluster_config.html.markdown
Adding new parameter `endpoint_type` for cluster_config datasource (IBM Cloud Kubernetes Service). This parameter can set what kind of URL is generated into the kubeconfig. The default is public - if the cluster has public service endpoint enabled option.
Possible options: 
- empty
- private (works for classic and VPC infrastructure)
- vpe (only for VPC)
- link (only for Satellite)
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not …
> add support for endpoint parameter in cluster_config

- ibm/service/iampolicy/resource_ibm_iam_authorization_policy.go
- ibm/service/iampolicy/resource_ibm_iam_authorization_policy_test.go
- website/docs/d/iam_authorization_policies.html.markdown
- website/docs/r/iam_authorization_policy.html.markdown
Relates OR Closes [IAM/AM-issues/issues/1777](https://github.ibm.com/IAM/AM-issues/issues/1777)
Tested against test service. Waiting on COS to update service definition in staging environment to test against global catalog available service.
Update: Tested against COS, and tests passed. Results below.
```bash
$ make testacc …
```
> fix(IAM Policy Management): allow sourceServiceName to be optional for authorization policy

- ibm/service/vpc/data_source_ibm_is_vpc_test.go
- website/docs/r/is_vpc.html.markdown
```
=== RUN   TestAccIBMISVPCDatasource_dns
--- PASS: TestAccIBMISVPCDatasource_dns (83.86s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     87.431s
```
> documents update and test case update for ibm_is_vpc

- examples/ibm-atracker/README.md
- examples/ibm-atracker/main.tf
- examples/ibm-atracker/variables.tf
- examples/ibm-atracker/versions.tf
- examples/ibm-metrics-router/README.md
- examples/ibm-metrics-router/variables.tf
- go.mod
- go.sum
- ibm/service/metricsrouter/data_source_ibm_metrics_router_targets.go
- ibm/service/metricsrouter/resource_ibm_metrics_router_target.go
- website/docs/d/atracker_routes.html.markdown
- website/docs/d/atracker_targets.html.markdown
- website/docs/d/metrics_router_targets.html.markdown
> Metrics router and atracker:  Updated platform-services-go-sdk to fetch Madrid endpoint

- ibm/service/cos/data_source_ibm_cos_bucket.go
--- PASS: TestAccIBMCOSBucketDataSource_basic (52.65s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	54.360s
> Change for the issue 4838 - ibm_cos_bucket data lookup is throwing NoSuchWebsiteConfiguration

- .secrets.baseline
- go.mod
- go.sum
- ibm/service/secretsmanager/data_source_ibm_sm_arbitrary_secret.go
- ibm/service/secretsmanager/data_source_ibm_sm_arbitrary_secret_test.go
- ibm/service/secretsmanager/data_source_ibm_sm_iam_credentials_secret.go
- ibm/service/secretsmanager/data_source_ibm_sm_imported_certificate.go
- ibm/service/secretsmanager/data_source_ibm_sm_imported_certificate_test.go
- ibm/service/secretsmanager/data_source_ibm_sm_kv_secret.go
- ibm/service/secretsmanager/data_source_ibm_sm_kv_secret_test.go
- ibm/service/secretsmanager/data_source_ibm_sm_private_certificate.go
- ibm/service/secretsmanager/data_source_ibm_sm_private_certificate_test.go
- ibm/service/secretsmanager/data_source_ibm_sm_public_certificate.go
- ibm/service/secretsmanager/data_source_ibm_sm_public_certificate_test.go
- ibm/service/secretsmanager/data_source_ibm_sm_username_password_secret.go
- ibm/service/secretsmanager/data_source_ibm_sm_username_password_secret_test.go
- ibm/service/secretsmanager/utils.go
- website/docs/d/sm_arbitrary_secret.html.markdown
- website/docs/d/sm_iam_credentials_secret.html.markdown
- website/docs/d/sm_imported_certificate.html.markdown
- website/docs/d/sm_kv_secret.html.markdown
- website/docs/d/sm_private_certificate.html.markdown
- website/docs/d/sm_public_certificate.html.markdown
- website/docs/d/sm_username_password_secret.html.markdown
> Get secret by name

- ibm/service/secretsmanager/resource_ibm_sm_public_certificate.go
Fix handling of bundle_certs in Secrets Manager public cert
Closes #4803
```
...
```
> Fix handling of bundle_certs in Secrets Manager public cert

- .secrets.baseline
- website/docs/r/sm_imported_certificate.html.markdown
Fix typo in the doc 
---
---
n/a (minor fix in doc only)
> Fix typo in example for sm_imported_certificate resource

- website/docs/r/kms_key.html.markdown
> Update key description docs

- ibm/service/vpc/resource_ibm_is_backup_policy.go
- ibm/service/vpc/resource_ibm_is_backup_policy_test.go
- website/docs/r/is_backup_policy.html.markdown
```
...
```
```
resource "ibm_is_backup_policy" "is_backup_policy" {
match_user_tags = ["tag-0"]
name            = "sunitha-terraform-baas"
}
resource "ibm_is_backup_policy" "is_backup_policy1" {
match_user_tags = ["tag-0"] 
match_resource_type = "volume"
name …
```
> Deprecated match_resource_types and Intoduced match_resource_type

- go.mod
- go.sum
- website/docs/r/cd_tekton_pipeline_trigger.html.markdown
###
Update continuous-delivery Go SDK version
```
=== RUN …
```
> fix(tekton): update CD Go SDK version

- ibm/service/vpc/resource_ibm_is_lb.go
- ibm/service/vpc/resource_ibm_is_lb_test.go
- website/docs/d/is_flow_log.html.markdown
- website/docs/r/is_lb.html.markdown
```
=== RUN   TestAccIBMISLB_basic_network_security_group
--- PASS: TestAccIBMISLB_basic_network_security_group (1104.20s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     1107.007s
```
> added support for security groups for network load balancers

- go.mod
- go.sum
- ibm/service/cdtoolchain/data_source_ibm_cd_toolchain_tool_securitycompliance_test.go
- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_securitycompliance_test.go
Bump up version of the Continuous Delivery Go SDK, which includes support for the new Madrid (eu-es) region
```
TF_ACC=1 go test ./ibm/service/cdtektonpipeline -v -run=TestAccIBMCdTekton* …
```
> feat(tekton): bump ContinuousDelivery Go SDK version

- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket_website_configuration_test.go
--- PASS: TestAccIBMCOSBucketDataSource_basic (38.56s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos	40.046s
--- PASS: TestAccIBMCOSBucketObjectDataSource_basic (45.83s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	47.900s
--- PASS: TestAccIBMCOSBucketObject_basic (65.82s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	67.577s
--- PASS: TestAccIBMCOSBucketObject_VersioningEnabled (31.05s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	32.666s
--- PASS: …
> Fix for COS issue 4844 

- README.md
Add IC_REGION because it is easy to miss out on when setting up the test environment.
Add a tip on how to locate the required environment variables that need to be set for each specific test
For example, if I am testing some code engine test cases on resources created in us-east resource group, my tests would fail with 403 forbidden because those IDs were not present in the default us-south region. The acctest.go precheck function did not mention IC_REGION for that particular test case and it took me some manual over the REST API to find out that the test code was hitting a different region than intended.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment …
> Add IC_REGION to readme and tip on env vars

- ibm/service/vpc/data_source_ibm_is_subnet.go
- ibm/service/vpc/data_source_ibm_is_subnets.go
- website/docs/d/is_subnet.html.markdown
- website/docs/d/is_subnets.html.markdown
Relates OR Closes #4872 
```
resource "ibm_is_vpc" "testacc_vpc" {
name = "sunitha-vpc"
}
resource "ibm_is_subnet" "testacc_subnet" {
name = "sunitha-subnet"
vpc = "${ibm_is_vpc.testacc_vpc.id}"
zone = "us-south-1"
total_ipv4_address_count = 16
}
data "ibm_is_subnet" "ds_subnet" {
identifier = …
```
> VPC ID Filter is added when Subnet Name is specified

- website/docs/r/container_ingress_secret_opaque.html.markdown
Fix required argument "fields" in Kubernetes Service `container_ingress_secret_opaque` resource documentation.
This is to prevent the following error:
```terraform
❯ terraform plan
╷
│ Error: Unsupported argument
│
│   on main.tf line 18, in resource "ibm_container_ingress_secret_opaque" "secret":
│   18:   fields = {
│
│ An argument named "fields" is not expected here. Did you mean to define a block of type
│ "fields"?
╵
```
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra …
> Fix wrong syntax in doc for Ingress Secret Opaque for required argument "fields"

- ibm/service/codeengine/resource_ibm_code_engine_domain_mapping_test.go
> fix the build

- website/docs/d/schematics_agent.html.markdown
- website/docs/d/schematics_agents.html.markdown
- website/docs/r/schematics_agent.html.markdown
ps : https://github.ibm.com/blueprint/product/issues/9535
> schematics agent doc fixes

- ibm/service/cis/resource_ibm_cis_domain_settings.go
- ibm/service/cis/resource_ibm_cis_tls_settings.go
Issue - https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4937
Test Cases - 
```
arpit-mac@Arpits-MacBook-Pro-6 terraform-provider-ibm % make testacc TEST=./ibm/service/cis TESTARGS='-run=TestAccIBMCisSettings_Basic'   
TF_ACC=1 go test ./ibm/service/cis -v -run=TestAccIBMCisSettings_Basic -timeout 700m
--- PASS: TestAccIBMCisSettings_Basic (675.20s)
PASS
ok 	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis	676.840s
```
```
arpit-mac@Arpits-MacBook-Pro-6 terraform-provider-ibm % make testacc TEST=./ibm/service/cis TESTARGS='-run=TestAccIBMCisTLSSettings_Basic'
TF_ACC=1 go test ./ibm/service/cis -v -run=TestAccIBMCisTLSSettings_Basic -timeout 700m
--- …
```
> fix: CIS - remove deafult value for min_tls_version

- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
Relates OR Closes #4938 
```
=== RUN   TestAccIBMISInstance_enc_catalog
--- PASS: TestAccIBMISInstance_enc_catalog (273.97s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     279.878s
```
> fix(is_instance): validation on encryption with catalog images fixed

- CHANGELOG.md
- version/version.go
> Release 1.60.0-beta1

- ibm/service/schematics/data_source_ibm_schematics_workspace.go
- website/docs/d/schematics_workspace.html.markdown
Fixed catalog service extensions and values metadata params of workspace ds
PS: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4907
> Fixed catalog service extensions and values metadata params of ws ds

- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance_test.go
- website/docs/r/pi_instance.html.markdown
This enhancement updates the pi_user_data field to accept a string input and encode it as it is passed down to the SDK instead of requiring the parameter to be pre-encoded.
I wrote an additional acceptance test and updated the documentation.
```
=== RUN   TestAccIBMPIInstanceUserData
--- PASS: TestAccIBMPIInstanceUserData (469.03s)
PASS
```
Fixes #4902
> Update pi_user_data to accept string input

- go.mod
- go.sum
- ibm/service/satellite/data_source_ibm_satellite_host_script.go
- ibm/service/satellite/data_source_ibm_satellite_host_script_test.go
- website/docs/d/satellite_attach_host_script.html.markdown
Added changes to see if the user supplied a host link endpoint variable. If they did, this will allow the host attach script resource to use the reduced firewall configuration with the IBM provider.
Updated the container service package to pick up the new SDK changes that allow this to happen
Added test cases to test functionality of user supplied sat link agent endpoint
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help …
> new host link endpoint commits

- ibm/service/vpc/resource_ibm_is_vpc.go
- ibm/service/vpc/resource_ibm_is_vpc_test.go
- website/docs/r/is_vpc.html.markdown
```
=== RUN   TestAccIBMISVPC_dns_delegated_first
--- PASS: TestAccIBMISVPC_dns_delegated_first (295.69s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     298.237s
```
> added enhancement to one step delegate resolver in is_vpc

- examples/ibm-mqcloud/README.md
- examples/ibm-mqcloud/main.tf
- examples/ibm-mqcloud/variables.tf
- go.mod
- go.sum
- ibm/acctest/acctest.go
- ibm/conns/config.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_application.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_application_test.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_keystore_certificate.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_keystore_certificate_test.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_queue_manager.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_queue_manager_test.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_truststore_certificate.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_truststore_certificate_test.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_user.go
- ibm/service/mqcloud/data_source_ibm_mqcloud_user_test.go
- ibm/service/mqcloud/resource_ibm_mqcloud_application_test.go
- ibm/service/mqcloud/resource_ibm_mqcloud_keystore_certificate.go
- ibm/service/mqcloud/resource_ibm_mqcloud_keystore_certificate_test.go
- ibm/service/mqcloud/resource_ibm_mqcloud_queue_manager.go
- ibm/service/mqcloud/resource_ibm_mqcloud_queue_manager_test.go
- ibm/service/mqcloud/resource_ibm_mqcloud_truststore_certificate.go
- ibm/service/mqcloud/resource_ibm_mqcloud_truststore_certificate_test.go
- ibm/service/mqcloud/resource_ibm_mqcloud_user_test.go
- ibm/service/mqcloud/utils.go
- website/docs/r/mqcloud_keystore_certificate.html.markdown
- website/docs/r/mqcloud_queue_manager.html.markdown
- website/docs/r/mqcloud_truststore_certificate.html.markdown
(cherry picked from commit e7253421db30943d3582ce07d9504a2117f30ce1)
Changes
- add fix for the multipart support from the new openapi-sdkgen version
- related readme and doc changes from the new openapi-sdkgen version
- related the test file changes from the new openapi-sdkgen version
```
$  make testacc …
```
> fix: add multipart support for mqcloud service

- ibm/service/vpc/resource_ibm_is_vpn_server.go
- ibm/service/vpc/resource_ibm_is_vpn_server_route.go
```
resource "ibm_is_vpn_server" "is_vpn_server" {
certificate_crn = "crn:v1:bluemix:public:secrets-manager:us-south:a/7f75c7b025e54bc5635f754b2f888665:0d7981e7-b381-424e-a3c7-0af38f471d87:secret:cdcee4c3-4558-ed20-2bc0-3df0a93af2aa"
client_authentication {
method        = "certificate"
client_ca_crn = "crn:v1:bluemix:public:secrets-manager:us-south:a/7f75c7b025e54bc5635f754b2f888665:0d7981e7-b381-424e-a3c7-0af38f471d87:secret:c329a9cd-08dc-bcae-b42b-bc8b0927562a"
}
client_ip_pool         = "192.167.0.0/16"
enable_split_tunneling = true
name                   = "sunitha-vpn-server"
port                   = 443
protocol               = "tcp"
subnets                = ["0727-5adc42b5-fcba-4f12-9c36-e15d305c919e"]
security_groups        = ["r006-a4281eaa-023b-41bb-8060-247eb0bb5e68"]
} …
```
> Delete wait logic changes

- .gitignore
- go.mod
- go.sum
- ibm/flex/structures.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster_test.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool_test.go
- ibm/service/satellite/data_source_ibm_satellite_host_script.go
- ibm/service/satellite/data_source_ibm_satellite_location.go
- ibm/service/satellite/resource_ibm_satellite_cluster.go
- ibm/service/satellite/resource_ibm_satellite_cluster_worker_pool.go
- ibm/service/satellite/resource_ibm_satellite_host.go
- ibm/service/satellite/resource_ibm_satellite_location.go
- ibm/service/satellite/resource_ibm_satellite_location_test.go
- website/docs/r/container_vpc_cluster.html.markdown
- website/docs/r/container_vpc_worker_pool.html.markdown
- website/docs/r/satellite_cluster.html.markdown
- website/docs/r/satellite_location.html.markdown
```
$ make testacc TEST=./ibm/service/satellite TESTARGS='-run=TestAccSatelliteLocation_PodAndServiceSubnet'
--- PASS: TestAccSatelliteLocation_PodAndServiceSubnet (1187.34s)
PASS
ok      command-line-arguments  1187.409s
```
> Add satellite features and add support to the user can direct which security groups are added to their workers

- website/docs/r/mqcloud_queue_manager.html.markdown
add `ibm_resource_instance` sample config code part in the website doc for improved reference.
```
not required.
...
```
> fix(docs): Add ibm_resource_instance sample config in the mqcloud website docs

- go.mod
- go.sum
- ibm/service/transitgateway/data_source_ibm_tg_gateway.go
Transit Gateway is enabling the pagination feature for GET connection API via the feature flag, if the customer enabled this feature, by default he will get only 50/500 connections, But in the Terraform we should get all connections irrespective of the pagination feature.
```
$ make testacc …
```
> listing all the connection for transit gateway over the pagination set

- ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_servers.go
> added a nil check on data source of bm servers

- ibm/service/schematics/data_source_ibm_schematics_agent.go
- ibm/service/schematics/data_source_ibm_schematics_agent_deploy.go
- ibm/service/schematics/data_source_ibm_schematics_agent_deploy_test.go
- ibm/service/schematics/data_source_ibm_schematics_agent_health.go
- ibm/service/schematics/data_source_ibm_schematics_agent_health_test.go
- ibm/service/schematics/data_source_ibm_schematics_agent_prs.go
- ibm/service/schematics/data_source_ibm_schematics_agent_prs_test.go
- ibm/service/schematics/data_source_ibm_schematics_agent_test.go
- ibm/service/schematics/data_source_ibm_schematics_policy.go
- ibm/service/schematics/data_source_ibm_schematics_policy_test.go
- ibm/service/schematics/resource_ibm_schematics_agent.go
- ibm/service/schematics/resource_ibm_schematics_agent_deploy.go
- ibm/service/schematics/resource_ibm_schematics_agent_deploy_test.go
- ibm/service/schematics/resource_ibm_schematics_agent_health.go
- ibm/service/schematics/resource_ibm_schematics_agent_health_test.go
- ibm/service/schematics/resource_ibm_schematics_agent_prs.go
- ibm/service/schematics/resource_ibm_schematics_agent_prs_test.go
- ibm/service/schematics/resource_ibm_schematics_agent_test.go
- ibm/service/schematics/resource_ibm_schematics_policy.go
- ibm/service/schematics/resource_ibm_schematics_policy_test.go
- website/docs/r/schematics_agent.html.markdown
ps: 
https://github.ibm.com/blueprint/product/issues/9763
https://github.ibm.com/blueprint/product/issues/9760
https://github.ibm.com/blueprint/product/issues/9762
https://github.ibm.com/blueprint/product/issues/9765
https://github.ibm.com/blueprint/product/issues/9766
https://github.ibm.com/blueprint/product/issues/9768
> Schematics agent related fixes for GA

- ibm/service/resourcecontroller/data_source_ibm_resource_instance.go
- website/docs/d/resource_instance.html.markdown
> support parameters for resource instance datasource

- .secrets.baseline
- examples/ibm-project/main.tf
- go.mod
- go.sum
- ibm/service/project/data_source_ibm_project.go
- ibm/service/project/data_source_ibm_project_config.go
- ibm/service/project/data_source_ibm_project_config_test.go
- ibm/service/project/data_source_ibm_project_environment.go
- ibm/service/project/data_source_ibm_project_environment_test.go
- ibm/service/project/data_source_ibm_project_test.go
- ibm/service/project/resource_ibm_project.go
- ibm/service/project/resource_ibm_project_config.go
- ibm/service/project/resource_ibm_project_config_test.go
- ibm/service/project/resource_ibm_project_environment.go
- ibm/service/project/resource_ibm_project_environment_test.go
- ibm/service/project/resource_ibm_project_test.go
- website/docs/d/project.html.markdown
- website/docs/d/project_config.html.markdown
- website/docs/d/project_environment.html.markdown
- website/docs/r/project.html.markdown
- website/docs/r/project_config.html.markdown
- website/docs/r/project_environment.html.markdown
```
rangelil@Riccardos-MacBook-Pro terraform-provider-ibm % make testacc "TEST=./ibm/service/project"
TF_ACC=1 go test ./ibm/service/project -v  -timeout 700m
[WARN] Set the environment variable IBM_APPID_TENANT_ID for testing AppID resources, …
```
> regenerate code for Projects service

- ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go
- ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go
- website/docs/d/cbr_rule.html.markdown
- website/docs/d/cbr_zone.html.markdown
- website/docs/r/cbr_rule.html.markdown
- website/docs/r/cbr_zone.html.markdown
```
$ make testacc TESTARGS='-run=TestAccIBMCbr'
=== RUN   TestAccIBMCbrRuleDataSourceBasic
--- PASS: TestAccIBMCbrRuleDataSourceBasic (14.90s)
=== RUN   TestAccIBMCbrRuleDataSourceAllArgs
--- PASS: TestAccIBMCbrRuleDataSourceAllArgs (11.43s)
=== RUN   TestAccIBMCbrZoneDataSourceBasic
--- PASS: …
```
> support empty lists for CBR rule contexts and zone addresses

- ibm/service/contextbasedrestrictions/data_source_ibm_cbr_rule_test.go
- ibm/service/contextbasedrestrictions/data_source_ibm_cbr_zone_test.go
- ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule_test.go
- ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone_test.go
```
$ make testacc TESTARGS='-run=TestAccIBMCbr'
=== RUN   TestAccIBMCbrRuleDataSourceBasic
--- PASS: TestAccIBMCbrRuleDataSourceBasic (14.90s)
=== RUN   TestAccIBMCbrRuleDataSourceAllArgs
--- PASS: TestAccIBMCbrRuleDataSourceAllArgs (11.43s)
=== RUN   TestAccIBMCbrZoneDataSourceBasic
--- PASS: …
```
> encode test ids as constants for easy replacement

- ibm/service/cos/resource_ibm_cos_bucket.go
Regression result :
=== RUN   TestAccIBMCosBucket_Objectlock_Bucket_Enabled
--- PASS: TestAccIBMCosBucket_Objectlock_Bucket_Enabled (75.90s)
=== RUN   TestAccIBMCosBucket_Objectlock_Configuration_Without_Rule
--- PASS: TestAccIBMCosBucket_Objectlock_Configuration_Without_Rule (71.78s)
--- PASS: TestAccIBMCosBucket_Objectlock_Configuration_Valid_Mode_and_Years  (75.59s)
=== RUN   TestAccIBMCosBucket_Objectlock_Configuration_Empty
--- PASS: TestAccIBMCosBucket_Objectlock_Configuration_Empty (0.39s)
=== RUN   TestAccIBMCosBucket_Objectlock_Configuration_Without_Mode
--- PASS: TestAccIBMCosBucket_Objectlock_Configuration_Without_Mode (0.37s)
=== RUN   TestAccIBMCosBucket_Objectlock_Configuration_With_Mode_Only
--- PASS: TestAccIBMCosBucket_Objectlock_Configuration_With_Mode_Only (49.26s)
=== …
> Adding the fix for cos deletion access denied issue

- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
Relates OR Closes #5068
```
=== RUN   TestAccIBMISInstance_RenameBoot
--- PASS: TestAccIBMISInstance_RenameBoot (258.38s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     262.650s
```
> fix: fixed name update issue on is_instance boot_volume

- website/docs/d/is_vpn_gateway.html.markdown
- website/docs/d/is_vpn_gateways.html.markdown
- website/docs/r/is_vpn_gateway.html.markdown
> docs(is-vpn-gateways): Remove status attribute from docs for vpngateway resources and data sources

- examples/ibm-openpages/README.md
- examples/ibm-openpages/main.tf
- examples/ibm-openpages/provider.tf
- examples/ibm-openpages/terraform.tfvars
- examples/ibm-openpages/variables.tf
- examples/ibm-openpages/versions.tf
- website/docs/r/resource_instance.html.markdown
> Adding OpenPages as part of UX030

- .secrets.baseline
- go.mod
- go.sum
- ibm/service/secretsmanager/data_source_ibm_sm_service_credentials_secret.go
- ibm/service/secretsmanager/data_source_ibm_sm_service_credentials_secret_metadata.go
- ibm/service/secretsmanager/data_source_ibm_sm_username_password_secret.go
- ibm/service/secretsmanager/data_source_ibm_sm_username_password_secret_metadata.go
- ibm/service/secretsmanager/data_source_ibm_sm_username_password_secret_metadata_test.go
- ibm/service/secretsmanager/data_source_ibm_sm_username_password_secret_test.go
- ibm/service/secretsmanager/resource_ibm_sm_service_credentials_secret.go
- ibm/service/secretsmanager/resource_ibm_sm_username_password_secret.go
- ibm/service/secretsmanager/resource_ibm_sm_username_password_secret_test.go
- website/docs/d/sm_username_password_secret.html.markdown
- website/docs/d/sm_username_password_secret_metadata.html.markdown
- website/docs/r/sm_username_password_secret.html.markdown
> Secrets manager custom password generation policy

- ibm/acctest/acctest.go
- ibm/flex/structures.go
- ibm/service/vpc/resource_ibm_is_lb_listener.go
- ibm/service/vpc/resource_ibm_is_lb_listener_policy.go
- ibm/service/vpc/resource_ibm_is_lb_listener_policy_test.go
- ibm/service/vpc/resource_ibm_is_lb_listener_test.go
- website/docs/r/is_lb_listener.html.markdown
- website/docs/r/is_lb_listener_policy.html.markdown
> deprecate(is-lb-listener-redirect): Deprecate lb listener https redirect flattened structure

- .gitignore
- examples/openshift-data-foundation/README.md
- examples/openshift-data-foundation/addon/4.12.0/README.md
- examples/openshift-data-foundation/addon/4.13.0/README.md
- examples/openshift-data-foundation/addon/4.14.0/README.md
- examples/openshift-data-foundation/addon/4.14.0/createaddon.sh
- examples/openshift-data-foundation/addon/4.14.0/createcrd.sh
- examples/openshift-data-foundation/addon/4.14.0/deleteaddon.sh
- examples/openshift-data-foundation/addon/4.14.0/deletecrd.sh
- examples/openshift-data-foundation/addon/4.14.0/schematics.tfvars
- examples/openshift-data-foundation/addon/4.14.0/updatecrd.sh
- examples/openshift-data-foundation/addon/4.14.0/updateodf.sh
- examples/openshift-data-foundation/satellite/README.md
- examples/openshift-data-foundation/satellite/odf-local/4.13/README.md
- examples/openshift-data-foundation/satellite/odf-local/4.13/input.tfvars
- examples/openshift-data-foundation/satellite/odf-local/4.13/main.tf
- examples/openshift-data-foundation/satellite/odf-local/4.13/variables.tf
- examples/openshift-data-foundation/satellite/odf-local/4.14/README.md
- examples/openshift-data-foundation/satellite/odf-local/4.14/input.tfvars
- examples/openshift-data-foundation/satellite/odf-local/4.14/main.tf
- examples/openshift-data-foundation/satellite/odf-local/4.14/variables.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.13/README.md
- examples/openshift-data-foundation/satellite/odf-remote/4.13/input.tfvars
- examples/openshift-data-foundation/satellite/odf-remote/4.13/main.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.13/variables.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.14/README.md
- examples/openshift-data-foundation/satellite/odf-remote/4.14/input.tfvars
- examples/openshift-data-foundation/satellite/odf-remote/4.14/main.tf
- examples/openshift-data-foundation/satellite/odf-remote/4.14/variables.tf
Added -
- ODF Satellite Documentation 
- ODF 4.14 addon doc fixed
```
...
```
> OpenShift Data Foundation Example Fix & Update

- ibm/conns/config.go
/fixes https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5161
```
...
```
> feat: remove CF auth to avoid delay of 60s for nothing

- examples/ansible/examples/simple-vm-power-vs/README.md
- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance.go
- website/docs/d/pi_instance.html.markdown
- website/docs/r/pi_instance.html.markdown
The correct spelling of the IBM i operating system name is "IBM i" with a space between "IBM" and "i".
> Fix the spelling of IBM i in documentation and strings

- ibm/service/iampolicy/resource_ibm_iam_user_policy_test.go
For whatever reason, one of the latest commits in the terraform plugin has some linting error.
> Fix iam policy linting issue

- ibm/service/vpc/data_source_ibm_is_ssh_key.go
- ibm/service/vpc/data_source_ibm_is_ssh_key_test.go
- ibm/service/vpc/data_source_ibm_is_ssh_keys.go
- ibm/service/vpc/data_source_ibm_is_ssh_keys_test.go
- website/docs/d/is_ssh_key.html.markdown
- website/docs/d/is_ssh_keys.html.markdown
```
=== RUN   TestAccIBMISSSHKeyDatasource_basic
--- PASS: TestAccIBMISSSHKeyDatasource_basic (53.61s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     55.217s
```
```
=== RUN   TestAccIBMIsSshKeysDataSourceTags
--- PASS: TestAccIBMIsSshKeysDataSourceTags (34.46s)
PASS
ok …
```
> adds tags support for is_ssh_key(s) datasource

- ibm/service/resourcecontroller/data_source_ibm_resource_instance.go
- ibm/service/resourcecontroller/data_source_ibm_resource_instance_test.go
- website/docs/d/resource_instance.html.markdown
```
=== RUN   TestAccIBMResourceInstanceDataSource_identifier
--- PASS: TestAccIBMResourceInstanceDataSource_identifier (63.86s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/resourcecontroller      78.275s
```
> Added support for identifier in ibm_resource_instance

- ibm/service/catalogmanagement/resource_ibm_cm_version.go
Issue : https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5181
```
...
```
> fix: mark x_auth_token as sensitive

- go.mod
- go.sum
- ibm/service/secretsmanager/data_source_ibm_sm_secrets.go
- website/docs/d/sm_secrets.html.markdown
Add new filter attributes in sm_secrets data source.
=== RUN   TestAccIbmSmArbitrarySecretMetadataDataSourceBasic
--- PASS: TestAccIbmSmArbitrarySecretMetadataDataSourceBasic (17.76s)
=== RUN   TestAccIbmSmArbitrarySecretDataSourceBasic
--- PASS: TestAccIbmSmArbitrarySecretDataSourceBasic (15.09s)
=== …
> Add filter attributes in sm_secrets data source

- go.mod
- go.sum
- ibm/flex/structures.go
- ibm/flex/terraform_problem.go
feat: add new TerraformProblem type for identifiable errors
This adds baseline support for a new error structure, created specifically
for Terraform code.
cc @hkantare @astha-jain - this is part of the identifiable error work we have been discussing the last couple of months. It enables the new error formats for some of the VPC resources (the ones that use `Create` instead of `CreateContext`, etc.) by wrapping the provider and catching errors coming from the resources. This will need to remain a draft until the [Go SDK Core PR](https://github.com/IBM/go-sdk-core/pull/199) and [Go SDK Generator PR](https://github.ibm.com/CloudEngineering/openapi-sdkgen/pull/1612) are merged and released.
Edit: the core and generator PRs are merged and this first step is ready to go.
* Please vote on this …
> feat: use new standardized structures for errors

- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway_test.go
- website/docs/r/is_virtual_endpoint_gateway.html.markdown
Relates OR Closes #5182 
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVirtualEndpointGateway_OptionalName'
=== RUN   TestAccIBMISVirtualEndpointGateway_OptionalName
--- PASS: TestAccIBMISVirtualEndpointGateway_OptionalName (110.38s)
PASS
ok …
```
> Added a empty string check on ips for endpoint gateway resource

- website/docs/d/pi_dhcps.html.markdown
The deprecated network field has already been removed in the dhcp data source, but was left in the documentation.
> Remove removed deprecated documentation

- go.mod
- go.sum
- ibm/conns/config.go
- ibm/flex/structures.go
- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket.go
Test cases :
--- PASS: TestAccIBMCosBucket_Basic (154.25s)
--- PASS: TestAccIBMCosBucket_Basic_Single_Site_Location (81.07s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	243.946s
-- PASS: TestAccIBMCosBucket_AllowedIP (116.93s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	122.044s
--- PASS: TestAccIBMCosBucket_ActivityTracker_Monitor (120.16s)
PASS
ok 	[github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos](http://github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cos)	123.591s
--- PASS: TestAccIBMCOSBucketDataSource_basic (47.68s)
PASS
ok …
> GO RC SDK v2 migration

- ibm/provider/provider.go
- ibm/service/globaltagging/resource_ibm_resource_access_tag.go
- ibm/service/globaltagging/resource_ibm_resource_access_tag_test.go
- ibm/service/globaltagging/resource_ibm_resource_tag.go
- ibm/service/globaltagging/resource_ibm_resource_tag_test.go
- ibm/service/vpc/resource_ibm_is_ssh_key.go
- website/docs/r/resource_access_tag.html.markdown
```
$ make testacc TEST=./ibm/service/globaltagging TESTARGS='-run=TestAccResourceAccessTag_Basic'
=== RUN   TestAccResourceAccessTag_Basic
--- PASS: TestAccResourceAccessTag_Basic (38.14s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/globaltagging   39.706s
```
```
$ make …
```
> Added support for resource access tag

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_snapshot_consistency_group.go
- ibm/service/vpc/data_source_ibm_is_vpn_gateway_connection.go
- ibm/service/vpc/data_source_ibm_is_vpn_gateway_connection_test.go
- ibm/service/vpc/data_source_ibm_is_vpn_gateway_connections.go
- ibm/service/vpc/data_source_ibm_is_vpn_gateway_connections_test.go
- ibm/service/vpc/resource_ibm_is_snapshot_consistency_group.go
- ibm/service/vpc/resource_ibm_is_snapshot_consistency_group_test.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connection_test.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connections.go
Breaking changes from sdk:
- ibm/service/vpc/data_source_ibm_is_snapshot_consistency_group.go name changed in vpc-go-sdk
- ibm/service/vpc/resource_ibm_is_snapshot_consistency_group.go same as above
- ibm/service/vpc/resource_ibm_is_snapshot_consistency_group_test.go test file changes
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connections.go, ibm/service/vpc/resource_ibm_is_vpn_gateway_connection_test.go added logic and test cases for converting based on the type 
```
vpnGatewayConnection := vpnGatewayConnectionIntf.(*vpcv1.VPNGatewayConnection)
```
- ibm/service/vpc/data_source_ibm_is_vpn_gateway_connections.go added logic for converting based on the type 
```
vpnGatewayConnection := vpnGatewayConnectionIntf.(*vpcv1.VPNGatewayConnection)
```
- …
> migrated vpc-go-sdk to 0.49.1 version

- ibm/provider/provider.go
- ibm/service/scc/data_source_ibm_scc_control_libraries.go
- ibm/service/scc/data_source_ibm_scc_control_libraries_test.go
- ibm/service/scc/data_source_ibm_scc_profiles.go
- ibm/service/scc/data_source_ibm_scc_profiles_test.go
- ibm/service/scc/data_source_ibm_scc_provider_type.go
- ibm/service/scc/data_source_ibm_scc_provider_types.go
- ibm/service/scc/data_source_ibm_scc_provider_types_test.go
- ibm/service/scc/resource_ibm_scc_control_library.go
- ibm/service/scc/resource_ibm_scc_control_library_test.go
- ibm/service/scc/resource_ibm_scc_profile_attachment.go
- ibm/service/scc/resource_ibm_scc_profile_attachment_test.go
- ibm/service/scc/resource_ibm_scc_profile_test.go
- website/docs/d/scc_control_libraries.html.markdown
- website/docs/d/scc_instance_settings.html.markdown
- website/docs/d/scc_profile.html.markdown
- website/docs/d/scc_profiles.html.markdown
- website/docs/d/scc_provider_types.html.markdown
- website/docs/r/scc_control_library.html.markdown
- website/docs/r/scc_instance_settings.html.markdown
- website/docs/r/scc_profile.html.markdown
- website/docs/r/scc_profile_attachment.html.markdown
- website/docs/r/scc_provider_type_instance.html.markdown
- website/docs/r/scc_rule.html.markdown
Updates:
* expose a new datasource `ibm_scc_control_libraries` that returns a list of control_libraries available to an instance.
* Users can now use the datasource to help create a profile resource given from the datasource. 
* expose a new datasource `ibm_scc_profiles` that returns a list of profiles available to an instance
* Users can now use the datasource to help create a profile_attachment resource in relation to the data given from the datasource 
* expose a new datasource `ibm_scc_provider_types` that returns a list of provider available to an instance 
* Users can use the datasource to find the ibm_scc_provider_type.id  needed to create a resource of  scc_provider_type_instance. 
* fixes the import of documentation of scc
* Please vote on this pull request by adding a 👍 …
> SCC: adding datasources for automated WP connection  and  Profile attachments

- ibm/service/kms/resource_ibm_kms_instance_policies.go
- ibm/service/kms/resource_ibm_kms_key.go
- website/docs/r/kms_instance_policies.html.markdown
- website/docs/r/kms_key.html.markdown
https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/738
Closes #5154 
```
...
```
> KP: Adding attribute registrations for resource instance key and attribute endpoint_type for key policies

- ibm/flex/structures.go
```
$ make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSubnet_basic
=== RUN   TestAccIBMISSubnet_basic
--- PASS: TestAccIBMISSubnet_basic (265.94s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     267.902s
```
```
--- PASS: TestAccIBMISVPC_basic_apm (121.70s) …
```
> added wait logic for tags async

- go.mod
- go.sum
- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_elasticsearch_test.go
- ibm/service/database/resource_ibm_database_etcd_test.go
- ibm/service/database/resource_ibm_database_mongodb_test.go
- ibm/service/database/resource_ibm_database_mysql_test.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_database_rabbitmq_test.go
- ibm/service/database/resource_ibm_database_redis_test.go
```
data "ibm_resource_group" "group" {
name = "default"
}
resource "ibm_database" "test_acc" {
resource_group_id = data.ibm_resource_group.group.id
name              = "min-compute-redis-03-13-two"
service           = "databases-for-redis"
plan              = "standard"
location          = "us-south"
adminpassword     = …
```
> Minimum validation for multitenant formations

- go.mod
- go.sum
- ibm/flex/structures.go
- ibm/flex/structures_test.go
This PR adds the Stringify() function and its unit tests to the `flex` module.  This new function will be used by Terraform code emitted by the SDK generator.
```
$ cd ibm/flex && go test -v -run TestStringify
=== RUN   TestStringifyString
--- PASS: TestStringifyString (0.00s)
=== RUN   TestStringifyBoolean
--- PASS: …
```
> fix(flex): add Stringify function and tests

- ibm/unittest/utils.go
This PR adds some new utility functions that can be used by the unit tests that will be generated along the resources/data source soon. I decided to create a new folder for the file, following the logic we already have:
`acctest` --> acceptance test
`unittest` --> unit test
cc @dpopp07 
```
$ make …
```
> feat: add utility functions for unit testing

- ibm/flex/structures.go
- ibm/service/globaltagging/resource_ibm_resource_tag.go
- ibm/service/globaltagging/resource_ibm_resource_tag_test.go
- website/docs/r/resource_tag.html.markdown
```
$ make testacc TEST=./ibm/service/globaltagging TESTARGS='-run=TestAccResourceTag_Wait'
=== RUN   TestAccResourceTag_Wait
--- PASS: TestAccResourceTag_Wait (102.57s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/globaltagging   104.798s
```
> Extended wait logic to ibm_resource_tag

- ibm/service/scc/resource_ibm_scc_profile_attachment.go
- ibm/service/scc/resource_ibm_scc_profile_attachment_test.go
- website/docs/r/scc_profile_attachment.html.markdown
Changes the logic for Profile Attachment. It now uses the `*schema.Set` correctly. 
- Made a sub Resource for AttachmentParameters
- renamed the SchemaSetFunc
- took out the usage of `NewSet`(giving too many problems in diff)
- Added an reordering for ProfileAttachment
Relates OR Closes #5259 
```shell 
$ make testacc …
```
> fix: prevent panic on SCC Profile Attachment

- ibm/service/power/resource_ibm_pi_instance.go
This PR undoes a type change from set to list due to compatibility reasons.
Reran changes to make sure it resolved the original problem:
```
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
2024-04-03T14:47:30.363-0500 [INFO]  backend/local: apply calling Apply
2024-04-03T14:47:30.363-0500 [DEBUG] Building and walking apply graph for NormalMode plan
2024-04-03T14:47:30.363-0500 [DEBUG] ProviderTransformer: "ibm_pi_instance.instance (expand)" (*terraform.nodeExpandApplyableResource) needs provider["terraform.local/local/ibm"]
2024-04-03T14:47:30.363-0500 [DEBUG] ReferenceTransformer: "ibm_pi_instance.instance (expand)" references: [var.pi_network] …
```
> Revert type change in the instance list

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_mongodb_enterprise_test.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
**Description**
We were making calls to get the multitenant cpu_enforcement_ratios for databases that do not support multitenant. The API would reply with an error. This fix makes sure that we don't try to get the cpu_enforcement_ratios in the event that a databases is NOT multitenant.
It also enhances the way we report errors for …
> fix(ibm_database resource): Fix cpuEnforcement multitenant bug

- ibm/service/power/data_source_ibm_pi_catalog_images.go
- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_instances.go
- ibm/service/power/resource_ibm_pi_instance.go
- website/docs/d/pi_catalog_images.html.markdown
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instances.html.markdown
- website/docs/r/pi_instance.html.markdown
After speaking with @michaelkad and John Nguyen from my team, we've decided to deprecate vtl related properties for terraform to match the CLI.
PowerVS no longer wishes to manage vtl.
The components affected are:
data source ibm_pi_catalog_images
data source ibm_pi_instance
data source ibm_pi_instances
resource ibm_pi_instance
> Deprecate vtl attributes in data source/resource

- ibm/service/iamaccessgroup/resource_ibm_iam_access_group.go
When access group is deleted outside terraform, resource fails with 404.
when error is returned after retry is done in read method, set id to empty to avoid such lifecycle issues.
```
make testacc TEST=./ibm/service/iamaccessgroup TESTARGS='-run=TestAccIBMIAMAccessGroup_Basic'
...
=== RUN   TestAccIBMIAMAccessGroup_Basic
--- PASS: TestAccIBMIAMAccessGroup_Basic (64.26s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/iamaccessgroup	67.286s
```
> fix access group resource: recreate ag when it is deleted outside terraform

- go.mod
- go.sum
- ibm/service/iampolicy/data_source_ibm_iam_policy_assignment.go
- ibm/service/iampolicy/data_source_ibm_iam_policy_assignments.go
- ibm/service/iampolicy/data_source_ibm_iam_policy_assignments_test.go
- website/docs/d/iam_policy_assignment.html.markdown
Relates OR Closes [#2348](https://github.ibm.com/IAM/AM-issues/issues/2348)
```
=== RUN   TestAccIBMIAMPolicyAssignmentsDataSourceBasic
--- PASS: TestAccIBMIAMPolicyAssignmentsDataSourceBasic (16.26s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/iampolicy	18.218s
...
```
> Fix data assignment APIs

- go.mod
- ibm/conns/config.go
Relates OR Closes [#5275 ](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5275)
**NOTE**: Any modifications not directly related to toolchain service was made by the formatter, or while installing modules needed for running acceptance tests.
Used the following env vars to run acceptance tests:
```
export IC_API_KEY="<IAM API Key>"
export …
```
> Produce error when selecting invalid region in toolchain service

- ibm/service/kms/resource_ibm_kms_instance_policies.go
- ibm/service/kms/resource_ibm_kms_key_test.go
- ibm/service/kms/resource_ibm_kms_key_with_policy_overrides_test.go
Changelog:
- fix drift: only policies specified in the config will be tracked
- fixed log to include INFO tag
- remove requirement for at least one policy to be specified(API allows an empty PUT request)
```
(base) wsiew@Williams-MacBook-Pro terraform-provider-ibm %  make testacc TEST=./ibm/service/kms …
```
> Fix instance policy drift

- go.mod
- go.sum
- ibm/flex/terraform_problem.go
- ibm/flex/terraform_problem_test.go
- ibm/provider/provider.go
This commit adds code that wraps the provider in order to catch errors and re-format them with the new system, to minimize the surface area of the changes required for non-generated resource/data source code.
The primary change to resource code comes in the from of updating calls to `fmt.Errorf` to be calls to a new wrapper function, `flex.FmtErrorf`. It accepts the same arguments but instead of wrapping errors coming from the underlying Go SDK so that we retain only the message, it creates instances of the new TerraformProblem type to be propagated to the wrapped provider code. This way, we preserve all of the information needed for the new error formats, including the information from previous errors.
Note: This PR just creates the baseline support. Resource code that returns an `error` …
> feat: wrap provider to create new error structures

- ibm/flex/terraform_problem.go
- ibm/flex/terraform_problem_test.go
If multiple errors may occur for the same operation in the same resource, and they are not caused by other tools like the SDK, we need a way to make the IDs for each error scenario unique. The way we support to do this is with a "discriminator" value but the `TerraformErrorf` function doesn't expose a way to set the discriminator. This commit adds an additional helper for use in scenarios where we need to create a discriminated error.
> fix: add helper for discriminating terraform problems

- ibm/service/enterprise/resource_ibm_enterprise_account.go
- website/docs/d/enterprise_accounts.html.markdown
```
make testacc TESTARGS='-run=TestAccIbmEnterpriseAccountBasic' TEST=./ibm/service/enterprise
```
> Added IAM fields in enterprise create child account response

- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_snapshot_test.go
- ibm/service/vpc/data_source_ibm_is_snapshots.go
- ibm/service/vpc/data_source_ibm_is_snapshots_test.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
- ibm/service/vpc/resource_ibm_is_snapshot_test.go
- website/docs/d/is_snapshot.html.markdown
- website/docs/d/is_snapshots.html.markdown
- website/docs/r/is_snapshot.html.markdown
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSnapshot_serviceTags'
=== RUN   TestAccIBMISSnapshot_serviceTags
--- PASS: TestAccIBMISSnapshot_serviceTags (262.35s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     264.318s
```
```
% make testacc …
```
> Added support for snapshot service tags

- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_instance_console_language.go
- ibm/service/power/resource_ibm_pi_instance_console_language_test.go
- website/docs/r/pi_console_language.html.markdown
This PR refactors the ibm_pi_console_language resource and cleans up the code.
```
--- PASS: TestAccIBMPIInstanceConsoleLanguage (18.54s)
PASS
```
> Refactor ibm_pi_console_language resource

- ibm/service/scc/resource_ibm_scc_rule.go
Add check on property `required_config.value` (not empty) on func `resourceIbmSccRuleMapToRequiredConfig` and `resourceIbmSccRuleMapToRequiredConfigBase` like it is already done in func `resourceIbmSccRuleMapToRequiredConfigItems` to fix issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5327
Relates OR Closes …
> Add check on property required_config.value (not empty)

- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster_test.go
```
tabori@attilas-mbp terraform-provider-ibm % make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainerVpcClusterBaseEnvvar'
TF_ACC=1 go test ./ibm/service/kubernetes -v -run=TestAccIBMContainerVpcClusterBaseEnvvar -timeout …
```
> remove workerpool related fields from vpc cluster Read

- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_volume.go
The attribute volume_id has accidentally been changed into volume_ids in the volume refactor PR (https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5329). This needs to be changed back for compatibility reasons. This bug was found while refactoring another resource.
> Fix volume_ids into volume_id

- ibm/unittest/utils.go
This PR updates the CreateMockByteArray() function used in unit tests that are generated by the SDK generator.  Specifically, it syncs the definition of the function with the version used in Go SDKs.  The change is to add code to do a base64-decode of the input string which is assumed to be a base64-encoded string (the original un-encoded data would be simply a `[]byte` value - binary data).
> fix: update CreateMockByteArray() to decode input string

- ibm/service/vpc/data_source_ibm_is_bare_metal_server_profile.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_profile_test.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_profiles.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_profiles_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISBMSProfileDataSource_EmptyResourceType'
=== RUN   TestAccIBMISBMSProfileDataSource_EmptyResourceType
--- PASS: TestAccIBMISBMSProfileDataSource_EmptyResourceType (27.26s)
PASS
ok …
```
> fix(bm-profiles): resolved nil pointer on resource type

- go.mod
- go.sum
- ibm/service/scc/resource_ibm_scc_profile.go
- ibm/service/scc/resource_ibm_scc_profile_test.go
Relates OR Closes #5292 
```shell
$ make testacc TEST=./ibm/service/scc  TESTARGS="-run TestAccIbmSccProfiles*" 
...
=== RUN   TestAccIbmSccProfileAttachmentDataSourceBasic
--- PASS: TestAccIbmSccProfileAttachmentDataSourceBasic (23.46s)
=== RUN   TestAccIbmSccProfileAttachmentDataSourceAllArgs
--- PASS: …
```
> scc fix: ability to add profile_version during create

- ibm/service/cloudshell/resource_ibm_cloud_shell_account_settings.go
```
harinireddy@Harinis-MBP default % unset TF_LOG
harinireddy@Harinis-MBP default % terraform1.5 apply  
var.ibmcloud_api_key
The IBM Cloud API token this account authenticates to
Enter a value: 
module.iam_account_settings.data.ibm_iam_account_settings.iam_account_settings: Reading...
module.iam_account_settings.data.ibm_iam_account_settings.iam_account_settings: Read complete after 1s [id=883079c85357a1f3f85d968780e56518]
module.iam_account_settings.data.ibm_cloud_shell_account_settings.cloud_shell_account_settings[0]: Reading...
module.iam_account_settings.data.ibm_cloud_shell_account_settings.cloud_shell_account_settings[0]: Read complete after 2s [id=883079c85357a1f3f85d968780e56518]
Terraform used the selected providers to generate the following execution plan. Resource actions are …
```
> Fix to handle crash for cloudshell

- ibm/service/kubernetes/resource_ibm_container_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster_test.go
- website/docs/r/container_vpc_cluster.html.markdown
```
[…]
[DEBUG] Wait for KMS to apply to master
[DEBUG] Waiting for state to become: [Ready]
[DEBUG] Waiting for KMS to apply to master
[DEBUG] REQUEST: [2024-05-22T15:53:06+02:00] GET /global/v2/getCluster?cluster=<redacted>&v1-compatible HTTP/1.1
[…]
[DEBUG] RESPONSE: [2024-05-22T15:53:07+02:00] …
```
> wait for kms apply

- ibm/service/kubernetes/resource_ibm_container_cluster.go
- ibm/service/kubernetes/resource_ibm_container_storage_attachment.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker.go
- ibm/service/satellite/resource_ibm_satellite_cluster.go
```
2024-05-27T14:35:36.064+0200 [DEBUG] sdk.helper_resource: Finished TestCase: test_name=TestAccIBMContainerVpcClusterBaseEnvvar
--- PASS: TestAccIBMContainerVpcClusterBaseEnvvar (4234.28s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes      4237.086
...
```
lowered …
> ContinuousTargetOccurence updates

- examples/ibm-usage-reports/README.md
- examples/ibm-usage-reports/variables.tf
- go.mod
- go.sum
- ibm/conns/config.go
- ibm/provider/provider.go
- ibm/service/usagereports/data_source_ibm_billing_snapshot_list.go
- ibm/service/usagereports/data_source_ibm_billing_snapshot_list_test.go
- ibm/service/usagereports/resource_ibm_billing_report_snapshot.go
- ibm/service/usagereports/resource_ibm_billing_report_snapshot_test.go
- website/docs/d/billing_snapshot_list.html.markdown
- website/docs/r/billing_report_snapshot.html.markdown
Relates https://github.ibm.com/BSS/metering-deliverables/issues/2243
```
$ make testacc TESTARGS='-run=TestAccIBMBillingReportSnapshot'
=== RUN   TestAccIBMBillingReportSnapshotBasic
--- PASS: TestAccIBMBillingReportSnapshotBasic (29.62s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/usagereports …
```
> Update Usage Reports terraform code to support new error handling

- ibm/service/kms/resource_ibm_kms_instance_policies.go
```
(base) wsiew@Williams-MacBook-Pro terraform-provider-ibm %  make testacc TEST=./ibm/service/kms TESTARGS='-run=TestAccIBMKMS'
TF_ACC=1 go test ./ibm/service/kms -v -run=TestAccIBMKMS -timeout 700m …
```
> fix instance policies to set endpoint type when api url specifies so

- ibm/service/iamidentity/resource_ibm_iam_service_api_key.go
- ibm/service/iamidentity/resource_ibm_iam_service_api_key_test.go
Relates OR Closes #4615 
```
$ make testacc TEST=./ibm/service/iamidentity/resource_ibm_iam_service_api_key_test.go
=== RUN   TestAccIBMIAMServiceAPIKey_Basic
--- PASS: TestAccIBMIAMServiceAPIKey_Basic (109.01s)
=== RUN   TestAccIBMIAMServiceAPIKey_doNotStoreApikeyValue
--- PASS: …
```
> Respect store_value argument when creating apikey for ServiceId #4615

- ibm/service/catalogmanagement/data_source_ibm_cm_offering.go
- ibm/service/catalogmanagement/resource_ibm_cm_offering.go
- ibm/service/catalogmanagement/resource_ibm_cm_version.go
- ibm/service/catalogmanagement/resource_ibm_cm_version_test.go
- website/docs/r/cm_version.html.markdown
PR to remove deprecated catalog management offering fields.  Newest SDK doesn't support these values anymore so they need to be removed.
```
make testacc TESTARGS='-run=TestAccIBMCmOfferingSimpleArgs'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccIBMCmOfferingSimpleArgs -timeout 700m
=== RUN …
```
> fix(CatalogManagement): remove deprecated arguments not supported in latest sdk

- GNUmakefile
- scripts/post-build.sh
- Add new target build-local to the Makefile for building the provider locally.
- Invoke post-build.sh script after the local build process to handle post-build tasks.
- Ensure cross-platform compatibility by setting appropriate paths for:
- Linux and macOS: $HOME/.terraform.d/plugins and $HOME/.terraformrc.
- Windows: …
> feat: add build-local target for easing local development

- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template.go
- ibm/service/iamaccessgroup/resource_ibm_iam_access_group_template_version.go
```
```
```
=== RUN   TestAccIBMIAMAccessGroupTemplateAssignmentDataSourceBasic
--- PASS: TestAccIBMIAMAccessGroupTemplateAssignmentDataSourceBasic (19.70s)
=== RUN   TestAccIBMIAMAccessGroupTemplateVersionsDataSourceBasic
--- PASS: …
```
> Fix policy references bug in AG templates

- website/docs/r/is_instance.html.markdown
- website/docs/r/is_share.html.markdown
- website/docs/r/is_share_mount_target.html.markdown
> doc update for vni in instance and shares

- ibm/service/mqcloud/data_source_ibm_mqcloud_queue_manager_options.go
- fix for queuemanager options data source to include latest version, versions, locations and sizes data.
```
$ make testacc TEST=./ibm/service/mqcloud/... 
=== RUN   TestLoadWaitForQmStatusEnvVar
=== RUN   TestLoadWaitForQmStatusEnvVar/EnvVar_Set_To_True
=== RUN …
```
> fix(MQ on Cloud): queue_manager_options data source to include whole data

- ibm/service/catalogmanagement/data_source_ibm_cm_catalog.go
- ibm/service/catalogmanagement/data_source_ibm_cm_catalog_test.go
- website/docs/d/cm_catalog.html.markdown
Closes #5434
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMCmCatalogDataSourceSimpleArgs -timeout 700m
=== RUN   TestAccIBMCmCatalogDataSourceSimpleArgs
--- PASS: TestAccIBMCmCatalogDataSourceSimpleArgs (21.18s)
```
> feat(Catalog Management): can create catalog data source with id or label

- ibm/service/power/resource_ibm_pi_instance.go
Attr_Fault should be initialized to nil on first read, so that terraform apply doesn't think there's a value left to compute after vm creation.
> Add initialize fault attribute to nil on first read

- ibm/service/kubernetes/resource_ibm_container_worker_pool_test.go
- ibm/validate/validators.go
IKS introduced the ability to resize an existing worker-pool to 0, so we have to allow that in the terraform provider as well. 
```
% export TESTARGS='-run "(TestAccIBMContainerWorkerPoolBasic|TestAccIBMContainerWorkerPoolZeroSize|TestAccIBMContainerWorkerPoolInvalidSizePerZone)"'
% make testacc
==> Checking that code complies …
```
> Allow resizing kubernetes service worker-pools to 0

- ibm/provider/provider.go
- ibm/service/logs/data_source_ibm_logs_data_access_rules.go
- ibm/service/logs/data_source_ibm_logs_data_access_rules_test.go
- ibm/service/logs/resource_ibm_logs_dashboard_folder.go
- ibm/service/logs/resource_ibm_logs_data_access_rule.go
- ibm/service/logs/resource_ibm_logs_data_access_rule_test.go
- website/docs/d/logs_data_access_rules.html.markdown
- website/docs/r/logs_data_access_rule.html.markdown
```
make testacc TEST=./ibm/service/logs TESTARGS='-run=TestAccIbmLogsDataAccessRule'
...
=== RUN   TestAccIbmLogsDataAccessRulesDataSourceBasic
--- PASS: TestAccIbmLogsDataAccessRulesDataSourceBasic (28.43s)
=== RUN   TestAccIbmLogsDataAccessRulesDataSourceAllArgs
--- PASS: TestAccIbmLogsDataAccessRulesDataSourceAllArgs (24.25s)
=== RUN   TestAccIbmLogsDataAccessRuleBasic
--- PASS: TestAccIbmLogsDataAccessRuleBasic (38.70s)
=== RUN   TestAccIbmLogsDataAccessRuleAllArgs
--- PASS: TestAccIbmLogsDataAccessRuleAllArgs (39.24s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/logs	133.959s
```
> Support Cloud Logs data access rules

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_attachment.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_network_attachment.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- ibm/service/vpc/resource_ibm_is_share_mount_target.go
> Added an empty check on protocol_state_filtering_mode

- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
> Updated docs for confidential compute mode in is_instance

- ibm/service/vpc/resource_ibm_is_vpn_gateway_connection_test.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connections.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVPNGatewayConnection_admin_state'
=== RUN   TestAccIBMISVPNGatewayConnection_admin_state
--- PASS: TestAccIBMISVPNGatewayConnection_admin_state (448.82s)
PASS …
```
> fixed admin_state_up default issue on vpn_gateway_connection

- website/docs/r/container_vpc_worker_pool.html.markdown
> add import_on_create param to ibm_container_vpc_worker_pool documentation

- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_template.go
> Fix(iam-identity):trusted profile templates TypeList to TypeSet

- ibm/service/kms/data_source_ibm_kms_key_rings.go
- ibm/service/kms/data_source_ibm_kms_kmip_adapter.go
- ibm/service/kms/data_source_ibm_kms_kmip_adapters.go
- ibm/service/kms/data_source_ibm_kms_kmip_client_certificate.go
- ibm/service/kms/data_source_ibm_kms_kmip_object.go
- ibm/service/kms/data_source_ibm_kms_kmip_objects.go
- ibm/service/kms/resource_ibm_kms_key.go
- ibm/service/kms/resource_ibm_kms_key_alias_test.go
- ibm/service/kms/resource_ibm_kms_key_rings_test.go
- ibm/service/kms/resource_ibm_kms_kmip_adapter.go
- ibm/service/kms/resource_ibm_kms_kmip_client_cert.go
- ibm/service/kms/resource_ibm_kms_kmip_client_cert_test.go
- website/docs/r/kms_key.html.markdown
- website/docs/r/kms_kmip_certs.html.markdown
> S2S documentation note for ibm_kms_key and minor linting fixes

- ibm/service/database/data_source_ibm_database.go
- ibm/service/database/resource_ibm_database.go
```
╷
│ Error: [ERROR] Error getting database autoscaling groups: Not Found
│  Hint: Check if there is a mismatch between your database location and IBMCLOUD_REGION
│ 
│   with ibm_database.elasticsearch,
│   on main.tf line 105, in resource "ibm_database" "elasticsearch":
│  105: resource "ibm_database" "elasticsearch" {
│ 
╵
``` …
> Update(Cloud-Databases): Added hints for region and location mismatches

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_edb_test.go
- ibm/service/database/resource_ibm_database_elasticsearch_platinum_test.go
- ibm/service/database/resource_ibm_database_elasticsearch_test.go
- ibm/service/database/resource_ibm_database_etcd_test.go
- ibm/service/database/resource_ibm_database_mongodb_enterprise_test.go
- ibm/service/database/resource_ibm_database_mongodb_sharding_test.go
- ibm/service/database/resource_ibm_database_mongodb_test.go
- ibm/service/database/resource_ibm_database_mysql_test.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_database_rabbitmq_test.go
- ibm/service/database/resource_ibm_database_redis_test.go
Current we have an issue where `connectionstrings` are not idempotent as seen below.
```
~ resource "ibm_database" "postgresql" {
+ connectionstrings       = (known after apply)
id                      = "crn:v1:bluemix:public:databases-for-postgresql:us-south:a/40ddc34a953a8c02f10987b59085b60e:1a9d66dd-48dd-4aa3-b7d8-8c9e30d44f63::"
name …
```
> fix(Cloud-Databases): Remove deprecated connectionstrings attribute

- ibm/service/kubernetes/data_source_ibm_container_vpc_cluster.go
- ibm/service/kubernetes/resource_ibm_container_vpc_cluster.go
Closes #5548
```
=== RUN   TestAccIBMContainerVpcClusterBasic
--- PASS: TestAccIBMContainerVpcClusterBasic (3422.43s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes      3426.144s
=== RUN   TestAccIBMContainerVPCClusterDataSource_basic
--- PASS: TestAccIBMContainerVPCClusterDataSource_basic …
```
> remove the return value from waitForVpcCluster

- ibm/service/cos/data_source_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket.go
Fix: Read endpoint from schema instead of fake generated bucketid.
```
...
```
> fix: read endpoint type from schema

- ibm/service/kms/resource_ibm_kms_key_rings.go
- ibm/service/kms/resource_ibm_kms_key_rings_test.go
- website/docs/r/kms_key_rings.html.markdown
- updated force delete tests
- changed key ring delete code to not read force_delete
- unsilenced 409 for delete
- update docs for resource with Deprecation Notice and date 1 year from now
1)Testing 409 block:
2)Forwards Compatible Test:
3)Testing normal create+destroy:
<details>
- Using instance built using existing provider to tf …
> deprecate force_delete arg from key ring resource

- examples/ibm-logs-routing/README.md
- examples/ibm-logs-routing/main.tf
- examples/ibm-logs-routing/outputs.tf
- examples/ibm-logs-routing/variables.tf
- examples/ibm-logs-routing/versions.tf
- go.mod
- go.sum
- ibm/conns/config.go
- ibm/provider/provider.go
- ibm/service/logsrouting/README.md
- ibm/service/logsrouting/data_source_ibm_logs-router_targets.go
- ibm/service/logsrouting/data_source_ibm_logs-router_targets_test.go
- ibm/service/logsrouting/data_source_ibm_logs-router_tenants.go
- ibm/service/logsrouting/data_source_ibm_logs-router_tenants_test.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant_test.go
- website/allowed-subcategories.txt
- website/docs/d/logs-router_targets.html.markdown
- website/docs/d/logs-router_tenants.html.markdown
- website/docs/r/logs-router_tenant.html.markdown
- Add IBM Cloud Logs Routing service to IBM Terraform Provider
```
$ make testacc TESTARGS='-run=TestAccIbmLogsRouter'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccIbmLogsRouter -timeout 700m
...
ok …
```
> Added new service Logs Routing to IBM Terraform Provider

- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_instance_ip.go
- ibm/service/power/data_source_ibm_pi_instances.go
- ibm/service/power/data_source_ibm_pi_network_port.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_cloud_connection.go
- ibm/service/power/resource_ibm_pi_dhcp.go
- ibm/service/power/resource_ibm_pi_image.go
- ibm/service/power/resource_ibm_pi_image_test.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance_test.go
- ibm/service/power/resource_ibm_pi_shared_processor_pool.go
- ibm/service/power/resource_ibm_pi_snapshot.go
- ibm/service/power/resource_ibm_pi_volume_group.go
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instances.html.markdown
- website/docs/r/pi_instance.html.markdown
```
--- PASS: TestAccIBMPIInstanceBasic (516.53s)
PASS
=== RUN   TestAccIBMPIInstanceIBMiLicense
--- PASS: TestAccIBMPIInstanceIBMiLicense (618.72s)
PASS
=== RUN   TestAccIBMPIInstanceReplicant
--- PASS: TestAccIBMPIInstanceReplicant (1239.04s)
PASS
=== RUN …
```
> Refactor PI Instance

- ibm/service/logs/data_source_ibm_logs_outgoing_webhook.go
- ibm/service/logs/resource_ibm_logs_alert.go
- ibm/service/logs/resource_ibm_logs_outgoing_webhook.go
make testacc TEST=./ibm/service/logs TESTARGS='-run=TestAccIbmLogsAlert'
=== RUN   TestAccIbmLogsAlertDataSourceBasic
--- PASS: TestAccIbmLogsAlertDataSourceBasic (26.48s)
=== RUN   TestAccIbmLogsAlertDataSourceAllArgs
--- PASS: TestAccIbmLogsAlertDataSourceAllArgs (23.16s)
=== RUN   TestAccIbmLogsAlertsDataSourceBasic
--- PASS: TestAccIbmLogsAlertsDataSourceBasic (23.21s)
=== RUN   TestAccIbmLogsAlertsDataSourceAllArgs
--- PASS: TestAccIbmLogsAlertsDataSourceAllArgs (22.61s)
=== RUN   TestAccIbmLogsAlertBasic
--- PASS: TestAccIbmLogsAlertBasic (36.95s)
=== RUN   TestAccIbmLogsAlertAllArgs
--- PASS: TestAccIbmLogsAlertAllArgs (40.51s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/logs	176.522s
> Fix panics on alerts resource.

- ibm/service/vpc/resource_ibm_is_lb_pool.go
Relates OR Closes #5380
```
resource "ibm_is_lb" "testacc_LB" {
name = "${var.name}-lb"
subnets = ["${var.subnet_id}"]
}
resource "ibm_is_lb_pool" "testacc_lb_pool" {
count   = 5
name = "${var.name}-lb-pool-${count.index}"
lb = "${ibm_is_lb.testacc_LB.id}"
algorithm = "round_robin"
protocol = "http"
health_delay= 45 …
```
> fix(lb_pool): removed lock on lb while lb pool creation

- ibm/service/kms/resource_ibm_kms_key_rings.go
```
Plan: 4 to add, 0 to change, 0 to destroy.
╷
│ Warning: Argument is deprecated
│ 
│   with ibm_kms_key_rings.key_ring,
│   on main.tf line 12, in resource "ibm_kms_key_rings" "key_ring":
│   12:   force_delete = true
│ 
│ force_delete is now deprecated. Please remove all references to this field.
│ …
```
> Add deprecation in resource ibm_kms_key_rings

- .secrets.baseline
- ibm/service/codeengine/resource_ibm_code_engine_secret.go
Relates OR Closes #5582
```
$ make testacc TESTARGS='-run=TestAccIbmCodeEngineSecretGeneric'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccIbmCodeEngineSecretGeneric -timeout 700m
=== RUN   -run=TestAccIbmCodeEngineSecretGeneric
--- PASS: …
```
> fix code engine secret update data mapping #5582

- go.mod
- go.sum
- ibm/service/kms/data_source_ibm_kms_kmip_object.go
- ibm/service/kms/resource_ibm_kms_key.go
- ibm/service/kms/resource_ibm_kms_key_alias.go
- ibm/service/kms/resource_ibm_kms_key_policies.go
- ibm/service/kms/resource_ibm_kms_key_rings.go
- ibm/service/kms/resource_ibm_kms_kmip_adapter.go
- ibm/service/kms/resource_ibm_kms_kmip_client_cert.go
- ibm/service/kms/resource_ibm_kp_key.go
Update kmip_adapter destroy behavior to force delete kmip_objects under the kmip_adapter to be destroyed. This will minimize scenarios where kmip_adapter parent resources cannot be destroyed to cleaned up due to failure to destroy kmip_adapter under parent resource.
Also updated areas of casting vars without validation (prevents potential panics)
Relates OR …
> [KMS] Force delete subresources during kmip_adapter destroy, avoid casting panics

- ibm/service/scc/resource_ibm_scc_profile_attachment.go
- ibm/service/scc/resource_ibm_scc_profile_attachment_test.go
- verify that a diff change seen
- verify that that a PUT is made from the diff change
Relates OR Closes #5535 
Depends on #5509 
```
...
```
> fix: update scc_profile_attachment parameters

- examples/ibm-event-streams/README.md
- examples/ibm-event-streams/main.tf
- examples/ibm-event-streams/provider.tf
- examples/ibm-event-streams/terraform.tfvars
This PR does not change any code. It is an update of Event Streams documentation with:
- Additional documentation of the use of `"ibm_resource_instance"` to create Event Streams instances
- New parameters available for provisioning (`metrics` and `kms_key_crn`)
- An example of using `"ibm_resource_tag"` to add an access tag to an Event Streams service instance
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the …
> feat: document tagging and enhanced metrics

- ibm/service/kubernetes/data_source_ibm_container_cluster.go
- ibm/service/kubernetes/data_source_ibm_container_cluster_test.go
- ibm/service/kubernetes/resource_ibm_container_cluster.go
- ibm/service/kubernetes/resource_ibm_container_cluster_feature.go
- ibm/service/kubernetes/resource_ibm_container_cluster_test.go
- website/docs/d/container_cluster.html.markdown
```
=== RUN   TestAccIBMContainerCluster_basic
--- PASS: TestAccIBMContainerCluster_basic (1077.40s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes      1080.663s
=== RUN   TestAccIBMContainerClusterDataSource_basic
--- PASS: TestAccIBMContainerClusterDataSource_basic …
```
> move wait_till logic into function, integrate it into cluster datasource

- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
Closes [#5618](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5618)
```
...
```
> fix: nil check for instance.LastOperation.Async

- ibm/service/eventstreams/resource_ibm_event_streams_topic.go
- ibm/service/eventstreams/resource_ibm_event_streams_topic_test.go
this PR fixes 2 issues:
-  https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3199, it returns sorted broker addresses, so topic state will not change.
- Acceptance test: deprecated RC V1 api returns unexpected results and causes checkInstanceDestroy fails, replace it with RC V2 API and check state to be removed or pending_reclamation.
Output from …
> fix: unexpected topic state change and acceptance test

- website/docs/r/atracker_target.html.markdown
> docs: add missing `target_type` from `ibm_atracker_target` documentation

- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
Relates OR Closes #5629
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_catalog_pna'
=== RUN   TestAccIBMISInstance_catalog_pna
--- PASS: TestAccIBMISInstance_catalog_pna (204.79s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     206.600s
```
> fix(is_instance): fixed vsi creation issue with catalog images and vni

- examples/ibm-atracker/main.tf
- go.mod
- go.sum
- ibm/service/atracker/data_source_ibm_atracker_targets.go
- ibm/service/atracker/data_source_ibm_atracker_targets_test.go
- ibm/service/atracker/resource_ibm_atracker_target.go
- website/docs/d/atracker_targets.html.markdown
- website/docs/r/atracker_target.html.markdown
Add service to service authentication for atracker to message hub through the new boolean field service_to_service_enabled in atracker event streams endpoint.
```
Helens-IBM:terraform-provider-ibm.helenxu1221 helenxu$ make fmt && make testacc …
```
> add service_to_service_enabled field to atracker event streams endpoint

- examples/ibm-logs-routing/README.md
- examples/ibm-logs-routing/main.tf
- go.mod
- go.sum
- ibm/service/logsrouting/data_source_ibm_logs-router_targets.go
- ibm/service/logsrouting/data_source_ibm_logs-router_targets_test.go
- ibm/service/logsrouting/data_source_ibm_logs-router_tenants.go
- ibm/service/logsrouting/data_source_ibm_logs-router_tenants_test.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant_test.go
- website/docs/d/logs-router_targets.html.markdown
- website/docs/d/logs-router_tenants.html.markdown
- website/docs/r/logs-router_tenant.html.markdown
- Adding a `region` parameter to allow for managing IBM Cloud Logs Routing tenants in multiple regions. 
Relates OR Closes #5616
```
$ make testacc TESTARGS='-run=TestAccIbmLogsRouter'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccIbmLogsRouter …
```
> Add region parameter to logs-routing resources and data sources

- ibm/provider/provider.go
- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip_patch.go
- ibm/service/vpc/resource_ibm_is_subnet_reserved_ip_patch_test.go
- website/docs/r/is_subnet_reserved_ip_patch.html.markdown
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSubnetReservedIPPatchResource_basic'
=== RUN   TestAccIBMISSubnetReservedIPPatchResource_basic
--- PASS: TestAccIBMISSubnetReservedIPPatchResource_basic (124.18s)
PASS …
```
> Added support for reserved ip patch resource

- ibm/service/vpc/resource_ibm_is_share.go
- ibm/service/vpc/resource_ibm_is_share_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIbmIsShareAllArgs_EmptyCheck'
=== RUN   TestAccIbmIsShareAllArgs_EmptyCheck
--- PASS: TestAccIbmIsShareAllArgs_EmptyCheck (121.08s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     123.164s
```
> fix(is_share): added empty check and moved source_share_crn outside

- go.mod
- go.sum
- ibm/service/eventnotification/data_source_ibm_en_destination_cf.go
- ibm/service/eventnotification/data_source_ibm_en_destination_slack.go
- ibm/service/eventnotification/data_source_ibm_en_destination_slack_test.go
- ibm/service/eventnotification/data_source_ibm_en_slack_subscription.go
- ibm/service/eventnotification/data_source_ibm_en_slack_subscription_test.go
- ibm/service/eventnotification/resource_ibm_en_destination_slack.go
- ibm/service/eventnotification/resource_ibm_en_destination_slack_test.go
- ibm/service/eventnotification/resource_ibm_en_subscription_slack.go
- ibm/service/eventnotification/resource_ibm_en_subscription_slack_test.go
- website/docs/d/en_destination_slack.html.markdown
- website/docs/d/en_subscription_slack.html.markdown
- website/docs/r/en_destination_slack.html.markdown
- website/docs/r/en_subscription_slack.html.markdown
- website/docs/r/en_topic.html.markdown
Tests Conducted:
Slack Direct Destination and Subscription Creation:
Subscription Update Test
Slack Direct Data sources:
> Slack Direct Destination Support, Updated Documentation, Fixed Documentation for Topic examples

- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_template_assignment.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_template_assignment_test.go
```
$ make testacc TESTARGS='-run=TestAccIBMTrustedProfileTemplateAssignmentBasic'
=== RUN   TestAccIBMTrustedProfileTemplateAssignmentBasic
--- PASS: TestAccIBMTrustedProfileTemplateAssignmentBasic (535.03s)
PASS
ok   
...
```
> fix for context and history parameter of template assignment

- ibm/service/eventstreams/data_source_ibm_event_streams_schema.go
- ibm/service/eventstreams/data_source_ibm_event_streams_topic.go
- ibm/service/eventstreams/resource_ibm_event_streams_schema.go
- ibm/service/eventstreams/resource_ibm_event_streams_topic.go
Update the contextualized error messages in existing Event Streams code to use the `flex.TerraformErrorf` package, as in https://github.ibm.com/CloudEngineering/client-error-toolchain/wiki/Terraform-Support-Instructions.
```
% make testacc TEST=./ibm/service/eventstreams …
```
> fix: update error diagnostic reporting in existing Event Streams code

- go.mod
- go.sum
- ibm/service/catalogmanagement/data_source_ibm_cm_offering.go
- ibm/service/catalogmanagement/resource_ibm_cm_offering.go
- ibm/service/catalogmanagement/resource_ibm_cm_version.go
- ibm/service/catalogmanagement/utils.go
- website/docs/r/cm_version.html.markdown
Supports new method of fetching all versions of an offering when doing read offering. Also added support for updating version with patch version instead of using patch offering.
<details>
<summary>Test results</summary>
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMCmCatalogBasic -timeout 700m
=== …
```
> feat(Catalog Management): support new offering version limit

- go.mod
- go.sum
- ibm/service/secretsmanager/data_source_ibm_sm_iam_credentials_configuration.go
- ibm/service/secretsmanager/data_source_ibm_sm_iam_credentials_secret.go
- ibm/service/secretsmanager/data_source_ibm_sm_iam_credentials_secret_metadata.go
- ibm/service/secretsmanager/resource_ibm_sm_iam_credentials_configuration.go
- ibm/service/secretsmanager/resource_ibm_sm_iam_credentials_secret.go
- website/docs/d/sm_iam_credentials_configuration.html.markdown
- website/docs/d/sm_iam_credentials_secret.html.markdown
- website/docs/d/sm_iam_credentials_secret_metadata.html.markdown
- website/docs/r/sm_iam_credentials_configuration.html.markdown
- website/docs/r/sm_iam_credentials_secret.html.markdown
Support for creating IAM credentials secret using service to service authorization with IAM service instead of API key.
```
...
```
> Secrets Manager IAM credentials secrets with S2S

- ibm/service/contextbasedrestrictions/resource_ibm_cbr_rule.go
- ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone.go
- ibm/service/contextbasedrestrictions/resource_ibm_cbr_zone_addresses.go
```
make testacc TEST=./ibm/service/contextbasedrestrictions TESTARGS='-run=TestAccIBMCbrRuleBasic'
=== RUN   TestAccIBMCbrRuleBasic
--- PASS: TestAccIBMCbrRuleBasic (12.78s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/contextbasedrestrictions        14.466s
make testacc …
```
> Fix: cbr-provider-produced-inconsistent-result

- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_identity.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_identity_test.go
- website/docs/r/iam_trusted_profile_identity.html.markdown
Fixes a bug handling identity id when that id contains a CRN. 
```
$ make testacc TEST=./ibm/service/iamidentity/resource_ibm_iam_trusted_profile_identity_test.go
=== RUN   TestAccIBMIamTrustedProfileIdentityBasic
--- PASS: TestAccIBMIamTrustedProfileIdentityBasic (43.22s)
=== RUN   TestAccIBMIamTrustedProfileIdentityAllArgs …
```
> Fix incorrect handling of trusted profile static CRN identities

- go.mod
- go.sum
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_definition.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_definition_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_definition.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_definition_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_test.go
- website/docs/d/cd_tekton_pipeline.html.markdown
- website/docs/d/cd_tekton_pipeline_trigger.html.markdown
- website/docs/r/cd_tekton_pipeline.html.markdown
- website/docs/r/cd_tekton_pipeline_trigger.html.markdown
Add support for the `enable_events_from_forks` property of Git Triggers in Tekton Pipeline
```
--- PASS: TestAccIBMCdTektonPipelineDefinitionDataSourceBasic (88.86s)
=== RUN   TestAccIBMCdTektonPipelinePropertyDataSourceBasic
--- PASS: TestAccIBMCdTektonPipelinePropertyDataSourceBasic (75.59s)
=== RUN   TestAccIBMCdTektonPipelinePropertyDataSourceAllArgs
--- PASS: TestAccIBMCdTektonPipelinePropertyDataSourceAllArgs (70.66s)
=== RUN   TestAccIBMCdTektonPipelineDataSourceBasic
--- PASS: …
```
> feat(tekton): add support for fork feature

- ibm/service/schematics/resource_ibm_schematics_agent.go
- website/docs/r/schematics_agent.html.markdown
ps: https://github.ibm.com/blueprint/product/issues/10856
> sch Agent resource updated to accommodate agent destroy resources

- go.mod
- go.sum
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_workspace.go
- ibm/service/power/resource_ibm_pi_workspace_test.go
- website/docs/r/pi_workspace.html.markdown
Adds user tags argument
Deprecates workspace details attribute.
```
--- PASS: TestAccIBMPIWorkspaceBasic (134.98s)
PASS
--- PASS: TestAccIBMPIWorkspaceUserTags (133.32s)
PASS
```
> [Resource] Add user tags to workspace resource

- examples/ibm-configuration-aggregator/README.md
- examples/ibm-configuration-aggregator/main.tf
- examples/ibm-configuration-aggregator/outputs.tf
- examples/ibm-configuration-aggregator/variables.tf
- examples/ibm-configuration-aggregator/versions.tf
- go.mod
- go.sum
- ibm/acctest/acctest.go
- ibm/conns/config.go
- ibm/provider/provider.go
- ibm/service/configurationaggregator/README.md
- ibm/service/configurationaggregator/data_source_ibm_config_aggregator_configurations.go
- ibm/service/configurationaggregator/data_source_ibm_config_aggregator_configurations_test.go
- ibm/service/configurationaggregator/data_source_ibm_config_aggregator_resource_collection_status.go
- ibm/service/configurationaggregator/data_source_ibm_config_aggregator_resource_collection_status_test.go
- ibm/service/configurationaggregator/data_source_ibm_config_aggregator_settings.go
- ibm/service/configurationaggregator/data_source_ibm_config_aggregator_settings_test.go
- ibm/service/configurationaggregator/resource_ibm_config_aggregator_settings.go
- ibm/service/configurationaggregator/resource_ibm_config_aggregator_settings_test.go
- ibm/service/configurationaggregator/utils.go
- website/allowed-subcategories.txt
- website/docs/d/config_aggregator_configurations.html.markdown
- website/docs/d/config_aggregator_resource_collection_status.html.markdown
- website/docs/d/config_aggregator_settings.html.markdown
- website/docs/r/config_aggregator_settings.html.markdown
git issue : https://github.ibm.com/devx-app-services/configuration-aggregator-planning/issues/326
terraform output 
```
ramyac@Ramyas-MacBook-Pro ibm-configuration-aggregator % terraform apply
ibm_config_aggregator_settings.config_aggregator_settings_instance: Refreshing state... [id=Profile-7d935dbb-7ee5-44e1-9e85-38e65d722398]
Changes to Outputs:
+ config_aggregator_settings       = {
+ additional_scope            = []
+ last_updated                = "2024-09-20T06:18:06Z"
+ regions                     = [
+ "all",
]
+ resource_collection_enabled = true
+ trusted_profile_id          = "Profile-7d935dbb-7ee5-44e1-9e85-38e65d722398"
}
- config_aggregator_settings_clean = {
- additional_scope            = []
- regions                     = [
- "all",
]
- resource_collection_enabled = true …
```
> config changes

- ibm/acctest/acctest.go
- ibm/service/power/data_source_ibm_pi_catalog_images.go
- ibm/service/power/data_source_ibm_pi_image.go
- ibm/service/power/data_source_ibm_pi_images.go
- ibm/service/power/resource_ibm_pi_image.go
- ibm/service/power/resource_ibm_pi_image_test.go
- website/docs/d/pi_catalog_images.html.markdown
- website/docs/d/pi_image.html.markdown
- website/docs/d/pi_images.html.markdown
- website/docs/r/pi_image.html.markdown
pi_catalog_images (d):
```
=== RUN   TestAccIBMPICatalogImagesDataSourceBasic
--- PASS: TestAccIBMPICatalogImagesDataSourceBasic (52.36s)
PASS
```
```
=== RUN   TestAccIBMPICatalogImagesDataSourceVTL
--- PASS: TestAccIBMPICatalogImagesDataSourceVTL (51.41s)
PASS
```
```
=== RUN …
```
> Granular CRN for image datasources and resources

- ibm/service/power/data_source_ibm_pi_cloud_instance.go
- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_instance_test.go
- ibm/service/power/data_source_ibm_pi_instances.go
- ibm/service/power/data_source_ibm_pi_instances_test.go
- ibm/service/power/resource_ibm_pi_capture.go
- ibm/service/power/resource_ibm_pi_capture_test.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance_test.go
- website/docs/d/pi_cloud_instance.html.markdown
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instances.html.markdown
- website/docs/r/pi_capture.html.markdown
- website/docs/r/pi_instance.html.markdown
pi_instance (r):
```
--- PASS: TestAccIBMPIInstanceBasic (341.98s)
PASS
```
```
=== RUN   TestAccIBMPIInstanceDeploymentType
--- PASS: TestAccIBMPIInstanceDeploymentType (982.16s)
PASS
```
```
=== RUN   TestAccIBMPIInstanceReplicant
--- PASS: …
```
> Granular CRN for instance datasources and resources

- ibm/service/power/data_source_ibm_pi_instance_volumes.go
- ibm/service/power/data_source_ibm_pi_volume.go
- ibm/service/power/data_source_ibm_pi_volume_test.go
- ibm/service/power/resource_ibm_pi_volume.go
- ibm/service/power/resource_ibm_pi_volume_clone.go
- ibm/service/power/resource_ibm_pi_volume_test.go
- website/docs/d/pi_instance_volumes.html.markdown
- website/docs/d/pi_volume.html.markdown
- website/docs/r/pi_volume.html.markdown
- website/docs/r/pi_volume_clone.html.markdown
pi_instance_volumes (d):
```
=== RUN   TestAccIBMPIVolumesDataSource_basic
--- PASS: TestAccIBMPIVolumesDataSource_basic (41.57s)
PASS
```
pi_volume (d):
```
=== RUN   TestAccIBMPIVolumeDataSource_basic
--- PASS: TestAccIBMPIVolumeDataSource_basic (158.29s)
PASS
```
```
=== RUN …
```
> Granular CRN for volume data sources and resources

- ibm/service/power/data_source_ibm_pi_instance_volumes.go
- ibm/service/power/data_source_ibm_pi_volume.go
- website/docs/d/pi_instance_volumes.html.markdown
- website/docs/d/pi_volume.html.markdown
pi_volume (d):
```
=== RUN   TestAccIBMPIVolumeDataSource_basic
--- PASS: TestAccIBMPIVolumeDataSource_basic (6.67s)
PASS
```
```
=== RUN   TestAccIBMPIVolumeDataSource_replication
--- PASS: TestAccIBMPIVolumeDataSource_replication (11.99s)
PASS
```
pi_instance_volumes (d):
```
=== RUN …
```
> Add GRS attributes to pi_volume (d) and pi_instance_volumes (d)

- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_volume.go
- website/docs/r/pi_volume.html.markdown
```
--- PASS: TestAccIBMPIVolumebasic (85.61s)
PASS
```
```
=== RUN   TestAccIBMPIVolumePool
--- PASS: TestAccIBMPIVolumePool (45.81s)
PASS
```
```
=== RUN   TestAccIBMPIVolumeGRS
--- PASS: TestAccIBMPIVolumeGRS (75.89s)
PASS
```
```
=== RUN   TestAccIBMPIVolumeUpdate …
```
> Add GRS Attributes/Arguments to pi_volume resource

- go.sum
- ibm/service/power/data_source_ibm_pi_sap_profile.go
- ibm/service/power/data_source_ibm_pi_sap_profiles.go
- website/docs/d/pi_sap_profile.html.markdown
- website/docs/d/pi_sap_profiles.html.markdown
```
=== RUN   TestAccIBMPISAPProfileDataSourceBasic
--- PASS: TestAccIBMPISAPProfileDataSourceBasic (10.83s)
PASS
=== RUN   TestAccIBMPISAPProfilesDataSourceBasic
--- PASS: TestAccIBMPISAPProfilesDataSourceBasic (9.42s)
PASS
```
> [Datasource] Add support_systems for sap profile

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_volume_group.go
- ibm/service/power/data_source_ibm_pi_volume_group_details.go
- ibm/service/power/data_source_ibm_pi_volume_groups.go
- ibm/service/power/data_source_ibm_pi_volume_groups_details.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_volume_group.go
- website/docs/d/pi_volume_group_details.html.markdown
- website/docs/d/pi_volume_groups.html.markdown
- website/docs/d/pi_volume_groups_details.html.markdown
- website/docs/r/pi_volume_group.html.markdown
pi_volume_group (d):
```
=== RUN   TestAccIBMPIVolumeGroupDataSource_basic
--- PASS: TestAccIBMPIVolumeGroupDataSource_basic (10.44s)
PASS
```
pi_volume_groups (d):
```
=== RUN   TestAccIBMPIVolumeGroupsDataSource_basic
--- PASS: TestAccIBMPIVolumeGroupsDataSource_basic (13.01s)
PASS
``` …
> Add GRS attributes to pi volume group data sources and related

- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool_test.go
- ibm/service/kubernetes/resource_ibm_container_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_worker_pool_test.go
- website/docs/r/container_vpc_worker_pool.html.markdown
- website/docs/r/container_worker_pool.html.markdown
```
=== RUN   TestAccIBMContainerVpcClusterWorkerPoolBasic
--- PASS: TestAccIBMContainerVpcClusterWorkerPoolBasic (1332.86s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/kubernetes      1336.034s
=== RUN   TestAccIBMContainerWorkerPoolBasic
--- PASS: …
```
> add orphan_resource_on_delete argument to worker pool resources

- go.mod
- go.sum
- ibm/flex/structures.go
- ibm/service/vpc/data_source_ibm_is_volume.go
- ibm/service/vpc/data_source_ibm_is_volume_profile.go
- ibm/service/vpc/data_source_ibm_is_volume_profile_test.go
- ibm/service/vpc/data_source_ibm_is_volume_profiles.go
- ibm/service/vpc/data_source_ibm_is_volume_profiles_test.go
- ibm/service/vpc/data_source_ibm_is_volume_test.go
- ibm/service/vpc/data_source_ibm_is_volumes.go
- ibm/service/vpc/data_source_ibm_is_volumes_test.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- ibm/service/vpc/resource_ibm_is_instance_volume_attachment.go
- ibm/service/vpc/resource_ibm_is_instance_volume_attachment_test.go
- ibm/service/vpc/resource_ibm_is_volume.go
- ibm/service/vpc/resource_ibm_is_volume_test.go
- website/docs/d/is_volume.html.markdown
- website/docs/d/is_volume_profile.html.markdown
- website/docs/d/is_volume_profiles.html.markdown
- website/docs/d/is_volumes.html.markdown
- website/docs/r/is_volume.html.markdown
```
=== RUN   TestAccIBMISVolumeDatasource_Sdp
--- PASS: TestAccIBMISVolumeDatasource_Sdp (56.36s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     57.975s
```
```
=== RUN   TestAccIBMISVolumeProfileDataSource_sdpbasic
--- PASS: TestAccIBMISVolumeProfileDataSource_sdpbasic …
```
> Added support for defined_performance changes in is_volume

- ibm/service/vpc/data_source_ibm_is_volume.go
- ibm/service/vpc/data_source_ibm_is_volume_test.go
- website/docs/d/is_volume.html.markdown
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVolumeDatasourceIdnetifier_basic'
=== RUN   TestAccIBMISVolumeDatasourceIdnetifier_basic
--- PASS: TestAccIBMISVolumeDatasourceIdnetifier_basic (59.01s)
PASS …
```
> added support for identifier in volume datasource

- ibm/service/vpc/resource_ibm_is_vpn_gateway_connection_test.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connections.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVPNGatewayConnection_routeDistributeTraffic'
=== RUN   TestAccIBMISVPNGatewayConnection_routeDistributeTraffic
--- PASS: TestAccIBMISVPNGatewayConnection_routeDistributeTraffic (444.79s)
PASS
ok …
```
> test fix on vpn gateway connection

- ibm/service/kms/data_source_ibm_kms_key.go
- ibm/service/kms/data_source_ibm_kms_key_rings.go
- ibm/service/kms/data_source_ibm_kms_keys.go
- ibm/service/kms/data_source_ibm_kms_kmip_adapters.go
- ibm/service/kms/data_source_ibm_kms_kmip_client_certificate.go
- ibm/service/kms/data_source_ibm_kms_kmip_client_certificates.go
- ibm/service/kms/data_source_ibm_kms_kmip_object.go
- ibm/service/kms/data_source_ibm_kms_kmip_objects.go
- ibm/service/kms/data_source_ibm_kp_key.go
- ibm/service/kms/resource_ibm_kms_instance_policies.go
- ibm/service/kms/resource_ibm_kms_key.go
- ibm/service/kms/resource_ibm_kms_key_alias.go
- ibm/service/kms/resource_ibm_kms_key_policies.go
- ibm/service/kms/resource_ibm_kms_key_rings.go
- ibm/service/kms/resource_ibm_kms_kmip_adapter.go
- ibm/service/kms/resource_ibm_kms_kmip_client_cert.go
- ibm/service/kms/resource_ibm_kp_key.go
- ibm/service/kms/utils.go
- ibm/service/kms/utils_test.go
sample error format
```
ibm_kms_key.key2: Creating...
╷
│ Error: [ERROR] Error while creating key: kp.Error: correlation_id='9d344201-315e-4b9d-9917-a0bb0e19b9bb', msg='Bad Request: Key could not be created: Please see `reasons` for more details (INVALID_FIELD_ERR)', reasons='[INVALID_FIELD_ERR: The …
```
> update kp operations to use flex logger

- ibm/acctest/acctest.go
- ibm/service/kubernetes/data_source_ibm_container_vpc_worker_pool_test.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool.go
- ibm/service/kubernetes/resource_ibm_container_vpc_worker_pool_test.go
```
% make testacc TEST=./ibm/service/kubernetes TESTARGS='-run=TestAccIBMContainerVpcClusterWorkerPool'
...
=== RUN   TestAccIBMContainerVpcClusterWorkerPoolDataSourceBasic
--- PASS: TestAccIBMContainerVpcClusterWorkerPoolDataSourceBasic (1081.74s)
=== RUN …
```
> ibm_container_vpc_worker_pool - remove Computed for secondary_storage property

- ibm/service/scc/resource_ibm_scc_profile_attachment.go
- ibm/service/scc/resource_ibm_scc_profile_attachment_test.go
Closes #5718
```console
$ make testacc TEST=./ibm/service/scc  TESTARGS="-run TestAccIbmSccProfileAttachment*"
...
=== RUN   TestAccIbmSccProfileAttachmentDataSourceBasic
--- PASS: TestAccIbmSccProfileAttachmentDataSourceBasic (34.28s)
=== RUN   TestAccIbmSccProfileAttachmentDataSourceAllArgs
--- PASS: …
```
> [SCC] Fix: correct ProfileAttachment for Updating a Profile Attachment

- go.sum
- ibm/service/power/resource_ibm_pi_capture.go
Description:
Fixes bug where capture image data CRN was read even though it could be nil during user tag handling in the creation function, which would cause an error.
```
=== RUN   TestAccIBMPICaptureBasic
--- PASS: TestAccIBMPICaptureBasic (81.80s)
PASS
```
```
=== RUN   TestAccIBMPICaptureUserTags …
```
> Fix potential null pointer bug in pi capture user tags during creation

- ibm/acctest/acctest.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interface_floating_ip.go
- ibm/service/vpc/data_source_ibm_is_virtual_network_interface_floating_ip_test.go
Relates OR Closes #5757
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMIsVirtualNetworkInterfaceFloatingIPDataSource404'
=== RUN   TestAccIBMIsVirtualNetworkInterfaceFloatingIPDataSource404
--- PASS: TestAccIBMIsVirtualNetworkInterfaceFloatingIPDataSource404 (11.68s)
PASS
ok …
```
> 404 error fix on ibm_is_virtual_network_interface_floating_ip datasource

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_elasticsearch_platinum_test.go
- ibm/service/database/resource_ibm_database_elasticsearch_test.go
- ibm/service/database/resource_ibm_database_etcd_test.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_database_rabbitmq_test.go
- ibm/service/database/resource_ibm_database_redis_test.go
Ticket: https://github.ibm.com/compose/App/issues/1600
**Summary:**
When importing an `ibm_database` terraform resource with `key_protect_key` and `key_protect_instance` attributes set, these values are not read or persisted from the remote state. This causes the resource to be marked for deletion.
**Fix:**
- Add `disk_encryption_instance_crn` and …
> Import a resource provisioned with key_protect_id and key_protect_instance attributes set

- go.mod
- go.sum
- ibm/service/kubernetes/resource_ibm_container_cluster.go
Requires https://github.com/IBM-Cloud/bluemix-go/pull/451
Underlying api call was changed as the old one was faulty
```
❯ make testacc TEST=./ibm/service/kubernetes TESTARGS='-run "TestAccIBMContainerCluster_basic"'
=== RUN   TestAccIBMContainerCluster_basic
--- PASS: TestAccIBMContainerCluster_basic (4475.05s)
PASS
ok …
```
> ListClassicWorkers => ListAllWorkers

- ibm/service/eventstreams/resource_ibm_event_streams_topic.go
**What was done:** A customer reported an error running the provider, 
```
'resourceIBMEventStreamsTopicCreate createSaramaAdminClient: kafka: invalid configuration (ClientID is invalid)'
```
The root cause is the use of `os.Hostname()` for the ClientID, which in rare cases has an illegal value (either it is `""`, or it contains an illegal character such as `$` or `#`).  Change the ClientID to `terraform-provider-ibm` which is legal.
Note: the ClientID has no effect on the Event Streams or Kafka operations. It is just used in some log messages.
* …
> fix: eventstreams sarama clientid

- ibm/service/vpc/data_source_ibm_is_image.go
- ibm/service/vpc/data_source_ibm_is_image_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISImageDataSource_id404'
=== RUN   TestAccIBMISImageDataSource_id404
--- PASS: TestAccIBMISImageDataSource_id404 (2.92s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     4.615s
```
> fix(ibm_is_image): 404 error fix on datasource

- ibm/service/vpc/data_source_ibm_is_share.go
- ibm/service/vpc/data_source_ibm_is_share_test.go
- ibm/service/vpc/data_source_ibm_is_source_share.go
- ibm/service/vpc/data_source_ibm_is_source_share_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIbmIsShareDataSource404'
=== RUN   TestAccIbmIsShareDataSource404
--- PASS: TestAccIbmIsShareDataSource404 (2.70s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     4.360s
```
```
% make testacc …
```
> fix(ibm_is_share): 404 error fix on datasource

- ibm/service/vpc/data_source_ibm_is_snapshot.go
- ibm/service/vpc/data_source_ibm_is_snapshot_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSnapshotDatasource_404'
=== RUN   TestAccIBMISSnapshotDatasource_404
--- PASS: TestAccIBMISSnapshotDatasource_404 (3.42s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     5.395s
```
> fix(ibm_is_snapshot): 404 error fix on datasource

- examples/ibm-event-streams/README.md
- examples/ibm-event-streams/main.tf
update mirroring example documentation to include topic/group renaming.
```
...
```
> chore: update mirroring example doc

- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_helpers_test.go
Ticket: https://github.ibm.com/compose/App/issues/1412
Refactoring acceptance tests is time consuming as running the tests takes a long time so refactoring bit by bit
- Removed common test functions into new file and out of PG file
- concatenate PG PITR test
```
$ make testacc …
```
> fix(cloud-databases): Refactor tests Part 1

- ibm/service/database/data_source_ibm_database_point_in_time_recovery_test.go
- ibm/service/database/data_source_ibm_database_remotes_test.go
- ibm/service/database/data_source_ibm_database_test.go
- ibm/service/database/resource_ibm_database_edb_test.go
- ibm/service/database/resource_ibm_database_elasticsearch_platinum_test.go
- ibm/service/database/resource_ibm_database_mongodb_enterprise_test.go
- ibm/service/database/resource_ibm_database_mongodb_test.go
Ticket: https://github.ibm.com/compose/App/issues/1697
- Fix 5 tests from ticket
- Formatting
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseDataSourceBasic'
=== RUN   TestAccIBMDatabaseDataSourceBasic
=== PAUSE TestAccIBMDatabaseDataSourceBasic
=== CONT  TestAccIBMDatabaseDataSourceBasic
--- PASS: …
```
> fix(cloud-databases): Acceptance test fixes

- examples/ibm-iam-identity-effective-account-settings/README.md
- examples/ibm-iam-identity-effective-account-settings/main.tf
- examples/ibm-iam-identity-effective-account-settings/variables.tf
- examples/ibm-iam-identity-effective-account-settings/versions.tf
- ibm/provider/provider.go
- ibm/service/iamidentity/data_source_ibm_iam_effective_account_settings.go
- ibm/service/iamidentity/data_source_ibm_iam_effective_account_settings_test.go
- website/docs/d/iam_effective_account_settings.html.markdown
> feat(IAM Identity): Effective account settings

- ibm/service/scc/resource_ibm_scc_instance_settings.go
- ibm/service/scc/resource_ibm_scc_instance_settings_test.go
- website/docs/r/scc_instance_settings.html.markdown
- include the following properties to scc_instance_settings:
- source_description
- source_name
#5817 
#5579 
```
$ make testacc TEST=./ibm/service/scc  TESTARGS="-run TestAccIbmSccInstance*"
TF_ACC=1 go test ./ibm/service/scc -v -run …
```
> fix: HOT FIX to include properties from issue 5579

- ibm/service/vpc/resource_ibm_is_volume.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVolume_snapshotcrn'
=== RUN   TestAccIBMISVolume_snapshotcrn
--- PASS: TestAccIBMISVolume_snapshotcrn (254.98s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     257.024s
```
> vol fix for snapshot crn

- ibm/acctest/acctest.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- website/docs/r/is_instance.html.markdown
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_volprototypes'
=== RUN   TestAccIBMISInstance_volprototypes
--- PASS: TestAccIBMISInstance_volprototypes (310.98s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     312.985s
```
> Added support for volume_prototypes on ibm_is_instance resource

- .secrets.baseline
- ibm/service/codeengine/resource_ibm_code_engine_app.go
- website/docs/d/code_engine_app.html.markdown
- website/docs/r/code_engine_app.html.markdown
Relates OR Closes a bug that was reported through the customer product support.
```
$ make testacc TESTARGS='-run=TestAccIbmCodeEngineAppBasic'
...
=== RUN   TestAccIbmCodeEngineAppBasic
--- PASS: TestAccIbmCodeEngineAppBasic (152.98s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/codeengine …
```
> fix: adjust validation for Code Engine application `scale_concurrency_target`

- ibm/flex/structures.go
- ibm/service/power/resource_ibm_pi_capture.go
- ibm/service/power/resource_ibm_pi_image.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_network.go
- ibm/service/power/resource_ibm_pi_network_address_group.go
- ibm/service/power/resource_ibm_pi_network_interface.go
- ibm/service/power/resource_ibm_pi_network_port_attach.go
- ibm/service/power/resource_ibm_pi_network_security_group.go
- ibm/service/power/resource_ibm_pi_network_security_group_member.go
- ibm/service/power/resource_ibm_pi_network_security_group_rule.go
- ibm/service/power/resource_ibm_pi_shared_processor_pool.go
- ibm/service/power/resource_ibm_pi_snapshot.go
- ibm/service/power/resource_ibm_pi_volume.go
- ibm/service/power/resource_ibm_pi_workspace.go
Adding `ResourcePowerUserTagsCustomizeDiff` because `ResourceTagsCustomizeDiff`  checks for `tags` but are using `pi_user_tags`.
```
=== RUN   TestAccIBMPICaptureUserTags
--- PASS: TestAccIBMPICaptureUserTags (204.92s)
PASS
=== RUN   TestAccIBMPIImageUserTags
--- PASS: TestAccIBMPIImageUserTags …
```
> Custom Diff User Tags

- ibm/acctest/acctest.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- website/docs/r/is_instance.html.markdown
Relates OR Closes #5827
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstance_primary_ip_consistency'
=== RUN   TestAccIBMISInstance_primary_ip_consistency
--- PASS: TestAccIBMISInstance_primary_ip_consistency (168.92s)
PASS …
```
> added primary_ip refernce to nac for consistency

- ibm/service/database/resource_ibm_database.go
- website/docs/r/database.html.markdown
This reverts commit f5425502e500d119ca517d45c268df36c86549b9.
Reverts this PR that is causing issues
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5791
```
$  make testacc TEST=./ibm/service/database TESTARGS='-run=TestAccIBMDatabaseInstance_Redis_Basic'
=== RUN …
```
> fix(Cloud-Databases): Revert "Add version validation (#5791)"

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
Workaround to fix validation errors that expect host flavor to be included with scaling request.
Host flavor will be included with each scaling API request.
```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstancePostgresGroup'
--- PASS: TestAccIBMDatabaseInstancePostgresGroup (1228.55s)
...
```
> fix(Cloud Databases): always include host flavor with scaling requests

- ibm/service/vpc/resource_ibm_is_volume.go
> Added 100 default capacity to the volume when no attributes is set

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_host.go
- ibm/service/power/data_source_ibm_pi_hosts.go
- ibm/service/power/ibm_pi_constants.go
- website/docs/d/pi_host.html.markdown
- website/docs/d/pi_hosts.html.markdown
pi_host (d)
```
=== RUN   TestAccIBMPIHostDataSourceBasic
--- PASS: TestAccIBMPIHostDataSourceBasic (82.79s)
PASS
```
pi_hosts (d)
```
=== RUN   TestAccIBMPIHostsDataSourceBasic
--- PASS: TestAccIBMPIHostsDataSourceBasic (80.24s)
PASS
```
> [Datasource] Add host reference to power dedicated host data sources

- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/logs/data_source_ibm_logs_outgoing_webhook.go
- ibm/service/logs/data_source_ibm_logs_stream.go
- ibm/service/logs/data_source_ibm_logs_stream_test.go
- ibm/service/logs/data_source_ibm_logs_streams.go
- ibm/service/logs/data_source_ibm_logs_streams_test.go
- ibm/service/logs/resource_ibm_logs_alert.go
- ibm/service/logs/resource_ibm_logs_data_access_rule_test.go
- ibm/service/logs/resource_ibm_logs_outgoing_webhook.go
- ibm/service/logs/resource_ibm_logs_stream.go
- ibm/service/logs/resource_ibm_logs_stream_test.go
- website/docs/d/logs_data_usage_metrics.html.markdown
- website/docs/d/logs_outgoing_webhook.html.markdown
- website/docs/d/logs_stream.html.markdown
- website/docs/d/logs_streams.html.markdown
- website/docs/r/logs_alert.html.markdown
- website/docs/r/logs_outgoing_webhook.html.markdown
- website/docs/r/logs_stream.html.markdown
```
$ make testacc TESTARGS='-run=TestAccIbmLogsStream'
=== RUN   TestAccIbmLogsStreamDataSourceBasic
--- PASS: TestAccIbmLogsStreamDataSourceBasic (69.38s)
=== RUN   TestAccIbmLogsStreamDataSourceAllArgs
--- PASS: TestAccIbmLogsStreamDataSourceAllArgs (60.33s)
=== RUN …
```
> Support streams in cloud logs

- examples/ibm-sdsaas/README.md
- examples/ibm-sdsaas/main.tf
- examples/ibm-sdsaas/outputs.tf
- examples/ibm-sdsaas/variables.tf
- examples/ibm-sdsaas/versions.tf
- go.mod
- go.sum
- ibm/conns/config.go
- ibm/provider/provider.go
- ibm/service/sdsaas/README.md
- ibm/service/sdsaas/resource_ibm_sds_host.go
- ibm/service/sdsaas/resource_ibm_sds_host_test.go
- ibm/service/sdsaas/resource_ibm_sds_volume.go
- ibm/service/sdsaas/resource_ibm_sds_volume_test.go
- website/allowed-subcategories.txt
- website/docs/r/sds_host.html.markdown
- website/docs/r/sds_volume.html.markdown
This PR adds terraform support for the software defined storage offering (Ceph as a Service). Terraform resources include volumes and hosts. 
```
$ export IC_API_KEY="<redacted>"                             
$ export IAAS_CLASSIC_USERNAME="<redacted>"     
$ export IAAS_CLASSIC_API_KEY="<redacted>"
$ export …
```
> Add SDSaaS to terraform provider

- .secrets.baseline
- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/cloudshell/data_source_ibm_cloud_shell_account_settings.go
- ibm/service/cloudshell/data_source_ibm_cloud_shell_account_settings_test.go
- ibm/service/cloudshell/resource_ibm_cloud_shell_account_settings.go
- ibm/service/cloudshell/resource_ibm_cloud_shell_account_settings_test.go
- website/docs/d/cloud_shell_account_settings.html.markdown
- website/docs/r/cloud_shell_account_settings.html.markdown
- Changes for IBM Cloud Shell - Optimize Terraform Error Messaging.
- New version of `platform-services-go-sdk` - 0.72.0 to Optimize Terraform Error Messaging for cloudshell.
1. make build
2. Unit tests
```
...
```
> IBM Cloud Shell: re-gen provider for adopting the new error toolchain

- website/docs/r/dns_custom_resolver.html.markdown
> fix(PDNS): add a note for custom resolver location order change

- ibm/service/vpc/resource_ibm_is_vpn_gateway_connection_test.go
- ibm/service/vpc/resource_ibm_is_vpn_gateway_connections.go
Relates OR Closes #5903
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVPNGatewayConnection_CIDRUpdates'
=== RUN   TestAccIBMISVPNGatewayConnection_CIDRUpdates
--- PASS: TestAccIBMISVPNGatewayConnection_CIDRUpdates (415.75s)
PASS …
```
> Vpngwconn fix

- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline.go
> fix(tekton): fix null pointer pipeline issue

- examples/ibm-logs-routing/README.md
- examples/ibm-logs-routing/main.tf
- go.mod
- go.sum
- ibm/service/logsrouting/data_source_ibm_logs-router_targets.go
- ibm/service/logsrouting/data_source_ibm_logs-router_tenants.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant.go
- ibm/service/logsrouting/utils.go
```
make testacc
TF_ACC=1 go test $(go list ./... | grep 'logsrouting') -v  -timeout 700m
=== RUN   TestAccIBMLogsRouterTargetsDataSourceBasic
--- PASS: TestAccIBMLogsRouterTargetsDataSourceBasic …
```
> Add Custom Endpoints to Logs Routing Service

- ibm/service/logsrouting/data_source_ibm_logs-router_targets.go
- ibm/service/logsrouting/data_source_ibm_logs-router_tenants.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant.go
- ibm/service/logsrouting/utils.go
This PR adds the ability to set custom endpoints for the Logs Routing service as described in https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/guides/custom-service-endpoints
```
make testacc
TF_ACC=1 go test …
```
> Add Custom Endpoints Support for Logs Routing service

- website/docs/d/pi_network_security_group.html.markdown
- website/docs/d/pi_network_security_groups.html.markdown
- website/docs/r/pi_network_security_group.html.markdown
- website/docs/r/pi_network_security_group_member.html.markdown
- website/docs/r/pi_network_security_group_rule.html.markdown
Updates tcp flag documentation to remove unsupported tcp flags.
> Update tcp flag documentation

- ibm/service/database/resource_ibm_database.go
- ibm/service/database/resource_ibm_database_edb_test.go
- ibm/service/database/resource_ibm_database_elasticsearch_platinum_test.go
- ibm/service/database/resource_ibm_database_elasticsearch_test.go
- ibm/service/database/resource_ibm_database_etcd_test.go
- ibm/service/database/resource_ibm_database_mongodb_enterprise_test.go
- ibm/service/database/resource_ibm_database_mongodb_sharding_test.go
- ibm/service/database/resource_ibm_database_mongodb_test.go
- ibm/service/database/resource_ibm_database_mysql_test.go
- ibm/service/database/resource_ibm_database_postgresql_test.go
- ibm/service/database/resource_ibm_database_rabbitmq_test.go
- ibm/service/database/resource_ibm_database_redis_test.go
- ibm/service/database/resource_ibm_database_test.go
This reverts commit 768de219360537b8bd0e49e9c383bd27f2b9c413.
Original PR: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5701
> IBM Cloud Databases will begin enforcing password complexity validation for database users created using the IBM Cloud console, CLI, API and Terraform. Database user passwords will be required to be a minimum of 15 characters, contain at least one letter and number and a mix of uppercase and lowercase letters.
This PR will enforce the new password complexity requirements for the `ibm_database` resource
* …
> feat(Cloud Databases): Update Database Password Complexity Validation

- ibm/service/power/resource_ibm_pi_instance_snapshot.go
- website/docs/d/pi_instance_snapshot.html.markdown
- website/docs/d/pi_instance_snapshots.html.markdown
- website/docs/r/pi_instance_snapshot.html.markdown
Are there any other tweaks I should make? 🙂 @yussufsh
```
--- PASS: TestAccIBMPIInstanceSnapshotbasic (995.27s)
PASS
--- PASS: TestAccIBMPIInstanceSnapshotUserTags (1052.50s)
PASS
```
> Remove snapshot get check and update documentation

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_shared_processor_pool.go
- ibm/service/power/data_source_ibm_pi_shared_processor_pools.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_shared_processor_pool.go
- website/docs/d/pi_shared_processor_pool.html.markdown
- website/docs/d/pi_shared_processor_pools.html.markdown
- website/docs/r/pi_shared_processor_pool.html.markdown
data source ibm_pi_shared_processor_pool
```
--- PASS: TestAccIBMPIPISharedProcessorPoolDataSource_basic (26.10s)
PASS
```
data source ibm_pi_shared_processor_pools
```
--- PASS: TestAccIBMPISharedProcessorPoolsDataSourceBasic (15.85s)
PASS
```
resource ibm_pi_shared_processor_pool
```
--- PASS: TestAccIBMPISPPbasic (49.09s)
PASS
--- PASS: TestAccIBMPISPPUserTags (68.63s)
PASS
```
> [Datasource][Resource] Add dedicated host id attribute to shared processor poo

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_network_interface.go
- ibm/service/power/data_source_ibm_pi_network_interfaces.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_network_interface.go
- ibm/service/power/resource_ibm_pi_network_interface_test.go
- website/docs/d/pi_network_interface.html.markdown
- website/docs/d/pi_network_interfaces.html.markdown
- website/docs/r/pi_network_interface.html.markdown
- website/docs/r/pi_network_security_group.html.markdown
Output from acceptance tests:
data source network interface
```
--- PASS: TestAccIBMPINetworkInterfaceDataSourceBasic (16.07s)
PASS
```
data source network interfaces
```
--- PASS: TestAccIBMPINetworkInterfacesDataSourceBasic (16.60s)
PASS
```
resource network interface
```
--- PASS: TestAccIBMPINetworkInterfaceBasic (23.25s)
PASS
--- PASS: TestAccIBMPINetworkInterfaceAllArgs (34.87s)
PASS
```
> [Datasource][Resource] Add network security group ids field to network interface

- go.mod
- go.sum
- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_instances.go
- ibm/service/power/ibm_pi_constants.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_instance_test.go
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instances.html.markdown
- website/docs/r/pi_instance.html.markdown
Output for acceptance tests:
data source instance
```
--- PASS: TestAccIBMPIInstanceDataSource_basic (22.52s)
PASS
```
data source instances
```
--- PASS: TestAccIBMPIInstancesDataSource_basic (23.48s)
PASS
```
resource instances
```
--- PASS: TestAccIBMPIInstanceBasic (927.38s)
PASS
--- PASS: TestAccIBMPIInstanceIBMiLicense (937.23s)
PASS
--- PASS: TestAccIBMPIInstanceNetwork (754.88s)
PASS
--- PASS: TestAccIBMPISAPInstance (1093.12s)
PASS
--- PASS: TestAccIBMPIInstanceStorageConnection (480.87s)
PASS
```
> [Datasource][Resource] Add dedicated host id to instance

- ibm/service/power/data_source_ibm_pi_catalog_images.go
- website/docs/d/pi_catalog_images.html.markdown
Removed vtl deprecation message. This will continue to be supported.
> Remove vtl deprecation message

- go.sum
- ibm/service/power/data_source_ibm_pi_network_security_group.go
- ibm/service/power/data_source_ibm_pi_network_security_groups.go
- ibm/service/power/resource_ibm_pi_network_security_group.go
- ibm/service/power/resource_ibm_pi_network_security_group_member.go
- ibm/service/power/resource_ibm_pi_network_security_group_rule.go
- ibm/service/power/resource_ibm_pi_network_security_group_rule_test.go
- website/docs/d/pi_network_security_group.html.markdown
- website/docs/d/pi_network_security_groups.html.markdown
- website/docs/r/pi_network_security_group.html.markdown
- website/docs/r/pi_network_security_group_member.html.markdown
- website/docs/r/pi_network_security_group_rule.html.markdown
Add network_interface_id and default to NSG
```
=== RUN   TestAccIBMPINetworkSecurityGroupDataSourceBasic
--- PASS: TestAccIBMPINetworkSecurityGroupDataSourceBasic (75.18s)
PASS
=== RUN   TestAccIBMPINetworkSecurityGroupsDataSourceBasic
--- PASS: TestAccIBMPINetworkSecurityGroupsDataSourceBasic (86.18s) …
```
> Update NSG datasources and resources

- ibm/provider/provider.go
- ibm/service/globaltagging/data_source_ibm_iam_access_tag.go
- ibm/service/globaltagging/data_source_ibm_iam_access_tag_test.go
- website/docs/d/iam_access_tag.html.markdown
Added missing data source for `ibm_iam_access_tag` terraform resource.
```
$ make testacc TEST=./ibm/service/globaltagging TESTARGS='-run=TestAccIamAccessTagDataSource_basic -count=1'
...
=== RUN   TestAccIamAccessTagDataSource_basic
--- PASS: TestAccIamAccessTagDataSource_basic (32.18s)
PASS
ok …
```
> Added data source ibm_iam_access_tag

- .secrets.baseline
- go.mod
- go.sum
- ibm/service/secretsmanager/data_source_ibm_sm_imported_certificate.go
- ibm/service/secretsmanager/data_source_ibm_sm_imported_certificate_metadata.go
- ibm/service/secretsmanager/data_source_ibm_sm_imported_certificate_metadata_test.go
- ibm/service/secretsmanager/data_source_ibm_sm_imported_certificate_test.go
- ibm/service/secretsmanager/resource_ibm_sm_imported_certificate.go
- ibm/service/secretsmanager/resource_ibm_sm_imported_certificate_test.go
- website/docs/d/sm_imported_certificate.html.markdown
- website/docs/d/sm_imported_certificate_metadata.html.markdown
- website/docs/r/sm_imported_certificate.html.markdown
Add support for managed CSR in Secrets Manager Imported Certificate secret
```
haims@Haims-MacBook-Pro terraform-provider-ibm % make testacc TEST=./ibm/service/secretsmanager
TF_ACC=1 go test ./ibm/service/secretsmanager -v  -timeout 700m …
```
> Add support for managed CSR in Secrets Manager Imported Certificate secret

- ibm/service/vpc/data_source_ibm_is_vpc.go
- ibm/service/vpc/data_source_ibm_is_vpc_test.go
- ibm/service/vpc/data_source_ibm_is_vpcs.go
- ibm/service/vpc/data_source_ibm_is_vpcs_test.go
- website/docs/d/is_vpc.html.markdown
- website/docs/d/is_vpcs.html.markdown
```
--- PASS: TestAccIBMISVPCsDatasource_basicDefaultAddressPrefixes (142.60s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     144.611s
```
```
--- PASS: TestAccIBMISVPCDatasource_basicDefaultAddressPrefixes (147.65s)
PASS
ok …
```
> Added support for default address prefixes in vpc(s) datasource

- ibm/service/vpc/data_source_ibm_is_ssh_key.go
- ibm/service/vpc/data_source_ibm_is_ssh_key_test.go
- ibm/service/vpc/resource_ibm_is_ssh_key.go
- ibm/service/vpc/resource_ibm_is_ssh_key_test.go
- website/docs/d/is_ssh_key.html.markdown
- website/docs/r/is_ssh_key.html.markdown
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSSHKey_CreatedAtHref'
=== RUN   TestAccIBMISSSHKey_CreatedAtHref
--- PASS: TestAccIBMISSSHKey_CreatedAtHref (36.03s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     38.097s
```
```
% make testacc …
```
> added support for created_at and href support in is_ssh_key

- README.md
Relates OR Closes #5846
```
...
```
> Updated readme for ansible collection

- ibm/service/vpc/resource_ibm_is_vpc.go
- ibm/service/vpc/resource_ibm_is_vpc_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVPC_ResolverTypeTransitionDnsNameUpdate'
=== RUN   TestAccIBMISVPC_ResolverTypeTransitionDnsNameUpdate
--- PASS: TestAccIBMISVPC_ResolverTypeTransitionDnsNameUpdate (507.15s)
PASS
ok …
```
> fix(vpc): dns name update issue fixed

- ibm/service/codeengine/resource_ibm_code_engine_app.go
- ibm/service/codeengine/resource_ibm_code_engine_function.go
- ibm/service/codeengine/resource_ibm_code_engine_job.go
Relates OR Closes #5939 
**code_engine_application**
```
$ make testacc TESTARGS='-run=TestAccIbmCodeEngineAppBasic'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIbmCodeEngineAppBasic -timeout 700m 
=== RUN   TestAccIbmCodeEngineAppBasic
--- PASS: …
```
> Change parameter updates in code engine to prevent panic #5939

- ibm/validate/validators.go
```
astha@Asthas-MBP vpc-terraform-config % tf plan
╷
│ Error: "priority" must be greater than 0
│ 
│   with ibm_is_lb_listener_policy.example,
│   on main.tf line 111, in resource "ibm_is_lb_listener_policy" "example":
│  111:   priority = 0
│ 
╵
...
```
> fix(priority): update validators.go 

- ibm/service/resourcecontroller/resource_ibm_resource_instance.go
```
=== RUN   TestAccIBMResourceInstanceBasic
--- PASS: TestAccIBMResourceInstanceBasic (157.14s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/resourcecontroller	161.337s
...
```
This change is maily to return appropriate error message during async operation in both create and …
> handle async provisioning during create and return proper error message

- go.mod
- go.sum
- ibm/service/eventstreams/resource_ibm_event_streams_topic.go
a followup fix for https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5822 which broke acceptance test.
this PR always uses sasl oauthbearer to configure sarama/kafka client no matter apikey or refresh token is configured in the session.
and uses `IamAuthenticator` from new [platform-sdk](https://github.com/IBM/platform-services-go-sdk) to build …
> fix: always use sasl oauthbearer for sarama client

- ibm/service/kubernetes/resource_ibm_ob_logging.go
- ibm/service/kubernetes/resource_ibm_ob_monitoring.go
Closes: https://github.ibm.com/alchemy-containers/armada-kedge/issues/1441
guidelines: https://developer.hashicorp.com/terraform/plugin/framework/deprecations#provider-data-source-or-resource-removal
> chore(add deprecation message to iks observability resource)

- ibm/service/eventnotification/resource_ibm_en_integration.go
The `ibm_en_integration` resource is printing `ibm_en_integration_cos` instead of  instead of `ibm_en_integration` in its logging. For example:
```
2025/03/03 11:00:46 Terraform apply | Error: ---
2025/03/03 11:00:46 Terraform apply | id: terraform-afa76cbf
2025/03/03 11:00:46 Terraform apply | summary: 'ReplaceIntegrationWithContext failed: Gateway Timeout' …
```
> fix: correct the resource name being printed in ibm_en_integration logging

- go.mod
- go.sum
> chore: update TKE SDK reference

- .secrets.baseline
- ibm/service/codeengine/resource_ibm_code_engine_app.go
- ibm/service/codeengine/resource_ibm_code_engine_app_test.go
- ibm/service/codeengine/resource_ibm_code_engine_function.go
- ibm/service/codeengine/resource_ibm_code_engine_function_test.go
- ibm/service/codeengine/resource_ibm_code_engine_job.go
- ibm/service/codeengine/resource_ibm_code_engine_job_test.go
Relates OR Closes #6013
```
$ make testacc TESTARGS="-run TestAccIbmCodeEngineAppBasic"
=== RUN   TestAccIbmCodeEngineAppBasic
--- PASS: TestAccIbmCodeEngineAppBasic (196.37s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/codeengine      206.201s
...
```
```
$ make testacc TESTARGS="-run …
```
> fix crashing provider due to Code Engine type casting #6013

- ibm/service/vpc/data_source_ibm_is_ssh_key.go
- ibm/service/vpc/data_source_ibm_is_ssh_key_test.go
- website/docs/d/is_ssh_key.html.markdown
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSSHKeyDatasource_basicidname'
=== RUN   TestAccIBMISSSHKeyDatasource_basicidname
--- PASS: TestAccIBMISSSHKeyDatasource_basicidname (47.26s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     49.344s
```
> Added support for id in is_ssh_key data source

- ibm/acctest/acctest.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISBareMetalServerMultiple'
=== RUN   TestAccIBMISBareMetalServerMultiple
--- PASS: TestAccIBMISBareMetalServerMultiple (73.97s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     76.096s
```
```
--- PASS: …
```
> Added retry logic for is_bare_metal_server 409

- website/docs/d/cm_account.html.markdown
- website/docs/r/cm_account.html.markdown
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMCmAccountBasic -timeout 700m 
=== RUN   TestAccIBMCmAccountBasic
--- PASS: TestAccIBMCmAccountBasic (13.88s)
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccIBMCmAccountDataSourceBasic -timeout 700m 
=== RUN …
```
> fix: update docs for cm account resource

- ibm/service/cis/data_source_ibm_cis_dns_records.go
- ibm/service/cis/resource_ibm_cis_dns_record.go
Currently, trying to create ibm_cis_dns_record resources causes the provider to panic and crash. For example, simple tf file
```hcl
resource "ibm_cis_dns_record" "record" {
cis_id    = var.cis_id
domain_id = var.domain_id
name      = var.record_name
content   = "foo.bar.baz"
type      = "CNAME"
ttl       = 0
}
```
results in:
```
ibm_cis_dns_record.record: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with ibm_cis_dns_record.record,
│   on main.tf line 21, in resource "ibm_cis_dns_record" "record":
│   21: resource "ibm_cis_dns_record" "record" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Stack trace from the terraform-provider-ibm_v1.76.1 plugin:
panic: runtime …
```
> fix(cis): don't panic when ZoneID/ZoneName not set

- ibm/service/vpc/data_source_ibm_is_region.go
- ibm/service/vpc/data_source_ibm_is_regions.go
- ibm/service/vpc/data_source_ibm_is_zone.go
- ibm/service/vpc/data_source_ibm_is_zones.go
```
--- PASS: TestAccIBMISZoneDataSource_basic (25.84s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     27.949s
```
```
--- PASS: TestAccIBMISZonesDataSource_1 (29.32s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     31.149s
--- PASS: …
```
> enhanced the is-geography datasources errors

- examples/ibm-atracker/README.md
- examples/ibm-atracker/main.tf
- ibm/service/atracker/README.md
- ibm/service/atracker/data_source_ibm_atracker_targets.go
- ibm/service/atracker/data_source_ibm_atracker_targets_test.go
- ibm/service/atracker/resource_ibm_atracker_target.go
- website/docs/d/atracker_targets.html.markdown
- website/docs/r/atracker_target.html.markdown
```
$ make testacc TEST=./ibm/service/atracker TESTARGS='-run=TestAccIBMAtracker*
=== RUN   TestAccIBMAtrackerRoutesDataSourceBasic
--- PASS: TestAccIBMAtrackerRoutesDataSourceBasic (16.71s)
=== RUN   TestAccIBMAtrackerTargetsDataSourceBasic
--- PASS: TestAccIBMAtrackerTargetsDataSourceBasic (15.39s) …
```
> (atracker) Deprecate logdna_endpoint attribute and logdna target_type

- ibm/service/power/resource_ibm_pi_instance.go
- website/docs/r/pi_instance.html.markdown
Remove deprecation note from pi_license_repository_capacity. Feature is still used by Falconstor.
> Remove deprecation note from pi_license_repository_capacity

- website/docs/d/pi_placement_group.html.markdown
- website/docs/d/pi_placement_groups.html.markdown
- website/docs/d/pi_shared_processor_pool.html.markdown
- website/docs/d/pi_shared_processor_pools.html.markdown
- website/docs/d/pi_spp_placement_group.html.markdown
- website/docs/d/pi_spp_placement_groups.html.markdown
- website/docs/r/pi_placement_group.html.markdown
- website/docs/r/pi_shared_processor_pool.html.markdown
- website/docs/r/pi_spp_placement_group.html.markdown
This PR removes the remaining warnings from the spp and placement-group documentation.
> Remove warnings from terraform spp and pg markdown files

- website/docs/d/pi_cloud_connection.html.markdown
- website/docs/d/pi_cloud_connections.html.markdown
- website/docs/d/pi_cloud_instance.html.markdown
- website/docs/d/pi_virtual_serial_number.html.markdown
- website/docs/d/pi_virtual_serial_numbers.html.markdown
- website/docs/r/pi_cloud_connection.html.markdown
- website/docs/r/pi_cloud_connection_network_attach.html.markdown
- website/docs/r/pi_virtual_serial_number.html.markdown
This PR removes the remaining warnings from the cloud connection and vsn documentation.
> Remove warnings from terraform cloud connection and vsn markdown files

- website/docs/d/pi_dhcp.html.markdown
- website/docs/d/pi_dhcps.html.markdown
- website/docs/d/pi_key.html.markdown
- website/docs/d/pi_keys.html.markdown
- website/docs/r/pi_dhcp.html.markdown
- website/docs/r/pi_key.html.markdown
This PR removes the remaining warnings from the dhcp and ssh-key documentation.
> Remove warnings from terraform dhcp and ssh-key markdown files

- website/docs/d/pi_catalog_images.html.markdown
- website/docs/d/pi_image.html.markdown
- website/docs/d/pi_images.html.markdown
- website/docs/r/pi_image.html.markdown
- website/docs/r/pi_image_export.html.markdown
This PR removes the remaining warnings from the image documentation.
> Remove warnings from terraform image markdown files

- website/docs/d/pi_volume.html.markdown
- website/docs/d/pi_volume_flash_copy_mappings_html.markdown
- website/docs/d/pi_volume_onboarding.html.markdown
- website/docs/d/pi_volume_onboardings.html.markdown
- website/docs/d/pi_volume_remote_copy_relationship.html.markdown
- website/docs/r/pi_volume.html.markdown
- website/docs/r/pi_volume_attach.html.markdown
- website/docs/r/pi_volume_clone.html.markdown
- website/docs/r/pi_volume_onboarding.html.markdown
This PR removes the remaining warnings from the volume documentation.
> Remove warnings from terraform volume markdown files

- website/docs/d/pi_network.html.markdown
- website/docs/d/pi_network_address_groups.html.markdown
- website/docs/d/pi_network_peers.html.markdown
- website/docs/d/pi_network_port.html.markdown
- website/docs/d/pi_network_security_groups.html.markdown
- website/docs/d/pi_networks.html.markdown
- website/docs/d/pi_public_network.html.markdown
- website/docs/r/pi_network.html.markdown
- website/docs/r/pi_network_port_attach.html.markdown
- website/docs/r/pi_network_security_group_rule.html.markdown
This PR removes the remaining warnings from the networks documentation.
> Remove warnings from terraform network markdown files

- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instance_ip.html.markdown
- website/docs/d/pi_instance_snapshot.html.markdown
- website/docs/d/pi_instance_snapshots.html.markdown
- website/docs/d/pi_instance_volumes.html.markdown
- website/docs/d/pi_instances.html.markdown
- website/docs/r/pi_capture.html.markdown
- website/docs/r/pi_instance.html.markdown
- website/docs/r/pi_instance_action.html.markdown
- website/docs/r/pi_instance_snapshot.html.markdown
This PR removes the remaining warnings from the instance documentation.
> Remove warnings from terraform instance markdown files

- website/docs/d/pi_host.html.markdown
- website/docs/d/pi_host_group.html.markdown
- website/docs/r/pi_host.html.markdown
- website/docs/r/pi_host_group.html.markdown
This PR removes the remaining warnings from the host and host-group documentation.
> Remove warnings from terraform host and host-group markdown files

- website/docs/d/pi_datacenter.html.markdown
- website/docs/d/pi_datacenters.html.markdown
- website/docs/d/pi_workspace.html.markdown
- website/docs/d/pi_workspaces.html.markdown
- website/docs/r/pi_workspace.html.markdown
This PR removes the remaining warnings from the datacenter and workspace documentation.
> Remove warnings from terraform datacenter and workspace markdown files

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_instance_template.go
- ibm/service/vpc/data_source_ibm_is_instance_templates.go
- ibm/service/vpc/data_source_ibm_is_instance_volume_attachment.go
- ibm/service/vpc/data_source_ibm_is_instance_volume_attachments.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_instance_template_test.go
- ibm/service/vpc/resource_ibm_is_instance_test.go
- ibm/service/vpc/resource_ibm_is_instance_volume_attachment.go
- ibm/service/vpc/resource_ibm_is_instance_volume_attachment_test.go
- ibm/service/vpc/resource_ibm_is_snapshot.go
- ibm/service/vpc/resource_ibm_is_volume.go
- ibm/service/vpc/resource_ibm_is_volume_test.go
- website/docs/d/is_instance_template.html.markdown
- website/docs/d/is_instance_templates.html.markdown
- website/docs/d/is_instance_volume_attachment.html.markdown
- website/docs/d/is_instance_volume_attachments.html.markdown
- website/docs/r/is_instance.html.markdown
- website/docs/r/is_instance_template.html.markdown
- website/docs/r/is_instance_volume_attachment.html.markdown
- website/docs/r/is_volume.html.markdown
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISVolume_bandwidth'
=== RUN   TestAccIBMISVolume_bandwidth
--- PASS: TestAccIBMISVolume_bandwidth (121.89s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     123.714s
```
```
% make testacc …
```
> Added support for volume bandwidth in vpc resources

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISBareMetalServer_network_interfaces'
=== RUN   TestAccIBMISBareMetalServer_network_interfaces
--- PASS: TestAccIBMISBareMetalServer_network_interfaces (1595.49s)
PASS …
```
> changed network_interfaces to typelist for is_bare_metal_server

- ibm/service/vpc/resource_ibm_is_vpc.go
- ibm/service/vpc/resource_ibm_is_vpc_test.go
```
--- PASS: TestAccIBMISVPC_ResolverTypeTransitionDnsNameUpdate (466.69s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     468.807s
--- PASS: TestAccIBMISVPC_ResolverTypeTransitionDnsNameVPCCrnUpdate (464.21s)
PASS
ok …
```
> fix for vpc_crn in is_vpc dns

- ibm/service/vpc/data_source_ibm_is_ike_policies.go
- ibm/service/vpc/data_source_ibm_is_ike_policy.go
- ibm/service/vpc/data_source_ibm_is_ipsec_policies.go
- ibm/service/vpc/data_source_ibm_is_ipsec_policy.go
- ibm/service/vpc/resource_ibm_is_ike_policy.go
- ibm/service/vpc/resource_ibm_is_ipsec_policy.go
```
--- PASS: TestAccIBMISIPSecPolicy_basic (45.26s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     47.435s
--- PASS: TestAccIBMISIKEPolicy_basic (47.55s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     49.393s
--- PASS: …
```
> enhancement: improved error handling for is (ike/ipsec) policy

- GNUmakefile
- ibm/service/vpc/data_source_ibm_is_ssh_key.go
- ibm/service/vpc/data_source_ibm_is_ssh_key_test.go
- ibm/service/vpc/data_source_ibm_is_ssh_keys.go
- ibm/service/vpc/data_source_ibm_is_ssh_keys_test.go
- ibm/service/vpc/resource_ibm_is_ssh_key.go
- ibm/service/vpc/resource_ibm_is_ssh_key_test.go
```
--- PASS: TestAccIBMISSSHKey_basic (39.70s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     41.849s
--- PASS: TestAccIBMISSSHKey_CreatedAtHref (36.38s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     38.170s
--- PASS: …
```
> enhancement: improved error handling for is_ssh_key

- ibm/service/vpc/data_source_ibm_is_ssh_key.go
> fix: set previously unset attribute on is_ssh_key datasource

- ibm/service/vpc/resource_ibm_is_instance_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstanceTDX_basic'
=== RUN   TestAccIBMISInstanceTDX_basic
--- PASS: TestAccIBMISInstanceTDX_basic (167.38s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     169.488s
```
```
% make testacc …
```
> Added tests for tdx confidential compute mode

- ibm/service/vpc/resource_ibm_is_instance_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISInstanceSGX_basic'
=== RUN   TestAccIBMISInstanceSGX_basic
--- PASS: TestAccIBMISInstanceSGX_basic (197.32s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     199.391s
```
> Added acceptance test for sgx confidential compute mode

- ibm/acctest/acctest.go
- ibm/service/power/data_source_ibm_pi_cloud_connection.go
- ibm/service/power/data_source_ibm_pi_cloud_connections.go
- ibm/service/power/data_source_ibm_pi_instance_volumes_test.go
- ibm/service/power/data_source_ibm_pi_sap_profile_test.go
- ibm/service/power/resource_ibm_pi_capture.go
- ibm/service/power/resource_ibm_pi_capture_test.go
- ibm/service/power/resource_ibm_pi_cloud_connection.go
- ibm/service/power/resource_ibm_pi_host.go
- ibm/service/power/resource_ibm_pi_image.go
- ibm/service/power/resource_ibm_pi_network.go
- ibm/service/power/resource_ibm_pi_placement_group_test.go
- ibm/service/power/resource_ibm_pi_spp_placement_group_test.go
This PR removes pending warnings in terraform code.
Removed nil check where it wasn't needed as len() for nil sliced is defined as zero.
Removed unused parameters.
Removed duplicate import.
Updated placement group resource tests to use environment variables for profile sap id.
Slightly improved readability in cloud_connection data source.
```
--- PASS: TestAccIBMPICloudConnectionsDataSourceBasic (14.16s)
PASS
--- PASS: TestAccIBMPICloudConnectionDataSource_basic (22.93s)
PASS
--- PASS: TestAccIBMPIVolumesDataSource_basic (27.84s)
PASS
--- PASS: TestAccIBMPIImagebasic (55.48s)
PASS
--- PASS: TestAccIBMPIImageUserTags (100.23s)
PASS
--- PASS: TestAccIBMPICloudConnectionbasic (353.63s)
PASS
--- PASS: TestAccIBMPICloudConnectionNetworks (505.72s)
PASS
--- PASS: …
```
> Fix warnings in pi data source and resources

- ibm/service/power/data_source_ibm_pi_instance_volumes.go
This crash occurred because the vm has no volumes and we tried to list them. I think this changed within the last year, and it is now possible to have a vm with no volumes.
This crash occurred because the vm has no volumes and we tried to list them. I think this changed within the last year, and it is now possible to have a vm with no volumes.
```
--- PASS: TestAccIBMPIVolumesDataSource_basic (28.58s)
PASS
```
List instance volumes from a vm with no volumes will look like
```
result = {
"boot_volume_id" = tostring(null)
"id" = "56349cd9-0269-1a8c-a609-60560b3c276d"
"instance_volumes" = tolist([])
"pi_cloud_instance_id" = "6021a723-bcab-4d3f-9985-d0cb2f864f35"
"pi_instance_name" = "0ad61745-e796-4de2-bde5-89fac02f2618"
}
```
> [Datasource] Fix crash when vm has no volumes

- ibm/service/power/data_source_ibm_pi_volume_snapshot.go
- ibm/service/power/data_source_ibm_pi_volume_snapshots.go
- website/docs/d/pi_volume_snapshot.html.markdown
- website/docs/d/pi_volume_snapshots.html.markdown
This field was mistakenly added and is not and has never been filled out by the service broker. It currently only applies to the instance_snapshot data source and resource.
Output from acceptance testing
```
--- PASS: TestAccIBMPIVolumeSnapshotsDataSourceBasic (16.48s)
PASS
--- PASS: TestAccIBMPIVolumeSnapshotDataSourceBasic (16.28s)
PASS
```
> [Datasource] Deprecate CRN attribute from ibm_pi_volume_snapshot(s)

- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_definition.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_definition_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_property.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_property_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger_property.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger_property_test.go
- ibm/service/cdtektonpipeline/data_source_ibm_cd_tekton_pipeline_trigger_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_definition.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_definition_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_property.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_property_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_property.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_property_test.go
- ibm/service/cdtektonpipeline/resource_ibm_cd_tekton_pipeline_trigger_test.go
Add some null pointer checks to fix errors when importing resources. Also make sure that pipeline_id and trigger_id are set in certain cases, to avoid resource replacement issues when importing existing resources.
```
--- PASS: TestAccIBMCdTektonPipelineDefinitionDataSourceBasic (71.72s)
=== RUN   TestAccIBMCdTektonPipelinePropertyDataSourceBasic
--- PASS: TestAccIBMCdTektonPipelinePropertyDataSourceBasic (63.20s)
=== RUN …
```
> fix(tekton): fix null pointers when importing resources

- ibm/service/vpc/resource_ibm_is_security_group_target.go
- ibm/service/vpc/resource_ibm_is_security_group_target_test.go
Successfully tested with concurrent security group target attachments to the same load balancer.
Relates OR Closes #6150
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISSecurityGroupTarget_UpdatePendingRetry'
=== RUN   TestAccIBMISSecurityGroupTarget_UpdatePendingRetry
--- PASS: …
```
> feat(is_security_group_target): Handle pending LB states during SG binding

- ibm/service/vpc/data_source_ibm_is_floating_ip.go
- ibm/service/vpc/data_source_ibm_is_floating_ip_test.go
- ibm/service/vpc/data_source_ibm_is_floating_ips.go
- ibm/service/vpc/data_source_ibm_is_floating_ips_test.go
- ibm/service/vpc/resource_ibm_is_floating_ip.go
- ibm/service/vpc/resource_ibm_is_floating_ip_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISFloatingIP_basic'
=== RUN   TestAccIBMISFloatingIP_basic
--- PASS: TestAccIBMISFloatingIP_basic (378.23s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     380.080s
% make testacc TEST=./ibm/service/vpc …
```
> enhancement: improved error handling for is_floating_ip(s)

- ibm/service/vpc/data_source_ibm_is_ike_policies_test.go
- ibm/service/vpc/data_source_ibm_is_ike_policy_test.go
- ibm/service/vpc/data_source_ibm_is_ipsec_policies_test.go
- ibm/service/vpc/data_source_ibm_is_ipsec_policy_test.go
- ibm/service/vpc/resource_ibm_is_ike_policy_test.go
- ibm/service/vpc/resource_ibm_is_ipsec_policy_test.go
```
% make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISIPSecPolicy_ComputedFields'
=== RUN   TestAccIBMISIPSecPolicy_ComputedFields
--- PASS: TestAccIBMISIPSecPolicy_ComputedFields (23.93s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     26.048s
% make testacc …
```
> updated is_ike_policy and is_ipsec_policy tests

- ibm/service/vpc/data_source_ibm_is_reservation.go
- ibm/service/vpc/data_source_ibm_is_reservations.go
- ibm/service/vpc/resource_ibm_is_reservation.go
- ibm/service/vpc/resource_ibm_is_reservation_activate.go
> enhancement: improved error handling for vpc reservations

- ibm/service/vpc/resource_ibm_is_ipsec_policy.go
> Added aes192 encryption algroithm in is_ipsec_policy validator

- examples/ibm-logs-routing/README.md
- ibm/service/logsrouting/data_source_ibm_logs-router_targets_test.go
- ibm/service/logsrouting/data_source_ibm_logs-router_tenants_test.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant.go
- ibm/service/logsrouting/resource_ibm_logs-router_tenant_test.go
- website/docs/d/logs-router_targets.html.markdown
- website/docs/d/logs-router_tenants.html.markdown
- website/docs/r/logs-router_tenant.html.markdown
These changes add the logdna deprecation notice and removes logdna as an option and from the tests
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep 'routing') -v  -timeout 700m
[WARN] Set the environment variable INGESTION_KEY for …
```
> Remove Logdna target option for IBM Cloud Logs Routing

- ibm/service/transitgateway/HOWTO.md
- ibm/service/transitgateway/resource_ibm_tg_gateway_connection.go
```
...
```
Issue: https://github.ibm.com/CloudBBS/ts-planning/issues/5664
> Fix: Fixed TGW-146 Terraform: some lines in logs are useless when create RGRE connection

- ibm/conns/config.go
Fix backupRecoveryConnectorClient usage
```
...
```
> fix connector client usage

- ibm/conns/config.go
fix backuprecovery client error handling
```
...
```
> fix: backuprecovery client error handling

- ibm/service/cos/resource_ibm_cos_bucket.go
- ibm/service/cos/resource_ibm_cos_bucket_lifecycle_configuration.go
Regression result :
```
=== RUN  TestAccIBMCosBucket_Basic
--- PASS: TestAccIBMCosBucket_Basic (107.10s)
=== RUN  TestAccIBMCosBucket_Basic_Single_Site_Location
--- PASS: TestAccIBMCosBucket_Basic_Single_Site_Location (64.43s)
=== RUN  TestAccIBMCosBucket_Lifecycle_Configuration_Expiration_With_Days
--- PASS: TestAccIBMCosBucket_Lifecycle_Configuration_Expiration_With_Days (77.43s)
=== RUN  TestAccIBMCosBucket_Lifecycle_Configuration_Expiration_With_Date
--- PASS: TestAccIBMCosBucket_Lifecycle_Configuration_Expiration_With_Date (68.67s)
=== RUN  TestAccIBMCosBucket_Lifecycle_Configuration_Transition_With_Days_Glacier
--- PASS: TestAccIBMCosBucket_Lifecycle_Configuration_Transition_With_Days_Glacier (72.72s)
=== RUN  TestAccIBMCosBucket_Lifecycle_Configuration_Transition_With_Date_Glacier …
```
> Adding the fix for github issue #5778

- ibm/service/appconfiguration/data_source_ibm_app_config_environment.go
- ibm/service/appconfiguration/data_source_ibm_app_config_environments.go
- ibm/service/appconfiguration/data_source_ibm_app_config_feature.go
- ibm/service/appconfiguration/data_source_ibm_app_config_features.go
- ibm/service/appconfiguration/data_source_ibm_app_config_segment.go
- ibm/service/appconfiguration/resource_ibm_app_config_collection_test.go
- ibm/service/appconfiguration/resource_ibm_app_config_environment.go
- ibm/service/appconfiguration/resource_ibm_app_config_environment_test.go
- ibm/service/appconfiguration/resource_ibm_app_config_feature.go
- ibm/service/appconfiguration/resource_ibm_app_config_feature_test.go
- ibm/service/appconfiguration/resource_ibm_app_config_property.go
- ibm/service/appconfiguration/resource_ibm_app_config_property_test.go
- ibm/service/appconfiguration/resource_ibm_app_config_segment.go
- ibm/service/appconfiguration/resource_ibm_app_config_segment_test.go
- ibm/service/appconfiguration/resource_ibm_app_config_snapshot.go
- ibm/service/cis/data_source_ibm_cis_test.go
- ibm/service/classicinfrastructure/resource_ibm_lb_vpx_vip.go
- ibm/service/hpcs/resource_ibm_hpcs_vault.go
- ibm/service/power/resource_ibm_pi_network.go
Fix the non format errors after go 1.24 upgrade
```
harinireddy@Harinis-MBP terraform-provider-ibm % make build
go vet .
ibm/service/appconfiguration/data_source_ibm_app_config_environment.go:80:25: non-constant format string in call to github.com/IBM-Cloud/terraform-provider-ibm/ibm/flex.FmtErrorf
ibm/service/appconfiguration/data_source_ibm_app_config_environments.go:168:25: non-constant format string in call to github.com/IBM-Cloud/terraform-provider-ibm/ibm/flex.FmtErrorf
ibm/service/appconfiguration/data_source_ibm_app_config_feature.go:175:25: non-constant format string in call to github.com/IBM-Cloud/terraform-provider-ibm/ibm/flex.FmtErrorf
ibm/service/appconfiguration/data_source_ibm_app_config_features.go:285:25: …
```
> Fix non-constant format string in call flex.FmtErrorf after go 1.24 upgrade

- ibm/service/vpc/resource_ibm_is_security_group_target.go
> fix status issue with vni on is_security_group_target

- ibm/service/power/data_source_ibm_pi_instance.go
- ibm/service/power/data_source_ibm_pi_instances.go
- website/docs/d/pi_instance.html.markdown
- website/docs/d/pi_instances.html.markdown
Remove deprecation note from license_repository_capacity attributes. Feature is still used by Falconstor. Previously only removed the notice from the argument. I missed the attributes in the first pass.
> [Datasource] Remove deprecation notice from VTL fields still in use by FalconStor

- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_placement_group.go
- ibm/service/power/resource_ibm_pi_placement_group_test.go
Description: 
`Computed: true` was erroneously added to `pi_placement_group_id` argument  in `pi_instance` resource refactor. This resulted in the placement group acceptance tests failing and a slight behavior change. This PR removes that property and fixes errors in placement group acceptance tests.
Instance refactor PR: …
> [Resource] Remove computed property from pi_instance "pi_placement_group_id", fix placement group acceptance test, add wait for placement group delete

- ibm/service/power/resource_ibm_pi_network_address_group.go
- ibm/service/power/resource_ibm_pi_network_address_group_test.go
```
--- PASS: TestAccIBMPINetworkAddressGroupUserTags (47.95s)
PASS
--- PASS: TestAccIBMPINetworkAddressGroupBasic (34.42s)
PASS
```
> [Resource] pi_network_access_group fix user tags argument crash, add user tags test

- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_network_attachment.go
- ibm/service/vpc/resource_ibm_is_instance.go
- ibm/service/vpc/resource_ibm_is_instance_network_attachment.go
- ibm/service/vpc/resource_ibm_is_instance_template.go
- ibm/service/vpc/resource_ibm_is_share_mount_target.go
- ibm/service/vpc/resource_ibm_is_virtual_network_interface.go
> fix(auto_delete): fixed default true on vni

- ibm/service/secretsmanager/resource_ibm_sm_private_certificate_configuration_intermediate_ca_test.go
- ibm/service/secretsmanager/resource_ibm_sm_private_certificate_configuration_root_ca_test.go
This commit is just a change in some private cert tests. This change allows the tests to run without leaving behind left over keys in the test environment, so there's no need to run a cleanup process after running the tests.
```
...
```
> Improve test of private certificate secret

- ibm/service/vpc/data_source_ibm_is_backup_policies.go
- ibm/service/vpc/data_source_ibm_is_backup_policy.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_job.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_jobs.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plan.go
- ibm/service/vpc/data_source_ibm_is_backup_policy_plans.go
- ibm/service/vpc/resource_ibm_is_backup_policy.go
- ibm/service/vpc/resource_ibm_is_backup_policy_plan.go
> enhancement: improved error handling for vpc backup policy

- ibm/service/iamidentity/resource_ibm_iam_trusted_profile.go
- ibm/service/resourcemanager/resource_ibm_resource_group.go
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
+ resource "ibm_iam_trusted_profile" "iam_trusted_profile_instance" {
+ account_id     = (known after apply)
+ assignment_id  = (known after apply)
+ created_at     = (known after apply)
+ crn            = (known after apply)
+ entity_tag     = (known after apply)
+ history        = (known after apply)
+ iam_id         = (known after apply)
+ id             = (known after apply)
+ ims_account_id = (known after apply)
+ ims_user_id    = (known after apply)
+ modified_at    = (known after apply)
+ name           = "newtrusted"
+ profile_id     = (known after apply)
+ template_id    = (known after …
```
> Add retry on GET for resource group and trusted profile

- ibm/service/vpc/resource_ibm_is_image.go
- ibm/service/vpc/resource_ibm_is_image_test.go
```
TF_ACC=1 go test ./ibm/service/vpc -v -run=TestAccIBMISImage_accessTags -timeout 700m 
=== RUN   TestAccIBMISImage_accessTags
--- PASS: TestAccIBMISImage_accessTags (184.58s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     186.194s
```
> fix(is-image): fixed the access_tags set on is_image

- ibm/service/vpc/data_source_ibm_is_share_mount_target.go
> fix(fs-mount-target): fix setting accesscontrolmode on mount target

- ibm/service/power/data_source_ibm_pi_hosts.go
- ibm/service/power/data_source_ibm_pi_image.go
- ibm/service/power/data_source_ibm_pi_images.go
- ibm/service/power/data_source_ibm_pi_network_address_group.go
- ibm/service/power/data_source_ibm_pi_network_address_groups.go
- ibm/service/power/data_source_ibm_pi_network_interface.go
- ibm/service/power/data_source_ibm_pi_network_interfaces.go
- ibm/service/power/data_source_ibm_pi_network_security_group.go
- ibm/service/power/data_source_ibm_pi_network_security_groups.go
- ibm/service/power/data_source_ibm_pi_volume.go
- ibm/service/power/resource_ibm_pi_instance.go
- ibm/service/power/resource_ibm_pi_network_address_group.go
- ibm/service/power/resource_ibm_pi_network_address_group_member.go
- ibm/service/power/resource_ibm_pi_network_interface.go
- ibm/service/power/resource_ibm_pi_network_security_group_member.go
- ibm/service/power/resource_ibm_pi_network_security_group_rule.go
We were calling each of these functions about half and half, but they do literally the same thing. We should be calling only one of them for consistency and clarity.
```
--- PASS: TestAccIBMPIInstanceUserTags (1239.10s)
PASS
--- PASS: TestAccIBMPINetworkAddressGroupBasic (29.89s)
PASS
--- PASS: TestAccIBMPINetworkAddressGroupMemberBasic (45.59s)
PASS
--- PASS: TestAccIBMPINetworkInterfaceAllArgs (52.77s)
PASS
```
> Replace GetTagsUsingCRN with GetGlobalTagsUsingCRN

- ibm/service/power/data_source_ibm_pi_datacenter.go
- ibm/service/power/data_source_ibm_pi_datacenters.go
- ibm/service/power/data_source_ibm_pi_host.go
- ibm/service/power/data_source_ibm_pi_hosts.go
- ibm/service/power/data_source_ibm_pi_network_interface.go
- ibm/service/power/data_source_ibm_pi_network_interfaces.go
- ibm/service/power/resource_ibm_pi_instance_console_language.go
- ibm/service/power/resource_ibm_pi_instance_snapshot.go
- ibm/service/power/resource_ibm_pi_key.go
- ibm/service/power/resource_ibm_pi_network.go
- ibm/service/power/resource_ibm_pi_placement_group.go
- ibm/service/power/resource_ibm_pi_snapshot.go
- ibm/service/power/resource_ibm_pi_volume.go
- ibm/service/power/resource_ibm_pi_volume_group.go
There were a couple of data sources that did not have the validation.NoZeroValues check that is required, and force new was added to the resources. The resources need force new on this argument because a user could accidentally update that field and think it does something when in reality it just messes up the state. Data sources don't need the value because data sources don't do updates.
```
--- PASS: TestAccIBMPIKey_basic (11.26s)
PASS
```
> Standardize Arg_CloudInstanceID argument across all data source and resource

- ibm/service/vpc/resource_ibm_is_vpc.go
- ibm/service/vpc/resource_ibm_is_vpc_test.go
Relates OR Closes #6313 
```
% make test-vpc TEST_NAME=TestAccIBMISVPC_DnsResolverUpdate
=== RUN   TestAccIBMISVPC_DnsResolverUpdate
--- PASS: TestAccIBMISVPC_DnsResolverUpdate (328.29s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     330.022s
```
> fix(is_vpc): added an empty check for dns binding id

- ibm/service/cdtoolchain/resource_ibm_cd_toolchain_tool_cos.go
The computed field forced the behaviour into always using `apikey`.  Unable to set `hmac`
```
...
```
> fix: cos toolchain tool remove computed field

- ibm/service/logs/resource_ibm_logs_alert.go
- ibm/service/logs/resource_ibm_logs_alert_test.go
- website/docs/r/logs_alert.html.markdown
Relates - https://github.ibm.com/Observability/dragonlog-cx/issues/1712
```
=== RUN   TestAccIbmLogsAlertBasic
--- PASS: TestAccIbmLogsAlertBasic (39.14s)
PASS
ok  	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/logs	40.355s
...
```
> fix alerts metadata_labels

- go.mod
- go.sum
Acceptance Tests Result:
```
(base) Phaneendras-MacBook-Pro:terraform-provider-ibm phaneendra.divi$ make fmt && make testacc TEST=./ibm/service/atracker TESTARGS='-run=TestAccIBMAtracker.*'
gofmt -w $(find .  -path ./.direnv -prune -false -o -name '*.go' |grep -v vendor) …
```
> Update SDK for MR for Error Format

- website/docs/d/iam_policy_templates.html.markdown
- website/docs/r/iam_action_control_assignment.html.markdown
- website/docs/r/iam_policy_assignment.html.markdown
Relates OR Closes #https://github.ibm.com/IAM/AM-issues/issues/3535
```
...
```
> Fixed documentation on access management templates

- ibm/service/vpc/resource_ibm_is_vpn_server_route.go
Relates OR Closes #6368 
```
...
```
> fix: handle nil pointer in VPN server route deletion wait

- ibm/service/iampolicy/data_source_ibm_iam_service_policy.go
- ibm/service/iampolicy/data_source_ibm_iam_trusted_profile_policy.go
- ibm/service/iampolicy/resource_ibm_iam_service_policy.go
- ibm/service/iampolicy/resource_ibm_iam_trusted_profile_policy.go
- website/docs/d/iam_service_policy.html.markdown
- website/docs/d/iam_trusted_profile_policy.html.markdown
- website/docs/r/iam_service_policy.html.markdown
- website/docs/r/iam_trusted_profile_policy.html.markdown
Relates OR Closes #https://github.ibm.com/IAM/AM-issues/issues/3414
```
**warning message**
$ terraform apply
ibm_iam_service_policy.policy: Refreshing state... [id=ServiceId-cb8cef2d-91ff-4292-9a1c-0fa230630af0/7de59ff8-6ba1-4875-80de-beed040f5ae6]
╷
│ Warning: Argument is deprecated
│ 
│   with ibm_iam_service_policy.policy, …
```
> deprecate iam_service_id and profile_id while creation of policies

- ibm/service/logs/resource_ibm_logs_dashboard.go
Relates OR Closes https://github.ibm.com/Observability/dragonlog-cx/issues/1713
Able to import the dashboards that was resulting in panic with latest version of provider.
as you see in the screenshot, after updating provider with fixed local binary th epanic is fixed and I am able to import dashboard
> fix dashboard panic

- ibm/service/vpc/resource_ibm_is_virtual_endpoint_gateway.go
…VPC ID during create
```
...
```
> fix: prevent 409 errors in is_virtual_endpoint_gateway by locking on VPC ID during create

- go.mod
- go.sum
- ibm/provider/provider.go
- ibm/service/eventnotification/data_source_ibm_en_code_engine_subscription.go
- ibm/service/eventnotification/data_source_ibm_en_code_engine_subscription_test.go
- ibm/service/eventnotification/data_source_ibm_en_code_engine_template.go
- ibm/service/eventnotification/data_source_ibm_en_code_engine_template_test.go
- ibm/service/eventnotification/data_source_ibm_en_pre_defined_template.go
- ibm/service/eventnotification/data_source_ibm_en_pre_defined_template_test.go
- ibm/service/eventnotification/data_source_ibm_en_pre_defined_templates.go
- ibm/service/eventnotification/data_source_ibm_en_pre_defined_templates_test.go
- ibm/service/eventnotification/resource_ibm_en_code_engine_template.go
- ibm/service/eventnotification/resource_ibm_en_code_engine_template_test.go
- ibm/service/eventnotification/resource_ibm_en_subscription_code_engine.go
- ibm/service/eventnotification/resource_ibm_en_subscription_code_engine_test.go
- ibm/service/eventnotification/resource_ibm_en_topic.go
- website/docs/d/en_code_engine_template.html.markdown
- website/docs/d/en_pre_defined_template.html.markdown
- website/docs/d/en_pre_defined_templates.html.markdown
- website/docs/d/en_subscription_ce.html.markdown
- website/docs/r/en_code_engine_template.html.markdown
- website/docs/r/en_subscription_ce.html.markdown
Tests: Conducted:
Pre-Defined Templates Data Sources:
List:
Read:
Code Engine Templates:
Data Source:
Resource:
Customer issue: https://ibm-cloudplatform.slack.com/archives/C0267256J4F/p1754578364321309?thread_ts=1754496531.581139&cid=C0267256J4F
The optional parameter starts_at and ends_at was setting default unix epoch time in case parameter was not provided
Fix Provided: fix additionally check for emtpy string along with nil value so that it does not result in invalid time value and subsequently values are not set to default time.
Tests:
Setting cron expression:
adding start time
adding end time
removing time constraints
> feat: pre-defined templates and code engine templates support

- ibm/service/vpc/data_source_ibm_is_volume.go
- ibm/service/vpc/data_source_ibm_is_volume_test.go
- ibm/service/vpc/data_source_ibm_is_volumes.go
- ibm/service/vpc/data_source_ibm_is_volumes_test.go
- ibm/service/vpc/resource_ibm_is_volume.go
- ibm/service/vpc/resource_ibm_is_volume_test.go
- website/docs/d/is_volume.html.markdown
- website/docs/d/is_volumes.html.markdown
- website/docs/r/is_volume.html.markdown
```
--- PASS: TestAccIBMISVolume_storage_generation (58.97s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     60.825s
```
```
--- PASS: TestAccIBMISVolumeDatasource_storage_generation (63.10s)
PASS …
```
> added storage_generation attribute to is_volume

- ibm/service/power/data_source_ibm_pi_cloud_connection.go
- ibm/service/power/data_source_ibm_pi_cloud_connections.go
- ibm/service/power/data_source_ibm_pi_cloud_instance.go
- ibm/service/power/data_source_ibm_pi_datacenter.go
- ibm/service/power/data_source_ibm_pi_datacenters.go
This PR does it for the cloud connection, cloud instance, and datacenter data sources.
Output of acceptance tests:
```
--- PASS: TestAccIBMPICloudConnectionsDataSourceBasic (11.54s)
PASS
--- PASS: TestAccIBMPICloudConnectionDataSource_basic (36.59s)
PASS
--- PASS: TestAccIBMPICloudInstanceDataSource_basic (10.01s)
PASS
--- PASS: TestAccIBMPIDatacenterDataSourceBasic (8.22s)
PASS
--- PASS: TestAccIBMPIDatacenterDataSourcePrivate (11.05s)
PASS
--- PASS: TestAccIBMPIDatacentersDataSourceBasic (7.89s)
PASS
--- PASS: TestAccIBMPIDatacentersDataSourcePrivate (10.27s)
PASS
```
> Refactor terraform errors to use new toolchain in cloud connection, cloud instance, and datacenter data sources

- ibm/service/vpc/data_source_ibm_is_instance_volume_attachment.go
- ibm/service/vpc/data_source_ibm_is_instance_volume_attachment_test.go
- ibm/service/vpc/data_source_ibm_is_instance_volume_attachments.go
- ibm/service/vpc/data_source_ibm_is_instance_volume_attachments_test.go
```
--- PASS: TestAccIBMISInstanceVolumeAttDataSource_nodevice (311.68s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     313.573s
```
```
--- PASS: TestAccIBMISInstanceVolumeAttsDataSource_nodevice (326.34s)
PASS
ok …
```
> fix(vsi): handled absent device on vsis

- go.mod
- go.sum
- ibm/service/catalogmanagement/data_source_ibm_cm_account.go
- ibm/service/catalogmanagement/data_source_ibm_cm_account_test.go
- ibm/service/catalogmanagement/data_source_ibm_cm_version.go
- ibm/service/catalogmanagement/data_source_ibm_cm_version_test.go
- ibm/service/catalogmanagement/resource_ibm_cm_account.go
- ibm/service/catalogmanagement/resource_ibm_cm_account_test.go
- ibm/service/catalogmanagement/resource_ibm_cm_version.go
- ibm/service/catalogmanagement/resource_ibm_cm_version_test.go
- ibm/service/iamidentity/data_source_ibm_iam_account_settings_template_assignment.go
- ibm/service/iamidentity/data_source_ibm_iam_trusted_profile_template_assignment.go
- ibm/service/iamidentity/resource_ibm_iam_account_settings_template_assignment.go
- ibm/service/iamidentity/resource_ibm_iam_trusted_profile_template_assignment.go
- website/docs/d/cm_account.html.markdown
- website/docs/d/cm_version.html.markdown
- website/docs/r/cm_account.html.markdown
- website/docs/r/cm_version.html.markdown
- Bumps `platform-services-go-sdk`, adds new fields from SDK update to catalog management account and version resources.
@hkantare @Daniel-Byrne: I was getting errors from `ibm_iam_trusted_profile_template_assignment` and `ibm_iam_account_settings_template_assignment` when bumping the go SDK to the latest version. It looks like there was a change in a previous SDK release that changed `PolicyTemplateRefs` to `PolicyTemplateReferences`.
@Daniel-Byrne Would you mind taking a look at the changes I made here to confirm if they are correct?
* Please …
> fix(CatalogManagement): bump platform go sdk, add new fields

- ibm/service/power/data_source_ibm_pi_host.go
- ibm/service/power/data_source_ibm_pi_hosts.go
- ibm/service/power/data_source_ibm_pi_image.go
- ibm/service/power/data_source_ibm_pi_images.go
- ibm/service/power/data_source_ibm_pi_instance_console_languages.go
This PR does it for the host, image location, and instance console language data sources.
Output of acceptance testing:
```
--- PASS: TestAccIBMPIHostsDataSourceBasic (14.79s)
PASS
--- PASS: TestAccIBMPIImagesDataSource_basic (203.41s)
PASS
--- PASS: TestAccIBMPIImageDataSource_basic (34.00s)
PASS
--- PASS: TestAccIBMPIInstanceConsoleLanguages (15.14s)
PASS
```
> Refactor terraform errors to use new toolchain in host, image location, and instance console language data sources

- go.mod
- go.sum
- ibm/service/vpc/data_source_ibm_is_bare_metal_server.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_initialization.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_initialization_test.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_server_test.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_servers.go
- ibm/service/vpc/data_source_ibm_is_bare_metal_servers_test.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_initialization.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_initialization_test.go
- ibm/service/vpc/resource_ibm_is_bare_metal_server_test.go
- website/docs/d/is_bare_metal_server.markdown
- website/docs/d/is_bare_metal_server_initialization.markdown
- website/docs/d/is_bare_metal_servers.markdown
- website/docs/r/is_bare_metal_server.markdown
- website/docs/r/is_bare_metal_server_initialization.markdown
```
make testacc TEST=./ibm/service/vpc TESTARGS='-run=TestAccIBMISBareMetalServer_updateInitialization'
--- PASS: TestAccIBMISBareMetalServer_updateInitialization (1646.38s)
PASS
ok github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc 1648.013s
make testacc TEST=./ibm/service/vpc …
```
> feat(bare-metal): Support for metadata service configuration

- ibm/service/catalogmanagement/resource_ibm_cm_account.go
This fixes an edge case bug in the `cm_account` resource. If a user's catalog account does not exist yet, there is no `Rev` field in the GET response. However, they should still be able to perform an update on the catalog account without the `Rev`. The backend API handles this and creates the catalog account.
___
```
==> …
```
> fix: only set rev field if it exists

- ibm/service/cis/resource_ibm_cis_ruleset_rule.go
```
$ make testacc TESTARGS='-run=TestAccIBMCISRulesetRule_Basic'
=== RUN   TestAccIBMCISRulesetRule_Basic
--- PASS: TestAccIBMCISRulesetRule_Basic (121.03ss)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cis     122.035s
```
> fix: check position index before updating CIS ruleset rule
